### ISSUE TITLE
Native VS Cordova

### ISSUE THREAD

**Issue by callmephilip** [RocketChat/Rocket.Chat.iOS#1]
Is there any particular reason you are going with a native app for this as opposed to doing Cordova with Meteor?

**Comment by rodrigok** [comment]
We are doing both :smile:

**Comment by gsaslis** [comment]
1. we want to play around with swift2
2. imho, speed is important in messaging apps (as an everyday tool). We'd like it to be smooth and fast, which is the main case for going native. 

any particular reason you would recommend cordova only, instead?

**Comment by tkowalczyk** [comment]
have you considered Xamarin?

**Comment by gsaslis** [comment]
tbh, no, because of #1   : )

why should we consider xamarin?

**Comment by tkowalczyk** [comment]
Xamarin compiles to native code, allows you to share logic between platforms (iOS, Android, WinPhone), allows to write apps for wearables etc. ... and it can be free for open source projects ;)

**Comment by gsaslis** [comment]
doesn't sound too bad, but I'm personally not looking for any x-platform frameworks (tbh, the write-once-run-everywhere promise they all make -- not just xamarin -- doesn't convince me.. imho, if you want the app you're building to go the distance, you need to go native...)

but let's not start a native vs. x-platform frameworks flame war here... I know each has its use-case...  : ) 

As @rodrigok mentioned, we're doing both.. I'm mainly involved on the Native (Swift2) side of things.. I'm sure someone else will be able to fill you in on how you can contribute to the other project   ; )

**Comment by Sing-Li** [comment]
Before the debate even starts, @rodrigok has released the Cordova implementation for testing.  [Try it now!](https://github.com/RocketChat/Rocket.Chat/wiki/Mobile-app-for-iPhones,-iPads,-iPod-Touch)

**Comment by rafaelks** [comment]
I would vote to use Swift or Objective-C simply because of the community and platform updates. Xamarim seems to be a great platform too, but AFAIK we don't have anyone with experience to start and keep the project running.
