### ISSUE TITLE
Chat controller is not displaying

### ISSUE THREAD

**Issue by demonotter** [RocketChat/Rocket.Chat.iOS#102]
![simulator screen shot aug 19 2016 14 19 30 pm](https://cloud.githubusercontent.com/assets/5362165/17803316/7e4e0dd4-6617-11e6-8844-421ab7341bd6.png)
App just showing this screen

**Comment by rafaelks** [comment]
@demonotter Are you using latest commits? Also, what's your iOS version?

**Comment by demonotter** [comment]
Yes, I'm using latest version

**Comment by rafaelks** [comment]
@demonotter Do you mind in putting a breakpoint (here)[https://github.com/RocketChat/Rocket.Chat.iOS/blob/develop/Rocket.Chat/Controllers/MainViewController.swift#L34] and see if this block is being called? Maybe the `subscriptions/get` method isn't in your server, because this is a new feature.

**Comment by VinayGaikwad** [comment]
@rafaelks Hey, I put a breakpoint there but that block is getting executed. How can I bypass this..? or add subscription/get method in the server.

**Comment by rafaelks** [comment]
@demonotter Can I close the issue?
