### ISSUE TITLE
[QUESTION] Unable to connect to our server except twice or thrice of times

### ISSUE THREAD

**Issue by asshewale** [RocketChat/Rocket.Chat.iOS#1020]
Hi Devs... i am new to RC, _i really loved the way it works._ 
Actually i downloaded the RC's clone from git repository, we do have integrated the RC in our web application within that we are using our own server's URL instead of using the open.rocket.chat, 
The same we tried to implement in our mobile app, As per that we replaced the open.rocket.chat url  with our server's url.
Issue is, sometimes we are able to connect to our server but most of times we fails to connect to our server... 
We tried to trace the issue from all aspects from front end also and from server side also, But we are not able to fix the issue.
Some one will please suggest me how should i trace the issue, 
The scenario is , 2-3 times we are able to connect to our server, it also allows us to login, but 3rd/onward time its not allowing us to connect to our server it just shows the loading and loading.. then we have to kill the app and try again to connect to our server... in this step sometimes it allows to connect again for 2-3 times or even sometimes it doesnt allow to connect to server any more, 
We are really struggling a lot to trace the issue from more than a week of time. 
Will you guys please help us with some ideas please.  
_Your any help will be highly appreciated._

**Comment by cardoso** [comment]
@asshewale 

- Are you sure this is a problem with the iOS App? 
- Are you using the App Store version or are you running from Xcode (develop branch)?
- If so, can you upload the console logs?

**Comment by asshewale** [comment]
@cardoso : Hi Cardoso, Thanks for your valuable time, Please find the scenarios are as below.. 

1. Are you sure this is a problem with the iOS App? 
=> Yes, as the same server is connecting swiftly and ideally from web and Cordova apps, The only issue is with iOS app, that also it allows us to connect twice or thrice latter it stuck, 

2. Are you using the App Store version or are you running from Xcode (develop branch)?
=> We are using the RC clone downloaded from RC's Git repository, means we are running from Xcode (develop branch)

3. If so, can you upload the console logs?

**The Success Response is as below :** 
`[WebSocket] http upgrade request (GET /websocket HTTP/1.1

Connection: Upgrade

Host: chat.mchat.com:443

Origin: wss://chat.mchat.com

Upgrade: websocket

Sec-WebSocket-Version: 13

Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits; server_max_window_bits=15

Sec-WebSocket-Key: cHdjeWRjYXVmZHlidXhxcg==




)
[WebSocket] http upgrade response (HTTP/1.1 101 Switching Protocols

Upgrade: websocket

Connection: Upgrade

Sec-WebSocket-Accept: Aw2jeQc2BYJEG2CxMdyxHRygkbs=

Sec-WebSocket-Extensions: permessage-deflate




)
Socket (<Starscream.WebSocket: 0x105a1c1e0>) did connect
Socket will send message: {
 "version" : "1",
 "id" : "dwWnE06jPRl7nbVnkE4K4IOMnr7zDsuZonrB34JTMNkA18yToz",
 "support" : [
   "1",
   "pre2",
   "pre1"
 ],
 "msg" : "connect"
}
[WebSocket] did receive JSON message: {
 "server_id" : "0"
}
Msg is invalid: {
 "server_id" : "0"
}
[WebSocket] did receive JSON message: {
 "session" : "xjtBZpQerMD6wnATe",
 "msg" : "connected"
}
Socket will send message: {
 "id" : "mRC5SWyizYdeESgoau6ddNeB8KFdagnv3blxmjYVKPrxwzBUgp",
 "method" : "public-settings\/get",
 "msg" : "method"
}`

**The Failure Response is as below :** 
`[WebSocket] http upgrade request (GET /websocket HTTP/1.1

Connection: Upgrade

Host: chat.mchat.com:443

Origin: wss://chat.mchat.com

Upgrade: websocket

Sec-WebSocket-Version: 13

Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits; server_max_window_bits=15

Sec-WebSocket-Key: ZGVyZWxxeWxjYm1sZG1tdQ==




)
[WebSocket] did disconnect with error (nil)
Socket will send message: {
 "id" : "dtDAgmzM7rVy1nrsaNXvBWpk5CJgjoaDENkTp5BkwyJB7XKyRb",
 "method" : "public-settings\/get",
 "msg" : "method"
}`


**Scenario :** 

1. Downloaded the code from RC Git portal
2. Tested RC, we loved the way it works, And decided to integrate the RC in our own Mobile app.
3. As per Read.me of RC's Git doc, we followed the steps, replaced the url of RC with our own server's url, 
4. App is connecting to our server 2-3 times then it just stuck.. with no error or no server hit. 


You will be life saver for us.. your any help will be highly appreciated..

**Comment by rafaelks** [comment]
@asshewale It would be very helpful if you could provide us the URL of your server. Or provide us the result of this request:

```shell
$ curl -i -N -H "Connection: Upgrade" -H "Upgrade: websocket" -H "Host: chat.youserver.com" -H "Origin: chat.youserver.com" -H "Sec-WebSocket-Key: fVXESE8fjBMx8HheW0YlZQ==" -H "Sec-WebSocket-Version: 13" https://chat.youserver.com/websocket
```

**Comment by cardoso** [comment]
@rafaelks looks like the connection is dropping before we ask for the public settings. Similar to what was happening in the authentication screen that we handled in #989

**Comment by asshewale** [comment]
Hi @rafaelks Thanks for your valuable time, Sure, our server URL is **"https://ctsichat.mvoipctsi.com"**, 
I hit the command on terminal as below =>
**On Mac mini -**
"Mac-mini:~ developer$ curl -i -N -H "Connection: Upgrade" -H "Upgrade: websocket" -H "Host: ctsichat.mvoipctsi.com” -H "Origin: ctsichat.mvoipctsi.com" -H "Sec-WebSocket-Key: fVXESE8fjBMx8HheW0YlZQ==" -H "Sec-WebSocket-Version: 13" https://ctsichat.mvoipctsi.com/websocket"

**Got the result as :**
only showing like -

"Mac-mini:~ developer$ curl -i -N -H "Connection: Upgrade" -H "Upgrade: websocket" -H "Host: ctsichat.mvoipctsi.com” -H "Origin: ctsichat.mvoipctsi.com" -H "Sec-WebSocket-Key: fVXESE8fjBMx8HheW0YlZQ==" -H "Sec-WebSocket-Version: 13" https://ctsichat.mvoipctsi.com/websocket"
>

**On Macbook -**
[Rahils-MacBook-Pro:~ arpitmakhija$ curl -i -N -H "Connection: Upgrade" -H "Upgrade: websocket" -H "Host: ctsichat.mvoipctsi.com” -H "Origin: ctsichat.mvoipctsi.com" -H "Sec-WebSocket-Key: fVXESE8fjBMx8HheW0YlZQ==" -H "Sec-WebSocket-Version: 13" https://ctsichat.mvoipctsi.com/websocket"

**Got the result as**
curl: (6) Could not resolve host: ctsichat.mvoipctsi.com -H Sec-WebSocket-Key
curl: (6) Could not resolve host: fVXESE8fjBMx8HheW0YlZQ== -H Sec-WebSocket-Version
curl: (1) Protocol "13 https" not supported or disabled in libcurl

Will you please correct me whether any problem is there with sockets...

Thanks.

**Comment by rafaelks** [comment]
@asshewale I was able to connect to your server here... can you try updating your server to the latest version? https://github.com/RocketChat/Rocket.Chat/releases

**Comment by asshewale** [comment]
@rafaelks  Hi , so i need to update the server only, i dont need to make any changes on our front end iOS code base..? Please correct me.

**Comment by rafaelks** [comment]
@asshewale Yes, update your server and lets try again.

**Comment by asshewale** [comment]
Hi @rafaelks  We tried upgrading the server to 0.59.6 we followed the steps and commands for 0.59.6 but the server auto updated to 0.59.4 only.. Now two times we are able to connect to our server swiftly and reliably, But if we tried to login 3rd time, its getting stuck. 

Steps How we are testing the app are as below : 
(We upgraded ther server to 0.59.6 , but server get upgraded to 0.59.4)
1. Installed the app
2. connected to our server
3. logged in with one user and got his all chat history
4. logged out from user one. 
5. logged in with user two and got his all chat history
6. kill the app and opened the app again, got all the data and history of user two instantly, we did the same thning most of times and we were able to play with the app swiftly and easily, like the way we want.
7. now we logged out from user two, and tried to login to user three, here we stuck.. here we are facing the never ending loop... 

Any idea @rafaelks  please... we are not able to understand or not able to trace why the same server is not able to accessible from 3rd attempt, Upgrading to 0.59.4 really helped us up to at least two attempts, we are really thankfull to you, but we are not able to understand the behaviour of app from 3rd attempt.

**Comment by rafaelks** [comment]
@asshewale I think the connection on the client-side is working just fine. I tried more then 3 times here in your server and it worked just fine. You may want to check your server/hosting reliability. My first attempt took too long to succeed.

**Comment by asshewale** [comment]
@rafaelks  Hi , ok Rafael, sure, we will check the server/hosting reliability, But will you please give me some areas that what should i check on server for reliability, means as you have more exposure on RC communication thats why i requesting you..

**Comment by asshewale** [comment]
Hi @rafaelks , one query apart from server issue, actually at one event i want to send a text message to other user with whome i am chatting programatically, for that in sendMessage() is the function in ChatViewController. 
Actually i want to send an attributed text in the message but though i am assigning attribted text to 'textView' still its taking it as a plain text. see.. how i am trying to assign the attributed text to textView.. as below..

`let attributedString = NSMutableAttributedString(string: "Click to join")
        attributedString.addAttribute(.link, value: "https://ctsivideo.mvoipctsi.com/1010", range: NSRange(location: 0, length: attributedString.length))
        textView.delegate = self
        textView.isSelectable = true
        textView.isUserInteractionEnabled = true
        textView.attributedText = attributedString
        textView.dataDetectorTypes = .all

        sendMessage()`


Then i reviewed the class SLKTextView.. with in that i found that one method is there 'slk_insertAttributedText' so i tried to assign the attributed text to textView as...

textView.slk_insertAttributedText(attributedString, in: NSRange(location: 0, length: attributedString.length))

but the app crashes at this place.. 

will you please help me how could i assign the attributed text to textView object please...
