### ISSUE TITLE
[BUG] Back Button in Login View Crashed the App if Multiserver Config is disabled

### ISSUE THREAD

**Issue by janrenz** [RocketChat/Rocket.Chat.iOS#1021]
- Your Rocket.Chat app version: 1.7.3
- Your Rocket.Chat server version: 0.59.3
- Device (or Simulator) you're running with: iPhone

If you set disable the Multiserver Config by setting a fixed hostname in the plist.info the app successfully skips the screen where this url is entered, but on the login screen the back button is still visible. If you then click the back button the app crashes.

**Comment by rafaelks** [comment]
@jprberlin I could not reproduce the crash. Could you send us the steps to reproduce it?

**Comment by jprberlin** [comment]
Independent of the crash, it makes no sense to show the back button if the server selection screen is not needed

**Comment by rafaelks** [comment]
@jprberlin I agree with you, but in this case, we need to make sure that if the connection was closed, we open the connection with the web socket again. You know? Have you tried this scenario?
