### ISSUE TITLE
[BUG] Links in messages don't work

### ISSUE THREAD

**Issue by BenjaminPrice** [RocketChat/Rocket.Chat.iOS#1026]
- Your Rocket.Chat app version: 1.7.3 (123)
- Your Rocket.Chat server version: 0.59.3
- Device (or Simulator) you're running with: iPhone 8 (confirmed on both iOS 11.1.2 & 11.2)

Links of all types, though most importantly #channel links do not work at all. Clicking them does nothing.

**Comment by cardoso** [comment]
@BenjaminPrice Thanks for bringing attention to this. Hopefully will be fixed on our next update.
