### ISSUE TITLE
We cant connect to our own server through https

### ISSUE THREAD

**Issue by reichert** [RocketChat/Rocket.Chat.iOS#103]
I don't have much information. All that appear in the screen is "Falha ao conectar ao servidor: abort. abort"
The same occurs with both the apple store version and the preview version. Only tested in iPhone 6 Plus with the latest IOS.

Regards!

**Comment by TheReal1604** [comment]
Hey @reichert, 

i used the google translator to translate your error message to english.. okay. It seems that on your server is an issue with the ssl-certificate chain. (Seen that thousand times before, with this failure..)

Please check your server configuration with: https://www.ssllabs.com/ssltest/ and post the result here.

**Comment by rafaelks** [comment]
@reichert Reichert, are you using the native version or the Cordova one?

**Comment by rafaelks** [comment]
@reichert What's your server URL? Maybe you're having the same problem as #106 .

**Comment by reichert** [comment]
Thanks for the answers!
Our URL is chat.angular-ecommerce.com and I believe the problem is the certificate chain. I already asked internally to change the certificate to a free one and see what happen. I'll update here when I have news.

Thanks!

The result from ssllabs:
Additional Certificates (if supplied)
Certificates provided	3 (3517 bytes)
Chain issues	Incorrect order, Contains anchor

**Comment by rikatz** [comment]
Same here, I think it's something about using a Self Signed Certificate / Invalid CA Certificate.

Is there an option to accept invalid certificates on IOS App?

Thanks

**Comment by reichert** [comment]
Hi, some new info:
@TheReal1604 We changed our certificate (that used to be a wildcard) to a [new one](https://www.ssllabs.com/ssltest/analyze.html?d=chat.angular-ecommerce.com&latest) and the problem persists;
@rikatz Our new certificate is not self-signed - it is issued by "Let's Encrypt"
- The chat server works well through Android and WEB
@rafaelks, the link to our server is in the link above

Anything I could do to help find the bug?
Regards.

**Comment by TheReal1604** [comment]
Hello @reichert, please do a check on the ssl qualys website mentioned above. Check if your certificate chain is complete.

**Comment by rafaelks** [comment]
@reichert What's your server URL?

**Comment by reichert** [comment]
chat.angular-ecommerce.com

--
Alessandro Reichert
CIO Partner Tecnologia da Informação
(11) 4114-0246

**Comment by rafaelks** [comment]
@reichert Seems that your SSL certificate isn't 100% correctly. You can test it here: https://www.ssllabs.com/ssltest/analyze.html?viaform=on&d=https%3A%2F%2Fchat.angular-ecommerce.com.

<img width="1079" alt="screen shot 2016-09-08 at 19 36 15" src="https://cloud.githubusercontent.com/assets/551004/18369351/a081bc9a-75fb-11e6-8d10-1ea36c72df55.png">
