### ISSUE TITLE
[CHORE] Replace deprecated Google pod

### ISSUE THREAD

**Issue by artrmz** [RocketChat/Rocket.Chat.iOS#1030]
Replace deprecated pod `Google/SignIn` with the newer pod `GoogleSignIn`.

*Questions:*
- Do we use Firebase? If so should we also include `pod 'Firebase/Core'` since it is not delivered with `GoogleSignIn` as it was with `Google/SignIn`
- Do we use `GoogleAnalytics`? If so -> `pod 'GoogleAnalytics'`

**Comment by rafaelks** [comment]
@artrmz Thanks for looking into it!

1. We don't use Firebase today in our iOS app, and we don't plan to use it;
2. No, we don't use Google Analytics;
