### ISSUE TITLE
fatal error: 'try!' expression unexpectedly raised an error: 

### ISSUE THREAD

**Issue by anappleapp** [RocketChat/Rocket.Chat.iOS#104]
Hi @rafaelks ,
When i run the App "branch: develop" i get this error, i am not sure what is it exactly, can you have a look please?
```
fatal error: 'try!' expression unexpectedly raised an error: Error Domain=io.realm Code=10 "Migration is required due to the following errors:
- Property 'lastSubscriptionFetch' has been added to latest object model.
- Property 'privateType' has been added to latest object model.
- Property 'otherUserId' has been added to latest object model.
- Property 'privateStatus' has been added to latest object model." UserInfo={NSLocalizedDescription=Migration is required due to the following errors:
- Property 'lastSubscriptionFetch' has been added to latest object model.
- Property 'privateType' has been added to latest object model.
- Property 'otherUserId' has been added to latest object model.
- Property 'privateStatus' has been added to latest object model., Error Code=10}: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-703.0.18.8/src/swift/stdlib/public/core/ErrorType.swift, line 54
```

**Comment by rafaelks** [comment]
@anappleapp Just remove the app from Simulator/Device and try again. This is happening because I changed the database scheme without doing a migration (we don't need to deal with it right now :-))

**Comment by anappleapp** [comment]
Thanks, it works now:)

**Comment by seirifat** [comment]
@rafaelks how if the App has been there in AppStore? we cannot force the user to uninstall the app before update. It's happen to my app, how is it? :)

**Comment by rafaelks** [comment]
@seirifat The app isn't in the store yet. I'm sure that after we've the first version in the store, we'll start doing database migrations ;-)

**Comment by oaksoeshein** [comment]
@seirifat how to add realm object new field name with https://realm.io/docs/swift/latest/#migrations
cause' previous version is in AppStore.

**Comment by tirthpatelflynn** [comment]
worked for me .. thanks

**Comment by reza-khalafi** [comment]
I deleted my app and install again. works good.

**Comment by abbasit786** [comment]
Thank God, it's working...

**Comment by BathiyaSeneviratne** [comment]
You Saved my day 🤩
