### ISSUE TITLE
How do i assign an attributed text in text area of chat which is the object 'textView' of class SLKTextView.

### ISSUE THREAD

**Issue by asshewale** [RocketChat/Rocket.Chat.iOS#1051]
Hi Devs actually at one event i want to send a text message to other user with whom i am chatting programatically, for that sendMessage() is the function in ChatViewController class.

Actually i want to send an attributed text in the chat but though i am assigning attribted text to 'textView' still its taking it as a plain text. see.. how i am trying to assign the attributed text to textView.. as below..

```
let attributedString = NSMutableAttributedString(string: "Click to join")
attributedString.addAttribute(.link, value: "https://cvideo.mvoip.com/1010", range: NSRange(location: 0, length: attributedString.length))
textView.delegate = self
textView.isSelectable = true
textView.isUserInteractionEnabled = true
textView.attributedText = attributedString
textView.dataDetectorTypes = .all

    sendMessage()
```

Then i reviewed the class SLKTextView.. with in that i found that one method is there 'slk_insertAttributedText' so i tried to assign the attributed text to textView as...

`textView.slk_insertAttributedText(attributedString, in: NSRange(location: 0, length: attributedString.length))`

but the app crashes at this place..

will you please help me how could i assign the attributed text to textView object please...

**Comment by rafaelks** [comment]
@asshewale We currently only support plain text into the TextView. You can use Markdown to add rich text features, and then it'll be rendered as attributedText in the chat messages list.

**Comment by asshewale** [comment]
@rafaelks  Thanks Mrakdown saved me , thanks a lot !!
