### ISSUE TITLE
[QUESTION] Notify other user to accept the video call initiated by user one (Video call by jitsi-meet from Rocket Chat)

### ISSUE THREAD

**Issue by asshewale** [RocketChat/Rocket.Chat.iOS#1057]
Hi Devs, 

We are trying to integrate Jitsi Video calling in Rocket chat, we succeeded to integrate the Jitsi SDK in Rocket chat, For that i have taken one button on chat window of rocket chat on tapping of which user navigating to Jitsi's video view controller, 

My problem is what, suppose 'user 1' and 'user 2' are chatting and 'user 1' want to have a video call with 'user 2' and for that he tap on video button then 'user 2' should get the video call invitation to accept it and start the video conference. 

The Web's Rocket chat app has the video button already on chat window of Rocket chat and also Web's Rocket chat has provided the settings from Admin's account to set the video call URL and room id names etc. so in web app of Rocket chat if 'user 1' taps on video button 'user 2' gets the invitation with 'Click to join' button in chat and video conference get starts in same window by tapping on button 'Click to join'.. 

As in iOS Rocket chat we dont have any default video button or any settings like web to allow the Jitsi video call to have confernce for users who are chatting, I took my own video button and landed user to next viewController and did the set up as per Jitsi's install guid, 
Which works for static Room ids, but i want it to work for different different users of different different sessions/logins.. 

Is there any thing is there in mobile Rocket chat to support Jitsi video calling like Web's Rocket chat..? Or how can i achieve the same functionality like web's Rocket chat+Jitsi in Mobile Rocket chat. 

Please.. Your any help will be highly appreciated.. 

Thanks

**Comment by asshewale** [comment]
Hi @rafaelks  could you please help me on this issue, i am really not able to get any clue or any idea that how should i implement the intended functionality, not able to find any steps or guide also.. Pleaes i am struggling hard for this.

**Comment by rafaelks** [comment]
Code in our back-end, for reference: https://github.com/RocketChat/Rocket.Chat/blob/master/packages/rocketchat-videobridge/client/views/videoFlexTab.js#L49

To generate the URL:
- You've to get the domain in a setting: `Jitsi_Domain`;
- The prefix (also a setting): `Jitsi_URL_Room_Prefix`; 
- Then a MD5 with `uniqueId` (server id + room id);

To identify a video message, I saw that in our web page we've this WebSocket call:

> {"msg":"method","method":"jitsi:updateTimeout","params":["8WmDXhgXSyKeGrF5LMHNCPQyQnzdjRPiuR"],"id":"20"}

But I've no idea how the "Click to Join!" button appear. Who would be the best person to help us here @rodrigok?

**Comment by asshewale** [comment]
Hi @rafaelks : thanks for your valuable time. 

I reviewed the back end code, Can't we have the same Jitsi support like web and cordova to Native..?

What i have done till now is..

1. Rocket chat with our server is working ideally and very well
2. Followed Jitsi installation guide and integrated Jitsi in our app, For that i have taken one ViewController (JitsiViewController) where we do have one View to which we assignes a 'JitsiMeetView' as a class as per the Jitsi Installation guide, Then 
3. Simply we loads our own server's Url in that View with the Method JitsiMeet'sObject.loadURLString("https://ctsiVideo.mvoipctsi.com/1010") : here in URL '1010' is conference ID which creates the new conference room and if other person used the same URL with same conference ID appended as above then that person enters in same conference and then they are able to have video conference in between. 
4. I have taken one video button on chat window of RC on top right, On tapping of that i am generating one random number that random number i am appending to our URL "https://ctsiVideo.mvoipctsi.com" to create a unique/seperate room each time, now i want that with whoever i am chatting, when i will tap on video button from chat window and will create a url by generating random number appended to it, I will send a text to other user from chat window that tap on the video button to connect with me in conference, and on tapping of video button from his chat window we both should be able to have a video conference.

Sorry i am bit exploring a lot but, i just want to have a video conferencing like the Web's RC app has..

**Comment by asshewale** [comment]
Hi @rafaelks  I want your little help for time being only, How can i get the last means rescent message in my chat window from person i am chatting with, Means suppost we both are chatting and you send me "Hi amol" , then if i want to access this message programatically then how can i get it.

**Comment by asshewale** [comment]
Hi @rafaelks In Rocket chat's native iOS app from App store(Rocket.chat app) on right side, we have the options 
'Room Info','Search Messages','Member List','Notifications','Files List','Mentions','Starred Messages','Keyboard Shortcuts','Pinned Messages','Off-the-record Conversation','**Video Call**', and 'Snippet Messages',

But when we are downloading the Rocket chat clone from Git and replaced the Rocket chat's URL with our and used/installed that app we are not able to find same options.

So is that Rocket.chat native app is Native iOS or its developed in Cordova.

**Comment by rafaelks** [comment]
@asshewale There are two version of Rocket.Chat right now in the App Store:

- **Rocket.Chat+**: native application, code is from this repository.
- **Rocket.Chat**: Cordova application, code is from this repository: https://github.com/RocketChat/Rocket.Chat.Cordova

**Comment by rafaelks** [comment]
Closing this issue since the questions are out of the topic.

**Comment by asshewale** [comment]
Hi @rafaelks  i am extremly sory for off topic question above about app, i am new to RC and Git also, 
But the root question is really related to our RC to jitsi connection like the Web RC, Please it will help me and other native developers also, even i am exploring my self in RC, its just my starting, Please will you open the issue, the main root question is really hard.... please

**Comment by rafaelks** [comment]
@asshewale I really don't understand your question. You also have a question related to Jitsi here: https://github.com/RocketChat/Rocket.Chat/issues/6773#issuecomment-350629736.

Can you explain what you need?

**Comment by asshewale** [comment]
Hi @rafaelks : Actually we are using Rocket chat with our server. 

With in that, we want to provide a video conferencing for the users who are chatting , 

for this functionality, the web version of Rocket chat do provide a support for Jitsi directly, under the Administration -> Settings from Admin login of web. 

on web rocket chat we do have the different option on right side , with in that we do have a video call button

So after doing this above settings from admin login from web RC,when web user of rocket chat (using our own server) initiates a video call other users gets the invitation to joine to that video conference, with in same window, 

So how could we achive the same functionality in iOS native RC , 

for that i have already searched a lot all around but no where under RC documentation or under Jitsi documentation i found any doc guiding us for video calling from native ios RC to jitsi.. 

If we acheived this functionality then it will really be helpful to all other developers too.. 

i am struggling for same from more than a week of time.  Please i do need your help for that.

**Comment by rafaelks** [comment]
@asshewale To make it clear: we don't have support for Jitsi yet in our app. In order to have Jitsi support, you'll have to integrate the SDK into the app and implement all the methods under WebSocket to communicate with Rocket.Chat's server. In what stage are you with it? What have you done already?

**Comment by asshewale** [comment]
@rafaelks I have integrated Jitsi SDK its fully working for static room ids, 

I have taken one Video button on top right corner of chat window of RC, i made it working for Peer-Peer for different users chatting seperately  (Its not ideal actually), 

It do not work for web to ios as call initiated from web RC didnt get recognized to native RC, 

also it fails for more than two people chatting together. 

Request : which classes are responsible for communication of RC to Jitsi means the WebSocket classes i am asking... so that i can study them and will give a try to implement same for native, of course if i need any help i will ask you. but first i will give my 100% . Please.

**Comment by rafaelks** [comment]
@asshewale This is something you'll be able to get from this question: https://github.com/RocketChat/Rocket.Chat/issues/6773#issuecomment-350629736, because they're related specifically to the WebSocket communication.

**Comment by asshewale** [comment]
ok @rafaelks thanks for your time and support.
