### ISSUE TITLE
[QUESTION] How should i get the message from chat window user tapped on programatically

### ISSUE THREAD

**Issue by asshewale** [RocketChat/Rocket.Chat.iOS#1069]
Hi Devs, 

I want to get the text of message from chat window on which user tapped, programatically. 

I am able to get the first and last message from chat messages like 
`let firstChatObj = String(describing: dataController.data.first?.message?.text)`
`let lastChatObj = String(describing: dataController.data.last?.message?.text)`,
but when i tried to access the message from chat with its index like ..
`var chatMessages = Array(dataController.data)`
`let lastMessageIndex = dataController.data.endIndex` 
`var data = chatMessages(lastMessageIndex)`
i am getting the error as below...
_"Can not call value of non-function type '[ChatData]'"_

>Also i am only able to get the first index and last index of chat messages, i want to get the index of message from chat on which message user tapped
>And i want to get its text

Will any one please help me for this please..

@rafaelks @rodrigok @cardoso please..

**Comment by cardoso** [comment]
Hi @asshewale! 😄 

For gestures you can look at ChatMessageCell.swift & ChatControllerMessageCellProtocol.swift

I hope that helps, but if you can explain better what you're trying to accomplish, I can give more specific directions.

**Comment by asshewale** [comment]
@cardoso  thanks for your valueable time, and helpful information. 

Actually i want, when user taps on particular message, then i will take the text of that message will check if it contains any URL, if it has the URL then i will compare it with our server URL and then i will have to show one pop up to user, it is one of the requirement actually. 

Thanks

**Comment by luismachado** [comment]
The app has already an openUrl somewhere in the code (which is used to open the URLs in the messages in a separate webview viewcontroller). 

You can probably override / edit that method in order to achieve what you need (which, to be honest, I'm yet to understand).
