### ISSUE TITLE
[QUESTION] Uploaded image don't show in App

### ISSUE THREAD

**Issue by fadanner** [RocketChat/Rocket.Chat.iOS#1075]
- Your Rocket.Chat app version: 1.7.4 (126)
- Your Rocket.Chat server version: 0.59.4
- Device (or Simulator) you're running with: IPhone 5s

When trying to upload a image (doesn't matter if from camera or from media library) the upload works fine. But the image doesn't show up in App. 
<img src="https://user-images.githubusercontent.com/7578777/33989751-dfdae2d4-e0c8-11e7-8819-cc9c38337d35.png" width=250px/>

In WebUI (withFirefox) on the desktop computer the picture shows up, but if trying to view the image, a error is shown.
<img src="https://user-images.githubusercontent.com/7578777/33989882-64460292-e0c9-11e7-8875-2551418ae8f9.png" width=100%/>
<img src="https://user-images.githubusercontent.com/7578777/33989925-804d3212-e0c9-11e7-95e8-2bb20f185b2f.png" width=100%/>
If trying to upload picture with firefox on the desktop computer everything works fine, the image shows up in app and browser.

Rocket.Chat server runs behind a nginx reverse proxy. NGinx logs following error when i try to load the image from any client.
`
2017/12/14 12:20:11 [error] 21136#21136: *30412802 upstream prematurely closed connection while sending to client, client: 10.11.13.1, server: xxx.example.com, request: "GET /file-upload/jzaNGjvqD7k8uPHH9/jakUHCacKjIliP79yxJN.jpeg HTTP/1.1", upstream: "http://10.10.1.xxx:3000/file-upload/jzaNGjvqD7k8uPHH9/jakUHCacKjIliP79yxJN.jpeg", host: "xxx.example.com", referrer: "https://xxx.example.com/direct/userXX"
`

Rocket.Chat itself doesn't log any errors neither on uplaoding nor on the request. 

Any suggestions where to look for?

**Comment by rafaelks** [comment]
@fadanner In order to investigate the issue, let me ask you a few questions:

1. What method of upload is your server using?
2. Does the URL is secured by SSL?
3. Is the generated URL from mobile different than the one generated when you upload from desktop?

Thanks,

**Comment by fadanner** [comment]
1. Server is using Filesystem upload
2. Server is secured with SSL between client and reverse proxy.  Connection from reverse proxy to rocket.chat is unsecured.

3. The http-Urls looks the same for me:
working image: https://xxx.example.com/file-upload/w9SLwG9X9jvwWhMMX/078EDBE7-45C4-4CCF-9C86-979E78E96D60.png
broken image: https://xxx.example.com/file-upload/jzaNGjvqD7k8uPHH9/jakUHCacKjIliP79yxJN.jpeg

the the first part of the url is random guid, the filenamepart is the generated filename. This is not the same, the app is using a random part here, too and it appends jpeg.

When i look into the data directory of the rocketchat server it is strange, that there is the jpeg extended, i think all with an extension here are the broken ones, but could not really test it for all.
<img src="https://user-images.githubusercontent.com/7578777/33993864-96b1bb5e-e0d8-11e7-99a3-174ab010ae45.png" width="70%"/>

**Comment by mxmo0rhuhn** [comment]
Same problem here:
Uploading a picture with the iOS client. 
- In the browser client pictures are shown 
- In the iOS App they are not
- In the Linux App they're also not 

Version: 0.59.4 (Which seems to be actually 0.59.6)
Storage Type: FileSystem

Can confirm that at least one Broken Picture has the .jpeg extension.

**Comment by rafaelks** [comment]
@mxmo0rhuhn @fadanner Can you guys give us access to your server (with a user) or give us a print screen of the exact same upload settings? We'll try to reproduce the issue.

**Comment by mxmo0rhuhn** [comment]
Well access to our prod servers will not be possible - we would have to put some work into deploying a staging system if it's really needed. 

For now: Our upload settings:
![latest-screenshot](https://user-images.githubusercontent.com/2327657/34130702-2111ebd4-e449-11e7-946a-f0071edb01c3.png)

**Comment by soundstorm** [comment]
We're just having the same or at least similar issue. I searched through the mongodb and noticed a mismatch of file size and "size" param. In our case "size" in mongo is e.g. 333782 and in filesystem 112995 and Safari tries to download full 334K, which leads to `Failed to load resource: Network connection was lost` (Server sends EOF) and blank image (builds up image until real file size reached, then waits until the error reported and switches to "image could not be displayed").

File shows up in Rambox client without a problem. Seems like some browsers/clients ignore this and show the file downloaded so far.

The original image was 1997083B 3024x4032 jpg, Server saved file as 112995B 1024x1366 jpeg, tries to download as 333782B jpeg.

**Comment by soundstorm** [comment]
Chrome and FF seem to ignore the bigger (pretended) file size but still try to download as many bytes as the header says. So just Safari/Webkit (Mac + iOS) seem to respect the header information, which is why I saw the images just in my Rambox client.

**Comment by soundstorm** [comment]
<details>
<summary>Analysis of Filesizes</summary>
<pre>
SIZE MISMATCH: MONGO 103667 - FS  29330
SIZE MISMATCH: MONGO 103667 - FS  29330
SIZE MISMATCH: MONGO 843472 - FS 384000
SIZE MISMATCH: MONGO 843472 - FS 384000
SIZE MISMATCH: MONGO 128660 - FS  43011
SIZE MISMATCH: MONGO 401760 - FS 180925
SIZE MISMATCH: MONGO 158451 - FS  75033
SIZE MISMATCH: MONGO 190593 - FS  76428
SIZE MISMATCH: MONGO 469538 - FS 189760
SIZE MISMATCH: MONGO 300708 - FS 123360
SIZE MISMATCH: MONGO 304329 - FS 145533
SIZE MISMATCH: MONGO 385197 - FS 130752
SIZE MISMATCH: MONGO 226542 - FS  88984
SIZE MISMATCH: MONGO 128956 - FS  45777
SIZE MISMATCH: MONGO 428377 - FS 165802
SIZE MISMATCH: MONGO 237150 - FS  86316
SIZE MISMATCH: MONGO 182542 - FS  82854
SIZE MISMATCH: MONGO 182542 - FS  82854
SIZE MISMATCH: MONGO 392665 - FS 140697
SIZE MISMATCH: MONGO 549776 - FS 216520
SIZE MISMATCH: MONGO 222073 - FS 102228
SIZE MISMATCH: MONGO 175973 - FS  50880
SIZE MISMATCH: MONGO 538672 - FS 200284
SIZE MISMATCH: MONGO 395724 - FS 156033
SIZE MISMATCH: MONGO 553070 - FS 220403
SIZE MISMATCH: MONGO 330323 - FS 111446
SIZE MISMATCH: MONGO 208276 - FS  72749
SIZE MISMATCH: MONGO 237746 - FS  74474
SIZE MISMATCH: MONGO 333630 - FS 123168
SIZE MISMATCH: MONGO 130069 - FS  61184
SIZE MISMATCH: MONGO 72373  - FS  33009
SIZE MISMATCH: MONGO 212477 - FS  72266
SIZE MISMATCH: MONGO 283368 - FS 131218
SIZE MISMATCH: MONGO 293963 - FS 100653
SIZE MISMATCH: MONGO 293963 - FS 100653
SIZE MISMATCH: MONGO 293963 - FS 100653
SIZE MISMATCH: MONGO 333782 - FS 112995
SIZE MISMATCH: MONGO 333782 - FS 112995
SIZE MISMATCH: MONGO 333782 - FS 112995
SIZE MISMATCH: MONGO 434765 - FS 182052
SIZE MISMATCH: MONGO 763831 - FS 312313
</pre>
</details>

<details>
<summary>Python script to fix MongoDB entries</summary>
<pre>
from pymongo import MongoClient
from glob import glob
import os

db_host = 'localhost'
db_port = 27017
db_name = 'rocketchat'
file_location = '/var/www/html/rocket.sndstrm.de/uploads/'

client = MongoClient(db_host, db_port)
db = client[db_name]
uploads = db.rocketchat_uploads

for upload in uploads.find():
        if upload['store'] == "GridFS:Uploads":
                continue
        f = glob(file_location + upload['_id'] + '*')
        if (len(f)):
                size = os.path.getsize(f[0])
                if size != upload['size']:
                        print("SIZE MISMATCH: MONGO %d - FS %d" % (upload['size'], size))
                        uploads.update_one(
                                {'_id': upload['_id']},
                                {'$set': {'size': size}}
                        )
</pre>

**Comment by rafaelks** [comment]
@mxmo0rhuhn @fadanner Can you guys try to see if the solution of @soundstorm works for you, please?

**Comment by mxmo0rhuhn** [comment]
Sadly due to our setup it is not that easy for us to perform this operation... 

However the approach seems very promising!

**Comment by soundstorm** [comment]
This could be seen as an migration fix, for normal operation this must be run continously, which is not good for productive environments.
Mid term fix: switch to GridFS (for single instance system not ideal)
Long term fix: check the calculation and fix that in code.

**Comment by rafaelks** [comment]
@mxmo0rhuhn @soundstorm I'm investigating the issue here, looks like is something wrong in our back-end code. I'll return to you guys as soon as I have an answer.

**Comment by rafaelks** [comment]
@mxmo0rhuhn If you get the fileURL, append `?rc_user=(your_user_id)&rc_token=(your_token)` does it work in the browser? I would love to have an example of URL that doesn't work in iOS but works on the browser.

**Comment by soundstorm** [comment]
@rafaelks
Safari + iOS App: fail if filesize doesn't match Content-Length (trying to get more after EOF)
Almost all other browsers discard the Content-Length if an EOF is received earlier.
Send the link via mail or how? Including token in public is not the best ;-)

**Comment by soundstorm** [comment]
Otherwise I can give you credentials for a [bot+user] user at our system and send you an image.

**Comment by rafaelks** [comment]
@soundstorm Yes, send me over email: `rafael.kellermann at rocket.chat`

**Comment by soundstorm** [comment]
@rafaelks Login credentials in your inbox [check spam?]

**Comment by rafaelks** [comment]
@soundstorm @mxmo0rhuhn OK, I'll try something... are you guys in our TestFlight? If not, send me your email to `rafael.kellermann at rocket.chat` and then you guys can help me testing it.

**Comment by soundstorm** [comment]
Confirmed! Great! Now just a simple python script migration until the public release.

**Comment by rafaelks** [comment]
@soundstorm Amazing, thank you very much for your help on tests! 👍

**Comment by MrBrobot1** [comment]
Having this issue currently with the latest snap I have available from Digital Ocean (0.74.2) on Ubuntu and the latest iOS app (Android apparently works fine) v3.3.1. The Rocket.Chat Experimental client v1.9.0 on iOS works fine. My site is behind an SSL cert (SSL only... HTTP is not accessible from the web).

**Comment by rafaelks** [comment]
@MrBrobot1 You don't see any assets, or just avatars?

**Comment by MrBrobot1** [comment]
> @MrBrobot1 You don't see any assets, or just avatars?

I'm not seeing any assets at all (no images, gifs, avatars, etc). For additional info, I'm using Caddy for a reverse proxy.

**Comment by rafaelks** [comment]
@MrBrobot1 Please contact me at open.rocket.chat: `rafael.kellermann`.
