### ISSUE TITLE
[NEW] Jit.si Integration - Initial remarks and ideas

### ISSUE THREAD

**Issue by luismachado** [RocketChat/Rocket.Chat.iOS#1076]
Hello,

I'll be attempting at integrating the Jit.si meet SDK into the chat.

However, after reading some of the webapp's code and some issues posted here (mainly #1057 and #6773) I wanted to share my thoughts and synthesise what should be needed:

- I won't approach the technicalities of the integration itself (at least for now :P) as that isn't a problem of RocketChat but of Jit.si itself. On broad strokes it should only be a case of:

     1.  Incorporating the SDK (or use a standalone app)
     2. Generate the url: (serverURL + prefix + randomString (UUID with slashes?) 
     3. Then segue to the jit.si view controller (or through deeplinking in case of the standalone app)

- The jit.si integration should work independently of the platform, so Web -> iOS / iOS -> iOS / iOS -> Web should be possible

- The Web -> iOS may be problematic as, from what I've gathered, when a new video call is created the other users receive a 'Click to Join' message. Looking at the JSON of that message it doesn't include any URL for the video room. Instead of that the javascript does a `Session.get('openedRoom')` on `actionLink.js`. I may be wrong about this thou, still have to review the code further...
Would I be able to get the link to the video call? I did a quick search on the API docs but didn't find anything regarding this.

- For video call created on the app, it should be easier but I'm torn between two approaches:

     1. Create the URL and post it as a message (using the REST API it should be quick and easy) before opening the new video call view. This will, however, differ from the webapp's approach
     2. I could, in theory, construct a similar message to display the "Click to Join" message but would that even work?

Would greatly appreciate your comments, hints or paths to follow. Thanks ;)

**Comment by luismachado** [comment]
[UPDATE]:

So I've been working on this on and off and managed to make some progress:

- [X] Grab the `serverId` and the `roomId` in order to build the MD5 Hash
- [ ]  Still have to grab the room prefix
- [X] Web -> iOS -> should be done too. 
      - The issue was that the actionLink didn't provided the videochatUrl but as I found out the url is fixed per room so I can build it in the app using the `serverId` and the `roomId.` 
      - I created a new cell chat view type to mirror the 'Click to Join!' of the webapp and I add that view to the chat cell stack when the `message.internalType == "jitsi_call_started" `
- [ ] The iOS - > Web might pose a problem thou:
      - If a simply create the videochat url and send it as a message it works okay (both to other iOS and to the web)
      - However I wanted to replicate the 'Click to Join' message to keep it seamless. I'm already creating the message correctly and the Web version displays it as it would if it was sent by another web client. HOWEVER if one clicks on the button (on the web client) it's going to say that the call already ended because the jitsiTimeout variable wasn't updated. This variable is accessed [here](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-videobridge/client/views/videoFlexTab.js#L81) and then it's refreshed by a timer until the call is closed. 

Now, this jitsiTimeout variable seems to be only accessed through Meteor but I could be wrong. Would it be accessible through the websocket?

This is probably the last piece of the puzzle :P

**Comment by rafaelks** [comment]
Great progress @luismachado! Do you have some branch that you could send us a PR so we could start looking into it? We're all very excited to have audio/video conversation support into the app.

Thank you!

**Comment by luismachado** [comment]
Hello @rafaelks, I'm taking some vacations right now but when I get back (in about 1.5 weeks time) I'll make sure to create a branch for this.

Happy holidays!

**Comment by luismachado** [comment]
@rafaelks created the PR #1126 for this ;)

**Comment by rafaelks** [comment]
@luismachado Thank you very much, I'll check it!

**Comment by luismachado** [comment]
@rafaelks okay! Things to keep in mind:
- The iOS -> Web issue described above is yet to be solved and, for now, I'm sending the chat url. You can change it [here](https://github.com/RocketChat/Rocket.Chat.iOS/pull/1126/files#diff-914164611cb69f4158d88d4fb8927685R393) by uncommenting this line and commenting the next one.
- Right now the url is being handled like a normal URL thus it will try to open the jit.si app through deeplinking. I already got it to work by adding the SDK files to the project (and it works) but I do get some random errors while building the app, due to the processor architecture the libs where build to.
