### ISSUE TITLE
[NEW] Search by messages in a channel/group/DM

### ISSUE THREAD

**Issue by bleomycin** [RocketChat/Rocket.Chat.iOS#1081]
Is it not possible to search conversations via the native ios app at this time? The only search box I can find is from the hamburger menu and that does not seem to search within conversations? I have to use the desktop client to search which is extremely annoying. Hopefully i'm missing something obvious?

**Comment by rafaelks** [comment]
@bleomycin Right now the app supports search for channels/groups/DMs, we currently don't support search over messages, but this is something we'll be supporting soon. I'll let this issue opened so we can work on that. Thanks!

**Comment by rafaelks** [comment]
DOCS: https://rocket.chat/docs/developer-guides/rest-api/chat/search/
