### ISSUE TITLE
Push Gateway https://gateway.rocket.chat/ is giving 502 Error

### ISSUE THREAD

**Issue by esolix** [RocketChat/Rocket.Chat.iOS#1085]
Looks like all our rocketchat ios is not getting notifications - due to https://gateway.rocket.chat/ giving 502

- Your Rocket.Chat app version: 0.59.6 (Updated to latest) (We have 3 different instances and installations - all has the same issues)

- Your Rocket.Chat server version: 1.74
- Device (or Simulator) you're running with: iPhone 8 Plus (IOS 11.2.1)

Looks like https://gateway.rocket.chat/ is down and not working correctly - Error of a message push we got on our log

`[34mI20171222-07:16:54.171(0) rocketchat_logger rocketchat_logger.js:375 [31mSystem ➔ error Error sending push to gateway (4 try) -> { [Error: failed [502] <html>  <head><title>502 Bad Gateway</title></head>  <body bgcolor="white">  <center><h1>502 Bad Gateway</h1></center>  <hr><center>nginx/1.10.2</center>  </body>  </html>  ]   response:     { statusCode: 502,      content: '<html>\r<br><head><title>502 Bad Gateway</title></head>\r<br><body bgcolor="white">\r<br><center><h1>502 Bad Gateway</h1></center>\r<br><hr><center>nginx/1.10.2</center>\r<br></body>\r<br></html>\r<br>',      headers:        { server: 'nginx/1.10.2',         date: 'Fri, 22 Dec 2017 07:16:54 GMT',         'content-type': 'text/html',         'content-length': '173',         connection: 'close' },      data: null } } 
`
Thanks

**Comment by esolix** [comment]
Thanks for getting the gateway back up! it is working now. I wonder if we have a way to setup self hosted gateway without the need to compile our own apps (using official apps)

**Comment by rafaelks** [comment]
@esolix There isn't, because you would need access to the certificates.
