### ISSUE TITLE
[BUG] Check if it's possible to force a new sync every time user opens the app

### ISSUE THREAD

**Issue by rex4539** [RocketChat/Rocket.Chat.iOS#1086]
- Your Rocket.Chat app version: 1.7.4 (126)
- Your Rocket.Chat server version: https://chat.zcashcommunity.com/
- Device (or Simulator) you're running with: iPhone 6s

Steps:
1. Log in as A from device A.
2. Connect to a server A on device A.
3. Add some channels on device A.
4. Log in as A from device B.
5. Connect to server A on device B.

What happened:
Not all channels are synced.

Expected result:
All channels are synced.

**Comment by rafaelks** [comment]
@rex4539 Can you be more specific? What things are not synced?

**Comment by rex4539** [comment]
See screenshots from device A and device B.

Device A has 6 channels and device B has 5 channels. zcash-dev is not syncing.

![device a](https://user-images.githubusercontent.com/227442/34328706-dc8559f6-e8ee-11e7-8113-0413d7a61e50.png)
![device b](https://user-images.githubusercontent.com/227442/34328707-dcbf8dec-e8ee-11e7-9323-188b4c1e5a4a.png)

**Comment by rafaelks** [comment]
@rex4539 Hum... I see! Does it sync after you kill the app and open again?

**Comment by rex4539** [comment]
No, I have tried everything.

Sending and receiving messages on that channel, restarting phone, logging out of server and logging back in.

No luck :)

**Comment by rafaelks** [comment]
@rex4539 Wondering if by some reason this room would not appear in the mobile app... do you mind uninstalling the app and installing again, to see if it shows?

**Comment by rex4539** [comment]
Uninstalling/reinstalling fixed it.

Though it would be good to investigate why it happens and fix the bug.

**Comment by rafaelks** [comment]
Sure thing. Wondering what happened. Would be good to have steps to reproduce it. Do you remember what/how you did?

**Comment by rex4539** [comment]
Steps are included in the original post.

I did try to reproduce but was unable to.

**Comment by rex4539** [comment]
I just upgraded to 1.8.0 (137) and the bug reappeared.

I see 5 channels on my iOS device while I have 10 channels on my Mac.

I think the app needs to perform some kind of sync on each launch.

If it's using some sort of caching, it is obviously not working.

**Comment by rex4539** [comment]
Also, this time, deleting and reinstalling the app didn't fix it.

This bug needs to be fixed ASAP.

**Comment by rafaelks** [comment]
@rex4539 Are you using some custom server or is it hosted in our cloud? This issue is only happening with you AFAIK. Could you tell me what's your server URL?

**Comment by rex4539** [comment]
https://chat.zcashcommunity.com/

**Comment by mineZcash** [comment]
I have updated the server to help with this issue.

I just wish one of the apps worked well. Right now users are asked to choose Rocket.chat or Rocket.chat+ apps (which is confusing especially considering that the Android App store recommends Rocket.chat first and Apple Store recommends Rocket.chat+ first, both of which have poor reviews)

The Cordova Rocket.chat app is still not showing notifications or unread rooms correctly since the update. And the Native Rocket.chat+ version is currently unable to provide full functionality or theme based on the server's settings. So we now have 2 half-working apps :/

**Comment by rafaelks** [comment]
@mineZcash We're working really hard to fix this issue. Our iOS is currently the most advanced in terms of features (search for Rocket.Chat+) and our Android native app is now being rewritten. I'm sure soon we'll have much better native apps. Stay tuned! 👍
