### ISSUE TITLE
Caller Banner cuts input field

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat.iOS#1093]
When the caller banner (or active GPS) is visible, the message input field is cut off when cold starting RC+. As soon as keyboard shows up (or input field comes up by switching back to RC+) for the first time it's okay again.

**Comment by artrmz** [comment]
Related to #923

**Comment by soundstorm** [comment]
So let's close this as they are similar. Reference now exists, we can discuss it over there :)
