### ISSUE TITLE
[NEW] Add reaction to message

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat.iOS#1096]
In the current build we can already add reactions if other users already added this emoji to the message. We need a option to add different [new] emojis.

**Comment by rafaelks** [comment]
@soundstorm Do you mind creating different issues to each action/feature missing? This way someone can refer the issue in the PR and close it. Thanks!

**Comment by cardoso** [comment]
> - [ ] add reaction (different emoji than already added ones)

We'll have 🔝 when #1084 is merged 😄

**Comment by soundstorm** [comment]
@cardoso long press is now #1100
#1084 looks well!

**Comment by cardoso** [comment]
Duplicate from #1084
