### ISSUE TITLE
[NEW] Long press of reaction emoji = list of users

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat.iOS#1100]
When long (or force) pressing a reaction emoji a list of users could pop up.
{n} person[s] reacted with {emoji}
 - {user1}
 - {user2}

**Comment by RahulDhiman93** [comment]
Can I work on this?

**Comment by RahulDhiman93** [comment]
Exactly which emoji are we talking about?

**Comment by soundstorm** [comment]
@RahulDhiman93 
If someone already reacted to a message, a long press of the emoji below the message.
