### ISSUE TITLE
[NEW] Translate "Add reaction"

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat.iOS#1107]
Currently there is just "Add Reaction" in english, which file do I need to modify to translate? ;)

**Comment by rafaelks** [comment]
Ops, looks like we didn't translate this one @cardoso: https://github.com/RocketChat/Rocket.Chat.iOS/blob/8e4dfe912bebcd3e7a026403993990b2583b4e1a/Rocket.Chat/Controllers/Chat/ChatControllerMessageActions.swift#L15.

**Comment by cardoso** [comment]
Oops! I'll add that to our localization files!

**Comment by cardoso** [comment]
@soundstorm can you help us with the german translation at #1109?

**Comment by soundstorm** [comment]
"Reaktion hinzufügen" would be okay.
But seems that the submenus are missing too 😅
So we got:
Choose a reaction: "[Eine] Reaktion auswählen" ("Eine" is optional)
Search for an emoji: "Nach einem Emoji suchen"
Frequently used: "Oft benutzt"
Categories also translated?
"Smileys & Personen", "Tiere & Natur", "Essen & Trinken", "Aktivität", "Reisen & Orte", "Objekte", "Symbole", "Flaggen"
And now: fun with flags 🇩🇪

**Comment by soundstorm** [comment]
I'll modify the current version to fully translate the german file, so we're able to merge that later when everything has an identifier.

**Comment by cardoso** [comment]
Great @soundstorm! Thanks for the help!
