### ISSUE TITLE
[BUG] Admin page not loading

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat.iOS#1111]
I just tried to open the admin page on our server with 0.60.2 in Build 132, but it just shows a spinning wheel and then a blank page.

**Comment by rafaelks** [comment]
@soundstorm Do you have access to the admin panel on the web? What's your server URL (send me in private if you want to).

**Comment by rafaelks** [comment]
OK, so we'll have to handle when the SiteURL setting ends with `/`.
