### ISSUE TITLE
[BUG] Critical issue missing messages in channel

### ISSUE THREAD

**Issue by SamSaffron** [RocketChat/Rocket.Chat.iOS#1113]
We are running hosted rocket chat and I am using the latest app via testflight. 

The app appears to have an issue "recovering" messages when a connection is interrupted. 

For example now I have a gap 8:19pm yesterday till 2:20am, where the app shows 0 messages yet in reality there are a big bunch of messages in the room. 

This is pretty much a blocker for me cause I can not trust that the app is showing me all the information. 

Since this is clearly the most important bug to sort out can I suggest a way of attacking it? 

- Add a "refresh" button in the channel options
- "refresh" should query for all messages from the 1st in local db till last in local db
- If there is an discrepancy, allow me to post diagnostics information 

I think the underlying bug is around timeline recovery, a simple workaround would be to chuck out history in the apps local db in smarter way so gaps are not possible. 

- always ask for n-1 messages when re-connecting
- if n-1 message does not match the message in the app, throw away local db

**Comment by rafaelks** [comment]
@SamSaffron Thanks for opening the issue! Investigating the issue, I think I got what's going on... let me explain what the app is doing right now:

1. When the app starts, we load local database messages from database on screen (20 latest messages);
2. At the same time, we request the latest 30 messages from that room and update the database;
3. When you scroll up (4 messages before the end) we request another 60 messages from the API and update our DB. If you have local messages at this point, we also show them (at the same time we do the request);

I reproduced the issue with a very simple test. Sent 32 test messages and opened the app, it was missing exactly 12 (GIF below).

What I'm going to do now: I'll increase the size of the history size to 60 and fetch the latest 20 from database, so we'll always fetch a bigger number than what we've on the app. After doing that, my test got "fixed". I'll make a PR and send another TestFlight build right now so you can help me testing it.

![2018-01-05 04 38 04](https://user-images.githubusercontent.com/551004/34603604-961d9edc-f1d2-11e7-8efd-64b0bc993def.gif)

**Comment by SamSaffron** [comment]
Thanks heaps for the quick fix, have not seen the issue anymore over the weekend, will let you know if it happens again

**Comment by rafaelks** [comment]
@SamSaffron Awesome, that's great to hear! 👍

**Comment by SamSaffron** [comment]
Sorry to report but this needs to be reopened still happening if there are
more than 50 messages in a gap

**Comment by crsCR** [comment]
I'm getting similar with Android app, Mac app, various browsers... Not sure if related.

https://github.com/RocketChat/Rocket.Chat/issues/9404
