### ISSUE TITLE
[BUG] Users getting mixed between servers

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat.iOS#1121]
Typing eg `@he` on our server (just one person has "he" in his name) shows `bshelton`, `michelle.loveless`, `rob.mitchell.chisholm` and the user I wanted. The three user names are belonging to open.rocket.chat (which is at second position if this is relevant again). Trying to archive the same when switching to open.rocket.chat fails.

**Comment by cardoso** [comment]
Yes, this is still happening 🙁 

Thanks for opening the issue

**Comment by soundstorm** [comment]
Working, but takes it time to fetch all usernames :)
