### ISSUE TITLE
[NEW] In-App Notifications

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat.iOS#1125]
While on desktop you see the whole sidebar, on mobile you just see your current channel.
So at least a unread messages dot on the top bar ≡ would be great and as a second step small banners, maybe just a single line overlaying the iOS status bar, so you don't get distracted too much (like regular iOS notification banners).

![Animation](https://user-images.githubusercontent.com/193273/34656333-5af6efdc-f418-11e7-80ae-00d4ae4a36c3.gif)

**Comment by rafaelks** [comment]
Sounds nice @soundstorm! I think we can do something more similar to Telegram/WhatsApp... it's a view with black background (translucent) that first 2 or 3 lines of the message. What do you guys think?

**Comment by soundstorm** [comment]
@rafaelks would be okay too, as soon its overlay is not higher than the channel top bar.
![iap notification](https://user-images.githubusercontent.com/193273/34676605-ab313564-f48d-11e7-9cb7-9d0409c2baef.png)

**Comment by rafaelks** [comment]
@soundstorm Yes, that sounds perfect. I think we can reduce the font size also. But looking pretty good!
