### ISSUE TITLE
[BUG] Error when trying to add screenshot

### ISSUE THREAD

**Issue by rex4539** [RocketChat/Rocket.Chat.iOS#1139]
- Your Rocket.Chat app version: 1.8.0 (137)
- Your Rocket.Chat server version: I don't know
- Device (or Simulator) you're running with: iPhone 6s (iOS 11.12.5)

Reproducibility: always

Steps:
1. Take a screenshot.
2. Try to add it to a conversation.

What happened:
Error is thrown.

![img_1850](https://user-images.githubusercontent.com/227442/34732975-82de30de-f56f-11e7-8d4c-4b99fe6e3767.PNG)

Expected result:
Screenshot is added.

**Comment by rafaelks** [comment]
@rex4539 Is this still happening after you updated your server?

**Comment by rex4539** [comment]
Fixed.
