### ISSUE TITLE
Sidemenu errors

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat.iOS#114]
Swapped my ruby version to 2.3.1 and did pod install.. no errors.  But when building I get:

![image](https://cloud.githubusercontent.com/assets/51996/18329143/b9a64ed2-7517-11e6-945f-a01a6162b881.png)

Ideas?

**Comment by rafaelks** [comment]
@geekgonecrazy You opened the `Rocket.Chat.xcworkspace` or `Rocket.Chat.xcodeproj`?

**Comment by geekgonecrazy** [comment]
@rafaelks I opened `Rocket.Chat.xcworkspace` It had Rocket.Chat and the pods displayed in it.  

![image](https://cloud.githubusercontent.com/assets/51996/18357557/0d204938-75b7-11e6-85e8-70c6901c79af.png)

**Comment by rafaelks** [comment]
@geekgonecrazy Cool! You're using Xcode 8 or 7? We're not supporting new Xcode yet, since it requires Swift 2.3+.

**Comment by geekgonecrazy** [comment]
@rafaelks look like i'm on XCode `Version 7.1.1`  So that shouldn't be the issue.  I've been holding off on Xcode 8

**Comment by rafaelks** [comment]
@geekgonecrazy OK, maybe this is the issue. Can you update your Xcode to 7.3.1?

**Comment by rafaelks** [comment]
@geekgonecrazy I'll close the issue, let me know if it works fine for you on 7.3.1.

**Comment by geekgonecrazy** [comment]
@rafaelks that seemed to do the trick.  👍
