### ISSUE TITLE
[QUESTION] Better conversation view like iMessage? (suggestion: JSQMessagesViewController)

### ISSUE THREAD

**Issue by internalG** [RocketChat/Rocket.Chat.iOS#1154]
How about popular JSQMessagesViewController to enhance current collection view?

**Comment by rafaelks** [comment]
@internalG Why do you think that's important? How do you think it would fit this project?

**Comment by soundstorm** [comment]
I still like the monotonic but yet clean view without the distinction between own messages on the right and foreign messages on the left. Also we got more space to use.
For some applications you want to see all timestamps, like logging. The swipe to the left is just a additional step and not persistent.

JSQMessageViewController is perfect for regular chats, but don't think it's good for this kind of [business] platform.

**Comment by rafaelks** [comment]
@internalG I agree 100% with you, we do have a lot of room to improve, I just don't think adding a lib like that would helps to achieve this goal. At the same time we need to improve, we also need to keep the same "style" of our web clients. Do you have any idea on what we could start improving in our list of messages?

**Comment by rafaelks** [comment]
Closing this one for now, if some suggestion appear, let's use our forums to discuss: https://forums.rocket.chat/c/feature-requests
