### ISSUE TITLE
[NEW] Authentication GitLab

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.iOS#1161]

**Comment by internalG** [comment]
Another side question is how about other authentications, CAS, LDAP, SAML? I can't find any API for mobile apps.

**Comment by rafaelks** [comment]
@internalG LDAP is already being supported. CAS and SAML isn't implemented and we don't have docs about that yet. Do you want to implement these authentication methods?

**Comment by internalG** [comment]
CAS is my first topic. I'll try it later.

**Comment by rafaelks** [comment]
@internalG Do you have any server & test user that we could use in order to implement it?

**Comment by internalG** [comment]
I have a local CAS testing server that need to integrate with RC server. It's better that we can find a public CAS server for production testing. And I can't find any REST api of CAS login on Rocket server!

https://github.com/apereo/cas
https://github.com/rubycas/rubycas-server
