### ISSUE TITLE
[I18N] [BUG] No more localization 

### ISSUE THREAD

**Issue by VassiliM** [RocketChat/Rocket.Chat.iOS#1162]
- Your Rocket.Chat+ app version: 1.8.0 (137) and previously 1.7 (126)
- Your Rocket.Chat server version: 0.60.2
- Device (or Simulator) you're running with: Iphone IOS 11.1.1

My Rocket.chat server is in french. My iphone is in french, my rocket.chat+ and rocket.chat apps were in french.
I made an upgrade from 1.7 (126) to 1.8.0 (137)... and now rocket.chat+ app is in english (and i can't modify as there is no menu for that) , while rocket.chat app remains in french.

Would it be possible to have the localization ?

**Comment by soundstorm** [comment]
You can translate following file (seems like it should show up mixed en and fr):

https://github.com/RocketChat/Rocket.Chat.iOS/blob/develop/Rocket.Chat/fr.lproj/Localizable.strings
