### ISSUE TITLE
[BUG] Spotlight not working

### ISSUE THREAD

**Issue by JamesMilneFilmlight** [RocketChat/Rocket.Chat.iOS#1164]
Using Rocket.Chat+ on iOS, it is not possible to send a Direct Message (DM) to a user that you haven't previously sent a direct message to via some other Rocket.Chat client, like the web interface.

The search box on iOS needs to include all users on the server, so that you can start a new DM channel with them.

This works fine via the web interface.

**Comment by cardoso** [comment]
Thanks for bringing light to this issue @JamesMilneFilmlight . It will be fixed on our next release. Stay tuned!
