### ISSUE TITLE
[NEW] Mark as read on quick reply

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat.iOS#1171]
If using the quick reply from notification center the messages in the channel stay currently unread.

**Comment by soundstorm** [comment]
Is the SocketManager available in background?
Then we could simply add
```swift
            let request = [
                "msg": "method",
                "method": "readMessages",
                "params": [notification.roomId]
            ] as [String: Any]
            SocketManager.send(request) { response in
                guard !response.isError() else { return Log.debug(response.result.string) }
            }
```
to [PushManager.swift](https://github.com/RocketChat/Rocket.Chat.iOS/blob/develop/Rocket.Chat/Managers/PushManager.swift#L170)
Otherwise we need to create a new session on socket just for pushing this message, as there is currently no REST endpoint for this.

**Comment by cardoso** [comment]
Yeah @soundstorm , we need to do this via HTTP. Thanks for opening the issue on the main repo.

**Comment by rafaelks** [comment]
@cardoso @soundstorm This is actually kind of "tricky"... Let's suppose you're in a channel with 100 messages unread, then you receive a mention and you quick reply it. Should we mark all the 100 messages as read? I don't think so... BUT that make sense for DMs I think.

**Comment by soundstorm** [comment]
With 0.62.0-rc.0 we now have the API to do that, thanks @rafaelks

**Comment by soundstorm** [comment]
@rafaelks @cardoso as I have no paid tier/not in the same team to have the tokens I can't test push notifications :( So anyone of you has to do this...

**Comment by rafaelks** [comment]
I think this can actually be bad for the user... just because you replied to a notification it doesn't mean you read the whole thread. Let's close this for now until we change our minds (opinions on this are welcome!)
