### ISSUE TITLE
[QUESTION] Client certificate authentication -> "Error Domain=WebSocket Code=4 "write wait timed out"  

### ISSUE THREAD

**Issue by jarrillaga** [RocketChat/Rocket.Chat.iOS#1176]
- Your Rocket.Chat app version: Last version
- Your Rocket.Chat server version: Last version
- Device (or Simulator) you're running with: Device & Simulator

Hi All, I added support for Client certificate authentication as it is described in other posts. I loaded the certificate OK because I´m watching the traces with Wireshark but I don´t know why the socket connection is giving a timeout. 

The error is: [WebSocket] wss://rocketchat.collectivetheory.io/websocket
 - did disconnect with error (Optional(Error Domain=WebSocket Code=4 "write wait timed out" UserInfo={NSLocalizedDescription=write wait timed out}))

I really need your help in order to figure out the problem. 

Thanks in advance.
Juan

**Comment by rafaelks** [comment]
@jarrillaga I'm trying to make the Upgrade request here and it says your certificate isn't valid.

```
➜  ~  curl -i -N -H "Connection: Upgrade" -H "Upgrade: websocket" -H "Host: rocketchat.collectivetheory.io" -H "Origin: rocketchat.collectivetheory.io" -H "Sec-WebSocket-Key: fVXESE8fjBMx8HheW0YlZQ==" -H "Sec-WebSocket-Version: 13" https://rocketchat.collectivetheory.io/websocket
curl: (35) error:14094412:SSL routines:SSL3_READ_BYTES:sslv3 alert bad certificate
```

What kind of certificate are you using?
