### ISSUE TITLE
Application Extremely Slow

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [RocketChat/Rocket.Chat.iOS#118]
Rocket Chat native app working very slow in IPhone or Ipad. 
Issue 1. If you type message letters appear with delay. I think it can be binded with auto-completion which not possible to disable. 
Issue 2. If you finished typing and lock your iphone or ipad(to blank screen). After you unlock screen again and focus to application it reload whole page including elements which can be easy cached. 
Issue 3. On Iphone 4S RocketChat app drain battery with speed about 20 % per hour.  It is bigger than video playback. Bigger even than some games.  
Issue 4. (Ergonomic) 
On iphone screen it is not enough space to chat because almost all screen busy with not important elements.

**Comment by rafaelks** [comment]
@jpVm5jYYRE1VIKL You're talking about the [Cordova app](https://github.com/RocketChat/Rocket.Chat.Cordova), not the native one.

**Comment by jpVm5jYYRE1VIKL** [comment]
I know exactly about what i tell . 
i using application which i downloaded using this link 
https://geo.itunes.apple.com/us/app/rocket.chat/id1028869439?mt=8

**Comment by rafaelks** [comment]
@jpVm5jYYRE1VIKL Yes, this is the Cordova one. The application from this repository isn't in the App Store yet.

**Comment by jpVm5jYYRE1VIKL** [comment]
Ok. thanks.Will post it there.
