### ISSUE TITLE
[BUG] Emoji reaction size x2

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat.iOS#1181]
This occurred on an iPhone 6s of a friend using the current 1.8.0 store version
The emoji scales x2 (and the container width too, on lower side simply cut off, not cropped by me).

![bigger reactions](https://user-images.githubusercontent.com/193273/35170011-f81b8468-fd5e-11e7-8b1d-cb79beafdbc6.jpeg)

**Comment by rafaelks** [comment]
@cardoso Do you mind taking a look on this one?

**Comment by cardoso** [comment]
Any steps to reproduce this?

**Comment by soundstorm** [comment]
@cardoso I'm trying but don't know how he got that. Zooming and larger font was switched off.

**Comment by cardoso** [comment]
I think we have some small and rare issues with message cell layout, I'll keep an eye out for them and try to find the cause.

**Comment by jselleck** [comment]
We have a problem with custom emoji's as well.  Odd shaped emojis get cropped instead of scaled to fit and some seem to be zoomed and cropped.

**Comment by cardoso** [comment]
Can you show a screenshot @jsellect? Maybe a link to the server?

Is it happening in the reaction view or inside the messages?

**Comment by jselleck** [comment]
It's in both messages and the selection:

![image](https://user-images.githubusercontent.com/22174775/35992740-67fcb770-0cc8-11e8-81af-46a1e265e01e.png)

![image](https://user-images.githubusercontent.com/22174775/35992761-7532114c-0cc8-11e8-8860-816f998fa50e.png)

I see this in both the web and the windows client.

**Comment by jselleck** [comment]
@cardoso Let me know if you need anthing else.  Thanks!

**Comment by jselleck** [comment]
Issue created here: https://github.com/RocketChat/Rocket.Chat/issues/9643

**Comment by rafaelks** [comment]
Just reproduced the issue @cardoso, happens on iOS 10.3.3.
