### ISSUE TITLE
[BUG] Channel creation - invited users are not added to the new created channel

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat.iOS#1184]
- Your Rocket.Chat app version: 1.8.0 (137) -> this issue is also happening in 2.0.0 (138)
- Your Rocket.Chat server version: 0.60.2
- Device (or Simulator) you're running with: iPhone 8

How to reproduce?

1. Go to the create a channel screen
2. Select a channel name
3. Add some users via the Invite Users screen on channel creation
4. create the channel

-> The added users are not added to the new created channel

What to expect?
-> The added users are added to the new channel

For reference: https://github.com/RocketChat/Rocket.Chat.iOS/pull/963

**Comment by rafaelks** [comment]
@TheReal1604 It does work for me... are you always able to reproduce it?

**Comment by TheReal1604** [comment]
Yes.
