### ISSUE TITLE
[NEW] Chat Privacy

### ISSUE THREAD

**Issue by RahulDhiman93** [RocketChat/Rocket.Chat.iOS#1187]
what if one of the user take screenshot of the chat. Other user should get notified about this screenshot.

**Comment by rafaelks** [comment]
Why do you think that? How would that notification work?

**Comment by RahulDhiman93** [comment]
what If someone don't want there messages to be seen to a particular group. I am not saying this feature should be activated always. Its up to users , they may to activate or not.

**Comment by rafaelks** [comment]
We would have to support this feature in our back-end also. Can you open the discussion [here](http://github.com/RocketChat/Rocket.Chat/) and then reference this issue? I'll close this one for now.
