### ISSUE TITLE
textfield in App

### ISSUE THREAD

**Issue by anappleapp** [RocketChat/Rocket.Chat.iOS#119]
Hi, 
When i run the App all it works, just there is one problem that i cannot write through the App to platform. 
Are you going to add it or already there is :? I mean textfield to write new message through the App.

Thanks :)

**Comment by black-lotus** [comment]
@anappleapp i am working on it, but i don't know the documentation about rocket.chat web socket.
I didn't found any documentation about write new message or reply message in https://rocket.chat/docs/

**Comment by rafaelks** [comment]
@anappleapp @black-lotus We're working on it, it's not finished yet.
