### ISSUE TITLE
Push Gateway (https://gateway.rocket.chat) is down 

### ISSUE THREAD

**Issue by esolix** [RocketChat/Rocket.Chat.iOS#1190]
Before writing an issue, please make sure you're talking about the native application (called Rocket.Chat+ in the App Store) and not the Cordova one (called Rocket.Chat in the App Store). If you are looking to open an issue to the Cordova application, go to this URL: https://github.com/RocketChat/Rocket.Chat.Cordova.

- Your Rocket.Chat app version: 0.60
- Your Rocket.Chat server version: 1.80
- Device (or Simulator) you're running with: ####

https://gateway.rocket.chat Is showing 502 Bad Gateway - push stopped working

**Comment by rafaelks** [comment]
@esolix Thank you! We're working to fix that.
