### ISSUE TITLE
Not able to upload a picture / "File size is too small"

### ISSUE THREAD

**Issue by samoyedskaya** [RocketChat/Rocket.Chat.iOS#1196]
I'm not able to upload any picture using the iOS app. The error message says "File size is too small (min = 1) [file-too-small]".

- Your Rocket.Chat app version: 1.8.0 (137)
- Your Rocket.Chat server version: 0.59.6

**Comment by rafaelks** [comment]
@samoyedskaya This is a known issue already, could you update your server to the latest stable version? 0.60.0+ is fine. Otherwise, you'll have to wait until the next iOS release. Thank you!

**Comment by samoyedskaya** [comment]
Sure! Thank you!
