### ISSUE TITLE
Avatar branch.

### ISSUE THREAD

**Issue by anappleapp** [RocketChat/Rocket.Chat.iOS#120]
Hi @rafaelks,

When i run the Avatar branch, i get this error. :(  can you help me please with that  :) 

![screen shot 2016-09-15 at 2 18 24 pm](https://cloud.githubusercontent.com/assets/11163232/18549537/6ac00f2c-7b4f-11e6-839e-ca0a7bc13772.png)
![screen shot 2016-09-15 at 2 18 24 pm](https://cloud.githubusercontent.com/assets/11163232/18549538/6b6ae8e8-7b4f-11e6-80ec-48ebddc0ec11.png)

**Comment by rafaelks** [comment]
@anappleapp `feature/avatar_initials` branch is still in development (not merged yet). If you want to run the project, use the `develop` branch.

**Comment by anappleapp** [comment]
Thanks @rafaelks
