### ISSUE TITLE
[IMPROVEMENT] Add an alert before deleting a message just so user can confirm it

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.iOS#1201]
Before deleting a message, show an alert with this properties:

**Title:** Delete this message?
**Text:** Are you sure you want to delete this message? This process can't be undone.
**Options:** (No) -- (Yes, delete it)

**Comment by soundstorm** [comment]
So you may move the ask() from #1169 and use it here? :)

**Comment by rafaelks** [comment]
@soundstorm Sure thing!
