### ISSUE TITLE
[NEW] Support Universal URLs

### ISSUE THREAD

**Issue by cardoso** [RocketChat/Rocket.Chat.iOS#1209]
We support deep links as of #1202 

We need to support universal URLs too:

https://deeplink.rocket.chat/auth?host=foo.bar.com/chat:3000
https://deeplink.rocket.chat/auth?host=foo.bar.com/chat:3000&token=123&userId=1234
https://deeplink.rocket.chat/room?host=foo.bar.com/chat:3000&rid=important&path=group/important

**Comment by rafaelks** [comment]
@cardoso Do you have the other issue code so we can monitor?
