### ISSUE TITLE
Error in Avatar Branch

### ISSUE THREAD

**Issue by anappleapp** [RocketChat/Rocket.Chat.iOS#121]
Hi @rafaelks, 

When i run the Avatar Branch, unfortunately i get this error. 
Still i use the Xcode 7.3 i didn't update it. 

Can you help me with that please.

![screen shot 2016-09-15 at 2 27 43 pm](https://cloud.githubusercontent.com/assets/11163232/18549741/9b8bf1ba-7b50-11e6-8f17-08167a3079c3.png)
![screen shot 2016-09-15 at 2 27 36 pm](https://cloud.githubusercontent.com/assets/11163232/18549744/9e703c9c-7b50-11e6-9023-2b14ddafca52.png)

**Comment by rafaelks** [comment]
@anappleapp See my answer here: https://github.com/RocketChat/Rocket.Chat.iOS/issues/120#issuecomment-247313221.
