### ISSUE TITLE
[NEW] Show subscriptions and chat in the same screen on iPad

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat.iOS#1214]
We have plenty of space on iPad, at least in single App landscape mode. An option to pin the sidebar would be great.

**Comment by cardoso** [comment]
@rafaelks is developing a new interface without the sidebar.

PR: https://github.com/RocketChat/Rocket.Chat.iOS/pull/731

I think for iPad it will be like the "Settings" App, using SplitViewController.

But I also think it should be optional like you said 🤔

**Comment by cardoso** [comment]
The Side Menu is very buggy and causes many strange issues like in the issue you just reported #1215

That's why we're removing it, and to give a more native feel to the App :)

**Comment by soundstorm** [comment]
@cardoso seems like I have to check this branch ;-)
