### ISSUE TITLE
[CI] Remove SemVer

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat.iOS#1223]
We only use server for comparing InfoRequestHandler for comparison of version numbers. This slows down CI, adds overhead and decencies that can't be fulfilled for #884.

**Comment by rafaelks** [comment]
@soundstorm Why does it slows down the CI? The SemVer is suppose to be cached in CocoaPods for the CI.

**Comment by soundstorm** [comment]
When I was watching the CI build it seems like circle resets something and fetches files again.
But nevertheless, we don't need the library anymore.

**Comment by rafaelks** [comment]
@soundstorm Why we don't need it anymore? It's being used to check the server's version. We optimised a lot the CI today, so let's close this one.
