### ISSUE TITLE
Member search does not work correctly

### ISSUE THREAD

**Issue by ArchimedesFM** [RocketChat/Rocket.Chat.iOS#1225]
- Your Rocket.Chat app version: 1.8.0
- Your Rocket.Chat server version: 0.61.0
- Device (or Simulator) you're running with: iPhone SE - iOS 11.2.5

The In-App search for members doesnt work correctly.
I can search for members with existing direct messages, but not for new users to start a new direct conversation. I can start a new DM by clicking on the user in a private channel, but not via search.

![img_0164](https://user-images.githubusercontent.com/26709898/35797736-f16e4f38-0a60-11e8-8b3a-fdc5dd7a15e2.PNG)

**Comment by cardoso** [comment]
This was fixed in #1165, but we haven't updated our App Store build yet.

Let us know if you want to be included in our TestFlight. Thanks!
