### ISSUE TITLE
[NEW] Support loading SVG images

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat.iOS#1226]
You are allowed to store emojis as svg, but then they won't show up within the app.

**Comment by cardoso** [comment]
I think we need to support SVG, also because of avatars, but I'm not sure if there's a good library

**Comment by artrmz** [comment]
What about [SVGKit](https://github.com/SVGKit/SVGKit)? Anyone tried it (2.x branch)?

**Comment by cardoso** [comment]
I remember looking for a macOS SVG lib and not liking the ones available, but this one for iOS looks good! @artrmz

**Comment by artrmz** [comment]
There is also [Macaw](https://github.com/exyte/Macaw) but maybe it's too "powerful" just for loading SVG images? Although we could add some awesome animations with that to make Rocket.Chat (unless we do not want such "eye catching features"?)

**Comment by soundstorm** [comment]
You can upload emojis and avatars as SVG, will they be converted by the server to PNGs? But anyway, someone could attach a SVG, which would be nice to render too (also DXFs show up with a blank preview on web frontend).

**Comment by rafaelks** [comment]
@soundstorm Yes, all SVG are going to be converted to PNGs (unless you upload an SVG as a file attachment I suppose). We could try to delegate the task of rendering an SVG to a browser (web view) or something else I guess... 🤔

**Comment by cardoso** [comment]
I think if we receive an svg, we can convert it to png client-side using a library and display that instead.

**Comment by rafaelks** [comment]
Guys, we're not planning in supporting SVG right now, that's why I'm closing the issue.
