### ISSUE TITLE
[IMPROVEMENT] Local date format

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat.iOS#1227]
Currently we are using `MMM dd, YYYY` as date format in separators, but here we use `dd MMM YYYY`. Currently the web frontend doesn't localize the date format either, but that doesn't mean we can't 😏

https://github.com/RocketChat/Rocket.Chat.iOS/blob/600e2902ad068187951e83d49c953f03fcc7ada1/Rocket.Chat/Controllers/Chat/MessagesListViewController.swift#L208
https://github.com/RocketChat/Rocket.Chat.iOS/blob/59accc427f0b60e000c75616bda22209ff4baf31/Rocket.Chat/Controllers/Chat/ChatViewController.swift#L858

Or for the hardcore ones a mode to show unix timestamps 🙈

**Comment by rafaelks** [comment]
Good finding @soundstorm! I think we need to format the date from what the device is configured. There are lots of ways to do that using `Date` object. 

You can try changing this and see if that works for you:

```swift
let dateFormatter = DateFormatter()
dateFormatter.dateStyle = .medium (full, long, short, medium, none)
return dateFormatter.string(from: self)
```
