### ISSUE TITLE
[INVESTIGATE] iOS app unable to connect to server

### ISSUE THREAD

**Issue by Endareth** [RocketChat/Rocket.Chat.iOS#1230]
For at least six months now, the Rocket.Chat+ iOS app has been unable to connect to my Rocket.Chat server. Attempting to connect gives: "Ooops! Could not connect to this server!". Using the Cordova app works correctly, as does macOS and browser based connections.

Rocket.Chat app version: 1.8 (also happened for all versions in past six months)
Rocket.Chat server version: 0.61.0
Device: iPhone X and iPhone 7, iOS 10.3.3, 11.0–11.3b

Server is behind a Cisco firewall, and supports websockets.

**Comment by soundstorm** [comment]
@Endareth and has an publicly trusted SSL cert?

**Comment by rafaelks** [comment]
@Endareth Thanks for opening the issue... could you send us your server URL, please?

**Comment by Endareth** [comment]
@rafaelks Server is at https://im.bluechain.com, and is using a valid DigiCert certificate.

**Comment by rafaelks** [comment]
@Endareth Looks like we cannot upgrade to a WebSocket connection in your server:

```shell
curl -i -N -H "Connection: Upgrade" -H "Upgrade: websocket" -H "Host: im.bluechain.com" -H "Origin: im.bluechain.com" -H "Sec-WebSocket-Key: fVXESE8fjBMx8HheW0YlZQ==" -H "Sec-WebSocket-Version: 13" https://im.bluechain.com/websocket
HTTP/1.1 400 Bad Request
Date: Wed, 14 Feb 2018 08:55:17 GMT
Server: Apache
Vary: Accept-Encoding
Connection: close
Transfer-Encoding: chunked

Not a valid websocket request
```

Are you using the required version of Apache (2.4)?

**Comment by rafaelks** [comment]
Closing this one due to inactivity.

**Comment by Endareth** [comment]
Sorry for the late response, but checking further at our end, and it look like the Sophos UTM wasn't handling the reverseproxying too well with the GUI config. Going to tinker further with the Apache config files and see if I can get it working. Thanks for pointing me in the right direction!

**Comment by rafaelks** [comment]
@Endareth Excellent! Glad it worked for you.

**Comment by soundstorm** [comment]
@rafaelks we may include a guide "How to test if my server supports web sockets" like you did with curl :)

**Comment by rafaelks** [comment]
@soundstorm Yes!!!!! 😂

**Comment by cristiandley** [comment]
@rafaelks @Endareth im having the same issue. My Domain is chat.jusneuquen.gov.ar. But im using Nginx. Any clue ?

**Comment by rafaelks** [comment]
@cristiandley Did you manage to fix it?

**Comment by cristiandley** [comment]
@rafaelks yes... my solution on Nginx:

    proxy_set_header Upgrade $http_upgrade;                 # to allow websockets
    proxy_set_header Connection $connection_upgrade;  #upgrade

**Comment by loymascarenhas** [comment]
@soundstorm @rafaelks I am facing the same issue on iPhone SE (v. 10.3.3) using RocketChat+
it is working fine in the web browser and Android.

Code below shows the rocketchat.conf in etc/apache2/sites-enabled.
Apache v. 2.4.18 (ubuntu)
`<VirtualHost *:443>
ServerAdmin email@domain.com
ServerName chat.domain.com
ErrorLog /var/log/chat.domain.com_error.log
TransferLog /var/log/chat.domain.com_access.log
LogLevel info
SSLEngine On
SSLCertificateFile /etc/letsencrypt/live/chat.domain.com/cert.pem
SSLCertificateKeyFile /etc/letsencrypt/live/chat.domain.com/privkey.pem
SSLCertificateChainFile /etc/letsencrypt/live/chat.domain.com/chain.pem

<Location "/">
        Order allow,deny
        Allow from all
</Location>

RewriteEngine On
RewriteCond %{HTTP:Upgrade} =websocket [NC]
RewriteRule /(.*)           ws://localhost:3000/$1 [P,L]
RewriteCond %{HTTP:Upgrade} !=websocket [NC]
RewriteRule /(.*)           http://localhost:3000/$1 [P,L]

ProxyPass /websocket ws://localhost:3000/websocket
ProxyPassMatch ^/sockjs/(.*)/websocket ws://localhost:3000/sockjs/$1/websocket
ProxyPass / http://localhost:3000/
ProxyPassReverse / http://localhost:3000/
</VirtualHost>
`

I am facing the same issue on NGINX even after allowing websockets using:
`
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $connection_upgrade;
`

This is what I am getting after using `curl`
`
TTP/1.1 400 Bad Request
Date: Wed, 18 Apr 2018 15:56:39 GMT
Server: Apache/2.4.18 (Ubuntu)
Content-Length: 29
Connection: keep-alive
`
What may I be missing?

**Comment by loymascarenhas** [comment]
[Solved] I had an issue with AWS Load Balancer
Solution: http://blog.flux7.com/web-apps-websockets-with-aws-elastic-load-balancing
