### ISSUE TITLE
[NEW] Only first attachment field gets displayed

### ISSUE THREAD

**Issue by MauriceBrg** [RocketChat/Rocket.Chat.iOS#1231]
- Your Rocket.Chat app version: 1.8.0
- Your Rocket.Chat server version: 0.61.0
- Device (or Simulator) you're running with: iPhone 7+

We use Rocket Chat in Connection with our Icinga Monitoring Platform. I recently updated our script to use the message attachments. This works great on the Desktop App. Unfortunately the iOS App only shows the first attachment field.

Btw.: The Emoji Tag doesn't seem to work on mobile as well.

Here is some sample Json we send to the hook:
*The `${...}` are variables in the shell script...*

```
{  
   "emoji":"${ICON}",
   "text":"*${NOTIFICATIONTYPE}* ${SERVICEDISPLAYNAME} ( _${HOSTDISPLAYNAME}_ ): *${SERVICESTATE}* | ${SERVICEOUTPUT} ",
   "attachments":[  
      {  
         "color":"${COLOR}",
         "fields":[  
            {  
               "short":"true",
               "title":"State",
               "value":"${SERVICESTATE}"
            },
            {  
               "short":"true",
               "title":"Host",
               "value":"${HOSTDISPLAYNAME}"
            },
            {  
               "short":"false",
               "title":"Service",
               "value":"${SERVICEDISPLAYNAME}"
            },
            {  
               "short":"false",
               "title":"Check Output",
               "value":"${SERVICEOUTPUT}"
            }
         ]
      }
   ]
}
```

**It looks fine in the Desktop Application**
![icinga_desktop](https://user-images.githubusercontent.com/14877287/35853289-66cf40f8-0b2d-11e8-992e-f4d0fbe924b9.png)

*The iOS Application shows only the first field even when you tap on it.*
![icinga_mobile](https://user-images.githubusercontent.com/14877287/35853294-68db8df2-0b2d-11e8-9abb-bffa4c0c9caa.png)

I'm happy to help if you guys need more information.

Thanks in advance, 
Maurice

**Comment by rafaelks** [comment]
@MauriceBrg That's correct, we're only getting the first one right now. I'll let this issue opened so we can work on to support multiple fields. 👍
