### ISSUE TITLE
[CHORE] SwiftLint

### ISSUE THREAD

**Issue by artrmz** [RocketChat/Rocket.Chat.iOS#1247]
Just wondering if it's a good idea to configure SwiftLint to be downloaded via CocoaPods? What do you guys think? This way we won't force people that want to contribute to install it on their machines.

**Comment by rafaelks** [comment]
@artrmz I think that's a good idea, will be much more straightforward to start the development. Want to give it a try?

**Comment by artrmz** [comment]
@rafaelks Sure, will do that once I am done with few things I am already going ;)
