### ISSUE TITLE
[NEW] Cannot post in readonly rooms even with "Post ReadOnly = True"

### ISSUE THREAD

**Issue by akachapati** [RocketChat/Rocket.Chat.iOS#1253]
- Your Rocket.Chat app version: 1.8.0(137)
- Your Rocket.Chat server version: 0.59.3

Noticed an issue in iOS only where 
- if the room is read only
- and the user group has "post readonly" enabled

user cannot post in the channel. Checked in Android, issue is only iOS related

**Comment by rafaelks** [comment]
Good finding, thank you!
