### ISSUE TITLE
The greek translation is incorrect I try to use only the english language but I can' t

### ISSUE THREAD

**Issue by George35mk** [RocketChat/Rocket.Chat.iOS#1254]
Before writing an issue, please make sure you're talking about the native application (called Rocket.Chat+ in the App Store) and not the Cordova one (called Rocket.Chat in the App Store). If you are looking to open an issue to the Cordova application, go to this URL: https://github.com/RocketChat/Rocket.Chat.Cordova.

- Your Rocket.Chat app version: ####
- Your Rocket.Chat server version: ####
- Device (or Simulator) you're running with: ####

**The app isn't connecting to your server?**
Make sure your server supports WebSocket. These are the minimum requirements for Apache 2.4 and Nginx 1.3 or greater.

Remove the Greek language from the rocket chat. Is confuse me and is incorrect

**Comment by George35mk** [comment]
I fix this

**Comment by soundstorm** [comment]
We don't have any greek translation here yet, so feel free to create one.

**Comment by George35mk** [comment]
Give the json with the data you want me to translate and I translate this. 
I gonna add more correct values. 
You can send me an email if you want.

Best

```gerge35mk@gmail.com```

**Comment by artrmz** [comment]
https://github.com/RocketChat/Rocket.Chat.iOS/blob/develop/Rocket.Chat/en.lproj/Localizable.strings

https://github.com/RocketChat/Rocket.Chat.iOS/blob/develop/Rocket.Chat/en.lproj/VoiceOver.strings

Those 2 files for now. Also would be nice to keep ot up to date once new features are added.

**Comment by soundstorm** [comment]
https://github.com/RocketChat/Rocket.Chat.iOS/blob/develop/Rocket.Chat/External/RCEmojiKit/en.lproj/RCEmojiKit.strings
Also this one :)

**Comment by kmav** [comment]
Hi  @George35mk  
I saw that you find some issues with Greek translation? Could you provide an example? 
Can you help in new update  #2622 ?
