### ISSUE TITLE
Missing text & emojis

### ISSUE THREAD

**Issue by mysiar** [RocketChat/Rocket.Chat.iOS#1258]
- Your Rocket.Chat app version: 1.8.0 (137)
- Your Rocket.Chat server version: 0.61.0
- Device (or Simulator) you're running with: iPhone X

Text in the attachment is missing (it does exist in web browser and native Linux app), only title visible
Emoji `:smile:` missing, instead `JE` icon displayed

![image](https://preview.ibb.co/inzb5n/IMG_5842.jpg )

**Comment by cardoso** [comment]
Hi @mysiar . This was fixed by #1145 and will be available when we update the App Store build.

It will probably be this week. Stay tuned!

**Comment by mysiar** [comment]
Thanks @cardoso
