### ISSUE TITLE
external OAuth 2.0 provider, iOS Authentication error

### ISSUE THREAD

**Issue by willow9886** [RocketChat/Rocket.Chat.iOS#1259]
- Your Rocket.Chat app version: 1.8
- Your Rocket.Chat server version: 2.10.5
- Device (or Simulator) you're running with: iPhone 5, running iOS 10.3.3 and iPhone 6, running 11.2.5

We have Rocket Chat setup with our external OAuth provider. Login against the external provider is working fine on Android devices, but getting an authentication error when attempting to login on iOS. 

Steps to reproduce:
- Open the iOS Rocket Chat+ app
- Input our server host: `https://chat.gluu.org`
- Click the `Click here to login` button, which should redirect to the external IDP
- Receive the below authentication error. 

Note: the above steps work as expected with no error when using the Android app, and the desktop clients for Windows and Mac.

Any help or ideas is greatly appreciated!!

![image](https://user-images.githubusercontent.com/5271048/36218155-21845dba-1179-11e8-8c9c-3a1f0beb75f8.png)

**Comment by willow9886** [comment]
Hi guys, thanks so much for the quick uptake! Out of curiosity, Is there an ETA for 2.0?

**Comment by cardoso** [comment]
Hi @willow9886 

Probably this week. If you want access to our TestFlight, please reach me at https://open.rocket.chat/direct/matheus.cardoso
with your Apple ID
