### ISSUE TITLE
[IMPROVEMENT] Search (channels, users) is case sensitive

### ISSUE THREAD

**Issue by janrudolph** [RocketChat/Rocket.Chat.iOS#1265]
- Your Rocket.Chat app version: 1.8.0
- Your Rocket.Chat server version: 0.61.0
- Device (or Simulator) you're running with: iPhone 5S

**Channel search is case sensitive**
Imagine you like to search for your channel `Team-chat`. If you insert `team-chat` in your channel search, Rocket.Chat+ will not find any match. Instead you have to search for the exact term (case sensitivity). Same applies if you search for users in the channel search. This is not user friendly. 

**Create new channel: User search is case sensitive** 
When you create a new channel and like to invite users, you have to insert the users' names. The search here is case sensitive as well. If you do not know the correct spelling, you simply will not find the users.

(edit: updated this issue with the user search)

**Comment by rafaelks** [comment]
Thanks for opening the issue, we'll address it soon. 👍
