### ISSUE TITLE
[Bug] Wrong error message at login

### ISSUE THREAD

**Issue by janrudolph** [RocketChat/Rocket.Chat.iOS#1266]
- Your Rocket.Chat app version: 1.8.0
- Your Rocket.Chat server version: 0.61.0
- Device (or Simulator) you're running with: iPhone 5S

**When inserting a wrong password the app displays `User not found [403]`**
If you enter a wrong password when connecting to a new server, you get the error message `User not found [403]`. This is semantically not correct. The error message has to be `Password not correct`.

**Comment by artrmz** [comment]
`Password not correct` would suggest there is such account and only password is wrong. That's not safe. Better would be `Incorrect username or password`.

**Comment by soundstorm** [comment]
https://github.com/RocketChat/Rocket.Chat/issues/9407

**Comment by rafaelks** [comment]
You guys are right, the API is returning this error, the application just shows it. Let's close the issue here and leave the issue that @soundstorm created opened to fix the message. Thank you all! ✌️
