### ISSUE TITLE
[BUG] App applies "UI_Allow_room_names_with_special_chars" but does not tell you

### ISSUE THREAD

**Issue by janrudolph** [RocketChat/Rocket.Chat.iOS#1267]
- Your Rocket.Chat app version: 1.8.0
- Your Rocket.Chat server version: 0.61.0
- Device (or Simulator) you're running with: iPhone 5S

**You cannot create channels with special chars**
Even if you configured `UI_Allow_room_names_with_special_chars = true`, you cannot create channels with special chars in the app. You always get an error message. The app should apply the same rules as web application.

In fact the app does not ignore the property. Moreover it displays, that you are not allowed to create a channel with special chars but in the background the app creates the channels.

**Example**
I wanted to create the channel `my iPhone test`. The app told me I am not allowed to do so. I changed the channel name to `my-iPhone-test` (failed again), then to `my-iphone-test` (failed again) and finally to `myiphonetest` (success). But on the server all channels were created.

![rocket_chat_](https://user-images.githubusercontent.com/3596824/36262604-3e14d14a-1268-11e8-9f71-26cce1879cff.png)

**Comment by rafaelks** [comment]
@janrudolph Thank you for opening the issue, but this is also a change that needs to be made in our back-end IMHO. Back-end should validate if the name of the channel/group is a valid name and can be created. Could you please create an issue on this repository with this description? 

https://github.com/RocketChat/Rocket.Chat/issues
