### ISSUE TITLE
[BUG] App does not render preview picture for videos directly

### ISSUE THREAD

**Issue by janrudolph** [RocketChat/Rocket.Chat.iOS#1268]
- Your Rocket.Chat app version: 1.8.0
- Your Rocket.Chat server version: 0.61.0
- Device (or Simulator) you're running with: iPhone 5S

**If you upload a video the preview picture is not rendered directly **
If a user uploads a video, the user will not get a preview picture. It does not matter how long the user waits for the picture. The upload animation will not disappear. 

![img_0232](https://user-images.githubusercontent.com/3596824/36263150-c5be3310-1269-11e8-909e-84b940bc7601.png)

The user has to switch to another channel and switch back in order to get a preview of the uploaded video. 

I tested it by uploading a very short video (about 2-3 seconds long).

**Comment by rafaelks** [comment]
Thanks for opening the issue @janrudolph!

**Comment by Hrayr2112** [comment]
I am currently working on this bug. Please assign this task to me

**Comment by cardoso** [comment]
Thanks for taking on this @Hrayr2112 . 

You are not showing up in the list of people to assign this, maybe try opening a [WIP] PR?

**Comment by Hrayr2112** [comment]
I will do [WIP] PR today after my classes in the evening. Thank you!

**Comment by Hrayr2112** [comment]
I opened the [WIP] PR, but for unblock users feature. Now I'm fixing this bug.

**Comment by Hrayr2112** [comment]
@cardoso , How can I send video on the simulator? Are there any ways to reproduce this bug?
