### ISSUE TITLE
[Bug] Adding users on channel creation does not work

### ISSUE THREAD

**Issue by janrudolph** [RocketChat/Rocket.Chat.iOS#1269]
- Your Rocket.Chat app version: 1.8.0
- Your Rocket.Chat server version: 0.61.0
- Device (or Simulator) you're running with: iPhone 5S

**You cannot invite users to a new channel**
If you create a new channel via the app and invite users, the users will not join the channel. You create an empty channel. It does not matter how many users you invite, as well as, who you invite.

**Comment by cardoso** [comment]
This was solved by #1194 and will be available soon on the App Store build

If you're interested in joining our TestFlight, please reach me at https://open.rocket.chat/direct/matheus.cardoso 
with your Apple ID.
