### ISSUE TITLE
[QUESTION] Push Notifications setup for Forked Version (Branded)

### ISSUE THREAD

**Issue by HarveyDoom** [RocketChat/Rocket.Chat.iOS#1271]
I have created a forked version of Rocket.Chat.iOS to brand for a client. It will be uploaded separately to the app store. I am running my own server instance.

I am having difficulty following the documentation under Push Notifications. Especially iOS which links to a tutorial that is written for cordova.

Could someone please explain the steps / settings to setup my server instance to send push notifications to my own forked version of Rocket.Chat.ios

**Comment by rafaelks** [comment]
@HarveyDoom That's a good question and we really need to improve our documentation related to that. Here are the steps, basically:

## Setup Push Notification for native iOS application with a custom bundle id

1. You need to have an Apple account; Then you need to create the Apple ID in your Apple Developer dashboard;
2. On the Application page, setup Push Notification for both Development and Production;
3. Copy the information required from your certificates and keys into the administration panel of `Rocket.Chat > Push > Certificates and Keys`. **You cannot use our Gateway if you're running a custom bundle id**;
4. Now your application should be ready to receive notifications once you setup the new bundle id and the new team;

Let me know if that works for you, then we'll update our docs.
