### ISSUE TITLE
[NEW] List of blocked users + unblock users

### ISSUE THREAD

**Issue by cardoso** [RocketChat/Rocket.Chat.iOS#1279]

**Comment by Hrayr2112** [comment]
I am working on it and I need more information about feature. Please assign it to me.

**Comment by Hrayr2112** [comment]
Where should I show the list of blocked users?

**Comment by cardoso** [comment]
@Hrayr2112 it's possible do block receiving messages for a certain user.

You can see how it works in MessageManager.swift `func blockMessagesFrom`

You can take a look at our other list of members to see how we do it. The only difference is that you will be able to unblock. You can do an Action Sheet on tap with "Unblock" and "Cancel".

Thanks!

**Comment by Hrayr2112** [comment]
Thank you, I will do it this evening

**Comment by artrmz** [comment]
Ad 1. There should be no any whitespaces in empty line. Xcode automatically adds those whitespaces unless you change it in Xcode -> Preferences

![zrzut ekranu 2018-02-20 o 10 23 33](https://user-images.githubusercontent.com/3925166/36416008-1ea084c6-1628-11e8-84b9-80c412ac22d7.png)

**Comment by Hrayr2112** [comment]
Thank you! I did it

вт, 20 февр. 2018 г. в 13:23, Artur Rymarz <notifications@github.com>:

**Comment by artrmz** [comment]
About the 2nd issue it seems like the email you use to commit on your MacBoko is not linked with GitHub Account. You can adjust email settings here: https://github.com/settings/emails

**Comment by Hrayr2112** [comment]
Thank you! Everything works correctly

**Comment by promehul** [comment]
Assign it to me and I will start working on it ASAP!!

**Comment by blewjy** [comment]
Hi! I'm interested to take on this issue. However, I'm unable to find the logic for blocking of users

> You can see how it works in MessageManager.swift `func blockMessagesFrom`

I can't seem to find `func blockMessagesFrom` in `MessageManager.swift`, has it been moved?

**Comment by rafaelks** [comment]
Sorry @blewjy, this feature was removed from the app and I forgot to close this issue. Thank you!
