### ISSUE TITLE
[IMPROVEMENT] Change text displayed to user on changing icon

### ISSUE THREAD

**Issue by louisemessage** [RocketChat/Rocket.Chat.iOS#1285]
https://github.com/RocketChat/Rocket.Chat.iOS/blob/2b2707ed9059b6deb34b364204321d3ec30a4a9d/Rocket.Chat/Resources/en.lproj/Localizable.strings#L203

This text is quite long and not grammatically correct. I suggest changing the text to something like 'Choose an icon'

**Comment by artrmz** [comment]
Here #1238 you can find the screen where this text is placed. I am not an UX designer but I think long text fits here quite well. What text would be grammatically correct? Unless we want to remove it completely since doubling it is definitely a no-no.

**Comment by rafaelks** [comment]
We can improve the style of this screen, let's do it for next release and then we can think about this text change 👍
