### ISSUE TITLE
[BUG] Attachment with no comment but reaction show »

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat.iOS#1287]
The » indicator for the comment on the attachment is normally hidden, but when expanding the container to add reactions, it shows up, even if there is no comment. Will fix that somehow :)

**Comment by rafaelks** [comment]
@soundstorm Thanks for opening the issue. Are you going to work on that?

**Comment by soundstorm** [comment]
Yep :)
