### ISSUE TITLE
[IMPROVEMENT] Multiple touches on menu entry lead to multiple open views

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat.iOS#1288]
When clicking e.g. "Application Icon" and your phone hangs a bit, you may touch it multiple times (still no "no slowdown update" from apple available yet). This will be registered, but not executed immediately, so after the phone restores normal operation it will open the view multiple times.

**Comment by rafaelks** [comment]
I'm not able to reproduce this one anymore, let us know if this is still happening a lot please.
