### ISSUE TITLE
[NEW] Indicate "@myusername" mention on autocomplete

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat.iOS#1290]
As we currently do on web frontend, we may indicate "@soundstorm (me)" in the overview.

**Comment by soundstorm** [comment]
@rafaelks In the sidebar (or if the no-sidebar-update is merged) in the overview of users we have on web:
@...
@...
@soundstorm (you)
@...

But adding yourself to autocomplete would be okay too (I have written a bot to order something from someone, a bit like a todo. So sometimes I assign things to my own and have to type my own username)

**Comment by rafaelks** [comment]
@soundstorm Gotcha! I think that makes sense. 👍
