### ISSUE TITLE
[BUG] Chat view distorted after opening "Info" screen then rotating device

### ISSUE THREAD

**Issue by johnmberger** [RocketChat/Rocket.Chat.iOS#1307]
- Your Rocket.Chat app version: 2.0.1 (144)
- Your Rocket.Chat server version: 0.59.0
- Device (or Simulator) you're running with: iPhone SE (simulator)

When you open the "Info" screen in a channel, rotate the device, then close the info screen, the chat view is distorted. This happens for both landscape-to-portrait and portrait-to-landscape.

_Here's what that looks like:_

**1.** (chat view)
<img width="252" alt="screen shot 2018-02-21 at 11 56 46 am" src="https://user-images.githubusercontent.com/15810385/36499549-d90196e4-16fe-11e8-9475-5d57f4fc61c6.png">

**2.** (click channel title to open info screen)
<img width="252" alt="screen shot 2018-02-21 at 11 56 56 am" src="https://user-images.githubusercontent.com/15810385/36499553-ddc755ba-16fe-11e8-82f4-2f994b4b1d3a.png">

**3.** (rotate)
<img width="441" alt="screen shot 2018-02-21 at 11 56 58 am" src="https://user-images.githubusercontent.com/15810385/36499561-e2f53d36-16fe-11e8-9567-0134b993f2ea.png">

**4.** (close info screen)
<img width="441" alt="screen shot 2018-02-21 at 11 57 02 am" src="https://user-images.githubusercontent.com/15810385/36499564-e6eaffe8-16fe-11e8-933a-222b9dcb737b.png">

**Comment by Sameesunkaria** [comment]
I'll be damned! It's `SideMenuController` calculating the frame incorrectly. 🤦🏻‍♂️
The frame is being calculated before the rotation, when the VC is not on screen.
