### ISSUE TITLE
[NEW] Record an audio & send it

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.iOS#1312]

**Comment by raghavgr** [comment]
Hi. I would like to work on this. I am looking at https://github.com/RocketChat/Rocket.Chat.iOS/blob/develop/Rocket.Chat/Controllers/Chat/ChatControllerUploader.swift and following the steps used for attaching images to make one for audio as well. 

Shall I follow this method?

**Comment by rafaelks** [comment]
@raghavgr Yes, you can use this method.

**Comment by rafaelks** [comment]
@szab100 This is going to be included in future releases, for sure. We're currently focused in other priorities for the app and making a better architecture, to include this kind of feature easily in the future. 👍

**Comment by szab100** [comment]
@rafaelks Great, thanks for the answer, super clear now! Speaking of a better architecture, could you pls take a look at #10963, I opened it for a sake of better permission / acl system as to me the current one is looks bad / inflexible and not viable in both short / longer term.. (and also not suitable for our current needs)

**Comment by MangoSmoothie101010** [comment]
Hey,

Just saw that this issue is awarded a 50$ bounty on bountysource upon completion.

Is somebody already working on this?

**Comment by rafaelks** [comment]
@MangoSmoothie101010 AFAIK nobody is working on that right now.

**Comment by MangoSmoothie101010** [comment]
I realized after writing my comment, that this is for the iOS-App. Any chance I can complete this issue, not having any Apple device?

**Comment by Sameesunkaria** [comment]
@MangoSmoothie101010 You would at least need a Mac.

**Comment by nodje** [comment]
This is also a key feature for our team. People like Rocket so far, bu they really miss the Whatsapp/Wechat way of leaving voice message from mobile iOS and Android.
At this point this becomes a bit of showstopper for the migration to Rocket.

Is there a place to support and checj the feature status? I mean it should be supported globally on al plateforms, not only iOS.

**Comment by rafaelks** [comment]
@nodje Yes, our currently plan is to work on this feature January / 2019.

**Comment by MathiasRenner** [comment]
The new verision (now called "experimental") has voice message again. A first test worked fine for me:
https://play.google.com/store/apps/details?id=chat.rocket.reactnative&hl=en

**Comment by reetp** [comment]
Note the 'Experimental version is React Native, not Swift.

https://rocket.chat/2019/10/11/moving-mobile-apps-to-react/

Here's the correct repo:

https://github.com/RocketChat/Rocket.Chat.ReactNative
