### ISSUE TITLE
[NEW] Allow user to see all attachments in a channel/group/DM

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.iOS#1314]

**Comment by Hrayr2112** [comment]
While I'm waiting for solution of my problem with feature #1342, I will start this feature. Can you tell me about this feature in details?

**Comment by artrmz** [comment]
Example on web:
<img width="277" alt="zrzut ekranu 2018-02-24 o 23 16 45" src="https://user-images.githubusercontent.com/3925166/36635626-d1098b9c-19b8-11e8-92f7-0d1a03d29897.png">
<img width="166" alt="zrzut ekranu 2018-02-24 o 23 16 21" src="https://user-images.githubusercontent.com/3925166/36635627-d1276d92-19b8-11e8-8d81-fb4911f9ae1f.png">

It's simply a file's list. I think it should be accessible from Channel's/Group's/DM's info, here:
![simulator screen shot - iphone se - 2018-02-24 at 23 17 47](https://user-images.githubusercontent.com/3925166/36635632-f994d5ee-19b8-11e8-8227-1ed7690c445f.png)

**Comment by Hrayr2112** [comment]
Ok, thanks. If you have a minute, can you help me with this problem? #1342

**Comment by Hrayr2112** [comment]
You are a mentor GSOC, aren't you?

**Comment by artrmz** [comment]
@Hrayr2112 You mean Google Summer of Code? Nope, I am not a mentor of that :) Why did you think so?

**Comment by Hrayr2112** [comment]
Because I got a lot of comments from you :)

**Comment by rafaelks** [comment]
@artrmz Thanks for the explanation! @Hrayr2112 He's a super active and dedicated contributor. :-)

@Hrayr2112 To list the attachments, you'll have to use this REST APIs, while we don't have a `v2` API that returns the files to any kind of room: 

> Public Channels: api/v1/channels.files
> Private Groups: api/v1/groups.files
> DMs: api/v1/dm.files

**Comment by Hrayr2112** [comment]
@rafaelks thanks! If you have a minute, can you review #1342?

**Comment by Hrayr2112** [comment]
@artrmz Can you help me with organisation my JSON body for getting channel/group/dm media files? I guess your experience in this project will allow you tell me about it :) If you can, please attach your account link in Rocket.Chat

**Comment by rafaelks** [comment]
@Hrayr2112 OK, let me try to introduce you to this methods (since we don't have docs for it yet cc @MarcosSpessatto).

1. You'll have to pass a `rid` query parameter, with the `rid` property of the Subscription object;
2. The request is paginated, so you can exactly copy this logic from our members API request;

**Comment by Hrayr2112** [comment]
Thanks! I will try do it after my classes today

**Comment by MarcosSpessatto** [comment]
@rafaelks, [docs](https://github.com/RocketChat/docs/pull/624).

**Comment by rafaelks** [comment]
@MarcosSpessatto You're the man! Thank you very much! 👍

**Comment by Hrayr2112** [comment]
Thanks!

**Comment by filipealva** [comment]
Update: waiting for a fix on the API to finish up this feature.

**Comment by rafaelks** [comment]
This one was closed by #1523
