### ISSUE TITLE
[NEW] Integrate Facebook authentication using Facebook SDK

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.iOS#1315]
Integrate authentication using Facebook SDK. There's one SDK that will only add the required files to authenticate the user: https://developers.facebook.com/docs/facebook-login

API DOCS: https://github.com/RocketChat/docs/pull/595

**Comment by imjog** [comment]
Hi @rafaelks Can I take this issue?

**Comment by cardoso** [comment]
Hi @imjog . Thanks for your interest, but we decided not to have third-party authentication SDKs on the App anymore.
