### ISSUE TITLE
[IMPROVEMENT] Optimize the emojis list picker

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.iOS#1316]
Main thread is being blocked while scrolling.

**Comment by Hrayr2112** [comment]
How can I reproduce this deadlock? Where is the emojis list picker? It isn't native emojis, is it?

**Comment by rafaelks** [comment]
@Hrayr2112 To reproduce, go to a message, long press it and press "Add a Reaction". This emoji picker is our own picker. The scroll is blocking the UI sometimes.

**Comment by Hrayr2112** [comment]
Thanks!

**Comment by Hrayr2112** [comment]
I reproduced it. I know what is the problem:

During scrolling the CPU usage reach to 96-98 percents, therefore we see bad performance and finally we see the deadlock.

Now I'm trying to change some implementation elements for picker, because we should decrease CPU usage.
