### ISSUE TITLE
[CI] CI uses wrong version of CocoaPods

### ISSUE THREAD

**Issue by artrmz** [RocketChat/Rocket.Chat.iOS#1326]
`[!] The version of CocoaPods used to generate the lockfile (1.4.0) is higher than the version of the current executable (1.3.1). Incompatibility issues may arise`

I think in `update_dependencies` script we should call `pod install` using bundler (`bundle exec pod install`) instead of calling it directly.

Side note: Do we have to call `bundle install` before `bundle exec`? What `before_install.sh` actually do? Why we do not keep `Gemfile.lock` file in the repository?

**Comment by rafaelks** [comment]
@artrmz Good finding! I'll have to investigate how to use the same version of CocoaPods, but I guess using a `Gemfile.lock` would solve the issue. 🤔
