### ISSUE TITLE
[NEW] Support Twitter OAuth

### ISSUE THREAD

**Issue by cardoso** [RocketChat/Rocket.Chat.iOS#1327]

**Comment by raghavgr** [comment]
Hi, I would like to work on this. I am following this tutorial: https://www.raywenderlich.com/177597/oauth-2-0-swift-tutorial. Could you let me know if I am following the right path?

**Comment by cardoso** [comment]
Hi @raghavgr You don't need to follow that tutorial.
We have all the boilerplate ready for this. You only need to find the right parameters for Twitter.

This is the ones we have for GitHub:

```swift
// LoginServiceModelMapping.swift
    func mapGitHub() {
        service = "github"
        scope = ""

        serverUrl = "https://github.com"
        tokenPath = "/login/oauth/access_token"
        identityPath = "https://api.github.com/user"
        authorizePath = "/login/oauth/authorize"
        buttonLabelText = "github"
        buttonLabelColor = "#ffffff"
        buttonColor = "#4c4c4c" // inspect from the web version
    }
```

All you need to do is make the mapTwitter function. Then add the new case here:

```swift
enum LoginServiceType {
    case github
    case facebook
    case linkedin
    case saml
    case cas
    case custom
    case invalid

    init(string: String) {
        switch string {
        case "github": self = .github
        case "facebook": self = .facebook
        case "linkedin": self = .linkedin
        case "saml": self = .saml
        case "cas": self = .cas
        default: self = .invalid
        }
    }
}
```

Add the new case here:

```swift
// LoginServiceModelMapping.swift
        switch type {
        case .github: mapGitHub()
        case .facebook: mapFacebook()
        case .linkedin: mapLinkedIn()
        case .saml: break
        case .cas: break
        case .custom: break
        case .invalid: break
        }
```

That should be it! Thanks!

**Comment by saigrandhi** [comment]
Thank you. I am on it!

**Comment by raghavgr** [comment]
Do I need to update AuthViewController as well?
https://github.com/RocketChat/Rocket.Chat.iOS/blob/develop/Rocket.Chat/Controllers/Auth/AuthViewController.swift

**Comment by cardoso** [comment]
Yes, @raghavgr . You can generate the twitter logo here: http://fa2png.io/

Just select brandico-twitter-bird and export the following:

twitter@1x.png (20px)
twitter@2x.png (40px)
twitter@3x.png (60px)

And add those to our assets where the other logos are. Then you need to update AuthViewController and to use the logo like the others (facebook, github, etc)

Many thanks!!

**Comment by raghavgr** [comment]
I have made the required changes to `AuthViewController.swift` and added Twitter image assets. 

Along with that, I made changes to `AuthSettingsModelMapping.swift` and `AuthSettings.swift` as there was similar code for the other authentication methods (github, facebook, etc).

**Comment by kmav** [comment]
Hi @raghavgr . Did you have sent any PR for this?

**Comment by rafaelks** [comment]
Closing this one in favor of #724.
