### ISSUE TITLE
[Bug] Inviting users case sensitive

### ISSUE THREAD

**Issue by mrsimpson** [RocketChat/Rocket.Chat.iOS#1330]
- Your Rocket.Chat app version: 2.0.2
- Your Rocket.Chat server version: 0.61.1
- Device (or Simulator) you're running with: SE

When creating a new channel, the selection for users is case sensitive.
How to test: 
- Create user Matheus (with upercase M)
- Create a new channel and add a user , starting with a lowercase "m"

=> You won't find it

**Comment by Hrayr2112** [comment]
While I'm waiting for solution of my problem with feature #1342, I will try fix this bug

**Comment by artrmz** [comment]
@Hrayr2112 I am already done with that. Just didn't have time to create PR yet ;)

**Comment by Hrayr2112** [comment]
ok

**Comment by Hrayr2112** [comment]
Please, comment, if u started task
