### ISSUE TITLE
[NEW] Support WordPress OAuth

### ISSUE THREAD

**Issue by flantascience** [RocketChat/Rocket.Chat.iOS#1337]

**Comment by imjog** [comment]
@rafaelks Can I take this issue?

**Comment by rafaelks** [comment]
@imjog Yes, please 👍

**Comment by cardoso** [comment]
@flantascience do you have a public server so I can confirm the feature will work for you?

**Comment by rafaelks** [comment]
@cardoso I believe this one isn't blocked anymore.
