### ISSUE TITLE
Don't see video chat and audio call options

### ISSUE THREAD

**Issue by flantascience** [RocketChat/Rocket.Chat.iOS#1338]
Am I missing a setting somewhere?
Is this not available in the app?   Should I be using Cordova instead?

- Your Rocket.Chat app version: iOS 2.02
- Your Rocket.Chat server version: 0.58.1
- Device (or Simulator) you're running with: iPhone 5

**Comment by rafaelks** [comment]
@flantascience We don't support these features yet. It's still be developed (already have an issue for that).
