### ISSUE TITLE
[NEW] Improve the ways the app receives push notification

### ISSUE THREAD

**Issue by ggrish** [RocketChat/Rocket.Chat.iOS#1339]
I want to receive push notification when I am online, too.
If I am talking in Channel A and User A sends message to me in Direct ChatRoom, I want to receive push notification of it.
So I made some changes on server side, too.
I need to receive current room id from mobile app.

**Comment by soundstorm** [comment]
You just need to enable "always notify mobile" in your server administration under general, no need to change any code.

**Comment by ggrish** [comment]
@soundstorm

Thanks for your comment.
But the "always notify mobile" is sending notification for every message.
so even I am chatting on Room A now, I will receive it's notification, too.

**Comment by soundstorm** [comment]
We're trying to implement in-app notifications to avoid "external" push messages #1125
