### ISSUE TITLE
Let user signup from the app

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.iOS#135]

**Comment by dnspyo** [comment]
I am searching for the api method for registering single users. I was able to try a few methods but could not get a success result. I am provably not providing the correct arguments. I tried using the method 'createUser' which gave a 403 error Signups Forbidden. I also tried 'registerUser' which gave 400 error Match Failed. 

Is this the Meteor method that we should call to register users? [https://github.com/RocketChat/Rocket.Chat/blob/develop/server/methods/registerUser.coffee](url)

**Comment by ktt9117** [comment]
I have tried and tried the following by looking at the Android code.
"RegisterUser" > "login" > "setUsername" > "joinDefaultChannels"
All of these methods must be successfully invoked to run successfully.
