### ISSUE TITLE
[I18N] Support Greek language

### ISSUE THREAD

**Issue by kmav** [RocketChat/Rocket.Chat.iOS#1350]
Do you want or plan to support Greek in native iOS app? Do you want translation? I could maybe do the translation and proceed to a pull request. 
In the case that you like the idea, could you please advise if I should first fork the repo. For the moment I just followed your instructions and did a git clone.
Best regards,
Konstantinos

**Comment by artrmz** [comment]
Yes, you have to fork it in order to ne able to push anything :) there is few .strings files to translate.

**Comment by Hrayr2112** [comment]
You just have to add translations in Lozalization files

**Comment by kmav** [comment]
Thanks for replies :)

I am working on it.

First step is to add the localization language in project so we have:
	modified:   Rocket.Chat.xcodeproj/project.pbxproj

If you want to avoid such a "serious" change to be done by this request, then you can add the language and then I can fork, do the changes and send PR.

**Comment by artrmz** [comment]
@kmav Feel free to do that :) If any conflict araises it'll be resolved.

**Comment by kmav** [comment]
After the changes, when compile against my device I am getting:

Code Signing Error: No account for team "S6UPZG7ZR3". Add a new account in the Accounts preference pane or verify that your accounts have valid credentials.
Code Signing Error: No profiles for 'chat.rocket.ios' were found:  Xcode couldn't find any iOS App Development provisioning profiles matching 'chat.rocket.ios'.
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'

Any advice?

Best regards,
Konstantinos

**Comment by rafaelks** [comment]
@kmav Yes, we do want to support Greek translation, thank you for asking! :-)

Let me try to help you: what do you think about I open a PR with the support and the Greek file all in English, then you just change the strings and submit your commit? Does that work for you?

**Comment by kmav** [comment]
@rafaelks Thank you very much for your kind response. 
Your suggestion is great! I would like very much to follow the "official" process as a first contribution exercise but I am facing these issues... 
Let me try a little bit more and I will let you know.

Could you please note that I have already the 3 Greek locaqlization files (emoji, LocalizedStrings and VoiceOver) commited in my fork and you may find them there. 
If I don;t find a solution to these build errors, we will be needed to follow your advise, In that case, I believe that first of all you need to add the Greek language in options as I did (to have the Greek file shown).

Please let me know if all of this makes sence to you.

**Comment by cardoso** [comment]
@kmav 

Those code signing errors are happening because you can't use the chat.rocket.ios bundle id without being added to our internal development team.

If you change it to something else like chat1.rocket.ios it should work 
But do not commit that change. 😅 

Thanks!

**Comment by kmav** [comment]
@cardoso and @rafaelks 
Thank you for your advise. I tried to change the bundle name but did not work...
What is suprised me is that in the beginning, that build using the specific code signing settings has worked... And in your contribution guidelines it says that the code signing messages shown in Rocket.Chat target are fine.
Anyway, I can proceed with PR and you may handle it there or advise further.

**Comment by kmav** [comment]
Could you please advise if anything is wrong with PR.
Thank you.
