### ISSUE TITLE
[QUESTION] Development: Code signing errors during build on device

### ISSUE THREAD

**Issue by kmav** [RocketChat/Rocket.Chat.iOS#1359]
I am getting 3 Code signing errors during build on device. The errors are: 

`Code Signing Error: No account for team "S6UPZG7ZR3". Add a new account in the Accounts preference pane or verify that your accounts have valid credentials.
Code Signing Error: No profiles for 'chat.rocket.ios' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'chat.rocket.ios'.
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'`

That behaviour was not expected because of the contribution guidelines, and does not allow to test the app on a real device.

@cardoso has commented in issue #1350, that this is a normal behavior for a user (like me) because you can't use the chat.rocket.ios bundle id without being added to our internal development team.

Does any one can help further to bypass this?

**Comment by kmav** [comment]
Code Signing Error: No account for team "S6UPZG7ZR3". Add a new account in the Accounts preference pane or verify that your accounts have valid credentials.
Code Signing Error: No profiles for 'chat.rocket.ios' were found:  Xcode couldn't find any iOS App Development provisioning profiles matching 'chat.rocket.ios'.
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'

**Comment by artrmz** [comment]
If you want to build for device, most likely you will have to change **Team** to _Personal_ (not sure about _bundle identifier_, but if changing team does not work, you can change it as well)

**Comment by kmav** [comment]
Do you mean that build and run on device does not work without this kind of changes?

Then, could you please verify if what is written in CONTRIBUTING.md is correct:
"project.pbxproj
Don't change this file unless required (added files). This includes signing of the application itself. The Team will be red in the Rocket.Chat.xcodeproj, that's fine."

**Comment by artrmz** [comment]
@kmav Yes, you can not run an app on a device that is not included in project's provisioning.

It's correct although you can edit this file as long as you do not push those (unnecessary) changes.

**Comment by kmav** [comment]
@artrmz Thank you very much for clarifications. I think that this can be closed now.

**Comment by cardoso** [comment]
Thank you @artrmz !

Closing this :)

**Comment by jframosg** [comment]
Hi guys, I have the same problem as @kmav:

> Code Signing Error: No account for team "S6UPZG7ZR3". Add a new account in the Accounts preference pane or verify that your accounts have valid credentials.
> Code Signing Error: No profiles for 'chat.rocket.ios.Rocket-Chat-ShareExtension' were found:  Xcode couldn't find any iOS App Development provisioning profiles matching 'chat.rocket.ios.Rocket-Chat-ShareExtension'.
> Code Signing Error: Code signing is required for product type 'App Extension' in SDK 'iOS 11.3'

I followed all the steps described in https://github.com/RocketChat/Rocket.Chat.iOS/blob/develop/CONTRIBUTING.md and, in the General Properties of xCode, I obtain the same result that appears in the image: https://user-images.githubusercontent.com/193273/35477109-ad451daa-03bc-11e8-828b-9238bdda438e.png

Could you help me to solve this problem?
@kmav could you describe me the steps you took to build the project without errors and to try the app on your iPhone device?

Thank you very much in advance!

**Comment by amoebav** [comment]
Is it possible to sideload Rocket.Chat.Ios using a free apple developer account?

![image](https://user-images.githubusercontent.com/53012340/61469889-9fc77f80-a945-11e9-81b4-75b754fbe7e5.png)
