### ISSUE TITLE
Let user send images/movies

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.iOS#136]

**Comment by jarrillaga** [comment]
Hey @rafaelks... I see a black square when I try to send an image in iOS App. Do you have any idea about this?

**Comment by cardoso** [comment]
@jarrillaga can you send a screenshot?

**Comment by jarrillaga** [comment]
@cardoso Look, this is the screenshot:

![img_2404](https://user-images.githubusercontent.com/11060950/35738703-62b2813c-080e-11e8-9c44-e3b97171b11c.PNG)

**Comment by cardoso** [comment]
What server is that @jarrillaga? 

Maybe this problem is related to #1169 and the asset is being served through HTTP instead of HTTPS?
