### ISSUE TITLE
Localization of AuthController scene is missing

### ISSUE THREAD

**Issue by kmav** [RocketChat/Rocket.Chat.iOS#1363]
In AuthViewController.swift related storyboard there is no localisation of the labels and button text shown. 
The strings are there, below the textfields, as labels and button text. There is no outlet to change them inside the code. In other scenes there are outlets to the code and then the localization text is added inside the code. So, what is needed is to add the missing outlets and update the Localized.strings files with new text properties for those labels and button texts...

**Comment by kmav** [comment]
Did really my 2nd PR for this has been "merged" with the 1st for translations? Why?

**Comment by kmav** [comment]
Something went wrong... 
1. two whanabee PRs merged to one (probably tryied to submit the latest two fast ?) and 
2. I had some end line white space violation errors...

I don't understand what is the status now for my latest PR...

**Comment by kmav** [comment]
Closing by PR: [NEW] Add authViewController localization #1373

**Comment by rafaelks** [comment]
This one can be closed now, thank you @kmav!
