### ISSUE TITLE
App crashes on team url input

### ISSUE THREAD

**Issue by filipealva** [RocketChat/Rocket.Chat.iOS#137]
The app crashes when I try to input my URL without `http://` or `https://` (e.g. `rocket.planejei.com`).

When I tried to input `https://rocket.planejei.com/` the app starts and ends loading but nothing happen. 

I discovered that `rocket.planejei.com` is down, btw. But I will submit this issue anyway since it is not supposed to crash when a URL is invalid.

**Comment by xandorlv** [comment]
+1 - try to put the rocket.chat server address and it is crashing. Irrelevant if I use with https or without.

**Comment by rafaelks** [comment]
@xandorlv What's your usage? Is your server offline too?

**Comment by xandorlv** [comment]
@rafaelks server was not offline as I was able to connect via web app.
