### ISSUE TITLE
[BUG] Random crashes when running unit tests

### ISSUE THREAD

**Issue by cardoso** [RocketChat/Rocket.Chat.iOS#1370]
There are some random crashes making the builds fail async tests randomly on circle-ci, but they can be reproduced locally.

**Comment by Hrayr2112** [comment]
You mean one of the tests isn't correct? I had the same problem, but now I cannot reproduce it

**Comment by rafaelks** [comment]
This one can be closed right @cardoso?

**Comment by cardoso** [comment]
Yes. I think it's not happening anymore @rafaelks . 🙏
