### ISSUE TITLE
[BUG] Layout is broken for rooms that user haven't joined on iPhone X

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.iOS#1378]
## General information

The UI is broken when user access a room that user haven't joined yet on iPhone X.

![img_3945](https://user-images.githubusercontent.com/551004/36973145-812b7e2a-2050-11e8-8fe6-a9c6c57ec041.png)

**Comment by Sameesunkaria** [comment]
And has an erratic scrolling behavior on all devices.
