### ISSUE TITLE
When i run the pod i get this error.

### ISSUE THREAD

**Issue by anappleapp** [RocketChat/Rocket.Chat.iOS#138]
Hi, 
When i run the pod install i get this Erro.
Any help appreciate.

!] Unable to satisfy the following requirements:

- `Fabric` required by `Podfile`
- `Fabric` required by `Podfile`
- `Fabric (= 1.6.9)` required by `Podfile.lock`

None of your spec sources contain a spec satisfying the dependencies: `Fabric, Fabric (= 1.6.9)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

**Comment by rafaelks** [comment]
@anappleapp Did you run `pod repo update` like the command response say to do?

**Comment by rafaelks** [comment]
Closing the issue due to inactivity.

**Comment by anappleapp** [comment]
Thanks @rafaelks , 
It solved my problem.
