### ISSUE TITLE
[BUG] Layout issues on multitasking environment

### ISSUE THREAD

**Issue by cardoso** [RocketChat/Rocket.Chat.iOS#1381]
|iPad Air 1 (iOS 11)|
|-|
|![](https://i.imgur.com/yF1uIFg.png)|

- Wrong spacing at the bottom - from iPhone X fix?
- Wrong height of attachments - I think we are calculating with full device width.

**Comment by Sameesunkaria** [comment]
@cardoso what steps can i take to reproduce the wrong spacing at the bottom?
