### ISSUE TITLE
[INVESTIGATE] PDF-Upload not possible

### ISSUE THREAD

**Issue by mrsimpson** [RocketChat/Rocket.Chat.iOS#1383]
- Your Rocket.Chat app version: #2.1.0
- Your Rocket.Chat server version: 0.61
- Device (or Simulator) you're running with: SE

Uploading a PDF is not possible, though the mime-type `application/pdf` is configured as accepted in the server.
The app returns an error "invalid-mime-type".

Using the browser, an upload of the same document is possible without any issues.

**Comment by rafaelks** [comment]
@mrsimpson Thanks for you opening the issue. Can you please contact me in `open.rocket.chat` with username `rafael.kellermann` and send me more information, like the PDF file (or send it over here if you want to)?

**Comment by mrsimpson** [comment]
@rafaelks you can use any, e. g. this one: http://unec.edu.az/application/uploads/2014/12/pdf-sample.pdf

**Comment by rafaelks** [comment]
@mrsimpson Thanks for reporting it, just fixed here: https://github.com/RocketChat/Rocket.Chat.iOS/pull/1389. This is going to be fixed for next release. 👍

**Comment by mrsimpson** [comment]
Now that’s what I call a simple fix for a lot of issues - or a simple error causing a lot of them earlier ;-)

Thanks for fixing!

**Comment by rafaelks** [comment]
Yes! I'm really sorry for that. 😞
