### ISSUE TITLE
[CHORE] Remove files from "root" folder and organize the same way Xcode project is

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.iOS#1385]
## General information

Organize all the files the same way it is in Xcode. There are a few files in the root of the project (filesystem).

**This issue needs to be done and merged before we finish the release, but only after we finish all PRs that are changing/creating files like Share Extension and Edit Profile.**

![screen shot 2018-03-07 at 14 20 00](https://user-images.githubusercontent.com/551004/37107310-c173be52-2212-11e8-8a13-61b39afdab22.png)

**Comment by imjog** [comment]
@rafaelks @cardoso Can I take this issue?
currently only `AppDelegate`, `Rocket.Chat-Bridge.h`, `Info.plist`, `Keys.plist` and `Rocket.Chat.entitlement` are not same way. We can put all these files in new folder **SupportingFiles** folder.
![screen shot 2018-03-09 at 10 26 17](https://user-images.githubusercontent.com/20956124/37191234-57fb3a54-2384-11e8-8838-8d08917d9b50.png)
