### ISSUE TITLE
iOS app doesn't load channels correctly.

### ISSUE THREAD

**Issue by muhv7** [RocketChat/Rocket.Chat.iOS#1392]
### Description:

iphone app doesn't load channels correctly after 0.62 update. Works fine on Android.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62
* Operating System: Ubuntu
* Deployment Method(snap/docker/tar/etc): Snap 
* Number of Running Instances: 1
* DB Replicaset Oplog: 
* Node Version: 
* mongoDB Version: 

### Steps to Reproduce:

Update
Use iPhone app
Blank screen

### Expected behavior:

Load normally?

### Actual behavior:

Blank screen on channels

![f6eed6b5-847e-4715-bcc5-e4c48ff3fcf2](https://user-images.githubusercontent.com/34287392/37216321-2bbfab3e-23c3-11e8-9a4e-ec0dd1b49af4.png)

**Comment by cardoso** [comment]
Hi @muhv7 ! 

Looks like you're using our Cordova App. You should open this issue at https://github.com/RocketChat/Rocket.Chat.Cordova

We will deprecate support and development of our Cordova App by the end of this month. 
I suggest you try out our native app, Rocket.Chat+.

Cheers!
