### ISSUE TITLE
[NEW] Allow sorting

### ISSUE THREAD

**Issue by Drangleic** [RocketChat/Rocket.Chat.iOS#1394]
Description:
Rocket Chat web and desktop allow for users to choose how to sort channels/DMs by activity/alphabetical/etc as well as how to group channels/DMs. The native Rocket Chat + Android/iOS mobile apps have no such control over sorting/grouping. This is highly desired by our users and impacts the way they communicate from their mobile devices.

Expected behavior:
Android/iOS mobile apps should at least replicate what users have set as their preference in the Desktop client, or allow them to configure sorting/grouping how they want.

Actual behavior:
Users have no control over sorting/grouping in the Rocket Chat + Android/iOS mobile apps.

I didn't include server details/logs as this isn't a bug or problem with the installation, but please let me know if they are required within the issue. Thanks!

**Comment by rafaelks** [comment]
@Drangleic Thank you for opening the issue! This is going to be addressed soon. 👍

**Comment by Drangleic** [comment]
Hello @rafaelks. Thanks for acknowledging this! Are there any plans to include this in a near-future release? Do you know when that might be?

**Comment by rafaelks** [comment]
@Drangleic I believe this is going to be address on next release, if not in the other one.

**Comment by GoetheG** [comment]
Good idea!

**Comment by bmstone** [comment]
Hey all, 2.3 and 2.4 have come and gone, is this still coming soon? This is a big deal for some people, since sorting is possible on desktop and Android, but still not on iOS. Really breaks some workflows as a result. Thanks!

**Comment by rafaelks** [comment]
@bmstone I'm working on this issue right now... take a look :-)

(still changes to be made, of course)

![2018-06-06 08 26 58](https://user-images.githubusercontent.com/551004/41039006-7ba9839a-696e-11e8-9400-9a1ddd214916.gif)

**Comment by bmstone** [comment]
@rafaelks Awesome! thanks so much for the update! Sorry, I hadn't seen #1720, I just had this one bookmarked to keep an eye on. Love the new layout! Can't wait to see that on TestFlight

**Comment by rafaelks** [comment]
This one is was done by #1720. 👍
