### ISSUE TITLE
[INVESTIGATE] "The URL you entered is invalid" (URL works fine from other apps.)

### ISSUE THREAD

**Issue by Epicanis** [RocketChat/Rocket.Chat.iOS#1398]
Ran into an issue with the Cordova app (and Safari as well) coming up with a blank page and nothing else when connecting (note: works fine from Android, desktop web browser, etc.), realized it was the outdated client so I downloaded the native Rocket.Chat+ one.

The new Rocket.Chat+ (v2.0.2) refuses to even accept my URL ( https://omniblab.dogphilosophy.net ). Simply pops up complaining mysteriously that "The URL you entered is invalid. Check it and try again, please!"

No indication *why* it thinks "https://omniblab.dogphilosophy.net" is "invalid". Same URL on the same device in Safari at least gets through "connecting" (but leaves me at a blank screen when it "finishes" loading, the same as the outdated Cordova app.) At the same time, desktop browsers and clients and the Android client are connecting just fine, using the same or different internet connections.

- Your Rocket.Chat app version: 2.0.2
- Your Rocket.Chat server version: 0.62.1
- Device (or Simulator) you're running with: Verizon iPhone 5C on iOS 10.3.3

**Comment by rafaelks** [comment]
@Epicanis Thanks for opening the issue and sorry about the error message. The error you're facing is because the app could not establish a secure connection with your server with the minimum requirements.

Note: Cordova, Safari and Android doesn't require all the security we're requiring in our iOS app, that's why it works.

### Logs

> Error Domain=NSURLErrorDomain Code=-1200 "Ocorreu um erro SSL e não é possível efetuar uma conexão segura com o servidor." UserInfo={_kCFStreamErrorCodeKey=-9802, NSLocalizedRecoverySuggestion=Deseja conectar ao servidor mesmo assim?, NSUnderlyingError=0x60800064a860 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, _kCFNetworkCFStreamSSLErrorOriginalValue=-9802, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802}}, NSLocalizedDescription=Ocorreu um erro SSL e não é possível efetuar uma conexão segura com o servidor., NSErrorFailingURLKey=https://omniblab.dogphilosophy.net/api/v1/info, NSErrorFailingURLStringKey=https://omniblab.dogphilosophy.net/api/v1/info, _kCFStreamErrorDomainKey=3}

### Your domain SSL report
(recommended is rating **A**)

Link: https://www.ssllabs.com/ssltest/analyze.html?d=omniblab.dogphilosophy.net

![screen shot 2018-03-12 at 10 42 56](https://user-images.githubusercontent.com/551004/37286999-61aecc90-25e2-11e8-989f-eb6a1d0f0c0c.png)

Also, looks like your certificate is expiring soon... can you take a look on it also?

Thank you!

**Comment by rafaelks** [comment]
Let me close the issue for now, since we already figure out the problem here.

**Comment by vytasmk** [comment]
It took a while to find this out. Now it shows error "The URL you entered is invalid. Check it and try again, please!" so how I can know that problem is with SSL certificate? Also it could point to the ssllabs.com site to find out the problem with SSL.

**Comment by rafaelks** [comment]
@vytasmk Yes, we can definelty improve the way we're handling this error, were you able to fix it?

**Comment by vytasmk** [comment]
Hi @rafaelks, yes we have today updated our HAProxy that was used as proxy. Before we have used quite old version that did not supported TLS 1.2 and without TLS 1.2 sslabs showed Rating "C". After we updated HAProxy now we have Rating "B" and it is working just fine now.

So if the message was more clear and may be with hint to check sslabs page for Rating (must be not less than "B") then users can save time for trying to identify the problem :)

**Comment by rafaelks** [comment]
@vytasmk Yes, makes total sense, just created an issue for that: https://github.com/RocketChat/Rocket.Chat.iOS/issues/1413.

**Comment by johnjoeallen** [comment]
I'm getting this issue with the latest native app and my SSL server has an A rating. Letsencrypt certificate

https://chat.moyville.net

**Comment by rafaelks** [comment]
@johnjoeallen WOW! You just own the title of oldest server version trying to connect to our iOS app, hahaha... you're running 0.14 (from 2016) 🥇. This is not supported, we support only 0.62+ and you can see the list here: https://rocket.chat/docs/developer-guides/mobile-apps/supported-servers-versions/#supported-servers-versions

**Comment by blackhatethicalhacking** [comment]
Hi, got also the same issue, but on android only.

After using LetsEncrypt, i can connect with IoS, on desktop too.

but on android i cannot, any nginx config i need to change maybe under docker compose config file?

**Comment by sigfriedseldeslachts** [comment]
Same here, I have an A+ rating on Qualys. I can't connect using any of the apps. Works fine on desktop and browser. Tried to mess with the reverse proxy but it doesn't seem to work.
Server is chat.dojocasts.com

**Comment by sigfriedseldeslachts** [comment]
@maziyarpanahi Thanks anyway. I not using Apache either. I'm using nginx. And I used the code that they specified in their docs. I tried both native and react app but they all give the an error.
@rafaelks do you have any idea?

**Comment by rafaelks** [comment]
@sigfriedseldeslachts This is the error that your server is showing...

```
[REST][RESULT][https://chat.dojocasts.com/api/v1/info]: {
  "status_code" : 404,
  "id" : "api.context.404.app_error",
  "message" : "Sorry, we could not find the page.",
  "detailed_error" : "There doesn't appear to be an api call for the url='\/api\/v1\/info'.  Typo? are you missing a team_id or user_id as part of the url?"
}.
```

**Comment by sigfriedseldeslachts** [comment]
Sorry for the late response. I know what the issue was. The ciphers nginx was set to aren't supported by the builtin http requests lib of Android. Adding more ciphers to fixed the issue. I also quickly tried out Mattermost but I don't like it. I'm gonna swtich back to Rocket.Chat.
Thanks anyway!
