### ISSUE TITLE
Direct Messages

### ISSUE THREAD

**Issue by anappleapp** [RocketChat/Rocket.Chat.iOS#142]
Hi @rafaelks , 

Are you going to add also Direct Messages label? 
To do Direct Message.

**Comment by rafaelks** [comment]
@anappleapp You mean, to be able to send DM to other users? What's this Label you're talking about?

**Comment by anappleapp** [comment]
Yes, i mean send DM to other users.

**Comment by rafaelks** [comment]
@anappleapp Yeah, it is availble today if you want to send to existent DMs, but you can't search for new subscriptions/users right now. It will definitely be a feature. Already created the issue: #149.

Thank you @anappleapp!

**Comment by anappleapp** [comment]
@rafaelks  thanks.
