### ISSUE TITLE
Issue when reusing Message cells for long texts

### ISSUE THREAD

**Issue by anappleapp** [RocketChat/Rocket.Chat.iOS#143]
Hi @rafaelks , 

When I write long text like more than 15 characters in textfield in doesnt read in Chat.Storyboard some characters appear some not.

**Comment by rafaelks** [comment]
@anappleapp Sorry, can you show some screenshot/gif? Thank you!

**Comment by anappleapp** [comment]
Yes, Sure. 

Here is the first screen i am trying to write long charters 
![one](https://cloud.githubusercontent.com/assets/11163232/19269302/2c2c5e12-8fba-11e6-8d59-532e4f234c99.png)

And here is when i click send button that not read all characters in story board.
![two](https://cloud.githubusercontent.com/assets/11163232/19269322/463acf32-8fba-11e6-880e-c162ba2e3a7a.png)

and here when i change the chanel and come back to my chanel after some mins the characters appear again as i wrote.

![three](https://cloud.githubusercontent.com/assets/11163232/19269345/6281090e-8fba-11e6-9bfc-88b546b20292.png)

I dont why it shows in this way, seems like problem of connection but i use good wifi.

**Comment by rafaelks** [comment]
@anappleapp OK, this is for sure some issue while reusing the cells. I'll take a look, thank you!

**Comment by anappleapp** [comment]
Thanks @rafaelks
