### ISSUE TITLE
[IMPROVEMENT] Migrate "Emojis" RealTime request to REST

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.iOS#1431]
Requires server version **0.61**, fallback to RealTime.
New API endpoint documentation: https://rocket.chat/docs/developer-guides/rest-api/emoji-custom/get/

**Comment by filipealva** [comment]
@rafaelks In the docs it says it was introduced on `0.61.0`. Are you sure it requires `0.63`?

```
Version | Description
-- | --
0.61.0 | Added
```

**Comment by rafaelks** [comment]
@filipealva You're right!!! Changed the description of the issue. Thanks!
