### ISSUE TITLE
[INVESTIGATE] Improve our build time

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.iOS#1435]

**Comment by rafaelks** [comment]
Update: just confirmed that the slowest file to compile is Emojione, everything is basically "fine".

### Screenshot 1

![screen shot 2018-03-27 at 07 12 53](https://user-images.githubusercontent.com/551004/37961318-4de2be9e-318e-11e8-817e-fd12c68fec39.png)


### Screenshot 2

![screen shot 2018-03-27 at 07 11 51](https://user-images.githubusercontent.com/551004/37961248-29cd8b10-318e-11e8-9a28-ccfddb3af8aa.png)

**Comment by Sameesunkaria** [comment]
@rafaelks I already have something in the works for this. I've managed to get the compile time down from about 1:40 sec to under 30 on my machine. Currently I'm testing it's performance impact on the application.

**Comment by rafaelks** [comment]
@Sameesunkaria Oh, that's great! You're working on the `Emojione.swift`?

**Comment by Sameesunkaria** [comment]
@rafaelks yup
