### ISSUE TITLE
App not starting

### ISSUE THREAD

**Issue by xandorlv** [RocketChat/Rocket.Chat.iOS#144]
`2016-10-10 21:26:33.028227 Rocket.Chat[57270:8137720] [] nw_connection_endpoint_report [1 settings.crashlytics.com:443 in_progress proxy (satisfied)] reported event flow:finish_transport
fatal error: 'try!' expression unexpectedly raised an error: Error Domain=io.realm Code=10 "Migration is required due to the following errors:
- Property 'Auth.settings' has been added.
- Property 'Message.attachments' has been added." UserInfo={NSLocalizedDescription=Migration is required due to the following errors:
- Property 'Auth.settings' has been added.
- Property 'Message.attachments' has been added., Error Code=10}: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-800.0.46.2/src/swift/stdlib/public/core/ErrorType.swift, line 178` in AuthManager.swift.
And after I pulled in latest changes I no longer can even start the app.

**Comment by rafaelks** [comment]
@xandorlv Remove the app and start again, database changed and I did not make a migration (will only do after App Store release).
