### ISSUE TITLE
[QUESTION] Difference between "Rocket.Chat" and "Rocket.Chat+" in the App Store

### ISSUE THREAD

**Issue by GoetheG** [RocketChat/Rocket.Chat.iOS#1456]
It's hard to understand the difference between Rocket.Chat and Rocket.Chat+ within the app store. It would be nice having a clarification on what that means.

**Comment by rafaelks** [comment]
@GoetheG That's a good question. Let me try to clarify it:

1. There are two apps right now in the App Store: "Rocket.Chat" and "Rocket.Chat+". They're both from us and when you search by "Rocket.Chat" both app will appear on the search;
2. The main difference between then: "Rocket.Chat" is written in Cordova and is being deprecated (until 31th March by us) and we're going to remove it from the store (or rename it to "Classic"). "Rocket.Chat+" is our native iOS application, the one that's present on this repository. It's faster, reliable and contains most of the features that the web application does (just like Cordova).
3. Witch one should I download today? The answer is "Rocket.Chat+".

I'm really sorry for the confusion, but we're working hard to solve it in the next weeks. 👍 

Hopefully this question was clarified for you guys.
