### ISSUE TITLE
[IMPROVEMENT] Improve type-checking time of some methods

### ISSUE THREAD

**Issue by cardoso** [RocketChat/Rocket.Chat.iOS#1478]
Use custom flags to see warnings: ```-Xfrontend -warn-long-function-bodies=200``` & ```-Xfrontend -warn-long-expression-type-checking=200```

![](https://i.imgur.com/ydvZsVh.png)

**Comment by Sameesunkaria** [comment]
Is anyone actively working on this?

**Comment by rafaelks** [comment]
@Sameesunkaria Not right now. Wanna go for it?

**Comment by Sameesunkaria** [comment]
I'm currently working on the in app notifications, I'll look into it when I'm done with that. But, it wouldn't be the first time that I'll be looking into reducing the type checking time. 🤠

**Comment by rafaelks** [comment]
@Sameesunkaria Great! Thanks!
