### ISSUE TITLE
[FEATURE REQUEST/IMPROVEMENT] Alternating Chat Bubbles

### ISSUE THREAD

**Issue by Drangleic** [RocketChat/Rocket.Chat.iOS#1479]
Description:
One of the features we'd like to see is to have chats (both DMs and group chats) come from alternating sides of the window based on who is sending it. As in Google Hangouts (and numerous other chat applications), a user's own chats appear on the right hand side of the window, and chats from other users appear on the left. We would highly appreciate the ability to toggle this on or off (would be great if it was a user setting), as it really improves clarity and speed when reading chats. This is especially true if you are reading back through a long conversation.

Please let us know if you would like additional description as to what we're talking about, or if this should be posted elsewhere.

Thanks!

**Comment by rafaelks** [comment]
@Drangleic Thanks for your suggestion! Since this is something that requires discussion, can you please start a new discussion in our forums under "Feature Requests" category? You can use this link: https://forums.rocket.chat/c/feature-requests. For now, I'm gonna close the issue. Thank you!

**Comment by vijay0964** [comment]
Do we have any update on this feature? In my project also, I would like to show the messages with alternative bubbles.
