### ISSUE TITLE
[BUG] Requests throwing version error mistakenly

### ISSUE THREAD

**Issue by filipealva** [RocketChat/Rocket.Chat.iOS#1499]
- Your Rocket.Chat app version: 2.1.1
- Your Rocket.Chat server version: 0.63.0
- Device (or Simulator) you're running with: iPhone 6s

All requests with a required version with the `patch` greater than the `patch` of the current server version are being considered as greater than the current server version, no matter if the major or minor, i.e with the current logic `0.62.2` would be considered greater than `0.63.0`.

**Comment by rafaelks** [comment]
This one can be closed for now.
