### ISSUE TITLE
[INVESTIGATE] New message notification on lock screen does not show message text

### ISSUE THREAD

**Issue by allabezroutchko** [RocketChat/Rocket.Chat.iOS#1501]
- Your Rocket.Chat app version: 2.1.1
- Your Rocket.Chat server version: 0.62.2
- Device (or Simulator) you're running with: iOS 11.2.6

The new message notifications on iOS lock screen do not contain the text of the message. If you tap View on the notification from lock screen, the text is still not shown. See screenshots below.

![img_0703](https://user-images.githubusercontent.com/35561893/38419077-4942226c-399f-11e8-89fe-07b2437b5caa.PNG)
![img_0704](https://user-images.githubusercontent.com/35561893/38419079-495b3c34-399f-11e8-82ab-171b8d48fa6e.PNG)

Expected behaviour: The message text is shown both in lock screen notifications and when tapping View from lock screen.

**Comment by rafaelks** [comment]
@allabezroutchko Thanks for the feedback! What message is that? When you open the chat, does it say something?

**Comment by allabezroutchko** [comment]
@rafaelks Here is what the message looks like when I open it in the app:
![img_0705](https://user-images.githubusercontent.com/35561893/38419694-ae5896de-39a1-11e8-940e-227df9887569.PNG)
This happens with all messages, not just this one.

**Comment by rafaelks** [comment]
@allabezroutchko OK, I'll move this issue to our back-end project. 👍

**Comment by rafaelks** [comment]
Issue moved to [RocketChat/Rocket.Chat #10364](https://github.com/RocketChat/Rocket.Chat/issues/10364) via [**ZenHub**](https://www.zenhub.com/)
