### ISSUE TITLE
IconColorOffline and Online ..etc Not update.

### ISSUE THREAD

**Issue by anappleapp** [RocketChat/Rocket.Chat.iOS#154]
Hi @rafaelks , 

I just checked the IconColors. But it doesnt update. 
I changed  `var color = iconColorOnline` but it update very late.

Thanks

**Comment by rafaelks** [comment]
@anappleapp You mean, in the subscriptions list or in the chat view?

**Comment by anappleapp** [comment]
In the subscriptions.
