### ISSUE TITLE
[QUESTION] Unable to connect to chat server using mobile app

### ISSUE THREAD

**Issue by KBPratap** [RocketChat/Rocket.Chat.iOS#1543]
I am able to connect to the chat server using browser and desktop application but the mobile version (on iPhone 7+) doesn't let me connect.

App doesn't show any version info. On referring app store, the version is 2.1.1

**Comment by Sameesunkaria** [comment]
@KBPratap Is the server configured for SSL (TLS 1.2)?

**Comment by mschaefers** [comment]
I have the same problem using Version 2.2.0 of "Rocket.Chat+" from the AppStore.

Our Server uses TLSv1.2. I did a `openssl s_client connect serveraddress:port` and essentially got

```
SSL handshake has read 2391 bytes and written 302 bytes
Verification: OK
---
New, TLSv1.2, Cipher is ECDHE-ECDSA-AES128-GCM-SHA256
Server public key is 256 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
```

**Comment by mschaefers** [comment]
My problem is **solved**. Was related to https://github.com/RocketChat/Rocket.Chat/issues/6435: RocketChat was behind apache2 proxy and websockets were not proxied correctly.

**Comment by rafaelks** [comment]
@mschaefers Thanks for the feedback. Let's close the issue for now.
