### ISSUE TITLE
SwiftLint, Debug Build Failed

### ISSUE THREAD

**Issue by philipborbon** [RocketChat/Rocket.Chat.iOS#1544]
For every Swift variables that start with underscore(_) e.g. 
`let _request = SubscriptionCreateRequest`

"Identifier Name Violation: Variable name should only contain alphanumeric" is thrown.

Code is from latest release in master branch,
https://github.com/RocketChat/Rocket.Chat.iOS/commit/cd0010c991c265b2ded7c7d287ab97e3ec6ca449

**Comment by cardoso** [comment]
I think that should be fixed once we merge beta into master (AppStore release) early this week.
