### ISSUE TITLE
[IMPROVEMENT] Remove Markdown tags from in some parts of the app

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.iOS#1563]
- [x] In-app notifications;
- [x] Reply/Quote pop-up;
- [x] Push notifications

**Comment by Sameesunkaria** [comment]
@rafaelks for in-app notifications, the markdown should be removed from the backend. 

There’s already an issue for that (posted by you) RocketChat/Rocket.Chat#9979.
You could maybe update it and mention the same requirement for desktop notifications? 🤔

**Comment by rafaelks** [comment]
@Sameesunkaria For now, we can remove the markdown by simply getting the cached value on Markdown library and transforming it in pure String (.string attribute of `NSAttributedString`). Would you mind doing this?
