### ISSUE TITLE
[IMPROVEMENT] Holding core chat references when adding a new server

### ISSUE THREAD

**Issue by filipealva** [RocketChat/Rocket.Chat.iOS#1568]
Since `SocketManager.connectionHandlers` is a dictionary it holds strong references to the values it stores. So when we go to add a new server we still hold in memory the core chat view controllers references on `SocketManager.connectionHandlers` when they should be gone and they keep interacting with the socket (reconnecting when we disconnect, sending commands, etc) which may cause problems when connecting to a new server not to say about performance issues due to heavy unnecessary instances being held in memory.

**Comment by rafaelks** [comment]
Good catch @filipealva, thanks for investigating! 👍
