### ISSUE TITLE
[QUESTION] OAuth with Custom Client

### ISSUE THREAD

**Issue by TannerJuby1** [RocketChat/Rocket.Chat.iOS#1570]
Before writing an issue, please make sure you're talking about the native application (called Rocket.Chat+ in the App Store) and not the Cordova one (called Rocket.Chat in the App Store). If you are looking to open an issue to the Cordova application, go to this URL: https://github.com/RocketChat/Rocket.Chat.Cordova.

- Your Rocket.Chat app version: 2.1.1
- Your Rocket.Chat server version: 0.54.0
- Device (or Simulator) you're running with: iPhone 8 (iOS 11.3)

**Just for some background so you understand the context of my situation**
I am working on integrating Rocket.Chat.iOS into another iOS native application. I have succeeded in transferring the source code into my workspace and have it compiling and running. The main difference is how we are handling the authorization process: a user is already logged into our app through our own server, and when they go into the Rocket.Chat portion of the app we authorize the user with Rocket.Chat via OAuth using our own client. The OAuth process is where I am running into some issues.

**The Issue**
When looking through your `OAuthController.swift file`, I noticed that in the `willNavigate(_ web view: WKWebView...)` function this block of code:
```
if url.fragment != nil {
    if let credentials = oauthCredentials(from: url) {
        success?(credentials)
    } else if !url.absoluteString.contains("code=") {
        failure?()
    }

     dismissWebViewController()
} 
```
is the only way to retrieve the credentials. The callback for our URL does not pass the `url.fragment != nil` check because it only passes back a code. 

As I understand the OAuth process, after retrieving the code from the client after authenticating with login credentials, you make a call to Rocket.Chat that sends to code in exchange for the oauth credentials (key and secret). 

My question is why are you failing if there is a `code` in the url fragment? If I were to add a block of code that instead grabbed the code from the url and finished the OAuth process as I described above, would it be an acceptable method?

Thanks for your help!

**Comment by cardoso** [comment]
Hi @TannerJuby1 . Thanks for your interest in working with our code.

> My question is **why are you failing if there is a code in the url fragment**? If I were to add a block of code that instead grabbed the code from the url and finished the OAuth process as I described above, would it be an acceptable method?

It seems to me in that piece of code we're doing the opposite. If it's the callback url, but there's no "code=" in it, we signal failure.

I'm probably not understanding the context very well, but if you're handling all the authentication process, why do you need to look into the OAuthController class? Why not just trade the credentials you have with the server directly?

**Comment by TannerJuby1** [comment]
Oh, thats my bad, I completely misread that part of the code, I missed the bang(!).

But we need the OAuthController because we are not storing the password on the phone for security reasons. Therefore, we can't just call the `authorize(username: String, password: String...)` that is provided. 

So, back to the callback url piece, what happens if the url is not fragmented, but there is a code in the query params? Right now, the WebView just hangs and doesn't do anything. But shouldn't it be sending that code to the rocket.chat server to get the oauth key and secret? How do you handle the OAuth process if the client doesn't fragment the oauth key and secret in the url?

**Comment by cardoso** [comment]
@TannerJuby1 
1. What are you storing then? Or is the user going to authenticate twice? 🤔

2. The client having the tokens in the url fragment is part of the OAuth 2.0 implicit grant spec. 

source: https://tools.ietf.org/html/draft-ietf-oauth-v2-26#section-4.2

Maybe your OAuth client doesn't have implicit grant enabled? Some services like WordPress have the option of disabling the implicit grant flow.

**Comment by TannerJuby1** [comment]
1. When the user is created, we create a Rocket.Chat user for them on our rocket.chat server. After the user logs into the app, a session is created and stored in cookies. When they go to the Rocket.Chat section of the app, we need to authenticate them through OAuth passing the cookie so the OAuth is all in the background. 

2. Okay, that makes sense. I’ll talk to the client about enabling implicit grant.

So does Rocket.Chat not support clients that disable implicit grant?

**Comment by TannerJuby1** [comment]
Good to know! Thanks for the help!

**Comment by cardoso** [comment]
Alright! Good luck @TannerJuby1 :)
