### ISSUE TITLE
[BUG] OAuth provider sign-in not working

### ISSUE THREAD

**Issue by Sameesunkaria** [RocketChat/Rocket.Chat.iOS#1577]
On tapping the OAuth provider above the username and password field, nothing happens. 
First noticed this on merging the commits from develop a few of minutes ago. (the merge before that would be about 4-5 days ago)

![OAuth not working](https://user-images.githubusercontent.com/7317008/39088004-5a014616-45c8-11e8-81ad-409a05e38f44.gif)

**Comment by cardoso** [comment]
Thank you @Sameesunkaria . I've identified an inconsistency in our API.
