### ISSUE TITLE
Using Without Pods

### ISSUE THREAD

**Issue by anappleapp** [RocketChat/Rocket.Chat.iOS#158]
Hi @rafaelks , 

If i want to add rocket.chat inside the project that wrote in objective -C and have pods also it gives error basically when i copy rocket.chat pods to another project that has 2 pods when  i click to install pods it gives many errors, however i wanted to ask you if there is anyway to not use rocket.chat pods and Directly add the framework of this pods to the rocket.chat instead of pod.
  pod 'Fabric'
  pod 'Crashlytics'

  # Code utilities
  pod 'SwiftyJSON'

  # UI
  pod 'SideMenu'
  pod 'SlackTextViewController'

  # Database
  pod 'RealmSwift'

  # Network
  pod 'SDWebImage', '~> 3.8'
  pod 'Starscream', '~> 2.0.0'

**Comment by rafaelks** [comment]
@anappleapp I've never done it, but you can try using this [tool](https://github.com/CocoaPods/cocoapods-deintegrate) that I found [here](http://stackoverflow.com/a/16427883/1088230).

Anyway, we have a plan to create a separated framework that anyone can integrates in the app, but that will take some time, hehe.

**Comment by anappleapp** [comment]
Thanks @rafaelks  :)
