### ISSUE TITLE
[INVESTIGATE] Consider "SFAuthenticationSession" for OAuth

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.iOS#1587]
Apple docs: https://developer.apple.com/documentation/safariservices/sfauthenticationsession

**Comment by cardoso** [comment]
We need to do this after we drop support for iOS 10

**Comment by rafaelks** [comment]
@cardoso Can we start using for iOS 11?

**Comment by cardoso** [comment]
http://www.openradar.me/35796658

SFAuthenticationSession requires us to specify a custom scheme for the redirection URL.
Most social logins (google and facebook for example) don't allow custom schemes in the redirection URL.

Closing this 😕
