### ISSUE TITLE
Pods install problem 

### ISSUE THREAD

**Issue by anappleapp** [RocketChat/Rocket.Chat.iOS#159]
Hi @rafaelks , 

i am trying to combine Rocket.Chat with another project. i started first to install the pods but when i install your project pods to new project, it gives error that No such model "SwiftyJSON" Do you know how can i solve this issue?

Here is the snapshot.

Thanks in advanced.:)

![one](https://cloud.githubusercontent.com/assets/11163232/19525201/76a08132-9620-11e6-94fc-78c8be2b4d1e.png)

![two](https://cloud.githubusercontent.com/assets/11163232/19525208/7ca35d70-9620-11e6-9093-453627be3649.png)

![three](https://cloud.githubusercontent.com/assets/11163232/19525213/80b8537a-9620-11e6-8c21-f5bf56e97b5d.png)

**Comment by rafaelks** [comment]
Sorry, I don't get what you're trying to do. Can you upload a demo?

**Comment by anappleapp** [comment]
Hi @rafaelks , 

Thanks, i solved the issue in pod file instead of writing my app name in target, i wrote my app name with test. i solved the issue. 
Thanks .
