### ISSUE TITLE
[NEW] Support "announcement" property

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.iOS#1593]
We need to display the *announcement* information in the app.

The announcement needs to appear on the top of the room, showing the property and supporting markdown tags. As an example, you can see how it looks on the web client.

**Comment by promehul** [comment]
Could please elaborate this issue a little more..

**Comment by rafaelks** [comment]
@promehul Done!

**Comment by blewjy** [comment]
@rafaelks, currently working on this issue. I managed to get the announcement to show up at the top of the chat window as a banner, but what colours should I use for the background and the label?

Currently, I'm using `theme.bannerBackground` and `theme.auxiliaryText`. Is that ok?

**Comment by rafaelks** [comment]
@blewjy Lovely, thank you! Here's how it looks on the web client, the ideal would be getting something similar to this, with the colors that we have in our Theme model. Let me know if I can help you with something else. 👍 

![screen shot 2019-01-24 at 13 59 03](https://user-images.githubusercontent.com/551004/51690622-368f3100-1fe0-11e9-8b92-385161cddb07.png)

**Comment by blewjy** [comment]
This is what I have currently for the 3 different themes! Achieved with `bannerBackground` and `auxiliaryText` from the Theme model

![announcement-light](https://user-images.githubusercontent.com/39292809/51691635-1ee29780-2036-11e9-9d17-18ffaf178211.png) ![announcement-black](https://user-images.githubusercontent.com/39292809/51691631-1e4a0100-2036-11e9-9902-df42927ec403.png) ![announcement-dark](https://user-images.githubusercontent.com/39292809/51691632-1e4a0100-2036-11e9-94b4-63cb0625a2df.png)

And this is how the action view looks like

![annoucement-action-view](https://user-images.githubusercontent.com/39292809/51691628-1e4a0100-2036-11e9-893f-2aa3dab396ee.png)

**Comment by rafaelks** [comment]
@blewjy That looks pretty awesome! Thank you! :-)
