### ISSUE TITLE
Won't Connect to URL with Trailing Slash

### ISSUE THREAD

**Issue by tarnover** [RocketChat/Rocket.Chat.iOS#160]
When you try to connect to Rocket.Chat server adding trailing slash gives error that mobile isn't enabled on server.

Example: https://chat.domain.com/ 

If user adds something like /home to URL gives error that server is running out of date version. 

![rocket-chat_ios-error](https://cloud.githubusercontent.com/assets/12649241/19657677/059c7fd2-99da-11e6-9314-795967c0a97b.png)

**Comment by rafaelks** [comment]
@tarnover This is related to the Cordova project, not this one: https://github.com/RocketChat/Rocket.Chat.Cordova.
