### ISSUE TITLE
Can't connect to my own server.

### ISSUE THREAD

**Issue by CharlesOy** [RocketChat/Rocket.Chat.iOS#162]
I can't connect to my own server, client says "**The server http://192.168.xxx.xxx is not enabled for mobile apps**". Anyone know how to fix this?

**Comment by CharlesOy** [comment]
Also I'm using the latest server(0.43.0).

**Comment by rafaelks** [comment]
@CharlesOy I believe you should open the issue into the [server project](https://github.com/RocketChat/Rocket.Chat).
