### ISSUE TITLE
how to block users?

### ISSUE THREAD

**Issue by edisonjoao** [RocketChat/Rocket.Chat.iOS#1625]
I'm curious, but how do you block users? Is there a feature that you guys have, so others won't message you?

**Comment by cardoso** [comment]
Currently, you do a long press on a message from that user and you can block them.

We plan on moving that to pressing on the username and on the cell in the channel's members list as of #1615

**Comment by edisonjoao** [comment]
i'm talking about on the back end of things, like do you have a security rules? aplogies about not being clear

**Comment by cardoso** [comment]
@edisonjoao I think you should ask at https://github.com/RocketChat/Rocket.Chat or in our forums https://forums.rocket.chat

This repository is only for the iOS native version.

But to partially answer your question, we don't support any server-side user blocking in the iOS app yet.

**Comment by willow9886** [comment]
Hi @cardoso do you know how I can unblock messages from a user that has previously been blocked?
