### ISSUE TITLE
[BUG] Aleatory blank messages

### ISSUE THREAD

**Issue by filipealva** [RocketChat/Rocket.Chat.iOS#1635]
We are experiencing aleatory blank messages as the screen shot below shows: 

![screen shot 2018-05-03 at 21 56 36](https://user-images.githubusercontent.com/6117280/39609154-0843699a-4f1d-11e8-90f4-ea89dfd9dcb2.png)

**Comment by rafaelks** [comment]
This one was closed by #1636
