### ISSUE TITLE
[QUESTION] Can't run this project!

### ISSUE THREAD

**Issue by linjiaxing1992** [RocketChat/Rocket.Chat.iOS#1639]
Why did I download this project, show the missing file, and can't run?

![image](http://opbgz9a4w.bkt.clouddn.com/Screenshot%202018-05-04_17-28-25.png)

![image](http://opbgz9a4w.bkt.clouddn.com/Screenshot%202018-05-04_17-30-44.png)

**Comment by artrmz** [comment]
Did you run „pod install” in terminal before building? (You need to install cocoapods to do that)

**Comment by Sameesunkaria** [comment]
@rafaelks Should we add instructions detailing how to get the project running on the repo README?

**Comment by linjiaxing1992** [comment]
ok,there is no problem. we should „pod install” in terminal before building.

but,This will take a long time. about 2 hours hahah
