### ISSUE TITLE
[QUESTION] Uploaded pictures are not displayed in the mobile version 

### ISSUE THREAD

**Issue by steffikunze** [RocketChat/Rocket.Chat.iOS#1646]
- Your Rocket.Chat app version: 2.2.0 (159)
- Your Rocket.Chat server version: 0.63.3
- Device (or Simulator) you're running with: iPhone SE

You can upload the image, but only see a white field. Also the uploaded pictures of others are not displayed correctly.

![picture upload](https://user-images.githubusercontent.com/39053063/39699690-8f799620-51fa-11e8-8fa9-ca54be5c21c1.PNG)

**Comment by rafaelks** [comment]
@steffikunze What's your server URL?

**Comment by janrudolph** [comment]
@rafaelks Why do you need the server URL to solve this issue?

**Comment by rafaelks** [comment]
@janrudolph @steffikunze I want to check your "Site_Url" settings. But maybe you can do that first: remove the last "/" from the setting, if it's present.

**Comment by janrudolph** [comment]
@rafaelks yeah, that seems to be the solution. But I suggest that Rocket.Chat checks the site URL and adjusts the URL internally if necessary. It is not obvious that you are not allowed to add an extra slash to the URL.

**Comment by rafaelks** [comment]
@janrudolph Yes, but really think this should be done on the back-end. Otherwise every client that needs this URL will have to take care of it :-)

Glad it worked. Closing the issue for now.

**Comment by janrudolph** [comment]
@rafaelks I added an issue https://github.com/RocketChat/Rocket.Chat/issues/10716
