### ISSUE TITLE
[QUESTION] No avatar of user

### ISSUE THREAD

**Issue by Radist7941** [RocketChat/Rocket.Chat.iOS#1661]
Server 0.64.1
1) No avatar user on Iphone X
There is no problem on iphone 5
2) no Russian language
![img_5591](https://user-images.githubusercontent.com/39255737/39980542-24e735f0-5755-11e8-9875-eeb1bdad2c47.PNG)

**Comment by rafaelks** [comment]
@Radist7941 Please, check if your `Site_Url` settings ends with `/`. If yes, then remove it please.

Related to the Russian language: could you translate our English file to Russian? In this case we can add support to your language. 👍
