### ISSUE TITLE
[BUG] Mixing up messages on opening notification

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat.iOS#1665]
When opening a notification, sometimes the last openend chat is loaded and the message from the notification is append to this conversation, even if the users are different.
![009bafee-ad2d-4089-94d9-5cbd4b75942e](https://user-images.githubusercontent.com/193273/39999070-480cc6e8-5788-11e8-8e95-1c25b2ff3344.png)

**Comment by martinvonwittich** [comment]
Can confirm, I've also seen this several times.

**Comment by rafaelks** [comment]
This one was fixed for 3.0.0, closing for now.
