### ISSUE TITLE
runing iOS  has problem with title ' Podfile.lock: No such file or directory'

### ISSUE THREAD

**Issue by TomWang1** [RocketChat/Rocket.Chat.iOS#1677]
Before writing an issue, please make sure you're talking about the native application (called Rocket.Chat+ in the App Store) and not the Cordova one (called Rocket.Chat in the App Store). If you are looking to open an issue to the Cordova application, go to this URL: https://github.com/RocketChat/Rocket.Chat.Cordova.

- Your Rocket.Chat app version: 2.3.0（167）
- Your Rocket.Chat server version: ####
- Device (or Simulator) you're running with: iPhone6（11.0.1）

**The app isn't connecting to your server?**
Podfile.lock: No such file or directory

**Comment by Sameesunkaria** [comment]
@TomWang1 did you run `pod install`? 

Rocket.Chat is using [CocoaPods](https://cocoapods.org) to manage its dependencies. Please [install](https://cocoapods.org) it of you haven't already.

**Comment by soundstorm** [comment]
Or simply refer to the guide:
https://github.com/RocketChat/Rocket.Chat.iOS/blob/develop/CONTRIBUTING.md

**Comment by rafaelks** [comment]
Closing this one, thanks for the help @soundstorm & @Sameesunkaria! 👊
