### ISSUE TITLE
[BUG] Status become offline & user cannot change the status anymore unless closing the app

### ISSUE THREAD

**Issue by kaiiiiiiiii** [RocketChat/Rocket.Chat.iOS#1681]
I don't get any notifications and I'm not able to see any online statuses since I've upgraded to the latest version today. Already tried a relogin to the server and a complete new install of the app, both didn't bring any success.

- Your Rocket.Chat app version: 2.4.0
- Your Rocket.Chat server version: 0.64.1
- Device (or Simulator) you're running with: iPhone 7, iOS 11.3.1

iOS App:
![img_e5039](https://user-images.githubusercontent.com/4711233/40234085-b51641b8-5aa5-11e8-952d-381e3f3e4a03.JPG)

Desktop Client:
![2018-05-18 14_10_40-rocket chat](https://user-images.githubusercontent.com/4711233/40234025-74d918dc-5aa5-11e8-81fb-71a44bfd8837.png)

**Comment by rafaelks** [comment]
@kaiiiiiiiii Thanks for the report! Let me ask you a few things:

1. Have you tried killing the app and opening again?
2. Have you tried logging out and logging in again?
3. Have you tried uninstalling the app and installing again?

Thank you!

**Comment by rafaelks** [comment]
Just saw your comments, you did that.

**Comment by kaiiiiiiiii** [comment]
Same problem on open.rocket.chat (Bradley’s marked as busy in the desktop client).

![cb5352fe-c537-45ee-aa92-1fa6134b8d2b](https://user-images.githubusercontent.com/4711233/40245931-4dde32c2-5ac7-11e8-9c2a-2b042f2ac8e0.png)

**Comment by Sameesunkaria** [comment]
@rafaelks I faced similar issues earlier today while I was testing out the changes to the notifications.

**Comment by kaiiiiiiiii** [comment]
@Sameesunkaria @rafaelks Logging out and back in only works as a fix as long as you don’t send the app to the background or lock your phone.

**Comment by eeldwin** [comment]
+1 for this issue

**Comment by AulaAstur** [comment]
+1 to this.

**Comment by rafaelks** [comment]
We're investigating this issue guys! 👍

**Comment by rafaelks** [comment]
I'm having a hard time reproducing this issue... could you please say what are the steps to reproduce this?

**Comment by AulaAstur** [comment]
Well,

In my case is a docker instance that I got up yesterday on my Synology NAS. All things are going great on the Web/Desktop app, but in iOS (iPhone 6) this things are happening:

Once on the app, you register the server and log-in. Go to another iOS app or lock the smartphone, once you're in again on the RocketChat app, the chaos has started.

I think this things are related:
1)You cannot set your status, and you cannot see the status of other people.
2) You do not receive notifications, and if someone invites you to a private channel, this does not appear on the iOS app.
3) If you open a chat you yourself, RocketChat shows the profile image of the last private chat with other user you opened. Or the word "label" if is the first private chat you open.

Thanks,

**Comment by rafaelks** [comment]
@kaiiiiiiiii @AulaAstur Thank you! Just reproduced the issue here, I'm working in a fix. 👍

**Comment by rafaelks** [comment]
@kaiiiiiiiii @AulaAstur @eeldwin Please, join our channel `ios-beta` in https://open.rocket.chat and send us your email so we can send you guys our beta builds. 👍
