### ISSUE TITLE
[BUG] Terms of Service and Privacy Policy Pages have no content

### ISSUE THREAD

**Issue by angelicamar** [RocketChat/Rocket.Chat.iOS#1690]
Environment:
Rocket.Chat app version: 2.4.0 (171)
Rocket.Chat server version: 0.64.0-rc.2
Device (or Simulator) you're running with: iPhone 7 (IOS 11.3) and iPad Pro (IOS 11.3.1)

Pre-condition:
User is in Login page.

Steps:
1. Click Terms of Service link
- Verify Terms of Service page
2. Click Done button on the upper left corner of the page
- Verify Login page
3. Click Privacy Policy link
- Verify Privacy Policy page

Expected Result:
Terms of Service and Privacy Policy pages should open without any issue.

Actual Result:
*QA FAILED*. Terms of Service and Privacy Policy pages have no content.

Please see attached photos:
Terms of Service Page:
https://www.dropbox.com/s/2bhzy3phmupcuft/Photo%2017-05-2018%2C%2011%2032%2058%20AM.png?dl=0
Privacy Policy Page:
https://www.dropbox.com/s/htt0ygbiranv7es/Photo%2017-05-2018%2C%2011%2034%2056%20AM.png?dl=0

**Comment by rafaelks** [comment]
@angelicamar Thanks for the issue, but this is not a bug. This is because the web server doesn't have any terms/policy configured. 👍
