### ISSUE TITLE
[Bug] New Account > New account with blank Name field was created successfully

### ISSUE THREAD

**Issue by angelicamar** [RocketChat/Rocket.Chat.iOS#1692]
**Environment:**
Rocket.Chat app version: 2.4.0 (171)
Rocket.Chat server version: 0.64.0-rc.2
Device (or Simulator) you're running with: iPhone 7 (IOS 11.3) and iPad Pro (IOS 11.3.1)

**Pre-condition:**
User is in Login page.

**Steps:**
1. Click Create New Account link
- Verify New Account Page
2. Leave the Name field blank
3. Complete Email and Password fields with valid details
4. Click Go button on the keyboard
- Verify Register Username page
5. Enter a valid username in the field box
- Verify account creation

**Expected Result:**
Account creation should be unsuccessful. An error message should be seen when creating an account with blank Name field.

**Actual Result:**
*QA FAILED*. New account with blank Name field was created successfully.

Please see attached video:
https://www.dropbox.com/s/o5jb6bhv8nal1xb/Video%2017-05-2018%2C%2012%2009%2017%20PM.mp4?dl=0

**Comment by rafaelks** [comment]
@angelicamar This is not a bug. The server needs to validate if the name is required or not (and that depends on the server information).
