### ISSUE TITLE
[Improvement] New Account > Add an error message when creating an account with blank Password field

### ISSUE THREAD

**Issue by angelicamar** [RocketChat/Rocket.Chat.iOS#1693]
**Environment:**
Rocket.Chat app version: 2.4.0 (171)
Rocket.Chat server version: 0.64.0-rc.2
Device (or Simulator) you're running with: iPhone 7 (IOS 11.3) and iPad Pro (IOS 11.3.1)

**Pre-condition:**
User is in Login page.

**Steps:**
1. Click Create New Account link
- Verify New Account Page
2. Complete Name and Email fields with valid details
3. Leave Password field blank
4. Click Go button on the keyboard
- Verify error message

**Expected Result:**
Please add an error message when creating an account with blank Password field.

**Actual Result:**
Creating an account did not progress but no error message was seen.

Please see attached video:
https://www.dropbox.com/s/exnjl7lyopjjozj/Video%2017-05-2018%2C%2012%2015%2057%20PM.mp4?dl=0

**Comment by rafaelks** [comment]
@angelicamar This is not a bug. The server needs to validate if the name is required or not (and that depends on the server information).
