### ISSUE TITLE
[BUG] New Account > Email was registered even if account was not created

### ISSUE THREAD

**Issue by angelicamar** [RocketChat/Rocket.Chat.iOS#1694]
**Environment:**
Rocket.Chat app version: 2.4.0 (171)
Rocket.Chat server version: 0.64.0-rc.2
Device (or Simulator) you're running with: iPhone 7 (IOS 11.3) and iPad Pro (IOS 11.3.1)

**Pre-condition:**
User is in Login page.

**Steps:**
1. Click Create New Account link
- Verify New Account Page
2. Complete Name and Email fields with valid details
3. Leave Password field blank
4. Click Go button on the keyboard
- Verify page behavior
5. Enter a password this time
6. Click Go button on the keyboard again
- Verify validation message

**Expected Result:**
Email address should not be registered when the account was not successfully created.

**Actual Result:**
*QA FAILED*. A validation message that the email already exist was seen.

Please see attached video:
https://www.dropbox.com/s/finmxrgaq4qcuwq/Video%2017-05-2018%2C%2012%2018%2012%20PM.mp4?dl=0

**Comment by rafaelks** [comment]
This is also a validation on the server side that needs to be done.
