### ISSUE TITLE
[BUG] Register Username > New Account with a blank Username was successfully created 

### ISSUE THREAD

**Issue by angelicamar** [RocketChat/Rocket.Chat.iOS#1695]
**Environment:**
Rocket.Chat app version: 2.4.0 (171)
Rocket.Chat server version: 0.64.0-rc.2
Device (or Simulator) you're running with: iPhone 7 (IOS 11.3) and iPad Pro (IOS 11.3.1)

**Pre-condition:**
User is in Login page.

**Steps:**
1. Click Create New Account link
- Verify New Account Page
2. Complete the fields with valid details
3. Click Go button on the keyboard
- Verify Register Username Page
4. Leave the username field blank
5. Click Go button on the keyboard
- Verify new account

**Expected Result:**
Account creation should be unsuccessful. An error message should be seen saying username is a required field.

**Actual Result:**
*QA FAILED*. New Account with a blank Username was successfully created.

Please see attached video:
https://www.dropbox.com/s/73b2qr0lzeyh8sx/Video%2017-05-2018%2C%201%2013%2034%20PM.mp4?dl=0

**Comment by rafaelks** [comment]
This is also allowed on the server-side, not a bug on the client.
