### ISSUE TITLE
[Improvement] Preferences > Edit Profile > Change the confirmation message to an error message when updating Name field with spaces only

### ISSUE THREAD

**Issue by angelicamar** [RocketChat/Rocket.Chat.iOS#1697]
**Environment:**
Rocket.Chat app version: 2.4.0 (171)
Rocket.Chat server version: 0.64.0-rc.2
Device (or Simulator) you're running with: iPhone 7 (IOS 11.3) and iPad Pro (IOS 11.3.1)

**Pre-condition:**
User is in Login page.

**Steps:**
1. Login with valid details
- Verify account
2. Click the hamburger menu button
- Verify sidebar
3. Click Sidebar header
- Verify User Preferences menu
4. Click Preferences
- Verify Preferences modal
5. Click Profile
- Verify Profile modal
6. Click Edit button on the upper right corner of the modal
7. Delete details on Name field
8. Type spaces only in the Name field box
9. Click Save button on the upper right corner
- Verify message

**Expected Result:**
Please change the confirmation message to an error message when updating Name field with spaces only.

**Actual Result:**
App did not update the Name with spaces only but confirmation message said "Profile Updated".

Please see attached video:
https://www.dropbox.com/s/h7pfhv7wy08u7g6/Video%2017-05-2018%2C%202%2023%2025%20PM.mp4?dl=0

**Comment by cardoso** [comment]
This is a problem with our API. Moving this issue to https://github.com/RocketChat/Rocket.Chat/issues/10917
