### ISSUE TITLE
[BUG] Preferences > Language > App language did not change to the selected language

### ISSUE THREAD

**Issue by angelicamar** [RocketChat/Rocket.Chat.iOS#1698]
**Environment:**
Rocket.Chat app version: 2.4.0 (171)
Rocket.Chat server version: 0.64.0-rc.2
Device (or Simulator) you're running with: iPhone 7 (IOS 11.3) and iPad Pro (IOS 11.3.1)

**Pre-condition:**
User is in Login page.

**Steps:**
1. Login with valid details
- Verify account
2. Click the hamburger menu button
- Verify sidebar
3. Click Sidebar header
- Verify User Preferences menu
4. Click Preferences
- Verify Preferences modal
5. Click Language
- Verify Language page
6. Click a language
7. Click Ok on the confirmation message
8. Close Rocket.Chat
9. Restart Rocket.Chat
- Verify app language

**Expected Result:**
App language should change to the selected language after restarting Rocket.Chat.

**Actual Result:**
*QA FAILED*. App language did not change to the selected language even after restarting.

Please see attached video:
https://www.dropbox.com/s/wpg9i4uqieiy9p8/Video%2017-05-2018%2C%203%2023%2019%20PM.mp4?dl=0

**Comment by cardoso** [comment]
I think I may have fixed this in https://github.com/RocketChat/Rocket.Chat.iOS/pull/1637 when I did the work on localizing error messages from the REST API.

**Comment by cardoso** [comment]
Closed by #1637
