### ISSUE TITLE
[IMPROVEMENT] New Channel > Channel with more than 21 characters on Channel Name was successfully created

### ISSUE THREAD

**Issue by angelicamar** [RocketChat/Rocket.Chat.iOS#1700]
**Environment:**
Rocket.Chat app version: 2.4.0 (171)
Rocket.Chat server version: 0.64.0-rc.2
Device (or Simulator) you're running with: iPhone 7 (IOS 11.3) and iPad Pro (IOS 11.3.1)

**Pre-condition:**
User is in Login page.

**Steps:**
1. Log in with valid details
- Verify account
2. Click the hamburger menu button
- Verify sidebar
3. Click "+" on the sidebar header
- Verify New Channel page
4. Enter a Channel Name with more than 21 characters
5. Add users on Invite Users field
6. Click Create button on the upper right corner
- Verify new channel

**Expected Result:**
As on the description below the field, creating a channel with more than 21 characters on Channel Name should not be allowed.

**Actual Result:**
*QA FAILED*. Channel with more than 21 characters on Channel Name was successfully created.

Please see attached video:
https://www.dropbox.com/s/wbfqgre1pf0fu20/Video%2018-05-2018%2C%207%2058%2042%20AM.mp4?dl=0

**Comment by rafaelks** [comment]
I think the solution here is to remove the footer text, because the validation needs to be server side.
