### ISSUE TITLE
[BUG] Unmuted user on a Broadcast channel was still not allowed to send messages

### ISSUE THREAD

**Issue by angelicamar** [RocketChat/Rocket.Chat.iOS#1702]
**Environment:**
Rocket.Chat app version: 2.4.0 (171)
Rocket.Chat server version: 0.64.0-rc.2
Device (or Simulator) you're running with: iPhone 7 (IOS 11.3) and iPad Pro (IOS 11.3.1)

**Pre-condition:**
User has been unmuted on a Broadcast channel through the web app.
User is already login on the mobile app.

**Steps:**
1. Go to the broadcast channel where you have been unmuted
- Verify sending message

**Expected Result:**
Unmuted user on a broadcast channel should be allowed to send messages to the channel.

**Actual Result:**
*QA FAILED*. Unmuted user on a Broadcast channel was still not allowed to send messages.

Please see attached photo:
https://storage.googleapis.com/openscreenshot/z/A/j/S14sAojAz.png?i=1

**Comment by rafaelks** [comment]
@angelicamar This is because the server is Broadcast... on Broadcast channels, only admin, moderators, owners and users with the permission `post-readonly` should be allowed to create new messages.

**Comment by cardoso** [comment]
Should this be closed @rafaelks ?
