### ISSUE TITLE
[BUG] New Channel > New Channel modal did not close after successfully creating a new channel

### ISSUE THREAD

**Issue by angelicamar** [RocketChat/Rocket.Chat.iOS#1704]
**Environment:**
Rocket.Chat app version: 2.4.0 (171)
Rocket.Chat server version: 0.64.0-rc.2
Device (or Simulator) you're running with: iPad Pro (IOS 11.3.1)

**Pre-condition:**
User is in Login page.

**Steps:**
1. Log in with valid details
- Verify account
2. Click the hamburger menu button
- Verify sidebar
3. Click "+" on the sidebar header
- Verify New Channel modal
4. Enter a valid Channel Name
5. Add users on Invite Users field
6. Click Create button on the upper right corner
- Verify New Channel modal

**Expected Result:**
New Channel modal should close after successfully creating the new channel.

**Actual Result:**
*QA FAILED*. New Channel modal did not close after successfully creating a new channel.

Please see attached video:
https://www.dropbox.com/s/hsno0fntmo87b37/Video%20May%2018%2C%202%2045%2011%20PM.mp4?dl=0

**Comment by cardoso** [comment]
Could not reproduce
