### ISSUE TITLE
[BUG] Client 2.4.0 doesn't work corretly with server 0.64.1

### ISSUE THREAD

**Issue by VareliyK** [RocketChat/Rocket.Chat.iOS#1706]
- Your Rocket.Chat app version: 2.4.0
- Your Rocket.Chat server version: 0.64.1
- Device (or Simulator) you're running with: iOS 11.3.1

After Update to version 2.4.0 client always offline. I don't see new rooms, new messages.
After reinstall or reload connection to server app correctly work only first time. After close app i offline again always.

**Comment by rafaelks** [comment]
@VareliyK We're releasing a new version today with this update in our TestFlight.

**Comment by VareliyK** [comment]
Thank's. We are waiting for.

**Comment by rafaelks** [comment]
@VareliyK Do you have any email I can send you the beta build?

**Comment by VareliyK** [comment]
I replied to your personal email

**Comment by VareliyK** [comment]
I just have tried. Deleted old version and install from TestFlight. I was online only first connection. After close app i offline again.

**Comment by VareliyK** [comment]
Ok :)

**Comment by VareliyK** [comment]
Hello! @rafaelks when you release new 2.4.1 (175)?

**Comment by rafaelks** [comment]
@VareliyK Currently waiting for Apple to approve the builds. 👍

**Comment by rafaelks** [comment]
Version 2.4.1 is already in the App Store, please go check it out. 👍

**Comment by VareliyK** [comment]
It works, thanks.  We hope, that your will improve testing process.
