### ISSUE TITLE
Account disconnects / user offline

### ISSUE THREAD

**Issue by cfv1000** [RocketChat/Rocket.Chat.iOS#1713]
Before writing an issue, please make sure you're talking about the native application (called Rocket.Chat+ in the App Store) and not the Cordova one (called Rocket.Chat in the App Store). If you are looking to open an issue to the Cordova application, go to this URL: https://github.com/RocketChat/Rocket.Chat.Cordova.

- Your Rocket.Chat app version: 2.4.0
- Your Rocket.Chat server version: 0.64.0
- Device (or Simulator) you're running with: Iphone 8

**The app isn't connecting to your server?**
Make sure your server supports WebSocket. These are the minimum requirements for Apache 2.4 and Nginx 1.3 or greater.

Steps: 
1. Open the app
2. Configure your server, username and password. Login succesfully
3. Use the app, then put it in background
4. bring the app back from background

Expected behaviour: you should be logged in 
Actual behaviour: your account is not logged in. For other users the account appears as offline.

If I logout and re-do the configuration, the app works. When I background the app, I have the same issue again.

**Comment by thrahlf** [comment]
I have got the same issue....

**Comment by VareliyK** [comment]
https://github.com/RocketChat/Rocket.Chat.iOS/issues/1706

**Comment by VareliyK** [comment]
Yesterday, Rafaelk promised new version. But i have not been seeing yet.

**Comment by rafaelks** [comment]
We're waiting for Apple to approve the beta builds and the build to the store now. 🤞

**Comment by rafaelks** [comment]
Version 2.4.1 is already in the App Store, please go check it out. 👍
