### ISSUE TITLE
Switching online-status is not reflected on the App

### ISSUE THREAD

**Issue by mrsimpson** [RocketChat/Rocket.Chat.iOS#1714]
- Your Rocket.Chat app version: 2.4.0
- Your Rocket.Chat server version: 0.63.3

When switching the status on the iOS-App, the status is properly changed server-side, but the UI of the App is not getting refreshed.

=> Other users can the the changed status correctly, but I don't know which state I'm in (kind-of philosophic, isn't it?)

**Comment by rafaelks** [comment]
This one was fixed for 2.4.1, already in the App Store.
