### ISSUE TITLE
[INVESTIGATE] Rocket.Chat iOS client accepting blank password field

### ISSUE THREAD

**Issue by xxmoC** [RocketChat/Rocket.Chat.iOS#1730]
### Description:

We use RocketChat with our AD servers for LDAP authentication. But we experience some strange behaviour on iOS devices as our users can authenticate without giving a password (read: empty field). 

As far as we can see the Android, Windows and webclient do work as expected, seems like the iOS device has no check whether the authentication is correct. 

We have got anonymous binding only open for RootDSE as designed and adviced by Microsoft (microsoft.png). When connecting to the OU of the users they're in this is absolutely not possible with anonymous binding.  

---------------
![microsoft](https://user-images.githubusercontent.com/32290203/40651223-6fd7edca-6335-11e8-8780-299d4ebe59b7.png)
---------------

### Server Setup Information:

* Version of Rocket.Chat Server: 0.64.1
* Version of Rocket.Chat iOS client: 2.2.0
* Operating System:  linux 4.4.0-98-generic
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* Node Version: v8.11.1

### Steps to Reproduce:

1. Open the iOS app (step1.png)
2. Fill in the username && blank password field (step2.png)
3. Logged in without a password (step3.png)

![step1](https://user-images.githubusercontent.com/32290203/40651763-cabfa18c-6336-11e8-922a-ac489c17ea55.png)
![step2](https://user-images.githubusercontent.com/32290203/40651764-caf0c5be-6336-11e8-8cc0-d38e0998f2a6.png)
![step3](https://user-images.githubusercontent.com/32290203/40651765-cb1910e6-6336-11e8-8088-4182ce464ba2.png)

### Expected behavior:

I would expect the system to give an error that the users haven't entered their passwords and cannot login

### Actual behavior:

The user is logged in on an iOS device, without entering a password 

### Relevant logs:

When I try to reproduce the LDAP query with my serviceaccount in AD (ldapsearch) and try to search and/or bind the user I cannot bind or search without entering a password in the particular OU, it is only accepting anonymous bindings on RootDSE. Probably the the iOS client is not checking this or whatsoever.

Also see ldapsearch1.png  & ldapsearch2.png

![ldapsearch1](https://user-images.githubusercontent.com/32290203/40651749-c44843d6-6336-11e8-90a9-b37c7096c419.png)
![ldapsearch2](https://user-images.githubusercontent.com/32290203/40651750-c47801fc-6336-11e8-8560-a115d1b58c7d.png)

**Comment by rafaelks** [comment]
@xxmoC Thanks for the investigation! Here's the API request we do on the app to authenticate the user:

```shell
curl "https://open.rocket.chat/api/v1/login" -H "Content-Type: application/json" -d '{"ldap": true, "username": "YOUR_USERNAME", "ldapPass": "YOUR_PASSWORD", "ldapOptions": []}'
```

Can you try with your values and an empty value for password and let me know the result? The iOS app would not be allowed to enter in the server if the API didn't provide us the token.

**Comment by xxmoC** [comment]
With password:

`$ curl "https://rocketchat.xxx.nl/api/v1/login" -H "Content-Type: application/json" -d '{"ldap": true, "username": "firstname.lastname@domain.com", "ldapPass": "Password", "ldapOptions": []}'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   216    0   116  100   100    265    228 --:--:-- --:--:-- --:--:--   494{"status":"success","data":{"userId":"xxxxxxxxx","authToken":"xxxxxxxx"}}`

Without password:

`$ curl "https://rocketchat.xxx.nl/api/v1/login" -H "Content-Type: application/json" -d '{"ldap": true, "username": "firstname.lastname@domain.com", "ldapPass": "", "ldapOptions": []}'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   223    0   136  100    87    108     69  0:00:01  0:00:01 --:--:--   178{"status":"error","error":"LDAP-login-error","message":"LDAP Authentication failed with (2) provided username [firstname.lastname@domain.com]"}`

So strange right, seems to be working correctly through the API 👍 

Any other ways of troubleshooting this?

**Comment by rafaelks** [comment]
@xxmoC Please, contact me at `rafael.kellermann` in https://open.rocket.chat. 👍

**Comment by VareliyK** [comment]
epic fail (((

**Comment by VareliyK** [comment]
Client Version 2.4.1 (176) - the same problem

**Comment by rafaelks** [comment]
@xxmoC @VareliyK We already discussed the problem... the API is returning the login token even when the password is empty. I asked @xxmoC to open an issue, did you open? Thanks!

**Comment by xxmoC** [comment]
Jep, here: https://github.com/RocketChat/Rocket.Chat/issues/11017. I'll close this one down.

**Comment by VareliyK** [comment]
@xxmoC why did you close this issue for iOS ?

**Comment by rafaelks** [comment]
@VareliyK The issue is on the API: https://github.com/RocketChat/Rocket.Chat#11017

**Comment by VareliyK** [comment]
@rafaelks thank's
