### ISSUE TITLE
[PROJECT] Delete duplicate files

### ISSUE THREAD

**Issue by tmbiOS** [RocketChat/Rocket.Chat.iOS#1747]
In `develop` branch you have duplicated files in Model's folder: `Auth, Subscription, User` and `SubscriptionUserStatusViewController`. You removed references of them but you should move them to trash.
![image](https://user-images.githubusercontent.com/37933181/41025711-4d4191de-697b-11e8-8dac-9799e64a86f3.png)
#

**Comment by rafaelks** [comment]
@tmbiOS Thanks for pointing that to us! Sending a PR right now removing it. 👍
