### ISSUE TITLE
[BUG] video/image view can't be closed

### ISSUE THREAD

**Issue by frdmn** [RocketChat/Rocket.Chat.iOS#1749]
When tapping on a video / image so it opens in full screen, I can't dismiss/close the view by tapping the `X` in the top left corner.

- Your Rocket.Chat app version: 2.4.1 (176)
- Your Rocket.Chat server version: latest (0.65.1)
- Device (or Simulator) you're running with: iPhone X but customer reports also confirm this on iPhone 8

**Comment by cardoso** [comment]
I'm not able to reproduce this. Tried on iPhone SE and iPad Pro.

**Comment by rafaelks** [comment]
@cardoso It happens on iPhone X.
