### ISSUE TITLE
[IMPROVEMENT][NEW ONBOARDING] Increase the amount of buttons displayed depending on the screen size

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.iOS#1759]
If the screen is big, let's show more buttons. Let's always present the number of buttons that allow the footer to be visible without any scrolling.

![simulator screen shot - ipad pro 10 5-inch - 2018-06-13 at 11 08 14](https://user-images.githubusercontent.com/551004/41356605-a0d1c72c-6efa-11e8-866f-de86b0fe98d2.png)

**Comment by filipealva** [comment]
@rafaelks I think we can show more than 3 buttons on `collapsed` state for large screens such as iPad screens, but I don't think we should add as much buttons as we can without scrolling. It seems that it is designed to have some blank space on`collapsed` state. 

I'm not sure if I'm expressing myself well, but I think we will be distorting the original intention of Thiago when he designed it if we just use all the space available by default. If he wanted it in the first place he would've not designed the following screen with empty space below the auth buttons.

![screen shot 2018-05-18 at 07 32 12](https://user-images.githubusercontent.com/551004/40230394-abf3e4d8-5a6d-11e8-92a4-687b3786352a.png)

Make sense?

**Comment by rafaelks** [comment]
@filipealva Yes, makes sense! 👍
