### ISSUE TITLE
[BUG] Images uploads are giant in Desktop / Web

### ISSUE THREAD

**Issue by ArchimedesFM** [RocketChat/Rocket.Chat.iOS#1766]
- Your Rocket.Chat app version: 2.4.1
- Your Rocket.Chat server version: 0.65.1
- Device (or Simulator) you're running with: iPhone SE - iOS 11.4

Image Uploads via iOS App are very huge on Desktop / Web Clients.
They take a full screen on an full hd display.
Normally they scale down and integrate themselves nicely in the ongoing chat.

Screenshot from Rocket.Chat Desktop:
![14-06-_2018_09-14-04](https://user-images.githubusercontent.com/26709898/41397187-ae35de80-6fb3-11e8-9642-acbf07e7d059.jpg)

**Comment by rafaelks** [comment]
Looks like this is a bug on the web displaying the image, fixed here: https://github.com/RocketChat/Rocket.Chat/pull/10998.
