### ISSUE TITLE
[BUG][NEW UI] Subscription list changing order mistakenly when scrolling

### ISSUE THREAD

**Issue by filipealva** [RocketChat/Rocket.Chat.iOS#1777]
When scrolling up and down the subscription list changes its order. Above my sorting setup and a gif demonstrating the bug (look at the first two subscriptions and how they change as I simply scroll up and down)

<img width="252" alt="screen shot 2018-06-15 at 10 15 07" src="https://user-images.githubusercontent.com/6117280/41469898-62488fd6-7085-11e8-83a5-f2c5363d1e1b.png"/>

![](http://g.recordit.co/TnDiGPSz0n.gif)

**Comment by soundstorm** [comment]
Seems like the "alphabetical" order type gets resetted to activity (also when closing the view/reopening the app etc.)

**Comment by soundstorm** [comment]
I see the favorites title two times; partly without channel names but the # image (and row)
