### ISSUE TITLE
[BUG] Allowing large message's text view to scroll on iOS 10

### ISSUE THREAD

**Issue by filipealva** [RocketChat/Rocket.Chat.iOS#1792]
It only happens on iOS 10
![](http://g.recordit.co/AKjTjoPQ7L.gif)

**Comment by rafaelks** [comment]
@filipealva I'm fixing this one in my PR of UI adjustments.

**Comment by filipealva** [comment]
@rafaelks nice! Feel free to close this issue or associate it with your PR
