### ISSUE TITLE
[BUG] The nav bar on an iPad running iOS 10 does not stretch to its full extents

### ISSUE THREAD

**Issue by Sameesunkaria** [RocketChat/Rocket.Chat.iOS#1794]
The nav bar title view for the chat VC should stretch to occupy the whole width of the detail VC.

The search bar is also not sizing correctly.

![simulator screen shot - ipad air - 2018-06-18 at 21 00 22](https://user-images.githubusercontent.com/7317008/41559318-9791ac0a-733b-11e8-9880-69b36b937278.png)

**Comment by rafaelks** [comment]
iOS 10 won't be supported anymore after 3.2.0.
