### ISSUE TITLE
[IMPROVEMENT] Prevent fullscreen white image from obscuring close button

### ISSUE THREAD

**Issue by janrudolph** [RocketChat/Rocket.Chat.iOS#1810]
If you open a white picture, it gets enlarged and covers the whole screen. From a user perspective, it is not obvious how to close the picture preview. I found out that an user has to slide sideway to close the preview. This is not intuitive.

Example:

![](https://user-images.githubusercontent.com/3596824/41762489-380311b2-75fb-11e8-87d4-4af3dfeacd25.png)

**Comment by cardoso** [comment]
Can you upload a screenshot?

We should have it, except it's in the top left corner.

**Comment by janrudolph** [comment]
Ah, I found it @cardoso , but it is very hard to see, please see screenshot of the screenshot below ;-) 

![img_6989](https://user-images.githubusercontent.com/3596824/41762449-14a621e6-75fb-11e8-9b55-64b8790aa42b.PNG)

Let's highlight it more.

**Comment by cardoso** [comment]
The problem is an image with a white background that is the same size as your screen, so it goes behind the white "x". In other situations the background is black.

I'll mark this as a ux improvement. We should look at this in the future 👍 Thanks for the report.

**Comment by rafaelks** [comment]
@cardoso Let's add a color to the navigationBar, black "transparent", what do you think? I also noticed that the X is too close to the clock, let's add some space also (at least 8px from the top)
