### ISSUE TITLE
[BUG] Clear button stays in searchbar when opening inapp notification

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat.iOS#1818]
If you entered something in the searchbar and scroll up, the (X) stays there. Also I see duplicates (?)
![4f208a42-ba52-4ba5-9cb6-6f02e5322972](https://user-images.githubusercontent.com/193273/41796413-b5e21d60-7666-11e8-9213-c6616b10168e.png)

**Comment by soundstorm** [comment]
Seems like an edge case (?)
Somehow can't reproduce

**Comment by soundstorm** [comment]
Reproduced it:
- Text entered in searchbar
- Opening an in-app notification
- Going back to channel overview - now you can scroll with collapsing searcher @Sameesunkaria

**Comment by Sameesunkaria** [comment]
@rafaelks @soundstorm I believe this issue presented itself because of the transparent nav bar. Now that we have fixed that, this shouldn't happen anymore.

**Comment by soundstorm** [comment]
@Sameesunkaria As your comment is gone, I think you noticed it yourself :)
Now only the bottom half of the (X) is visible.

When searching we have a view with the searchbar pinned to the top replacing the server etc. info. When returning from an in-app notification we have the normal layout and this produces this ui bug.

**Comment by soundstorm** [comment]
![screenrecording_07-14-2018 21-58-24](https://user-images.githubusercontent.com/193273/42728524-62a50222-87bc-11e8-8288-8b66bb95d320.gif)
