### ISSUE TITLE
[IMPROVEMENT] Theme startup image

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat.iOS#1823]
When loading the white image with red logo is default.
But when toggled to dark/black mode the startup image should also get a color scheme like this.

**Comment by artrmz** [comment]
I do not think it's possible to theme LaunchScreen though 😭 Or is it?

**Comment by Sameesunkaria** [comment]
Not sure if we're allowed to have multiple launch screens and load the one we want to display. 🤷🏻‍♂️ If that's possible we "might" have a themed launch screen.........

**Comment by artrmz** [comment]
@Sameesunkaria Can have few storyboards with LaunchScreen - for each language in the app to localize it (can set storyboard's name in `InfoPlist.strings`) but that's all from what I know.

**Comment by rafaelks** [comment]
I don't think we can do that either... will close the issue and if anyone discovers how to do it, please comment here so we can reopen the issue! 👍
