### ISSUE TITLE
[IMPROVEMENT] Extended/Condensed channel view

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat.iOS#1826]
With 3.0 we changed to the channel view mode called extended on web frontend. Before we had a condensed view with only the channel name and image. Some admins may have deactivated the option to store the last message, so users will see a list of
```
#channelname
No message

#channelname
No message

```
We may include a switch to collapse the view back to
```
#channelname
#channelname
```

**Comment by rafaelks** [comment]
@TheReal1604 @soundstorm Yes!!! And this thing was a learning for me when we launched the Android app... I wrote few words about it here, please take a look: https://forums.rocket.chat/t/improving-the-onboarding-of-new-servers-into-the-ecosystem-of-mobile-clients/1388.
