### ISSUE TITLE
[I18N] Prepare strings for 3.0.0 release

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.iOS#1830]
- [ ] cs
- [x] de
- [ ] el
- [x] en
- [ ] es
- [x] fr
- [ ] pl
- [x] pt-BR
- [x] pt-PT
- [ ] ru

**Comment by rafaelks** [comment]
(cc @TheMythPT)

**Comment by soundstorm** [comment]
* [x] de 😜

**Comment by kaiiiiiiiii** [comment]
I’m more than happy to review the DE translations 🙃

**Comment by rafaelks** [comment]
@soundstorm @kaiiiiiiiii You guys are more than welcome to contribute, thank you!!! :-)

**Comment by coruble** [comment]
@rafaelks Currently working on French. Pull Request coming shortly.

**Comment by rafaelks** [comment]
@coruble Amazing, thank you very much!
