### ISSUE TITLE
[BUG] Text marked as code is not rendered correctly on iOS

### ISSUE THREAD

**Issue by rex4539** [RocketChat/Rocket.Chat.iOS#1836]
- Your Rocket.Chat app version: 2.5.0 (179)
- Your Rocket.Chat server version: 0.63.3
- Device (or Simulator) you're running with: iPhone 6s

I entered this code on the macOS client: ```java -jar ./zcash/src/ZcashSwingWallet.jar``` but the word java was not included inside the code in iOS.

See attached screenshots.

![screen shot 2018-06-26 at 20 30 46](https://user-images.githubusercontent.com/227442/41929916-3ef4e718-7982-11e8-9b09-149b1a59c3ef.png)
![img_4070](https://user-images.githubusercontent.com/227442/41929925-45ce47b4-7982-11e8-960b-39d530c287c5.png)

**Comment by rex4539** [comment]
@rafaelks Check https://chat.zcashcommunity.com/channel/zcash?msg=H7AqGvA6vzGwiCPSF

**Comment by rafaelks** [comment]
@rex4539 We currently don't have any support for code styling in our markdown. There's already an issue opened for this: https://github.com/RocketChat/Rocket.Chat.iOS/issues/1245

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
