### ISSUE TITLE
[BUG] Join The Community button directs to Server Sign in page

### ISSUE THREAD

**Issue by GeTadle** [RocketChat/Rocket.Chat.iOS#1839]
Environment:
Rocket.Chat app version: 2.4.0 (171)
Device (or Simulator) you're running with: iPhone X ios version 11.3

Pre-condition:
Rocket Chat App fresh installed

Steps:

1. Launch Rocket Chat app
2. Tap Join The Community
- Verify correct landing page should display

Expected Result:
Should direct to open.rocket.chat (community) page

Actual Result:
Page directs first to Server Sign in then to Community page

Please see attached video:
https://www.dropbox.com/s/6trgakb8nfs3chp/Video%2027-06-2018%2C%209%2014%2004%20AM.mp4?dl=0

**Comment by rafaelks** [comment]
@GeTadle This is the expected action. 👍
