### ISSUE TITLE
[Bug] open.rocket.chat opens when connecting to a null server

### ISSUE THREAD

**Issue by GeTadle** [RocketChat/Rocket.Chat.iOS#1840]
Environment:
Rocket.Chat app version: 2.4.0 (171)
Device (or Simulator) you're running with: iPhone X ios version 11.3

Pre-condition:
Rocket Chat App fresh installed

Steps:

1. Launch Rocket Chat app
2. Tap Connect To A Server
3. Leave Server URL field null then tap connect

Expected Result:
Server entry should be unsuccessful. A validation message should appear

Actual Result:
open.rocket.chat page opens when connecting to a null server

Please see attached video:
https://www.dropbox.com/s/cihdjmum686o5f9/Video%2027-06-2018%2C%209%2015%2038%20AM.mp4?dl=0

**Comment by Sameesunkaria** [comment]
@GeTadle This is actually the expected behavior. The placeholder is there to let you know that if no url is entered, you will by default be connected to the open.rocket.chat server.

**Comment by rafaelks** [comment]
Yes, closing the issue for now. 👍
