### ISSUE TITLE
[BUG] Hamburger menu > Logout > App crashes when logged out

### ISSUE THREAD

**Issue by YanniStaMaria** [RocketChat/Rocket.Chat.iOS#1841]
Environment:
Rocket.Chat app version: 3.0.0(184)
Device (or Simulator) you're running with: iPad 5th Gen (IOS 11.1.2)

Pre-condition:
User account is logged in.

Steps:

1. Tap the hamburger menu icon on the upper left corner of the page
2. Tap Logout from Rocket.Chat

Expected Result:
User account should be logged out. User should be redirected to Server URL page.

Actual Result:
open.rocket.chat crashes when logged out

Please see attached video:
https://www.dropbox.com/home/rocket%20chat?preview=Video+27-06-2018%2C+9+40+57+AM.mp4

**Comment by rafaelks** [comment]
@YanniStaMaria Cannot see the video... version 3.0.0 doesn't have a hamburger menu... can you send us the video?

**Comment by Sameesunkaria** [comment]
@rafaelks I believe @YanniStaMaria is talking about the settings glyph, which kinda looks like a hamburger (tho one needs a good imagination 😅). But, this issue is really related to the app crashing on logout.

**Comment by rafaelks** [comment]
@Sameesunkaria Right!!! So this is fixed in `develop` branch already, thanks for reporting @YanniStaMaria!
