### ISSUE TITLE
[BUG] Hamburger menu > Profile > Edit > Save > Validation message was consist of codes

### ISSUE THREAD

**Issue by YanniStaMaria** [RocketChat/Rocket.Chat.iOS#1842]
Environment:
Rocket.Chat app version: 3.0.0 (184)
Device (or Simulator) you're running with: iPad 5th Gen (IOS 11.1.2)

Pre-condition:
User account is logged in.

Steps:

1. Click the hamburger menu icon on the upper left corner of the page
2. Tap > on the username
3. Tap Edit
4. Enter a username on username field that is already registered on Rocket.Chat
5. Tap Save

Expected Result:
Edit profile should be unsuccessful. A validation message should be seen.

Actual Result:
Validation message was consist of codes
_Note: Issue also occurs on creating an existing channel and creating an account with invalid email_

Please see attached photo:
https://prnt.sc/jzroy8

**Comment by rafaelks** [comment]
@YanniStaMaria I understand the issue... but the error comes from the API and there's currently no way for us to know what's the error to be showed (in order to show a different message). Can you open this issue in our API repo? http://github.com/RocketChat/Rocket.Chat/
