### ISSUE TITLE
[QUESTION] How to log in without SSL

### ISSUE THREAD

**Issue by CH1PSET1** [RocketChat/Rocket.Chat.iOS#1843]
- Your Rocket.Chat app version: 2.5.0
- Your Rocket.Chat server version: 0.65.2
- Device (or Simulator) you're running with: Iphone 7

Please tell me why I can not connect to my server without SSL from the Rocket.Chat + for ios application? And there is a choice for andorid.
2. When connecting from iphone to https://open.rocket.chat, chats are not downloaded and the eternal download hangs from above. (loading).

3. I have Ip thrown through mikrotik, but I can throw only http, if I put SSL, can I also connect via http but with SSL or what should I do in this situation?

**Comment by Sameesunkaria** [comment]
Hi @CH1PSET1 

Currently, some of the code related to connecting with the server automatically assumes that you can connect over HTTPS and exclusively uses it even if you entered an HTTP url. If you want to, you can make changes to the code to work with HTTP (search for all HTTPS string in the app), but it is definitely not recommended, due to the security implications it has.

As for the other two points, I'm not completely sure what you're trying to say. A little more context would be helpful.

**Comment by breezeeluo** [comment]
make changes to the code to work with HTTP (search for all HTTPS string in the app),make sure url = IP:3000/url else; or make sure the port of server is 80;

**Comment by Sameesunkaria** [comment]
@CH1PSET1 and replace `wss` with `ws`.

**Comment by CH1PSET1** [comment]
And how can I make changes to the application?

**Comment by Sameesunkaria** [comment]
clone the repository and open up the project in Xcode. (don't forget to `pod install`)

**Comment by rafaelks** [comment]
Closing this one for now.

**Comment by stephensworld** [comment]
Hey, we would like to use this great tool in hamnet. Hamnet is a amateur radio ip network in the 44.0.0.0/8 subnet. We do not have any trusted certificates. So for us it would be great to have a possibility to connect unsecure without ssl. Is it possible to implement this? If it is a security reason maybe you can allow this if the destination server is in 44.0.0.0/8 subnet. 
Thank you very much. 
Stephan

**Comment by reetp** [comment]
> Hey, we would like to use this great tool in hamnet.

Are you talking about Rocketchat in general or the iOS app ?

This particular issue is for the iOS and app specifically and I don't believe this will change so it will not be reopened.

If you are talking about Rocketchat in general then yes you can still use http if you really must. 

The main repo for Issues is here https://github.com/RocketChat/Rocket.Chat but note this is to report bugs, not for help/setup.

There is documentation here https://rocket.chat/docs/

For general help you can ask in the forums or come and chat at open.rocket.chat #support
