### ISSUE TITLE
Can't build app from xcode

### ISSUE THREAD

**Issue by y00rb** [RocketChat/Rocket.Chat.iOS#1852]
- My Rocket.Chat app version: 3.0.0, build 183
- I just get latest code in develop branch, commit: f489710fb4c8aabe12c75fb228bf1594995f1100

After run `pod install`, I want to build app in my local after opened `Rocket.Chat.xcworkspace`. But I got error when building app:
```
Type 'APIRequestOption' does not conform to protocol 'Hashable'
Type 'APIRequestOption' does not conform to protocol 'Equatable'
```
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/444876/42131021-0de6091c-7d2a-11e8-9a95-d5849276b176.png">

Does anyone know how to fix it, running built app in local?

**Comment by Sameesunkaria** [comment]
@y00rb What version of Xcode are you running?

**Comment by y00rb** [comment]
@Sameesunkaria  Version 9.2 (9C40b)

**Comment by y00rb** [comment]
@Sameesunkaria  Yes, I running it in latest version. Thank you very much!
