### ISSUE TITLE
[BUG] Conversations are not updated on Subscriptions view when app is reopened

### ISSUE THREAD

**Issue by coruble** [RocketChat/Rocket.Chat.iOS#1855]
- Rocket.Chat app version: 3.0.0 (dev branch, build 183)
- Rocket.Chat server version: 0.66.0
- Device (or Simulator) : iPhone X (iOS 11.4), iPhone 8 (iOS 11.2, Simulator)

Conversations are not updated on Subscriptions view when app is reopened. Works great when app is foreground / on screen.

**Steps to reproduce :**

1. Send message (channel / private / DM, doesn't matter) to user logged in on iOS while app is not running (completely closed or in background state)
2. Open app : new message doesn't appear, Subscriptions view stays the same as before.

Messages appear on conversation view if you open the conversation. But it won't update Subscriptions view if when you go back.

Looks like a problem introduced with #1809 ?
Thanks for the hard work !

**Comment by coruble** [comment]
@rafaelks Looks like this problem is solved in the latest beta branch. I'll close the issue now. Good job ! :-)

**Comment by rafaelks** [comment]
Amazing! 👊
