### ISSUE TITLE
[IMPROVEMENT] Login Page > "Create an Account" should stay in place when the keyboard is hidden

### ISSUE THREAD

**Issue by YanniStaMaria** [RocketChat/Rocket.Chat.iOS#1856]
**Environment:**
Rocket.Chat app version: 3.0.0(184)
Device (or Simulator) you're running with: iPad 5th Gen (11.1.2)

**Pre-condition:**
Rocket.Chat is installed

**Steps:**

1. Launch Rocket.Chat
2. Tap connect to a server
3. Input a valid server
4. Tap anywhere to hide the keyboard
- Verify create an account 

**Expected Result**
"Create an Account" should stay in place when keyboard is hidden

**Please see attached video:**
https://www.dropbox.com/s/aik71upwntddnql/Video%2002-07-2018%2C%207%2044%2003%20AM.mp4?dl=0

**Comment by rafaelks** [comment]
@YanniStaMaria Thanks for the report, but the version of this build is 3.0.0, not 2.4.0.
