### ISSUE TITLE
[BUG] App crashes when signing out and connecting to server again

### ISSUE THREAD

**Issue by GeTadle** [RocketChat/Rocket.Chat.iOS#1857]
Environment:
Rocket.Chat app version: 2.4.0 (171)
Device (or Simulator) you're running with: iPhone 6+ ios version 11.3.1

Pre-condition:
User is logged in.

Steps:

1. Tap the hamburger menu icon on the upper left corner of the page
2. Tap Logout from Rocket.Chat
3. Tap Connect to a Server
4. Enter valid Server URL on field

Expected Result:
Should be able to type in url on field without app crashing

Actual Result:
App crashes  after signing out and connecting to server again

Please see attached video:
https://www.dropbox.com/s/trpl1jgtramilyb/Video%2002-07-2018%2C%201%2040%2042%20PM.mp4?dl=0

**Comment by rafaelks** [comment]
@GeTadle Thanks for the report, this one is already fixed in `develop` branch. 👍
