### ISSUE TITLE
[IMPROVEMENT] (Landscape mode) Sign in to Server > Logo should have the same size regardless if the keyboard is visible or not

### ISSUE THREAD

**Issue by YanniStaMaria** [RocketChat/Rocket.Chat.iOS#1858]
**Environment:**
Rocket.Chat app version: 3.0.0(184)
Device (or Simulator) you're running with: iPhone6 (IOS 11.4)

**Pre-condition:**
Mobile should be on Landscape mode
Rocket.Chat is installed

**Steps:**

1. Launch Rocket.Chat
2. Tap connect to a server
- Verify logo

**Expected Result**
Logo should have the same size regardless if the keyboard is visible or not

**Please see attached video:**
https://www.dropbox.com/s/kutc9qzee5qcw2q/Video%20Jul%2002%2C%2010%2052%2014%20AM.mp4?dl=0

**Comment by rafaelks** [comment]
@YanniStaMaria Thanks for the report, but the version of this build is 3.0.0, not 2.4.0.
