### ISSUE TITLE
[BUG] Chat page > Three-Dots Menu > Nothing happens when tapping User menu

### ISSUE THREAD

**Issue by GeTadle** [RocketChat/Rocket.Chat.iOS#1861]
Environment:
Rocket.Chat app version: 2.4.0 (171)
Device (or Simulator) you're running with: iPhone 6+ ios version 11.3.1

Pre-condition:
User is logged in.
There should be an existing Direct Message from other user.

Steps:

1. Select any Direct Message from other user
2. Tap three-dot menu
3. Tap User Menu

Expected Result:
User menu should open

Actual Result:
Nothing happen when tapping user menu

Please see attached video:
https://www.dropbox.com/s/l8ljmwxspd0wbmn/Video%2002-07-2018%2C%203%2007%2002%20PM.mp4?dl=0

**Comment by rafaelks** [comment]
This is being implemented in #1837, not a bug. 👍
