### ISSUE TITLE
[Bug] Conversation list (activity) is not sorted correctly

### ISSUE THREAD

**Issue by dennispost** [RocketChat/Rocket.Chat.iOS#1866]
- Your Rocket.Chat app version: 3.0.0
- Your Rocket.Chat server version: 0.63.3-0.8.3
- Device (or Simulator) you're running with: Device iPhone X

1. The conversation list is not sorted correctly when ‚sort by activity‘ is selected. (Image 1)
2. Tapping on one of the conservations opens a different one (Image 2)
3. Sliding back shows the one wich was open that differs from the one wich was tapped before. (Image 3)
4. Scrolling this one out of view and back in leads to a change back to the first state (1). 

![Image 1](https://user-images.githubusercontent.com/1068264/42180344-2cf30018-7e37-11e8-97f5-0ab814038eca.png)
![Image 2](https://user-images.githubusercontent.com/1068264/42180350-2dfae462-7e37-11e8-8171-83c11f596851.png)
![Image 3](https://user-images.githubusercontent.com/1068264/42180347-2d160676-7e37-11e8-9bcf-98d76d466002.png)

**Comment by soundstorm** [comment]
#1777 ?

**Comment by dennispost** [comment]
yep its the same
