### ISSUE TITLE
[BUG] New Account > Wrong error message was displayed

### ISSUE THREAD

**Issue by YanniStaMaria** [RocketChat/Rocket.Chat.iOS#1868]
**Environment:**
Rocket.Chat app version: 3.0.0(184)
Device (or Simulator) you're running with: iPad 5th Gen (IOS 11.1.2)

**Pre-condition:**
Rocket.Chat is installed

**Steps:**

1. Launch Rocket.Chat
2. Tap Connect to a Server
3. Tap Create New Account
4. Verify New Account page
5. Leave input fields null/blank
6. Tap Return on the keyboard

**Expected Result**
New account should not be created. Error message should be seen.

**Actual Result**
Wrong error message was displayed for null fields
_NOTE: Issue also occurs on Creating new account on Join the Community_

**Please see attached video:**
https://www.dropbox.com/s/iojnymmqcu03qxg/Video%2003-07-2018%2C%209%2035%2059%20AM.mp4?dl=0

**Comment by rafaelks** [comment]
@YanniStaMaria Not all the fields are always required... this is a validation that's done via server-side right now. I'm closing the issue for now because of that. Thank you! 👍
