### ISSUE TITLE
[BUG] Channels you have left from desktop client are still shown on mobile

### ISSUE THREAD

**Issue by rex4539** [RocketChat/Rocket.Chat.iOS#1871]
- Your Rocket.Chat app version: 2.5.0 (179)
- Your Rocket.Chat server version: 0.63.3
- Device (or Simulator) you're running with: iPhone 6s

Steps:
1. Leave a channel from the desktop client.
2. Log in from mobile.

What happened:
The channel is still listed (see mobile screenshots below). I left the "zcon0" channel days ago.

![img_4111](https://user-images.githubusercontent.com/227442/42231582-9721ce70-7ef4-11e8-9bb8-bc28c514ab06.png)
![img_4112](https://user-images.githubusercontent.com/227442/42231606-ac4df4cc-7ef4-11e8-9bb0-da2b920694c7.png)

Expected result:
The channel is not listed (see desktop screenshot below). This is the correct behavior.

![screen shot 2018-07-03 at 18 58 44](https://user-images.githubusercontent.com/227442/42231660-d0cb399a-7ef4-11e8-8aab-1fa18dcae950.png)

**Comment by rafaelks** [comment]
This one is fixed for 3.1.1.
