### ISSUE TITLE
[BUGS] Share extension works weird

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat.iOS#1874]
Any direction:
- [x] Clicking "Search" on keyboard clears searchbar and therefor resets the list
- [x] Cancel button is shown if tapped on searchbar but leaving it empty, then selecting channel and going back to overview (or simply by hitting "Search" like above)
- [x] At least with 3.0.0 I see duplicate channel names

Landscape (opening share menu in landscape, not switching from portrait to landscape while menu is opened):
- [x] Tapping searchbar doesn't open keyboard
- [x] When selecting channel/group/user the recipient hides under top bar when using the iOS screenshot instant share function (not if sharing from gallery) due to a not hidden statusbar

**Comment by cardoso** [comment]
Hi @soundstorm . I was able to address all these issues, except the duplicate channel names.

I could not reproduce it. Let me know if you have specific steps to reproduce it.

**Comment by soundstorm** [comment]
@cardoso may have been before #1809 :)

**Comment by cardoso** [comment]
@soundstorm maybe it was about favorites appearing in both the "favorites" section and their type section? In which case I fixed that now.
