### ISSUE TITLE
[QUESTION] Can't connect server says "impossible to connect to the server" or the messages are all white

### ISSUE THREAD

**Issue by TheMMcOfficial** [RocketChat/Rocket.Chat.iOS#1877]
Before writing an issue, please make sure you're talking about the native application (called Rocket.Chat+ in the App Store) and not the Cordova one (called Rocket.Chat in the App Store). If you are looking to open an issue to the Cordova application, go to this URL: https://github.com/RocketChat/Rocket.Chat.Cordova.

- Your Rocket.Chat app version: ####rocketchat legacy 2.8.0 and rocketchat 2.5.0
- Your Rocket.Chat server version: ####0.63.1
- Device (or Simulator) you're running with: #### iPhone X

**The app isn't connecting to your server?**
Make sure your server supports WebSocket. These are the minimum requirements for Apache 2.4 and Nginx 1.3 or greater.

The rocketchat server is behind an ngnix proxy. But the apps specialy the new one told me that the server is not using ssl. But the proxy have the an certificate and it's valid. I called the server in https but the app doesn't want to connect. 

The legacy app was usable before some of updates. Now I can't use any ios app to use rocketchat. (I need to connect via Safari...) All devices or app are able to connect to the server exept those for IOS.

**Comment by Sameesunkaria** [comment]
@TheMMcOfficial Is it possible for you to share the url to your RC server?

**Comment by TheMMcOfficial** [comment]
Maybe in private but not here. It's a server for the work I don't want everybody know about this private service.

**Comment by Sameesunkaria** [comment]
@TheMMcOfficial How about you send me the url via DM on the open.rocket.chat server. I am @sameesunkaria on there.

**Comment by TheMMcOfficial** [comment]
![Image](https://i.imgur.com/fV9VQHJ.jpg)
![Image](https://i.imgur.com/SrAdJ2j.jpg)

The first image is with the new app  and the second is with the old one (legacy). A long time ago I managed to connect with the old ios app (legacy) but since a few month I can't use rocket chat with the app.

**Comment by Sameesunkaria** [comment]
@rafaelks @TheMMcOfficial is having problems with connecting to the web sockets. They are using nginx as a reverse proxy, and get an error `400` when they try to upgrade web sockets to wss.

```
HTTP/2 400 
server: nginx
date: Thu, 05 Jul 2018 15:14:58 GMT
strict-transport-security: max-age=15768000; includeSubdomains

Not a valid websocket request
```

**Comment by TheMMcOfficial** [comment]
Yes WSS is enable !

**Comment by TheMMcOfficial** [comment]
We have update the server now the legacy app works (my message are not all white) but the "new" app still have the error.

**Comment by TheMMcOfficial** [comment]
the websocket was missing something we add this config:
location ~ "^/sockjs/[\d]{3}/[\w]{8}/(xhr_send|websocket)"
location ~ "^/websocket"

the last one wasn't their
