### ISSUE TITLE
[BUG] Channel > App crashes upon clicking share

### ISSUE THREAD

**Issue by YanniStaMaria** [RocketChat/Rocket.Chat.iOS#1892]
**Environment:**
Rocket.Chat app version: 3.0.0(188)
Device (or Simulator) you're running with: iPad Pro  (IOS 11.3.1)

**Pre-condition:**
Rocket.Chat is installed
User is registered to the app

**Steps:**

1. Launch Rocket.Chat App
2. Open a chat room
3. Tap the vertical ellipsis
4. Tap Share
- Verify sharing action

**Expected Result**
Sharing action should open

**Actual Result**
App crashes upon clicking share

**Please see attached video**
https://www.dropbox.com/s/y23f21zpqj5yelm/Video%20Jul%2006%2C%2012%2056%2003%20PM.mp4?dl=0

**Comment by rafaelks** [comment]
This one was fixed already in version 3.0.0. 👍
