### ISSUE TITLE
[IMPROVEMENT] Join the Community > Create new account > Register button keeps loading when registering with null password

### ISSUE THREAD

**Issue by GeTadle** [RocketChat/Rocket.Chat.iOS#1896]
Environment:
Rocket Chat App version 3.0.0 (188)
Device (or simulator) you're running with: iPad 5th gen ios 11.1.2

Pre-Condition:
Rocket.Chat fresh installed

Steps:
1. Launch Rocket Chat app
2. Tap Join The Community
3. Tap Create New Account
4. Input valid details on Name, Username and Email field
5. Leave Password field null/blank
6. Tap Register

Expected Result:
New account should not be created. An error message should display

Actual Result:
No error message appeared. Register button keeps on loading

Please see attached video:
https://www.dropbox.com/s/i94gn2thla5qubg/Video%2006-07-2018%2C%201%2013%2035%20PM.mp4?dl=0

Note:
Also occurs in Connect to a server > Create new account

**Comment by filipealva** [comment]
I could not reproduce it no matter how I tried. The only issue I could notice is that when there's an invalid field sometimes it takes some seconds more to return the error, but I did not experience more than a few seconds of loading (depending on my internet connection). 

As an improvement, I'll add client validation so the user can't even send a request with invalid data.
