### ISSUE TITLE
Push notifications on iOS

### ISSUE THREAD

**Issue by markusstoll** [RocketChat/Rocket.Chat.iOS#1898]
Before writing an issue, please make sure you're talking about the native application (called Rocket.Chat+ in the App Store) and not the Cordova one (called Rocket.Chat in the App Store). If you are looking to open an issue to the Cordova application, go to this URL: https://github.com/RocketChat/Rocket.Chat.Cordova.

- Your Rocket.Chat app version: 2.5.0 (179)
- Your Rocket.Chat server version: 0.66.2
- Device (or Simulator) you're running with: iPhone 7+

In the server, I configured Push notifications, using the gateway (https://gateway.rocket.chat)
For my account, I did configure to get mobile notifications.

Sending a test notification DOES work! However from normal usage, I never get (got) a notification on any iOS device. I guess I missing something, but do not see it....

I do not even see, in which logs I could see whats happening (using the official docker image, logs are quite slim)

Could someone give me a hint, please

**Comment by Sameesunkaria** [comment]
@markusstoll Just making sure, are you using the app from the App Store, or have you compiled a version of your own?

**Comment by markusstoll** [comment]
From App Store

thx, Markus

**Comment by soundstorm** [comment]
@markusstoll are the rooms you're testing having more than 100 members or does this also happen on direct messages? And try to enable "always send mobile notifications" as an active desktop session may prevent mobile notifications.

**Comment by markusstoll** [comment]
Thank you, this solved my problem!
This setting was quite hidden, so I was not aware

Regards, Markus

**Comment by rafaelks** [comment]
Wow, this one I didn't know too... thank you @soundstorm!

**Comment by eidermar** [comment]
> @markusstoll are the rooms you're testing having more than 100 members or does this also happen on direct messages? And try to enable "always send mobile notifications" as an active desktop session may prevent mobile notifications.

And where exactly would I find that setting? I seem to be unable to locate it.
