### ISSUE TITLE
[IMPROVEMENT] Important labels should be translated according to the selected language.

### ISSUE THREAD

**Issue by GeTadle** [RocketChat/Rocket.Chat.iOS#1914]
Environment:
Rocket Chat App version 3.0.0 (188)
Device (or simulator) you're running with: iPhone 6+ version 11.3.1

Pre-Condition:
User is logged in.

Steps:
1. Tap the hamburger menu icon on the upper left corner of the page
2. Tap Language
3. Select any language (e.g. Español)
4. Tap OK on Validation message

Expected Result
Important labels should be translated according to the selected language. 

Actual Result
Some labels stayed in language

Please see attached photos:
![r16cyulqm](https://user-images.githubusercontent.com/38445437/42433616-c4b1bd04-8382-11e8-86ae-3323997c94a0.png)
![s19pfdlmm](https://user-images.githubusercontent.com/38445437/42433621-c894b46c-8382-11e8-8213-e0984098df96.png)

**Comment by soundstorm** [comment]
@GeTadle are they yet translated? If you switch your phone to spanish, are they still in english? If they are so, please help to translate them :)

**Comment by rafaelks** [comment]
@GeTadle @soundstorm Yes, translation is working fine, just needs to be updated. Also, when you change it, you need to restart the application. Please give it a try with another language. 👍
