### ISSUE TITLE
[BUG] New message banner too big

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat.iOS#1915]
It's now (188) often, that the "new messages" banner is floating somewhere over the messages and the margin above the separator is huge too.

![GitHawk Upload by soundstorm](https://i.imgur.com/zb1KzVY.jpg)

**Comment by soundstorm** [comment]
Weirdo: the banner just jumped up (has hidden the message above) and back down while typing. So there is something missligned...

**Comment by rafaelks** [comment]
@soundstorm Are you still able to reproduce this one in 193? Thank you!

**Comment by rafaelks** [comment]
Closing it for now, thank you @soundstorm! 👊
