### ISSUE TITLE
[BUG] Upload from Library doesn't work

### ISSUE THREAD

**Issue by coruble** [RocketChat/Rocket.Chat.iOS#1917]
Uploads from library don't work in latest beta branch. Uploading through share extension works tho.

- Rocket.Chat app version: 3.0.0 (latest beta branch as of July 9th 2018)
- Rocket.Chat server version: 0.66.0
- Device (or Simulator) you're running with: iPhone X / iOS 11.4

**Steps to reproduce :**

1. Open channel or DM session
2. Tap "+", "Choose from library"
3. Tap any file / photo
4. Tap "Upload"

**Expected behavior :**

File uploads and appears in conversation.

**Actual behavior :**

Nothing happens (at least for me)

**Comment by coruble** [comment]
Xcode debug console shows that requests are indeed sent. But no payload ?

```
[REST][REQUEST]: https://{domain.com}/api/v1/rooms.upload/iTsYkQZMR9b6eNpzF: 
[REST][RESULT][https://{domain.com}/api/v1/rooms.upload/iTsYkQZMR9b6eNpzF]:
```

**Comment by coruble** [comment]
@rafaelks Any idea why this happens ? Looks like all the changes regarding upload are in a specific branch ? Both current beta and develop have the problem. Just reproduced it on other devices too.

**Comment by coruble** [comment]
Android client has trouble uploading too, throwing an error `Use JsonReader.setLenient(true) to accept malformed JSON at path $`. So it's probably server-related. Will investigate and close the issue if it's indeed on the server side.

**Comment by coruble** [comment]
Solved by increasing `client_max_body_size` on nginx config, as provided on https://github.com/RocketChat/Rocket.Chat.Android/issues/1050. Closing now. Sorry for the false flag.

**Comment by rafaelks** [comment]
Nice! 👍
