### ISSUE TITLE
[BUG] Attachment coloring does not work anymore

### ISSUE THREAD

**Issue by kaiiiiiiiii** [RocketChat/Rocket.Chat.iOS#1920]
**Before (2.5):**
![img_5182](https://user-images.githubusercontent.com/4711233/42475792-0ad7d7ca-83cc-11e8-8fce-06b7ee028b56.jpg)

**After:**
![img_5183](https://user-images.githubusercontent.com/4711233/42475808-1141c986-83cc-11e8-99a5-f5d24af52726.jpg)

It would be nice if the entire line were colored :) (maybe it's already possible and I'm missing something in my webhook configuration?)

- Your Rocket.Chat app version: #### latest beta
- Your Rocket.Chat server version: #### 0.66.1
- Device (or Simulator) you're running with: #### iPhone 7, latest iOS 11

Thx Guys :)

**Comment by Sameesunkaria** [comment]
@kaiiiiiiiii is it possible for you to send a message with colored attachments to #iosnativeapp ?

**Comment by kaiiiiiiiii** [comment]
@Sameesunkaria I don't think that's possible as colored attachments only work when they were created by a webhook (as far as I know).

But as I can see you already fixed the issue anyways :)
