### ISSUE TITLE
[QUESTION] Crash in old version v2.3.0 after merging my changes in a fork ...

### ISSUE THREAD

**Issue by kmav** [RocketChat/Rocket.Chat.iOS#1921]
Does anyone know for any crash when trying to click and open Members list (inside chat) and what is the commit that resolved that? I am trying to create another app based on Rocket.chat and I have been lost in that crash for 2-3 weeks! I am using a branch based on v2.3.0 were I applied my changes.

When using the release v2.3.0 code it does not crash on opening members list. Also, when I checkout v2.3.0 from master it does not crash. It crashes after merging my changes. I did not do any change in chat storyboard. I had created a separate auth storyboard to handle my login. I have not been able yet to reproduce the issue with oroginal rocket.chat.ios code.

**Comment by kmav** [comment]
[Rocket.chat-v2.3.0-fork-crash.txt](https://github.com/RocketChat/Rocket.Chat.iOS/files/2178020/Rocket.chat-v2.3.0-fork-crash.txt)

**Comment by Sameesunkaria** [comment]
@kmav are your changes public on github?

**Comment by kmav** [comment]
No. I am sorry. They are not...

**Comment by Sameesunkaria** [comment]
Can you try adding an exception breakpoint, and posting the console output when the application pauses? 

https://stackoverflow.com/questions/17802662/exception-breakpoint-in-xcode

**Comment by kmav** [comment]
When I have done that I was a little bit confused because it had created two breakpoints: one in Application and another in another point later. In the first I had to continue execution to get the crash to the 2nd point...

**Comment by Sameesunkaria** [comment]
@kmav what was the output right before the crash?

**Comment by kmav** [comment]
I am in the main chat screen and I select "general  v" from the top to get the next view ...

![screen shot 2018-07-10 at 00 29 38](https://user-images.githubusercontent.com/3893463/42477015-66e09b5e-83d8-11e8-923a-be3ddfe7f1c5.png)

**Comment by kmav** [comment]
2nd breakpoint...

![screen shot 2018-07-10 at 00 33 28](https://user-images.githubusercontent.com/3893463/42477202-ef39daba-83d8-11e8-86e5-12928f078210.png)

**Comment by kmav** [comment]
Breakpoint 2nd
![breakpoint-2](https://user-images.githubusercontent.com/3893463/42477416-a2de3a52-83d9-11e8-9f3b-2759df93d69e.png)

**Comment by Sameesunkaria** [comment]
can you post what's on the console for the second breakpoint? I'm especially interested in the setValue call.

**Comment by kmav** [comment]
Is this OK? can you advise more?

![breakpoint-2](https://user-images.githubusercontent.com/3893463/42477612-6e9353d0-83da-11e8-8669-90d3e7b59118.png)

**Comment by Sameesunkaria** [comment]
@kmav the console is visible if you click this button 

<img width="938" alt="screen shot 2018-07-10 at 3 16 09 am" src="https://user-images.githubusercontent.com/7317008/42477695-b565bbb2-83ef-11e8-9050-06bc886fe919.png">

**Comment by kmav** [comment]
OK. What do you want exactly from the console? I run bt there to get stack trace...
Do you need all log?

**Comment by kmav** [comment]
[crash-console-last.txt](https://github.com/RocketChat/Rocket.Chat.iOS/files/2178120/crash-console-last.txt)

**Comment by Sameesunkaria** [comment]
All I'm really looking for are the arguments to the setValue method call. Yup, that is 2 and 3 on the left.

**Comment by kmav** [comment]
[setValue.txt](https://github.com/RocketChat/Rocket.Chat.iOS/files/2178140/setValue.txt)

**Comment by Sameesunkaria** [comment]
This is just the implementation of the setValue method. How about we start by verifying that there aren't any unneeded referencing outlets in the Interface builder?

**Comment by kmav** [comment]
Can you advise how?
I think that I had checked that if I understand correctly... There are no outlets with X in the front. Is this what you mean?

**Comment by kmav** [comment]
![member-list-vc](https://user-images.githubusercontent.com/3893463/42478611-fec21254-83dd-11e8-8e47-677c56783c55.png)

**Comment by Sameesunkaria** [comment]
There is only one outlet declared in the view controller file. (the property is called `tableView`). If you find any other element in the storyboard file (for members list vc) that is referencing a outlet (check by right clicking on each element in the view), then remove that reference.

**Comment by kmav** [comment]
![screen shot 2018-07-10 at 01 13 01](https://user-images.githubusercontent.com/3893463/42478729-74d45236-83de-11e8-8c97-a74ff083d929.png)

**Comment by kmav** [comment]
![members-list-vc-links](https://user-images.githubusercontent.com/3893463/42478857-ed8af388-83de-11e8-99da-7964c659221c.png)

**Comment by kmav** [comment]
I don't see anything wrong in the outlets... Do you?

**Comment by kmav** [comment]
I am I correct that the table view data source is empty/nil ?

**Comment by Sameesunkaria** [comment]
@kmav Because the crash is happening on a `setValue:forKey` message, its almost certainly setting an outlet, which may not exist in code.

**Comment by kmav** [comment]
I am looking at the xml of chat.storyboard for memberList vc. I cannot see any other outlet apart the membersTableView: 

```
                    <connections>
                        <outlet property="membersTableView" destination="hz2-84-IvC" id="29I-J5-lyC"/>
                    </connections>
```

**Comment by Sameesunkaria** [comment]
Is there anything set in the User defined runtime attributes?

**Comment by kmav** [comment]
What is that "User defined runtime attributes" ? User profile data from the server?
The application is working fine as v2.3.0 original...

**Comment by Sameesunkaria** [comment]
@kmav How about we override setValue forKey in an extension to UIView. And print the key after calling super?

```
extension UIView {
    open override func setValue(_ value: Any?, forKey key: String) {
        super.setValue(value, forKey: key)
        print(key)
    }
}
```

**Comment by kmav** [comment]
Yes. Should I put that code at the end of MemberListVC ?

**Comment by Sameesunkaria** [comment]
Sure. anywhere is fine.

**Comment by kmav** [comment]
```[WebSocket] wss://chat.emos1.com/websocket
 - did receive JSON message:
{
  "msg" : "ping"
}
[WebSocket] wss://chat.emos1.com/websocket
 -  will send message: {
  "id" : "aqbNgAGUkk9J8Rgjheinh86gmgUEhuwDlvk1TEQTZAaDqSM5NC",
  "msg" : "pong"
}
dataSource
delegate
labelTitle
labelDescription
labelTitle
labelDescription
labelTitle
labelDetail
labelTitle
labelDetail
labelTitle
labelDetail
labelTitle
labelDetail
labelTitle
labelDetail
labelTitle
dataSource
delegate
(lldb) ```

**Comment by Sameesunkaria** [comment]
And whats on the variables view? 

this is what it should look like
<img width="342" alt="screen shot 2018-07-10 at 4 21 16 am" src="https://user-images.githubusercontent.com/7317008/42479923-b3d22be2-83f8-11e8-913e-bc1b91d97a8f.png">

**Comment by kmav** [comment]
value	Any?	some
key	String	"loaderViewContainer"	
_core	_StringCore	
self	UIView	0x00007fb22b8cca00

**Comment by kmav** [comment]
![setvalue2](https://user-images.githubusercontent.com/3893463/42480371-b5a64ad8-83e5-11e8-92f0-1ba3b0a8f7a1.png)

**Comment by Sameesunkaria** [comment]
@rafaelks any theories?

**Comment by kmav** [comment]
Thank you for your assistance and patience 🥇 😄

**Comment by rafaelks** [comment]
@Sameesunkaria @kmav Please, try adding the super call after opening the func:

```swift
override func viewDidLoad() {
        super.viewDidLoad()
```

**Comment by kmav** [comment]
Unfortunately it crashed again after clean/rebuild..

**Comment by rafaelks** [comment]
@kmav Got it. Could you try pulling from develop please?

**Comment by kmav** [comment]
This branch I am working is based on your master's v2.3.0 with added only my changes... 
I was initially working on develop. That develop is behind release v2.3.0.
Do you want me to pull latest changes in my new "v2.3.0 master" or in the old "develop" that I was working?

**Comment by Sameesunkaria** [comment]
@kmav Just a sanity check, can you make sure that the custom class under the identity inspector is set as `LoaderTableViewCell`?  (in `LoaderTableViewCell.xib`)

**Comment by kmav** [comment]
Wooaaaaa !!!! 😄 🚀 🎆 
@Sameesunkaria you are absolutely wonderful !!!

The name of custom class was correct but... the module was customized, so it kept the original Module value. Inherit Module from Target was unchecked !!!

![loadertableview](https://user-images.githubusercontent.com/3893463/42537020-629553f4-849c-11e8-968a-4ba7b3bc7827.png)

I am grateful to both of you @Sameesunkaria and @rafaelks 😄

**Comment by Sameesunkaria** [comment]
@kmav awesome!

**Comment by kmav** [comment]
Maybe it could be a good idea to apply this in main Rocket.chat.

**Comment by kmav** [comment]
@Sameesunkaria The value is correct.

**Comment by kmav** [comment]
Yes of course it is correct. 
But if you check "Inherit Module from Target" it will work automatically... In that way you do not need to add "fixed" value. It will inherit it. So, the overall configuration of target could be more flexible.
