### ISSUE TITLE
[BUG] Highlighting does not stop when more than one person is tagged

### ISSUE THREAD

**Issue by kaiiiiiiiii** [RocketChat/Rocket.Chat.iOS#1922]
The highlighting of @all, @here and @username never stops when you try to notify more than one person. In addition, if you place text before the tag, alternately a user is not selected.

![img_5189](https://user-images.githubusercontent.com/4711233/42476203-71e344b2-83cd-11e8-84cd-6eb291acd51a.PNG)

- Your Rocket.Chat app version: latest beta
- Your Rocket.Chat server version: 0.66.1
- Device (or Simulator) you're running with: iPhone 7, latest iOS 11

Thx Guys and nevermind if it's already fixed :)

**Comment by artrmz** [comment]
Does this still happen? I could not reproduce.

**Comment by kaiiiiiiiii** [comment]
![7122beb3-cd6c-445a-9e92-6bba0cac4bb5](https://user-images.githubusercontent.com/4711233/42884033-82b0d7d8-8a9d-11e8-94d5-c7140b5f3ae6.jpeg)

Yes, it still happens 😕

**Comment by artrmz** [comment]
@kaiiiiiiiii Could you possibly DM me on open.rocket.chat and reproduce it there? (artrmz @ open.rocket.chat)

**Comment by artrmz** [comment]
Seems like the issue is caused by activating "Use real names" on the server. Sadly I have no server to test that on 👎

**Comment by filipealva** [comment]
I'm working on it, soon I'll push a fix

**Comment by kaiiiiiiiii** [comment]
Thanks guys! :)
