### ISSUE TITLE
Handle offline / flight mode

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat.iOS#194]
Your Rocket.Chat version: demo

Create a message / notification or gray out the send button if the mobile phone is offline or in flight mode. Just for a nice user experience.

![img_3668](https://cloud.githubusercontent.com/assets/5877910/20713507/d5ecafec-b648-11e6-88c5-34d200371cec.PNG)

**Comment by rafaelks** [comment]
@TheReal1604 That's a good one, thank you!

**Comment by TheReal1604** [comment]
@rafaelks Great!
