### ISSUE TITLE
[BUG] Various problems with latest message in channel overview

### ISSUE THREAD

**Issue by kaiiiiiiiii** [RocketChat/Rocket.Chat.iOS#1951]
Here are a few things I noticed in the latest beta version of the app related to the channel overview.

### 1. Nothing is displayed if the latest message was an emoji

![img_5204](https://user-images.githubusercontent.com/4711233/42656534-d8a00ec0-861f-11e8-9d74-21221c1352e5.PNG)

![img_5206](https://user-images.githubusercontent.com/4711233/42656541-de91b8b0-861f-11e8-9ef1-7c5a3b73576d.PNG)

Sometimes (especially after a re-login) it seems to work, but most of the times nothing is rendered at all.

### 2. Although messages are present, "no message" is displayed

<img width="375" alt="img_5207" src="https://user-images.githubusercontent.com/4711233/42656763-8ea17060-8620-11e8-9f0f-0c449eeaa220.PNG">

<img width="375" alt="img_5208" src="https://user-images.githubusercontent.com/4711233/42656808-aa9d3218-8620-11e8-8fe3-160e75ee4af3.PNG">

As you can see (or not thanks to blur), the channel has heaps of messages :)

### 3. Instead of the latest message, the penultimate message is displayed

![img_5211](https://user-images.githubusercontent.com/4711233/42656900-ff289994-8620-11e8-8995-529bd36a7c5e.PNG)

![img_5210](https://user-images.githubusercontent.com/4711233/42656918-05b8809e-8621-11e8-94dd-29b68aaf9de9.PNG)

I think thats it for now :) Thanks guys for your efforts to make this app even greater!

- Your Rocket.Chat app version: 3.0 beta latest
- Your Rocket.Chat server version: 0.66.3
- Device (or Simulator) you're running with: iPhone 7, iOS 11 latest

**Comment by Sameesunkaria** [comment]
@kaiiiiiiiii This is the first time I've seen someone use the word "penultimate" in context. Cheers 🍻

Couldn't resist commenting.. 😛
