### ISSUE TITLE
[BUG] Wrong order of channels in overview

### ISSUE THREAD

**Issue by kaiiiiiiiii** [RocketChat/Rocket.Chat.iOS#1952]
It's just the default channel #general which is sticked to the top of my channel list. Everything else is sorted in the right way.

<img width="375" alt="img_5212" src="https://user-images.githubusercontent.com/4711233/42657586-ef1d734c-8622-11e8-865b-3e7306686700.PNG">

- Your Rocket.Chat app version: 3.0 beta latest
- Your Rocket.Chat server version: 0.66.3
- Device (or Simulator) you're running with: iPhone 7, iOS 11 latest

**Comment by kaiiiiiiiii** [comment]
@rafaelks Default channel (#general) is still on top in the latest testflight release =(

**Comment by rafaelks** [comment]
@kaiiiiiiiii Are you using sorting by name?

**Comment by kaiiiiiiiii** [comment]
@rafaelks Yes, I do.

![img_5223](https://user-images.githubusercontent.com/4711233/42694623-59b8fa56-86b3-11e8-9fc0-b6e7ef05ee0c.PNG)

Channel sorting still looks like on the first screenshot.

**Comment by rafaelks** [comment]
@kaiiiiiiiii I see what's going on... you're probably using full names and `general` have `fname` propert as an empty string. 👍

**Comment by kaiiiiiiiii** [comment]
Yipp you're right @rafaelks, the general channel does not have a fname at all ^^' I've added it to the DB document and everything seems to be alright now :)

**Comment by rafaelks** [comment]
@kaiiiiiiiii OK, I'm going to resolve that in another PR ;)
