### ISSUE TITLE
[BUG] Channels are displayed even though they are hidden

### ISSUE THREAD

**Issue by kaiiiiiiiii** [RocketChat/Rocket.Chat.iOS#1953]
As @rafaelks confirmed in the #ios-beta channel on open.rc, this shouldn't be the expected behavior.

**Web Client:**
![screen shot 2018-07-12 at 22 22 22](https://user-images.githubusercontent.com/4711233/42657990-461a5826-8624-11e8-8d6f-7cfbb76fd5c3.png)

**iOS App:**
<img width="375" alt="img_5209" src="https://user-images.githubusercontent.com/4711233/42658002-4f325206-8624-11e8-9cbd-d5e4d00abbf0.PNG">

And those are just the dms that start with an A ... :D

- Your Rocket.Chat app version: 3.0 beta latest
- Your Rocket.Chat server version: 0.66.3
- Device (or Simulator) you're running with: iPhone 7, iOS 11 latest

**Comment by rafaelks** [comment]
This one was fixed in #1937, thank you @kaiiiiiiiii!
