### ISSUE TITLE
[BUG] Notifications open chat at wrong position

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat.iOS#1979]
When opening a notification the app opens the channel about 200+ lines above the new message separator.
It'd be okay if the scroll position is zero/newest message, but would be ideal if it's at the newest unread message.

**Comment by soundstorm** [comment]
Seems like an edge case or resolved again 🤔

**Comment by rafaelks** [comment]
@soundstorm I believe I fixed this one before we release to the store. Let's close it for now and then we can reopen if you notice it again, thank you!
