### ISSUE TITLE
[BUG] Only a single subscription cell is selected even if multiple for the same room appear on screen

### ISSUE THREAD

**Issue by Sameesunkaria** [RocketChat/Rocket.Chat.iOS#1982]
Here, I tapped the blue cell but the red cell is the only one which is shown as selected.

This only applies to the iPad and iPhone Plus

![img_0484](https://user-images.githubusercontent.com/7317008/42723692-63aef40c-8780-11e8-8eda-3460702735bc.jpg)

**Comment by soundstorm** [comment]
Why do we even show the room twice?

**Comment by rafaelks** [comment]
@soundstorm Great question, in this case, we should really not display it! :-)
