### ISSUE TITLE
createChannel: realtime-api returns error.

### ISSUE THREAD

**Issue by njt28** [RocketChat/Rocket.Chat.iOS#199]
Rocket.Chat version: "0.47.0-develop"

I'm following realtime-api doc and call this request:

            "msg": "method",
            "method": "createChannel",
            "params": ["channel-name", "abc"]

but it returned the error:

 [WebSocket] did receive JSON message: {
  "id" : "o63tIV86AINOh9YORJILBqMRP0GFmgCyGXrol9EIfjZmY867th",
  "error" : {
    "message" : "Match failed [400]",
    "reason" : "Match failed",
    "error" : 400,
    "errorType" : "Meteor.Error"
  },
  "msg" : "result"
}

Any helps? thanks.

**Comment by rafaelks** [comment]
@njt28 Are you trying to implement a new feature in the app? This call isn't being used yet in the iOS application.

**Comment by graywolf336** [comment]
@njt28 That's because you're not calling it with the correct parameters, the second parameter needs to be an array of strings which are the usernames who are in the channel when it is created.

**Comment by rafaelks** [comment]
I'm closing this one, since it's already answered by @graywolf336 (thanks!)
