### ISSUE TITLE
[INVESTIGATE][QUESTION] URL is not valid

### ISSUE THREAD

**Issue by reinerj** [RocketChat/Rocket.Chat.iOS#2011]
Jut got the upgrade for version 3 of the client. Installed it and did try to connect to a server where the URL is something like

https://rocket.xxx.xx:3000/

Response from the client. URL invalid

**Comment by Sameesunkaria** [comment]
@reinerj Are you able to share the URL for the server publicly?

**Comment by reinerj** [comment]
no, i cant

**Comment by reinerj** [comment]
This could be possible but I on meetings now

Von meinem iPhone gesendet

**Comment by rafaelks** [comment]
@reinerj Please, provide us the URL in order for us to check.

Make sure you've:

- SSL cert valid;
- HTTPS is supported;
- You don't have any spaces in the URL (this is going to be improved in future releases);

Thank you!

**Comment by reinerj** [comment]
@rafaelks 

The SSL certificate is valid until 2020 and as I wrote before, Rocket work with the desktop client, the browser and was working without any problems until we upgraded to the latest iOS release

On the server only https is supported 

And no, there are no spaces in the URL ...

I could send you the URL in a privat message but cannot write it here in the ticket

Regards

**Comment by Sameesunkaria** [comment]
@reinerj i'm @sameesunkaria on the open.rocket.chat server. You can DM me there

**Comment by Sameesunkaria** [comment]
Resolved in private conversation.
