### ISSUE TITLE
[IMPROVEMENT] Clean chat room using mobile app

### ISSUE THREAD

**Issue by serge-petrov** [RocketChat/Rocket.Chat.iOS#2015]
Hello. Please add an ability to clean chat room using mobile app. Now there is the only one way available: delete messages one-by-one.

**Comment by rafaelks** [comment]
@serge-petrov Thanks for the feature request! We don't plan to add this feature soon to the mobile apps, so I'm going to close it for now. If in the future we decide that this feature is important to most of the mobile users, we can reopen it. Thank you very much!
