### ISSUE TITLE
[BUG] UserDetails popover arrow not themed. 

### ISSUE THREAD

**Issue by Sameesunkaria** [RocketChat/Rocket.Chat.iOS#2022]
![untitled](https://user-images.githubusercontent.com/7317008/42890211-e2681ad4-8ac9-11e8-82e5-9836cde1a8d6.png)

**Comment by Sameesunkaria** [comment]
🤔

**Comment by cardoso** [comment]
@Sameesunkaria I mean, so we don't have to write extra code for every new popover.

**Comment by Sameesunkaria** [comment]
@cardoso I have something in mind. Hope that it works out.
