### ISSUE TITLE
[INVESTIGATE][BUG] Sometimes the user keeps looping to connect into the server (Realm becomes inconsistent)

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.iOS#2028]
This one is very hard to reproduce, but here's a GIF showing how it looks:

![2018-07-19 00 24 51](https://user-images.githubusercontent.com/551004/42919832-31f38db6-8aea-11e8-8b93-cc3affb04abf.gif)

**Comment by artrmz** [comment]
Ah, good to know you are aware of that, happened to me as well when I accidentally popped Siri and immediately canceled it while Rocket.Chat was open but cannot reproduce it now 😢
