### ISSUE TITLE
Cannot compile.

### ISSUE THREAD

**Issue by Syirrus** [RocketChat/Rocket.Chat.iOS#204]
Your Rocket.Chat version: (make sure you are running the latest)
Shell Script Invocation Error Group

PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock /Users/johnhand/Library/Developer/Xcode/DerivedData/Rocket.Chat-bhxdjgxsqknfkhftwjvtmctknkhp/Build/Intermediates/Rocket.Chat.build/Debug-iphonesimulator/Rocket.Chat.build/Script-5A6B94785E51D859BD0468DE.sh
    cd /Users/johnhand/Downloads/Rocket.Chat.iOS-develop
    /bin/sh -c /Users/johnhand/Library/Developer/Xcode/DerivedData/Rocket.Chat-bhxdjgxsqknfkhftwjvtmctknkhp/Build/Intermediates/Rocket.Chat.build/Debug-iphonesimulator/Rocket.Chat.build/Script-5A6B94785E51D859BD0468DE.sh

**Comment by rafaelks** [comment]
@Syirrus Please, make sure you're running latest Xcode version and following the [development guide](https://github.com/RocketChat/Rocket.Chat.iOS#setting-up-a-development-environment) to run the project.
