### ISSUE TITLE
[BUG] Sometimes single messages are scrollable => #1656

### ISSUE THREAD

**Issue by hubermat** [RocketChat/Rocket.Chat.iOS#2045]
Rocket.Chat app 3.0.1 (199)
Rocket.Chat server 0.66.3
iPhone 5S, iOS 11.4

Single multiline messages, that have just one word on the last line, are scrollable! The last line is not displayed and will only become visible through scrolling, which is very annoying and often leads to confusion, as the sense of the message is lost or sometimes inverted.

For this bug already an issue exists under #1656, but it is closed with fixed in 3.0. But the bug still exists in 3.0.1. As I cannot reopen closed issues, this issue is a reminder to reopen the #1656 .

Proof that it is still not fixed:
![img_7649](https://user-images.githubusercontent.com/1336497/42985200-b0340b5e-8bf0-11e8-8306-2bae43355b1a.PNG)

**Comment by rafaelks** [comment]
Duplicates #1656, thanks @hubermat
