### ISSUE TITLE
[BUG/HANG] Quick Reply on different servers confuse App

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat.iOS#2046]
I recently had this twice, but I think I can now see why.

- Close RC while on Server X
- Reply to a message on Server Y via notification
- Open RC again

Now the app tries to open the conversation you replied to (probably trying it on Server X) instead of simply opening the state in that you left the app.
RC shows up a blank chat with only the room name loaded. As soon as you swipe right to open the channels it tries to fetch the subscriptions of the wrong server and hangs completely (needs force quit of the app).
After a restart you will see the channel overview of server Y instead of X.

I noticed this, because I was previously on a new server and when opening the app it opened "offtopic" which was not present on this server.
![GitHawk Upload by soundstorm](https://i.imgur.com/Db2GUtr.jpg)

Do we alter anything like the serverid when using quick reply?

**Comment by soundstorm** [comment]
Picture shows the ui slightly shifted (trying to open the subscription list) where it hangs.

**Comment by cardoso** [comment]
@soundstorm is this still happening? I fixed a related issue while investigating this:

https://github.com/RocketChat/Rocket.Chat.iOS/pull/2071

But I could not get the App to hang.

**Comment by cardoso** [comment]
Closing this for now.
