### ISSUE TITLE
[BUG] messed up servers (creating channel)

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat.iOS#2060]
I tried to create a channel on server x after I switched from server y (while on Edge connection) where a channel with this name already exists.

So:
Server Y has channel XY.
Switch to Server X, try to create channel XY.
Now the app yields, that the channel already exists.
![GitHawk Upload by soundstorm](https://i.imgur.com/tKRAm3B.jpg)

**Comment by soundstorm** [comment]
Okay, seems like web frontend messed this up...

**Comment by soundstorm** [comment]
Okay, searched for the channel and it had no members.
So maybe the app created the channel - don't know what really happend @rafaelks

**Comment by cardoso** [comment]
So the problem here is that the App somehow created a channel without your consent @soundstorm ?

**Comment by soundstorm** [comment]
Not necessarily, maybe the name duplication is just a bad example where it happend.
Could have been a combination of different circumstances like channel created but not joined, retried to create but then failing.

Don't remember exactly if I pressed the create button twice (because the channel creation screen didn't hide or simply double tapped).

**Comment by rafaelks** [comment]
@soundstorm Just to make sure I understood the problem here... you're saying that when you changed the server, the app was still creating the channel in the other server? 🤔
