### ISSUE TITLE
[QUESTION] Cannot upload images from Library.

### ISSUE THREAD

**Issue by Cikcak** [RocketChat/Rocket.Chat.iOS#2066]
Cannot upload images from Library.

- Your Rocket.Chat app version: 3.0.2
- Your Rocket.Chat server version: 0.66.0
- Device (or Simulator) you're running with: iPhone 6

**Comment by rafaelks** [comment]
@Cikcak Can you describe the error you're having?

**Comment by Cikcak** [comment]
App shows dialogs for choosing picture, but after clicking to Upload button, nothing happens.

**Comment by rafaelks** [comment]
@Cikcak Can we have access to your server?

**Comment by Cikcak** [comment]
eee.... yes. Can I contact you somehow direct?

**Comment by rafaelks** [comment]
@Cikcak Yes, contact me at `open.rocket.chat` server, my username is `rafael.kellermann`.

**Comment by rafaelks** [comment]
The issue was on the configuration of `client_max_body_size` of Nginx.
