### ISSUE TITLE
[BUG] Forgot Password does not send a reset message

### ISSUE THREAD

**Issue by Renzmu** [RocketChat/Rocket.Chat.iOS#2076]
Environment:
Rocket.Chat app version: 3.0.0 (193)
Device (or Simulator) you're running with: iPhone 7 (IOS 11.4) and iPad Pro (IOS 11.3.1)

Pre-condition:
Rocket.Chat is installed

Steps:

1.Click Join the Community
2.Sign in to server
3.Click "Forgot your password?"
4.Type in Valid email

Expected Result:
Forgot password message should be sent to the email typed in

Actual Result:
Forgot password message was not sent to user

**Comment by cardoso** [comment]
I could not reproduce this. Are you sure you have an account in open.rocket.chat?

**Comment by Renzmu** [comment]
Hello,tried it at 3 accounts from cloudstaffqa.rocket.chat only 1 received the link after 4 hours.Let me try it again today maybe its a server/internet issue.
