### ISSUE TITLE
[BUG] Message actions not taking into account room roles

### ISSUE THREAD

**Issue by Renzmu** [RocketChat/Rocket.Chat.iOS#2082]
Environment:
Rocket.Chat app Version 3.0.2 (193)
Device (or Simulator) you're running with: iPad Pro version 11.3.1, Iphone 7 ver 11.4.1

Pre-condition:
User is logged in on cloustaffqa.rocket.chat
There should be an existing Message to the user.

Steps:

1.Select any Message from other user
2.Long Press the message
3.Verify the options

Expected Result:
Pin message should be available
Actual Result:
Pin message was not in the option

Please see attached proof:
![image](https://user-images.githubusercontent.com/41657529/43243005-bf5d8728-90d6-11e8-9b71-07f11bd5dda2.png)

**Comment by rafaelks** [comment]
@Renzmu Does your user have permission to pin a message?

**Comment by Renzmu** [comment]
Yes i do, Please see attached image taken from the site and ipad:
Ipad:

![](https://storage.googleapis.com/openscreenshot/Q/E/v/ByroDCvEQ.png)


Site:

![](https://storage.googleapis.com/openscreenshot/X/N/v/S1p08RvNX.png)

Video:
https://www.dropbox.com/s/bl0hrln8vjtbzov/no%20pin%20privelage.mp4?dl=0
