### ISSUE TITLE
Where can I find the "Messages" specification?

### ISSUE THREAD

**Issue by ktt9117** [RocketChat/Rocket.Chat.iOS#209]
Your Rocket.Chat version: 0.48.2 (Latest release version at this time)

My Rocket.Chat server gives the following these message:
I cannot understood "t" attribute meaning likes "uj", "r", "au" etc...
However, where can I find the Messages specification?
I already checked document (https://rocket.chat/docs/developer-guides/realtime-api/the-message-object) but there is no answers. Please let me know thanks

[WebSocket] did receive JSON message: {
  "id" : "NQnEti5CiBCdjQKcs5x6Thp0yoKE9TcZdpq6tWhNNLYRSMSsYy",
  "result" : {
    "unreadNotLoaded" : 0,
    "messages" : [
      {
        "_id" : "WT4XjGRtApAsyL2uB",
        "t" : "uj",  <-- This
        "_updatedAt" : {
          "$date" : 1482825773896
        },
        "ts" : {
          "$date" : 1482825773896
        },
        "rid" : "GENERAL",
        "u" : {
          "_id" : "bpz8hgJq5SS3p9yPa",
          "username" : "cjswntjd"
        },
        "msg" : "cjswntjd",
        "groupable" : false
      },
      {
        "rid" : "GENERAL",
        "ts" : {
          "$date" : 1482797322172
        },
        "_id" : "DaGqKAPx2AonDp2tG",
        "msg" : ":man_dancing:",
        "u" : {
          "_id" : "mwW3Z9QE8mrRcJCDG",
          "username" : "장동건"
        },
        "_updatedAt" : {
          "$date" : 1482797322178
        }
      },
      {
        "rid" : "GENERAL",
        "ts" : {
          "$date" : 1482796722528
        },
        "_id" : "95JJHQ5r2PYgoK7hQY",
        "msg" : "에이요맨",
        "u" : {
          "_id" : "ZsAA3e53nHeCWu8vo",
          "username" : "gradle"
        },
        "_updatedAt" : {
          "$date" : 1482796722536
        }
      },
      {
        "rid" : "GENERAL",
        "ts" : {
          "$date" : 1482737327475
        },
        "_id" : "dCQjrN9yn7ROOI6Kvs",
        "msg" : "",
        "u" : {
          "_id" : "ZsAA3e53nHeCWu8vo",
          "username" : "gradle"
        },
        "_updatedAt" : {
          "$date" : 1482737327479
        }
      },
      {
        "_id" : "WvPYcLEG5fb7JzHNY",
        "t" : "r",  <-- This
        "_updatedAt" : {
          "$date" : 1482731721025
        },
        "ts" : {
          "$date" : 1482731721025
        },
        "rid" : "GENERAL",
          "_id" : "TZZePZf8BW7Lt8oMW",
          "username" : "김성중_LDCC-e-서비스팀-모바일담당"
        },
        "msg" : "공지사항",
        "groupable" : false
      },
    ...
    ...
}

**Comment by laggedHero** [comment]
@ktt9117 We do have a repo for our docs, including its own issues (https://github.com/RocketChat/Rocket.Chat.Docs/issues)

I added this issue there and will close this one.

You can follow: https://github.com/RocketChat/Rocket.Chat.Docs/issues/165
