### ISSUE TITLE
[BUG] Take photo freezes app

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat.iOS#2093]
I recently had bugs uploading photos taken within the app. As soon as I shot the photo and was prompted the "use photo"/"retake" options the touch of at least "use photo" freezed the app.

**Comment by rafaelks** [comment]
@soundstorm Are you running what version of the iOS?

**Comment by soundstorm** [comment]
Im running 11.4.1 on iP8+

**Comment by rafaelks** [comment]
@soundstorm Thanks, will try to reproduce it! 👍

**Comment by rafaelks** [comment]
Closed by #2118

**Comment by soundstorm** [comment]
@rafaelks @Sameesunkaria seems like we have to reopen this. If I take a photo and tap the "use photo" button directly afterwards, the app still freezes.

**Comment by Sameesunkaria** [comment]
@soundstorm Does the app become unresponsive intermittently, or does it completely freeze and not recover afterwards?

**Comment by soundstorm** [comment]
Even closing and opening again has no effect, need to force quit. So it's a real freeze.

**Comment by Sameesunkaria** [comment]
@soundstorm what the setting for `Maximum File Upload Size (in bytes)` on your server? And does this happen on open.rocket.chat?

**Comment by soundstorm** [comment]
Is currently at `1073741824` - should be sufficient ;)
Currently hard to reproduce.

**Comment by Sameesunkaria** [comment]
@soundstorm Can you please give #2191 a try? I have moved all the media processing to a background thread. 

I haven't been able to reproduce this on my device, so this is just a hunch on what may be happening.

**Comment by rafaelks** [comment]
This is now fixed in 3.1.1, thanks a lot for the help. 👍

**Comment by rafaelks** [comment]
@soundstorm Let us know if you still experience this please!
