### ISSUE TITLE
Integrations that use slash commands don't work

### ISSUE THREAD

**Issue by branic** [RocketChat/Rocket.Chat.iOS#2099]
Integrations that make use of slash commands don't work in the iOS app. For example we have /giphy and /topgif integrations enabled, but they cannot be used from the iOS app.

- Your Rocket.Chat app version: 3.0.3 (203)
- Your Rocket.Chat server version: 0.67.0
- Device (or Simulator) you're running with: iPhone 7

**Comment by rafaelks** [comment]
@branic Thanks for the heads up... this issue duplicates https://github.com/RocketChat/Rocket.Chat.iOS/issues/1611.

**Comment by cpitman** [comment]
@rafaelks I'm not sure that is correct. This is a defect in how the app works with current functionality in the server, not an RFE for new functionality around Apps, which are not out yet.

**Comment by rafaelks** [comment]
@cpitman `/giphy` is an App command, right?

**Comment by cardoso** [comment]
@rafaelks I remember `/giphy` used to work on iOS, but would select the first option implicitly when sending the command message.

Not sure where the regression is, but probably in the Giphy integration.

**Comment by rafaelks** [comment]
`/giphy` command right now depends on previewing the images and selecting them, it's not just like a simple command (like the `/invite` for example). This is an App specific command that requires things aren't implemented in iOS and Android yet.

**Comment by cpitman** [comment]
There may be a new app that provides a `/giphy` command, but long before that we have used outgoing integrations triggered on `/giphy` to provide similar functionality. Users are used to using `/` as the prefix for all commands on slack, so all of our integrations also use `/` as part of their trigger. This is supported on the server side, as well as the Android app.

**Comment by rafaelks** [comment]
@cpitman Does it work on Android for you? If yes, it should work on iOS as well.

**Comment by cpitman** [comment]
Yes, it works on Android, and does not work on iOS. Screenshots/videos attached.

Android works:
![Android Working](https://user-images.githubusercontent.com/852230/43654206-7637adc4-9718-11e8-9dab-155c1fb4c382.jpg)

iOS doesn't:
![iOS Not Working](https://user-images.githubusercontent.com/852230/43654477-510b7d72-9719-11e8-800d-64c05911f137.gif)
