### ISSUE TITLE
Messages can no longer be marked as unread

### ISSUE THREAD

**Issue by dbluxo** [RocketChat/Rocket.Chat.iOS#2102]
- Your Rocket.Chat app version: 3.0.3
- Your Rocket.Chat server version: 0.66.3
- Device (or Simulator) you're running with: Iphone 6 (11.3.1)

Messages can no longer be marked as unread.

**Comment by rafaelks** [comment]
It was never possible on the iOS app, but this is being implemented here: https://github.com/RocketChat/Rocket.Chat.iOS/pull/1960.

Thanks for the issue @dbluxo!
