### ISSUE TITLE
[NEW] Integrate with Siri Shortcuts (iOS 12)

### ISSUE THREAD

**Issue by artrmz** [RocketChat/Rocket.Chat.iOS#2116]
iOS 12, Xcode 10 brings new feature - Siri Shortcuts.

Create custom shortcuts that can be added by the user to for example:

- open certain channel
- open certain direct message
- send a predefined message to certain channel/dm

**Comment by Sameesunkaria** [comment]
I'm still not on the Shortcuts beta 😭

**Comment by rafaelks** [comment]
Lovely! Would love to have that.
