### ISSUE TITLE
Scrolling through history not working properly

### ISSUE THREAD

**Issue by sanderv32** [RocketChat/Rocket.Chat.iOS#212]
Your Rocket.Chat version: 2.5.0

Scrolling through the message history selects messages instead of scrolling. Maybe it's a better idea that if you want to select a message that the default behaviour of Apple is used so select it and hold it. This way you can scroll through the history.

**Comment by rafaelks** [comment]
@sanderv32 Are you talking about the Cordova application or the native one? We currently don't have the `select` state of the message in the native app.

**Comment by sanderv32** [comment]
How can i see which version is downloaded from the app store?

**Comment by TheReal1604** [comment]
@sanderv32 hey @sanderv32,

the app in the App Store is the Cordova one. I think the native iOS Application is only available via alpha / beta testing or if you compile it yourself.

**Comment by sanderv32** [comment]
Ok, i will play with the native app.
