### ISSUE TITLE
[BUG] Double notification on mention + subscription

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat.iOS#2120]
Maybe caused by server update to 0.68.3 but I receive notifications about the same message twice if I subscribed the channel and am mentioned within a message.

**Comment by Sameesunkaria** [comment]
In-app, push or both?

**Comment by soundstorm** [comment]
At least push, In-App: hard to tell as they come at same time. For push you can see two separate banners.

**Comment by Sameesunkaria** [comment]
This seems to be an issue with the server. Opened an issue on the Rocker.Chat repo. RocketChat/Rocket.Chat#11825
