### ISSUE TITLE
[BUG] Quick reply adds new chat view

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat.iOS#2121]
I'm using quick reply much, so I experience this bug:

Quick replys open a **new** chat view in the background (app closed) instead of replacing any chat view (removing old ones). This leads to multiple chats opened as a stack. So quick reply #a #a #b causes three chat views. If you open the app and hit the "<" to get back from #b to the channel overview, you'll open #a (twice if you hit "<" again) before getting to the overview.

**Comment by filipealva** [comment]
@soundstorm good catch! Thanks for reporting
