### ISSUE TITLE
[BUG] Messages are cut and not displayed fully

### ISSUE THREAD

**Issue by slajerek** [RocketChat/Rocket.Chat.iOS#2123]
- Rocket.Chat app version: 3.0.4 (206)
- Rocket.Chat server version: 0.65.1
- Device: iPhone 6, iOS 10.3.3

Often there's a situation that multi-line message is not displayed fully and last line is cut.

However, it is possible to scroll the text down within message boundaries and it is then seen that last line of text is was missing, but that makes first line of the multi-line message to disappear. It seems the height of message box boundaries is not calculated correctly as it is sometimes one line less than it should be.

**Comment by filipealva** [comment]
@slajerek Thanks for reporting! We working on a big update on chat components in order to fix this and other similar issues. I'll make sure to let you know when it gets fixed.
