### ISSUE TITLE
[QUESTION] Support for Arabic

### ISSUE THREAD

**Issue by TannerJuby01** [RocketChat/Rocket.Chat.iOS#2125]
Before writing an issue, please make sure you're talking about the native application (called Rocket.Chat+ in the App Store) and not the Cordova one (called Rocket.Chat in the App Store). If you are looking to open an issue to the Cordova application, go to this URL: https://github.com/RocketChat/Rocket.Chat.Cordova.

- Your Rocket.Chat app version: 3.1.0 (204)
- Your Rocket.Chat server version: 0.63.0
- Device (or Simulator) you're running with: iPhone 8

**The app isn't connecting to your server?**
Make sure your server supports WebSocket. These are the minimum requirements for Apache 2.4 and Nginx 1.3 or greater.

I noticed since releasing 3.0, Arabic is no longer supported. Is there plans in the future for Arabic support, and if so, is there an estimated timeline?

Thanks!

**Comment by rafaelks** [comment]
@kaiiiiiiiii Thanks for taking care of this one!

@TannerJuby01 If you can, please help us translating the files, we can add it to the next release! :-)
