### ISSUE TITLE
Which API should I use for set up user's APNS Token?

### ISSUE THREAD

**Issue by ktt9117** [RocketChat/Rocket.Chat.iOS#213]
Your Rocket.Chat version: 0.48.2

I analyzed how to store APNS tokens for user account information in the version of Rocket.chat Cordova, and then tried to apply it to Rocket.chat.iOS as follows:

```
static func setPushToken(_ userId: String, token: String, completion: @escaping MessageCompletion) {
        Log.debug("setPushToken")
        let request = [
            "msg": "method",
            "method": "raix:push-update",
            "params": [
                    "id": userId,
                    "token": ["apn": token],
                    "appName": "main",
                    "userId": NSNull(),
                    "metadata": []
                ]
            ] as [String : Any]
        SocketManager.send(request) { (response) in
            completion(response)
        }
}
```

but server return : 

```
[WebSocket] did receive JSON message: {
  "reason" : "Malformed method invocation",
  "offendingMessage" : {
    "id" : "qiMghFFXWejxW3HSvjxGQwYHCIPYrlVMfTxREMXqjJJ80QfyAW",
    "method" : "raix:push-update",
    "msg" : "method",
    "params" : {
      "metadata" : [

      ],
      "id" : "vbgh79B9pvgdHu87n",
      "appName" : "main",
      "userId" : null,
      "token" : {
        "apn" : "c1c3f74c364a60f0a17532d28f48e39507356c32f41c14cd63ee4f02ccc28a75"
      }
    }
  },
  "msg" : "error"
}
```

I'm not sure if the request format is wrong, or if that method is not available in the native iOS app.
Which API should I use for set up user's APNS Token? Please help me.
Thanks

**Comment by rafaelks** [comment]
Hey @ktt9117, thanks for opening the issue.

I think the only problem in your request is that the params must be an `Array` instead of a `Dictionary`. For example:

```swift
static func setPushToken(_ userId: String, token: String, completion: @escaping MessageCompletion) {
        Log.debug("setPushToken")
        let request = [
            "msg": "method",
            "method": "raix:push-update",
            "params": [[
                    "id": userId,
                    "token": ["apn": token],
                    "appName": "main",
                    "userId": NSNull(),
                    "metadata": []
                ]]
            ] as [String : Any]
        SocketManager.send(request) { (response) in
            completion(response)
        }
}
```

Can you try it please?

**Comment by ktt9117** [comment]
Hi @rafaelks, I tried it that way. Then server response is :


2017-01-09 09:14:26.110166 Rocket.Chat[852:507827] [WebSocket] did receive JSON message: {
  "id" : "hhtiSqF7eEcfLSX8RKnXdqnyKGLjJgZgAxLBbDlNNA0KIDyx1B",
  "error" : {
    "message" : "Match failed [400]",
    "reason" : "Match failed",
    "error" : 400,
    "errorType" : "Meteor.Error"
  },
  "msg" : "result"
}


server side log is :

[34mI20170109-09:08:14.916(9) rocketchat_lib rocketchat_lib.js:1011 [34mMeteor ➔ method raix:push-update -> userId: cmgXMpDWsB8YAHGk9 , arguments:  { '0':     { metadata: [],      appName: 'main',      userId: null,      id: 'cmgXMpDWsB8YAHGk9',      token: { apn: 'c1c3f74c364a60f0a17532d28f48e39507356c32f41c14cd63ee4f02ccc28a75' } } } 
[34mI20170109-09:08:14.920(9) Exception while invoking method 'raix:push-update' Error: Match error: Expected plain object in field metadata   at exports.check (packages/check.js:57:15)   at [object Object].raixPushUpdate (/opt/Rocket.Chat/programs/server/packages/raix_push.js:845:7)   at [object Object].methodsMap.(anonymous function) (/opt/Rocket.Chat/programs/server/packages/rocketchat_lib.js:1013:26)   at maybeAuditArgumentChecks (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:2108:12)   at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:1042:22   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:1041:43   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:1040:48   at Session.method (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:1018:23)   at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:880:89  
[34mI20170109-09:08:14.922(9) Sanitized and reported to the client as: Match failed [400] 
[34mI20170109-09:08:14.922(9) undefined undefined

**Comment by rafaelks** [comment]
@ktt9117 This is probably something wrong in your server-side. Let's see if someone from @RocketChat/core can take a look.

**Comment by ktt9117** [comment]
Hello @rafaelks !
I have compared the server logs for raix: push-update (Android, Cordova) and failing (iOS). The following differences have been found:

Succeed case:
method raix: push-update -> userId: bpz8hgJq5SS3p9yPa, arguments: {'0 ': {id: '76a3f3eecf354024b72defed81d70151', appName: 'main', userId: null, **_metadata: {}_**, token: {gcm: 'cvn9sehC8AA: APA91bFwEbcloVXdNec5qJi3j_pcMM_iYwI2qeQDmNVnx2PUoRNGeaBbJirFkUIJq7GOkoee1RppLvyr_zl4EWduKuVW7qiFPWwOKxi4sxtg5upZDB6D3z7gmVMV -shOqnJA7ONzDYft '}}}

Failed case:
method raix: push-update -> userId: oYsTgM4jCK4z8a84v, arguments: { '0': { **_metadata: []_**, appName: 'main', userId: 'oYsTgM4jCK4z8a84v', id: '498A5D7FCBCD4D88BF9C04756BD399D9', token: {apn: 'c1c3f74c364a60f0a17532d28f48e39507356c32f41c14cd63ee4f02ccc28a75 '}}}

If you look carefully, metadata is passed to json object if it succeeds. If it fails, json array is passed. 
How do I send metadata items to a json object?

**Comment by rafaelks** [comment]
@ktt9117 Sorry for the delay, can you try doing that?

```
static func setPushToken(_ userId: String, token: String, completion: @escaping MessageCompletion) {
        Log.debug("setPushToken")
        let request = [
            "msg": "method",
            "method": "raix:push-update",
            "params": [[
                    "id": userId,
                    "token": ["apn": token],
                    "appName": "main",
                    "userId": NSNull(),
                    "metadata": [:]
                ]]
            ] as [String : Any]
        SocketManager.send(request) { (response) in
            completion(response)
        }
}
```

**Comment by ktt9117** [comment]
@rafaelks It works. Thanks! 👍

**Comment by rafaelks** [comment]
@ktt9117 Awesome! What do you think about sending a PR that makes this request? :-)

**Comment by ktt9117** [comment]
@rafaelks It sounds great. But I don't know how to do PR. so you can do it however you like.

**Comment by rafaelks** [comment]
@ktt9117 Sounds good! Let me know if you want to learn how to do it. Here's some interesting resources from GitHub (it's pretty easy, actually): https://guides.github.com/activities/contributing-to-open-source/.

Thanks! 👍

**Comment by ktt9117** [comment]
@rafaelks OK. I'll try it. Thanks for your homework :)

**Comment by imrealashu** [comment]
Hey @rafaelks 
I'm sending this data using websocket...
```json
{
  "msg": "method",
  "method": "raix:push-update",
  "params": [
    {
      "id": "bq6G5kApbi7bmyyFM",
      "token": {"gcm": "token"},
      "appName": "main",
      "userId": null,
      "metadata": []    
    }
  ]
}
```

I'm getting "Malformed method invocation" error

**Comment by rafaelks** [comment]
@imrealashu You can see how we're doing on iOS here:

https://github.com/RocketChat/Rocket.Chat.iOS/blob/42b2aa6a351135f642f11b699e6c71361bacde42/Rocket.Chat/Managers/PushManager.swift#L16-L33

**Comment by imrealashu** [comment]
@rafaelks I tried to follow previous post only. Can you find any issue in my JSON version ?

**Comment by rafaelks** [comment]
@imrealashu Yes, you're updating GCM instead of APN?

**Comment by imrealashu** [comment]
@rafaelks yes. is there anything wrong ?
I tried this https://github.com/RocketChat/Rocket.Chat/issues/5503#issuecomment-271936955 as well, but got "Bad Request" error.

**Comment by rafaelks** [comment]
@imrealashu GCM is Android, not iOS. For iOS you should use `apn`.
