### ISSUE TITLE
[BUG] :orange_heart: reaction does not work 

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat.iOS#2137]
I just added a reaction using the :orange_heart: emoji, then the :yellow_heart:, but instead of just adding the yellow one it replaced the orange one.

**Comment by soundstorm** [comment]
Seems like it's a bug with the :orange_heart: - is there serverside an orange one? Gets deleted even without adding a new heart

**Comment by soundstorm** [comment]
Okay:
There is no :orange_heart: serverside, but we have it in our assets and selection list.
We may either add it to the server or delete it from the app (prefere first one).

**Comment by cardoso** [comment]
I'll close this and refer this issue: https://github.com/RocketChat/Rocket.Chat/issues/6740

I've been told it's not simple to update the emojione package :/
