### ISSUE TITLE
User status not updated properly

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat.iOS#214]
Your Rocket.Chat version: demo

Hi @rafaelks ,

the user status is not synced properly, can you recheck this?

Here are some screenshots: (made on the same time)

![2017-01-08 22-03-11 3767](https://cloud.githubusercontent.com/assets/5877910/21753489/c0b1e370-d5ee-11e6-9f98-b30a259a7b4b.png)
(User status on my iPhone, pretty much users online on the demo :-D)

When I look into my electron client.. and .. surprising :( not that much users are online:

<img width="271" alt="bildschirmfoto 2017-01-08 um 22 03 28" src="https://cloud.githubusercontent.com/assets/5877910/21753493/e8476522-d5ee-11e6-8b87-8d84b4f83145.png">

**Comment by rafaelks** [comment]
@TheReal1604 Yes, thank you! 👍
