### ISSUE TITLE
[BUG] Create an Account > Wrong error message was seen if account is already registered

### ISSUE THREAD

**Issue by YanniStaMaria** [RocketChat/Rocket.Chat.iOS#2159]
Environment:
Rocket Chat App version 3.1.0 (209)
Device (or simulator) you're running with: iPad Pro IOS 11.4.1

Pre-Condition:
Rocket.Chat fresh installed
There is an existing account

Steps:

1. Launch Rocket Chat app
2. Tap Connect to a server
3. Sign in to your server
4. Tap Create New Account
- Verify New Account page
5. Input the details of the existing account
7. Tap Register
- Verify validation message

Expected Result:
"Account already exist" should appear

Actual Result:
Wrong error message was seen

Please see attached photo:
Existing Account:
![rc](https://user-images.githubusercontent.com/40617185/44963156-ec3ae400-af5a-11e8-801e-05d1c08a3b48.png)

Create an Account:
![rc1](https://user-images.githubusercontent.com/40617185/44963191-1c828280-af5b-11e8-81b4-faa036aaa7be.png)

**Comment by rafaelks** [comment]
@YanniStaMaria This error is returned from the back-end right now, in order to fix that, we need to improve the way we handle the errors and the way back-end sends it.
