### ISSUE TITLE
Messages is not appeared

### ISSUE THREAD

**Issue by ktt9117** [RocketChat/Rocket.Chat.iOS#216]
Your Rocket.Chat version: 0.48.2

When I move the channel, the messages on the channel are not visible at first, but when the keyboard is up or the hamburger menu is pressed, the messages are seen at the moment.

(1)
![image](https://cloud.githubusercontent.com/assets/5284987/21838129/a37770fa-d813-11e6-86cb-f1d222ac4899.png)

(2)
![image](https://cloud.githubusercontent.com/assets/5284987/21838133/a995678a-d813-11e6-9c4c-4142a1eb1212.png)

For channels that does not have a lot of message history, sending a message might show only the last message you sent, hiding the keyboard and then re-appearing, or you might see a list of messages you previously sent when you clicked the hamburger menu.

(3)
![image](https://cloud.githubusercontent.com/assets/5284987/21838527/c1f1900e-d815-11e6-9bae-61cb4629a7ad.png)

(4)
![image](https://cloud.githubusercontent.com/assets/5284987/21838529/c69a67b6-d815-11e6-94d2-b81e32ace6fb.png)

**Comment by rafaelks** [comment]
@ktt9117 Thanks for taking this is screenshots and opening the issue. This is a known issue related to the loading of messages. The scroll becomes in the wrong position 🙄.

I'll keep the issue opened until we fix it. I'll make sure that this get fixed soon.

Thank you! 👍

**Comment by gradler** [comment]
@rafaelks Hi rafael. This issue is still happening.
If you do not have a conversation before (after creating a new person or a new channel) you will see this situation.

**Comment by rafaelks** [comment]
@gradler To clarify... this is two issues?

1. Message list doesn't get refresh when chat doesn't have messages;
2. To show in the bottom the messages instead of the top, when chat have just a few messages;

**Comment by gradler** [comment]
@rafaelks No, just one! The second one is just a suggestion.

When you enter a message in the room where you started a new conversation, the message goes out of the screen and only the last message entered is displayed.

I solved it this way, but I do not know if this is a good way.

where : Rocket.Chat > Controllers > Chat > ChatViewController.swift > appendMessages()

`      let offsetY = collectionView.contentOffset.y
        let bottomOffset = contentHeight - offsetY

        DispatchQueue.main.async {
            CATransaction.begin()
            CATransaction.setDisableActions(true)
            collectionView.performBatchUpdates({
                collectionView.insertItems(at: indexPaths)
            }, completion: { _ in
                **var shouldScroll = true
                if let contentHeight = self.collectionView?.contentSize.height {
                    if let collectionViewHeight = self.collectionView?.frame.height {
                        if contentHeight < collectionViewHeight {
                            shouldScroll = false
                        }
                    }
                }**
                
                if updateScrollPosition && shouldScroll {
                    collectionView.contentOffset = CGPoint(x: 0, y: collectionView.contentSize.height - bottomOffset)
                }
                
                CATransaction.commit()                
            })
        }`

**Comment by rafaelks** [comment]
@gradler I believe the bug is just that new messages aren't appearing in the screen, but we get them. That's a nice solution, wanna send a PR or let me do it?
