### ISSUE TITLE
[BUG] Join the community>Login with a email does not accept a valid email

### ISSUE THREAD

**Issue by Renzmu** [RocketChat/Rocket.Chat.iOS#2161]
Environment:
Rocket Chat App version 3.1.0 (209)
Device (or simulator) you're running with: iPhone 6+ IOS 11.4.1

Pre-Condition:
Rocket.Chat fresh installed

Steps:
1. Launch Rocket Chat app
2. Tap Join the community
3. Tap Login with email
4. Login using a valid account (eg. chinoc@sonarlogic.biz)
5. Verify the message

Expected Result:
valid email should work and user should be logged in

Actual Result:
credential is rejected

note: used the same password on both platform  pw:test

Please see attached photo:
Site account
![image](https://user-images.githubusercontent.com/41657529/44964378-b699f900-af62-11e8-8b3a-2083f1a917fe.png)

When logged on app using iphone 6+
![image](https://user-images.githubusercontent.com/41657529/44964386-cb768c80-af62-11e8-9336-6bac98e986d4.png)

**Comment by rafaelks** [comment]
You are testing with a user that doesn't have account on the community server.
