### ISSUE TITLE
[BUG] Open Chat room >  Hide Chat room > App crashes when the hidden chat room is opened

### ISSUE THREAD

**Issue by YanniStaMaria** [RocketChat/Rocket.Chat.iOS#2164]
Environment:
Rocket Chat App version 3.1.0 (209)
Device (or simulator) you're running with: iPad Pro IOS 11.4.1

Pre-Condition:
Rocket.Chat fresh installed

Steps:

1. Launch Rocket Chat app
2. Tap Connect to a server
3. Enter valid URL on Server URL field
- Verify Login Page
4. Open a chat room
5. On the left panel, hide the opened chat room
- Verify chat room is still open
6. Search for the hidden chat room

Expected Result:
Chat room should open without issue

Actual Result:
App crashes when a hidden chat room is opened

Please see attached video:
https://www.dropbox.com/s/a06q9dzdvv0ctm9/Video%20Sep%2003%2C%203%2019%2030%20PM.mp4?dl=0

**Comment by rafaelks** [comment]
This one is fixed in 3.1.1.
