### ISSUE TITLE
 [BUG] Horizontal View on login page is not working

### ISSUE THREAD

**Issue by Renzmu** [RocketChat/Rocket.Chat.iOS#2165]
Environment:
Rocket Chat App version 3.1.0 (209)
Device (or simulator) you're running with: iPhone 6+ IOS 11.4.1

Pre-Condition:
Rocket.Chat fresh installed

Steps:

1. Launch Rocket Chat app
2. Set phone on horizontal
3. Verify the page

Expected Result:
Horizontal must adapt the view of the page

Actual Result:
Horizontal view did not follow the phone orientation

Please see proof
https://www.dropbox.com/s/czqas5mdjgm1ej9/Issue%20on%20horizontal%20view.mp4?dl=0

**Comment by rafaelks** [comment]
We decided to not support horizontal for now because we don't think that makes sense, only for iPads (and we support it).
