### ISSUE TITLE
[BUG] Add/Attach Files button > Choose an option > White spaces as filename was uploaded

### ISSUE THREAD

**Issue by YanniStaMaria** [RocketChat/Rocket.Chat.iOS#2168]
Environment:
Rocket Chat App version 3.1.0 (209)
Device (or simulator) you're running with: iPad Pro IOS 11.4.1

Pre-Condition:
Rocket.Chat fresh installed

Steps:

1. Select any conversation on the list
- Verify conversation page should display
2. Tap Add/Attach Files Button
- Verify adding file option
3. Choose an option (Take a Photo, Record Video, Choose from library, Attach files or Drawing)
4. Delete inputted text on title field
5. Enter white spaces in title field
6. Tap Uploaded

Expected Result
Attached file should not be uploaded with white spaces as a title

Actual Result:
White spaces as title was uploaded

Please see attached video:
https://www.dropbox.com/s/h8r6529l0vkf0mx/Video%20Sep%2004%2C%209%2029%2011%20AM.mp4?dl=0

**Comment by rafaelks** [comment]
That's not a problem the app needs to control since the API endpoint accepts whitespaces.
