### ISSUE TITLE
[BUG] Horizontal View on a channel ,and returning to vertical view closes the channel

### ISSUE THREAD

**Issue by Renzmu** [RocketChat/Rocket.Chat.iOS#2170]
Environment:
Rocket Chat App version 3.1.0 (209)
Device (or simulator) you're running with: iPhone 6+ IOS 11.4.1

Pre-Condition:
User is logged in

Steps:
1. Go to a channel
2. Change the phone orientation to horizontal
3. Change to vertical and observe

Expected Result: 
When the orientation is changed user should be still in the channel

Actual Result:
When the orientation was changed user was not in the channel

Please see video:
https://www.dropbox.com/s/u64sxoc9k4wgk3z/signout%20on%20channel%20when%20changing%20pone%20orientation.mp4?dl=0

**Comment by rafaelks** [comment]
This is the expected behaviour on iPhone Plus models.
