### ISSUE TITLE
[IMPROVEMENT] Join Jitsi conference link

### ISSUE THREAD

**Issue by frdmn** [RocketChat/Rocket.Chat.iOS#2174]
- Your Rocket.Chat app version: `3.1.0 (210)`
- Your Rocket.Chat server version: `0.66.0`
- Device (or Simulator) you're running with: iPhone X

### Description:

Unable to join Jitsi conference from within the iOS client

### Steps to reproduce:

1. Open desktop/browser version of Rocket.Chat
2. Create/send out Jitsi invitation 
3. On the receiving end, try to open the Jitsi conference from the iOS client

### Expected behavior:

Open/follow Jitsi link/message in (installed) Jitsi Meet application

### Actual behavior:

Just a regular "`Started a conference`" message that we're not able to interact with. People have to manually switch to Jitsi Meet and enter the conference link by hand.

### Additional context

![unbenannt-1](https://user-images.githubusercontent.com/944459/45145900-075b5d00-b1c2-11e8-8888-543d9f76da1a.png)

**Comment by rafaelks** [comment]
This one is fixed and merged.
