### ISSUE TITLE
[BUG] Changed avatar in app/web won't show to other users

### ISSUE THREAD

**Issue by flowli** [RocketChat/Rocket.Chat.iOS#2183]
# Description
Avatars not being updated for other users when changed via desktop app/web browser or the mobile apps (Android/iOS).

# Devices and Versions
iOS Rocket.Chat: 3.1.0 (210)
Tested on iPhone SE and iPhone 6

# Steps to reproduce
Use any client, change the avatar, check on the iOS app. The avatar will be default or some old version.

**Comment by rafaelks** [comment]
@flowli Thanks for opening the issue, this is going to be address here: #2197.

**Comment by flowli** [comment]
@rafaelks Thanks, does that mean I upgrade the server and it just works?

**Comment by rafaelks** [comment]
@flowli No... we'll need an update in the iOS app, but we already have this issue to track it: #2197.
