### ISSUE TITLE
iOS12 Take photo -> Use photo -> App freeze

### ISSUE THREAD

**Issue by piotrkochan** [RocketChat/Rocket.Chat.iOS#2193]
- Your Rocket.Chat app version: 3.1.0
- Your Rocket.Chat server version: 0.69.1
- Device (or Simulator) you're running with: iPhone SE

In https://github.com/RocketChat/Rocket.Chat.iOS/issues/2184 I've introduced some issues which I have with file-uploads. Meanwhile I've updated to iOS12 and the issue is that after taking a photo and tapping on "use photo" application freezes and only app kill helps.

**Comment by Sameesunkaria** [comment]
@piotrkochan Can you try running #2191 ?

**Comment by piotrkochan** [comment]
I dont have mac so I cant compile ios app
W dniu wt., 18.09.2018 o 15:59 Samar Sunkaria <notifications@github.com>
napisał(a):

**Comment by Sameesunkaria** [comment]
@piotrkochan Can you try this on the latest update?

**Comment by piotrkochan** [comment]
I tried it today, and I think it works.
