### ISSUE TITLE
[CHORE] Create a default warning message to users using E2E

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.iOS#2196]
If the message has type `e2e`, since we don't have a way to support them in mobile yet, we'll be showing this message to the user:

> Encrypted message (we are working to support them).

**Comment by Sameesunkaria** [comment]
Do we have a spec for how the e2e works?

**Comment by rafaelks** [comment]
@Sameesunkaria The APIs are still under development (to be ready for 0.71 release). Today I'll have a call to understand it better and see if we can do something right now. 👍
