### ISSUE TITLE
[QUESTION] Login using Crowd

### ISSUE THREAD

**Issue by Emersonyh** [RocketChat/Rocket.Chat.iOS#2198]
- Your Rocket.Chat app version: 3.1.0
- Your Rocket.Chat server version: 0.68.3
- Device (or Simulator) you're running with: 11.4.1

When trying to login with ths iOS app, I'm unable to use Crowd, he goes back to the local password on MongoDB.
Since our server is configured to use Crowd, the mobile app is not working properly

**Comment by rafaelks** [comment]
@Emersonyh Can you elaborate your issue? What's Crowd?

**Comment by piotrkochan** [comment]
Native apps does not have anything to crowd, it should and work for me. Check RocketChat log when someone logs in

**Comment by rafaelks** [comment]
Closing this issue for now in this case, thanks for the reply @piotrkochan! 👍
