### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by gsaslis** [RocketChat/Rocket.Chat.iOS#22]
Support all 4 native notifications types in iOS, each with appropriate actions:

Banner
Alert
Badge
Sound 

More info: 
https://developer.apple.com/library/prerelease/ios/documentation/UserExperience/Conceptual/MobileHIG/NotificationCenter.html#//apple_ref/doc/uid/TP40006556-CH39-SW1

**Comment by kormic** [comment]
When should we receive notifications? I guess when we have a pm?

**Comment by NickBusey** [comment]
I would label this not as a feature, but a bug. Without notifications, a chat app is not very useful..

I want a notification whenever there is a new message in any channel I'm in.
