### ISSUE TITLE
[CRASH][SHARE EXTENSION] Crash on trying to share a screenshot from iPhone (from the screenshot modal)

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.iOS#2200]

**Comment by coruble** [comment]
Thank you for this fix @rafaelks our users were going crazy ! Already merged in my fork, works like a charm (after a first unsuccessful try, for some reason..)

**Comment by rafaelks** [comment]
@coruble Amazing, great to know! 👊
