### ISSUE TITLE
Create a ModelHandler that will handle model changes (mainly from Socket) and implements it in BaseModel

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.iOS#222]
Your Rocket.Chat version: (make sure you are running the latest)

**Comment by ktt9117** [comment]
Hi @rafaelks

When I added a new channel, the added channel was applied directly to the table in SubscriptionsViewController. 

But, this does not apply after merging the applied code (# 220 ~ # 222).
After debugging, if I request to create a new channel as shown below,

Socket will send message: {
  "method" : "createPrivateGroup",
  "id" : "ug723Wwql5zJGKxof54KO6RVisqvo369p1Ola0wMTOQVRyWptl",
  "params" : [
    "asdlas_emQtd",
    [

    ],
    false
  ],
  "msg" : "method"
}

The following response message arrives,

[WebSocket] did receive JSON message: {
  "fields" : {
    "eventName" : "oYsTgM4jCK4z8a84v\/subscriptions-changed",
    "args" : [
      "insert",
      {
        "unread" : 0,
        "t" : "p",
        "_updatedAt" : {
          "$date" : 1484896241981
        },
        "open" : true,
        "ts" : {
          "$date" : 1484896241972
        },
        "rid" : "FXCkR9XatDJrzfgtn",
        "u" : {
          "_id" : "oYsTgM4jCK4z8a84v",
          "username" : "gradlerpad"
        },
        "ls" : {
          "$date" : 1484896241972
        },
        "_id" : "4834fsFYTqt7cBMoi",
        "alert" : false,
        "name" : "asdlas_emQtd"
      }
    ]
  },
  "collection" : "stream-notify-user",
  "id" : "id",
  "msg" : "changed"
}

After the method is called, the following function is finally called.
SubscriptionManager > changes 
SubscriptionsViewController > handleModelUpdates<T>

```
func handleModelUpdates<T>(_: RealmCollectionChange<RealmSwift.Results<T>>?) {
	guard !isSearchingLocally && !isSearchingRemotely else { return }
	guard let auth = AuthManager.isAuthenticated() else { return }
	subscriptions = auth.subscriptions.sorted(byProperty: "lastSeen", ascending: false)
		
	> I've logged subscriptions here and it does not contain any new subscriptions.
	> I tried to solve it by myself, but I could not. Please help me.

	 groupSubscription()
	 tableView?.reloadData()
 }
```

**Comment by rafaelks** [comment]
@ktt9117 Good catch, I'm fixing it in #227.
