### ISSUE TITLE
The transmitted / received message is invisible.

### ISSUE THREAD

**Issue by ktt9117** [RocketChat/Rocket.Chat.iOS#223]
Your Rocket.Chat version: (make sure you are running the latest)

I tested on iPad.
If I switch the app to the background and then run the app again about 20-30 seconds later, 
there is a problem that the send/receive message is not normally displayed on the currently entered channel. 
If I move to another channel, the channel normally works.

Also, in the simulator, the reception of the message including the ping / pong normally works even if it enters the background, but it is not the case in the real device. Can you explain why?

**Comment by rafaelks** [comment]
@ktt9117 It can be related to the thread we're receiving the messages and trying to add it to the interface while the app is in foreground (we shouldn't try to do it, obviously). I'll let this issue open to investigate further.

Thank you!

**Comment by gradler** [comment]
@rafaelks I tried test again with lastest develop version, but it has not been reproduced anymore. It seems that the #228 issue has been resolved together. You can close this. If it happens again, I'll report it. Thanks for your help.

**Comment by rafaelks** [comment]
@gradler That's awesome! 👍
