### ISSUE TITLE
[IMPROVEMENT] Swipe to read message appear different background

### ISSUE THREAD

**Issue by thiagosanchz** [RocketChat/Rocket.Chat.iOS#2230]
When I swipe a message to right to make message read or unread, another background (grey) appear. We can set this background with blue too. 
![img_47b1e7ac7473-1](https://user-images.githubusercontent.com/39275608/46315742-9cc0f580-c5a4-11e8-9309-e3ae36be3bc8.jpeg)

**Comment by SIMRAN1** [comment]
@rafaelks may I work on this issue?

**Comment by Sameesunkaria** [comment]
@SIMRAN1 Sure! We want the gesture to mimic how it looks like on iOS 11. So the glyph should stay on the leading edge until the action is about to be selected, and like @thiagosanchz said, it should have a homogeneous background. (See the Mail app for reference)

Cheers!

**Comment by SIMRAN1** [comment]
okk @Sameesunkaria I will send a pr for this soon!

**Comment by rafaelks** [comment]
@SIMRAN1 Are you working on this?
