### ISSUE TITLE
[QUESTION] Navigating Issues From ChatViewController

### ISSUE THREAD

**Issue by TannerJuby1** [RocketChat/Rocket.Chat.iOS#2249]
- Your Rocket.Chat app version: Latest
- Your Rocket.Chat server version: Not sure, but API is latest
- Device (or Simulator) you're running with: iPhone XS Max (occurs on all)

I am using Rocket.Chat.iOS to embed into a single tab of a larger application. Everything seems to work perfectly fine, except when navigating or presenting a view onto `ChatViewController`. When I open either `ChannelActionsViewController`, `MessageListControllerSearch`, or I opt to select an image from the library, they open fine. However when they are dismissed, instead of going back to the `ChatViewController` I am sent back to the `SubscriptionsViewController`... 

I changed the two spots (`MainSplitViewController` and `AppManager`) I found where you attempt to get the `MainSplitViewController` from the UIApplication's shared rootViewController (i.e. `(UIApplication.shared.delegate as? AppDelegate)?.window?.rootViewController as? MainSplitViewController`) to instead map to my own view architecture in order to get the `MainTabViewController` but that didn't change anything. 

My guess is that is all caused by the BaseNavigationViewController or something, but the only thing I find in there when pushing, popping, presenting, etc. is modifying the navigation bar, not the viewController. 

If it helps, here is what my view architecture looks like compared to Rocket.Chat's in regards to the views listed above when the respected view is present:

**MY APP**:
     _ChatViewController_
           - MainTabViewController > MainSplit > BaseNavigation > Chat
     _ChannelActionsViewController_
           - BaseNavigationController > ChannelActionsViewController
     _MessageListControllerSearch_
           - BaseNavigationController > MessageListControllerView
     _Selecting Photo From Library_
          -  UIImagePickerController -> PUPhotoPickerHostViewController

**ROCKET.CHAT**:
     _ChatViewController_
           - MainSplit > BaseNavigation > Chat
     _ChannelActionsViewController_
           - BaseNavigationController > ChannelActionsViewController
     _MessageListControllerSearch_
           - BaseNavigationController > MessageListControllerView
     _Selecting Photo From Library_
           - UIImagePickerController -> PUPhotoPickerHostViewController

The view architecture looks correct between the two, so my only guess is that is must occur when dismissing these view controllers...

Could you please help point me in a direction where the issue could be?

Thanks

**Comment by rafaelks** [comment]
@TannerJuby1 You should probably navigate the controller using a different navigation controller stack instead of the one use are using. 🤔

**Comment by TannerJuby1** [comment]
I should use a different navigation stack on Rocket.Chat than the one Rocket.Chat created? That doesn't make any sense. 

The only difference between the architecture is that the app I'm working on has the root of Rocket.Chat on a TabViewController instead of the key window. 

In regards to stacks, with proper practice, if I'm trying to pop off the nth item in the stack, I should be on the n-1 item in the stack, regardless of what the root is.

**Comment by rafaelks** [comment]
@TannerJuby1 Is this happening on iPad and iPhone?

**Comment by TannerJuby1** [comment]
@rafaelks we were only testing for iPhone. But we were able to resolve the issue by setting 
```
self.definesPresentationContext = true
```
in all of the places where navigations away from ChatViewController occurs.

**Comment by rafaelks** [comment]
Awesome! I'm gonna close the issue in this case. Thank you! 👍
