### ISSUE TITLE
[BUG] Bug with upload photo from Camera and from MediaLibrary

### ISSUE THREAD

**Issue by Shaverdoff** [RocketChat/Rocket.Chat.iOS#2264]
- Your Rocket.Chat app version: 3.1.1
- Your Rocket.Chat server version: 0.70.3
- Device (or Simulator) you're running with: iPhone X 12.0.1, iPhone 6 11.3.1, iPhone 5S 12.0.1 and more

Login to Rockeet.chat on-premise server, tap on DM/CH/PG with my colleague, tap blue "+" and choose make photo, use photo to send, fill named-dialog and tap upload... uploading progress bar in the top of telephone screen is blinked and disappear so no photo was uploading. The same issues happend time to time with files from medialibrary. sometimes that files uploading well somitimes not.

**Comment by Shaverdoff** [comment]
Rafael we talk in email about that issue, i write to you from sha***ail.com. We can proceed here.

**Comment by rafaelks** [comment]
@Shaverdoff Can you post that screenshot here? I could not see over there.

**Comment by Shaverdoff** [comment]
[image1.jpeg]
Here you go

Отправлено с iPhone

26 окт. 2018 г., в 18:10, Rafael Kellermann Streit <notifications@github.com<mailto:notifications@github.com>> написал(а):


@Shaverdoff<https://github.com/Shaverdoff> Can you post that screenshot here? I could not see over there.

**Comment by Shaverdoff** [comment]
damn))) i was answer to you on email ))) here you go twice)
![upload-size](https://user-images.githubusercontent.com/43804710/47575291-caeee680-d952-11e8-9777-a25a30ca14d0.jpg)

**Comment by Shaverdoff** [comment]
Rafael.. maybe this helps.. i use default gridfs on single instance on-premise server instead of filesystem to upload and other store.

Отправлено с iPhone

26 окт. 2018 г., в 18:19, Rafael Kellermann Streit <notifications@github.com<mailto:notifications@github.com>> написал(а):


@Shaverdoff<https://github.com/Shaverdoff> There's no image yet...

**Comment by Shaverdoff** [comment]
update relase 071 of rocketchat server but still bug to upload in ios app

**Comment by rafaelks** [comment]
@Shaverdoff What error are you seeing?

**Comment by Shaverdoff** [comment]
@rafaelks no any error, just bliking upload progress indicator on the top of rocketchat screen and nothing happing... there are no uploaded file on chat .

**Comment by rafaelks** [comment]
@Shaverdoff Do you have debugging skills with iOS? Would be nice to understand what's happening.

**Comment by Shaverdoff** [comment]
no i'am not developer at all. only with administrative skills. but i think a can make video through second phone and send to you

**Comment by rafaelks** [comment]
@Shaverdoff Sounds good!

**Comment by Shaverdoff** [comment]
https://yadi.sk/i/NrguySL70sh1tg
here you go.

**Comment by Shaverdoff** [comment]
also right ""button" send photo" pereodical sticks too

**Comment by Shaverdoff** [comment]
trying to rocketchat experimental. it will told me that error with upload file...

**Comment by Shaverdoff** [comment]
i asked at parallel-mobile world - Android users - thre are uploads failed too.... may be it a bug on-permis server?

**Comment by rafaelks** [comment]
@Shaverdoff I would love to have access to the logs of your error... can I have a user in your server?

**Comment by Shaverdoff** [comment]
can we speak in private about access? do not want to public secret url here. my skype is shaverdoff. knok me and i 'll provide url  to you.

**Comment by rafaelks** [comment]
@Shaverdoff Yes, send me an email at `rafael.kellermann at rocket.chat`.

**Comment by Shaverdoff** [comment]
successful?

**Comment by Shaverdoff** [comment]
Login: rafael
Pass: As123456
url https://rocket.altarix.ru
also you have email rafael@altarix.ru<mailto:rafael@altarix.ru>
try to login

--
Gerasim Shaverdov | Deputy CTO | Altarix
Mobile: +7 937 070 66 84<tel:+7%20937%20070%2066%2084> | Skype/email : gerasim@altarix.ru<mailto:gerasim@altarix.ru>
Lenina av.25, Samara, Russia, 443068

**Comment by Shaverdoff** [comment]
with Rafael find a missconfigure nginx )
https://github.com/RocketChat/Rocket.Chat.iOS/issues/2184#issuecomment-423517754
issues close.
