### ISSUE TITLE
[NEW] Remove `@` from mentions on the text of the message

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.iOS#2289]
In order to support Federation, Rocket.Chat internally decided that removing `@` from mentions in the message is a good solution.

In summary, the changes are:

1. In order to mention someone, `@all` or `@here` you keep using `@`;
2. When the clients display the mention, the `@` is removed from the text;

**Comment by cardoso** [comment]
I don't agree with this :p 

Having '@' is the norm pretty much everywhere.
And If there's @ it will be easier for users not familiar with chat tools to know how to mention.

**Comment by rafaelks** [comment]
@cardoso I also don't agree, I think it'll confuse many people... but Rocket.Chat decided that removing `@` from mentions would be important/required for Federation (internal discussions). Unfortunately I couldn't see any online discussion right now about this topic to attach here, that's why I moved it to 3.3.0... let's see what happens.

**Comment by cardoso** [comment]
@soundstorm this is only a cosmetic change in the message view.

You still have to type @ to mention someone (then it's magically omitted)
