### ISSUE TITLE
[PROBLEM] Invalid Certificate

### ISSUE THREAD

**Issue by rafaelvicio** [RocketChat/Rocket.Chat.iOS#2313]
My RocketChat is on a server that does not have a valid international certificate, this is preventing users from using IOS / Android applications.

- Your Rocket.Chat app version: Last IOS/Android
- Your Rocket.Chat server version: 0.70.0

**Comment by rafaelks** [comment]
@rafaelvicio You just need a valid SSL certificate. You can get it for free on Let's Encrypt: https://letsencrypt.org.

**Comment by danielddcl** [comment]
We have the same problem. Our certificate is valid: ICP Brasil, from Certisign. You can see here: https://chat.pf.gov.br

**Comment by rafaelks** [comment]
@danielddcl Can you change to something like Let's Encrypt? Look what I get in your server:

![screen shot 2018-11-14 at 09 18 48](https://user-images.githubusercontent.com/551004/48479406-5c34d880-e7ee-11e8-99c7-e33a7ef78432.png)
![screen shot 2018-11-14 at 09 18 43](https://user-images.githubusercontent.com/551004/48479407-5c34d880-e7ee-11e8-99db-8e02ecd3aeb4.png)

**Comment by rafaelvicio** [comment]
At the outset we must use ICP-Brasil certificate. Let's check the possibility of switching to Let's Encrypt.

Accept or allow certificates like ICP-Brasil can become a feature? @rafaelks

**Comment by rafaelks** [comment]
@danielddcl Acabei de confirmar que nem o Google Chrome aceita este intermediate. Vocês já tentaram fazer esta configuração? https://support.apple.com/pt-br/HT204477

**Comment by rafaelvicio** [comment]
@rafaelks Ja tentei adicionar o certificado manualmente, no IPhone 7 mesmo adicionando ele não reconhece o certificado.

**Comment by rafaelvicio** [comment]
Certificado no IOS.

![Certificado IOS](https://image.ibb.co/eq5TVL/43273d30-bb1d-433d-b110-9df22ba0848d.jpg)

**Comment by rafaelks** [comment]
@danielddcl @rafaelvicio E vocês chegaram a ver esta nossa documentação? https://rocket.chat/docs/developer-guides/mobile-apps/supporting-ssl/

**Comment by danielddcl** [comment]
@rafaelks Conversei com algumas pessoas de infra e obtive algumas informações. O Let's Encrypt acabou proibido aqui na Polícia Federal por dois motivos: parece que existe legislação orientando o uso de certificados ICP Brasil (não tenho certeza disso, vou pesquisar melhor) e o outro motivo foi a desconfiança em relação ao Let's Encrypt por ser uma solução externa (fora do país), não sabemos se é realmente seguro.

**Comment by danielddcl** [comment]
@rafaelks Obrigaod, vou tentar essa configuração. Tenho android aqui.

**Comment by rafaelvicio** [comment]
@rafaelks E possivel transformar esse problema em uma feature dos aplicativos?
Que o aplicativo aceita conexão de Certificados Invalidos.

**Comment by rafaelks** [comment]
@rafaelvicio No Android, pode-se entrar utilizando o protocolo HTTP ao invés de HTTPS. No iOS não suportamos esta funcionalidade na versão da loja, mas é possível fazer um fork da aplicação e suportar certificados inválidos e URLs inseguras. A solução ali em cima não funcionou? Podemos pensar em alguma solução para resolver quando o certificado está instalado no iOS... sabes dizer qual o erro que aparece?

**Comment by rafaelvicio** [comment]
@rafaelks Estou tentando tornar o certificado reconhecido no IOS, mas sem sucesso ate o momento.

O Erro apresentado no IOS e o seguinte ![IOS](https://image.ibb.co/crEEn0/ios.jpg)

**Comment by rafaelks** [comment]
@rafaelvicio Consegue entrar em contato comigo no nosso chat? `open.rocket.chat`, fala comigo lá: `rafael.kellermann`.

**Comment by rafaelvicio** [comment]
@rafaelvicio Estou la, mas no aplicativo nao consigo abrir conversar um um ususario. Pode me mandar uma mensagem rafaelvicio

**Comment by rafaelks** [comment]
@romuloslv Para acessar servidores com certificados self-signed, você vai precisar instalar o certificado no dispositivo (iOS ou Android) e confiar manualmente neles. Você pode consultar nossa documentação sobre como fazer isto: https://rocket.chat/docs/developer-guides/mobile-apps/supporting-ssl/.

De qualquer maneira, recomendamos que você use algum serviço com o [Let's Encrypt](http://letsencrypt.org) para deixar o seu servidor mais seguro.
