### ISSUE TITLE
[NEW][RCVC] Add a placeholder title to attachments with `fields` but no title

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.iOS#2323]
Add the default title: "No title"

**Comment by jswedenburg** [comment]
Is this referring to the title and description of the upload dialog? If so, the title field already has a default title of the file name. Clarification would be nice! Thanks

``if fileName?.text?.isEmpty == false {
                name = fileName?.text ?? file.name
            }``

**Comment by rafaelks** [comment]
@jswedenburg No, sorry... this is related to not showing attachments with `fields` properties without title null when collapsed, like this:

![screen shot 2018-11-20 at 13 34 23](https://user-images.githubusercontent.com/551004/48784046-0027f380-ecc9-11e8-8b47-b734db2ac66f.png)
