### ISSUE TITLE
Since new update (24.01.2017) app is crashing

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat.iOS#234]
Your Rocket.Chat version: demo

If i try to open the app, until the last release in testflight the app is constantly crashing.

**Comment by rafaelks** [comment]
@TheReal1604 Yep, it's related to some Swift optimizations. Fixing it in a few and sending another beta.

**Comment by TheReal1604** [comment]
@rafaelks thanks for explanation! Just want to report this. So its noticed.
