### ISSUE TITLE
[IMPROVEMENT][RCVC] HintsView layout adjustments & user priority

### ISSUE THREAD

**Issue by cardoso** [RocketChat/Rocket.Chat.iOS#2347]
- Users need to be the last 5 to send messages in the current channel

![](https://i.imgur.com/mU6NwgS.jpg)

- Missing darkened background & rounded corners

![](https://i.imgur.com/gB65jQg.png)

- Align avatars with 'Suggestions' & cell separator with usernames

![](https://i.imgur.com/jObM5Bv.png)

- remove own user from list

**Comment by rafaelks** [comment]
@cardoso It should also avoid showing your own username in the first position 😂
