### ISSUE TITLE
Error messages are not being displayed

### ISSUE THREAD

**Issue by jm4rc05** [RocketChat/Rocket.Chat.iOS#235]
Your Rocket.Chat version: development branch updated at 1/24

_I'm using the simulator since my phone went M.I.A. :(_

Steps to reproduce the error:

**For a incorrect server (after a fresh install)**, just input a non valid server like _https://error.rocket.chat_.

Result in nothing: no message to alert the user and the prompt keep waiting at the server field.
For now I added a Toast (yes, I'm a Android developer;-) from [Toaster](https://github.com/devxoul/Toaster))

**For a incorrect user/password (after connecting to a valid server)**, just input a incorrect password.

Results in a _wait forever_ situation: the activity indicator is running near password field (and debugging the app, it's running a loop of "ping/pong" messages).

**Comment by rafaelks** [comment]
@jm4rc05 Yep, that's very important! 😂 

I've added this bug to the `v1.0.0-alpha` milestone.

Thank you for reporting it! 👍
