### ISSUE TITLE
sorting message

### ISSUE THREAD

**Issue by Shaverdoff** [RocketChat/Rocket.Chat.iOS#2354]
Before writing an issue, please make sure you're talking about the native application (called Rocket.Chat+ in the App Store) and not the Cordova one (called Rocket.Chat in the App Store). If you are looking to open an issue to the Cordova application, go to this URL: https://github.com/RocketChat/Rocket.Chat.Cordova.

- Your Rocket.Chat app version: 311
- Your Rocket.Chat server version: 0.71
- Device (or Simulator) you're running with: iPhoneX 12.1

Than write message on mobile to user with DM and user at once answer message sort is broken..
in desktop all fine

![default](https://user-images.githubusercontent.com/43804710/48954322-654a4600-ef62-11e8-9c57-7cc17e6aefc1.png)

and that cut-screen on mobile

![default](https://user-images.githubusercontent.com/43804710/48954295-4c419500-ef62-11e8-9f3e-c4f70014da54.png)

it took about 5-10 minute on mobile sorting was correcting

![default](https://user-images.githubusercontent.com/43804710/48954506-341e4580-ef63-11e8-99b9-4139ba79f17c.png)

**Comment by rafaelks** [comment]
This is already fixed in 3.2.0, thank you! 👍

**Comment by Shaverdoff** [comment]
Rafael, and when 3.2.0 version is appear in appStore?

--
Gerasim Shaverdov | Deputy CTO | Altarix
Mobile: +7 937 070 66 84<tel:+7%20937%20070%2066%2084> | Skype/email : gerasim@altarix.ru<mailto:gerasim@altarix.ru>
Lenina av.25, Samara, Russia, 443068

**Comment by rafaelks** [comment]
@Shaverdoff Not yet, it's still under development.

**Comment by Shaverdoff** [comment]
;)
In this case, I wish you a speedy successful coding and deployment

Отправлено с iPhone

23 нояб. 2018 г., в 23:51, Rafael Kellermann Streit <notifications@github.com<mailto:notifications@github.com>> написал(а):


@Shaverdoff<https://github.com/Shaverdoff> Not yet, it's still under development.
