### ISSUE TITLE
[BUG] Composer doesn't show up when opening DM from User Details popover

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.iOS#2362]
On the iPad:

1. Tap in a user mention;
2. See user information;
3. Tap to message the user;

The composer will be hidden.

**Comment by cardoso** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat.iOS/commit/8a7888a9c93aca2eeb4339d4d28d51ce009f091f
