### ISSUE TITLE
Undo & Redo

### ISSUE THREAD

**Issue by gsaslis** [RocketChat/Rocket.Chat.iOS#24]
Support undo and redo, as very useful text input - related actions

**Comment by kormic** [comment]
What do you mean exactly? It this something like history in terminal? Could you give me a better description?

**Comment by gsaslis** [comment]
I opened this after reading: https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/UndoRedo.html 

Not sure if it's supported by default...?

**Comment by kormic** [comment]
Undo your typing? Yes, ok I guess we can do this but who actually uses this? :)

**Comment by gsaslis** [comment]
well, for once, i do, but also - and more importantly - Apple suggests we
do, because it turns out there might be more crazy ppl like me out there!
 ; )

-- 
Yorgos Saslis
Software Engineer

**Comment by kormic** [comment]
OK then!!! :D

**Comment by kormic** [comment]
I was looking to see how I can implement this but then I checked to see if this is supported by default and guess what!!! :)

**Comment by gsaslis** [comment]
awesome! guess we can close this then! ;)
