### ISSUE TITLE
[BUG] Not all channels shown

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat.iOS#2403]
I'm currently in 74 channels and have 26 open conversTions, of which 6 channels + 1 user are in fav list (counting the shown ones on desktop).
All users are shown in the app, but not all channels (64).

**Comment by rafaelks** [comment]
@soundstorm Few questions... Are you using 3.2.0? Are you using any filters? Is anything special about those missing channels?

**Comment by soundstorm** [comment]
Filters? If I search them, I can see them, but not in the regular list.

I see no real pattern in the missing channels. Some are letters only, others have dashes or start with numbers.
Some of them are created in the past via slack before migration, others in RC. As other channels created in slack show up, thats weird.

But seems like the missing ones are the same.

Examples from mongo:
```
{ "_id" : "fYeEJJ84T9sPp8SjL", "name" : "ardumower", "t" : "c", "msgs" : 34, "u" : { "_id" : "FSDQcz2Sd2uYPMbCv", "username" : "xxx" }, "ts" : ISODate("2017-06-18T15:15:39.610Z"), "ro" : false, "sysMes" : true, "_updatedAt" : ISODate("2018-10-10T20:45:39.524Z"), "importIds" : [ "C5VFCP2BC" ], "lm" : ISODate("2018-10-04T16:39:27.715Z"), "archived" : false, "usersCount" : 9, "lastMessage" : { "_id" : "tz3dm7TqB3vnj8rir", "rid" : "fYeEJJ84T9sPp8SjL", "msg" : "xxx", "ts" : ISODate("2018-10-04T16:39:27.715Z"), "alias" : "I=o", "u" : { "_id" : "NQF4gENguRnTQJ5oS", "username" : "xxx", "name" : "I=o" }, "_updatedAt" : ISODate("2018-10-04T16:39:28.134Z"), "editedBy" : null, "editedAt" : null, "emoji" : null, "avatar" : null, "customFields" : null, "groupable" : null, "attachments" : null, "reactions" : null, "urls" : [ { "url" : "xxx", "meta" : { "oembedProviderName" : "YouTube", "oembedHtml" : "xxx", "oembedTitle" : "xxx", "oembedType" : "video", "oembedProviderUrl" : "https://www.youtube.com/", "oembedAuthorUrl" : "xxx", "oembedAuthorName" : "Ingmar Stapel", "oembedVersion" : "1.0", "oembedThumbnailUrl" : "xxx", "oembedUrl" : "xxx" }, "headers" : { "contentType" : "application/json" }, "parsedUrl" : { "host" : "www.youtube.com", "hash" : null, "pathname" : "/oembed", "protocol" : "https:", "port" : null, "query" : { "maxheight" : "200", "url" : "xxx }, "search" : "xxx", "hostname" : "www.youtube.com", "slashes" : true, "auth" : null, "path" : "xxx", "href" : "xxx" } } ], "mentions" : [ { "_id" : "FSDQcz2Sd2uYPMbCv", "username" : "xxx", "name" : "xxx" } ], "channels" : [ ] } }
```
```
{ "_id" : "CnPwTWhppx28LhECk", "name" : "3dprinting", "t" : "c", "msgs" : 1105, "u" : { "_id" : "GRD6zto8H27QvpWba", "username" : "xxx" }, "ts" : ISODate("2016-12-22T10:48:43.874Z"), "ro" : false, "sysMes" : true, "_updatedAt" : ISODate("2018-12-02T17:58:37.401Z"), "importIds" : [ "C0Y37E2JU" ], "lm" : ISODate("2018-12-02T17:58:37.328Z"), "lastMessage" : { "_id" : "zhRWB8E2EaPzApRMm", "rid" : "CnPwTWhppx28LhECk", "msg" : "xxx", "ts" : ISODate("2018-12-02T17:58:37.328Z"), "alias" : "xxx", "u" : { "_id" : "9psaZv9fcob94rRBW", "username" : "xxx", "name" : "xxx" }, "_updatedAt" : ISODate("2018-12-02T17:58:37.364Z"), "editedBy" : null, "editedAt" : null, "emoji" : null, "avatar" : null, "customFields" : null, "groupable" : null, "attachments" : null, "reactions" : null, "mentions" : [ ], "channels" : [ ], "sandstormSessionId" : null }, "usersCount" : 36 }
```

Maybe a paging issue?

**Comment by soundstorm** [comment]
Had the issue on App Store and TestFlight versions.

**Comment by rafaelks** [comment]
@soundstorm We don't use pagination on the app, it returns everything in one page... do you have custom type of channels?

**Comment by soundstorm** [comment]
Nope, nothing special configured...

**Comment by soundstorm** [comment]
Also weird: in the sharing plugin all channels show up.

**Comment by soundstorm** [comment]
After restart I now don't see any channels before `c`, sometimes they show up again. I'll see if I can investigate via debugger.

**Comment by soundstorm** [comment]
Okay, seems like reinstalling the app did it. Somehow some neccessary updates weren't applied 🤔

**Comment by soundstorm** [comment]
Reinstalling was sadly just atemporary fix.

**Comment by rusty1281** [comment]
Would like to comment on the same matter. server version 0.71 with the latest ios version for the client. 

After some channel search I lose some channels in the main list view. Reset of the client app fixes the problem

**Comment by rafaelks** [comment]
@rusty1281 What are the steps to reproduce? Could you record a video or something of that happening please?

**Comment by rafaelks** [comment]
@rusty1281 Thank you, we'll be investigating the issue! 👍

**Comment by soundstorm** [comment]
Still a bug. But now ordered. So currently 9/67 (+7 favourites) channels are cut off from the list beginning (alphabetical order).
Having them in order by activity makes no difference, which channels are missing, still the first 9 of alphabetical order.

Maybe an allocation problem?

**Comment by soundstorm** [comment]
So the numbers of the missing channels have shifted due to the fact, that now one more channel is favorite.
But it seems like the **magic number per section is 58**, as it is back than and now the same. Searching for this number in the repository gave no useful results.
