### ISSUE TITLE
[BUG] Whitescreen after successful oauth login

### ISSUE THREAD

**Issue by tdihp** [RocketChat/Rocket.Chat.iOS#2407]
> Before writing an issue, please make sure you're talking about the native application (called Rocket.Chat+ in the App Store) and not the Cordova one (called Rocket.Chat in the App Store). If you are looking to open an issue to the Cordova application, go to this URL: https://github.com/RocketChat/Rocket.Chat.Cordova.

The app was called Rocket.Chat in AppStore but the newest version of the app matches this app ;)

- Your Rocket.Chat app version: `3.1.2`
- Your Rocket.Chat server version: `rocket.chat:0.69.1`
- Device (or Simulator) you're running with: IPhone SE (IOS 12.1)

After I resolved websocket issues (normal login works perfectly), the custom oauth provider would give a whitescreen after authentication. 

![image](https://user-images.githubusercontent.com/1396390/49638219-8458d580-fa42-11e8-865c-8314016705cf.png)

I have used mitmproxy to trace the flow:

![rocketchat ios mitmflow](https://user-images.githubusercontent.com/1396390/49638113-3217b480-fa42-11e8-9101-daaf52ebe218.png)

It seems the login worked and a white success screen isn't closed.
The content of the last 200 response was:

```<!DOCTYPE html>
<html>
<body>
  <p id="completedText" style="display:none;">
    Login completed. <a href="#" id="loginCompleted">
      Click here</a> to close this window.
  </p>

  <div id="config" style="display:none;">{"setCredentialToken":false,"storagePrefix":"Meteor.oauth.credentialSecret-","isCordova":true}</div>
  <script type="text/javascript" src="/packages/oauth/end_of_popup_response.js"></script>
</body>
</html>```

**Comment by cardoso** [comment]
Generally, we need access to the server to be able to debug this kind of issue, since every OAuth might work in an arbitrarily different way.

Can you speak to me over at https://open.rocket.chat/direct/matheus.cardoso ?

Questions for you:

- Have you or anyone you know tested on our Android client?
- Can you provide me with a test account to your server for debugging purposes?

**Comment by tdihp** [comment]
UPDATE: After changing OAuth configuration `Login Style` of Rocket.Chat from `Default` to `Redirect`, we can properly see the client logged in now. Now we think it's the popup behavior webkit client didn't cope well.

> Have you or anyone you know tested on our Android client?
We have tested and the Android client also didn't login.

**Comment by cardoso** [comment]
@tdihp thanks for the details. I'm glad you were able to get this to work. I'll pass this problem on to the web team.
