### ISSUE TITLE
[INVESTIGATE] Message font size decreased in version 3.2.0

### ISSUE THREAD

**Issue by guillaumerybak** [RocketChat/Rocket.Chat.iOS#2439]
- Your Rocket.Chat app version: 3.2.0
- Your Rocket.Chat server version: 0.72.3
- Device (or Simulator) you're running with: iPhoneXS Max

Since the last update of the Rocket.Chat iOS app, the font size seems to have decreased and is getting a bit hard to read and does not seem to follow the iOS font size.

**Comment by guillaumerybak** [comment]
I can provide a screenshot if you need :).

**Comment by rafaelks** [comment]
@guillaumerybak Yes, send us a screenshot please!

**Comment by guillaumerybak** [comment]
![img_4764](https://user-images.githubusercontent.com/5887099/50283645-cc222880-0456-11e9-88dc-6bcaf7b87010.png)

**Comment by rafaelks** [comment]
@guillaumerybak What's your configuration of fonts on iOS for accessibility? Are you using a lower font?

**Comment by guillaumerybak** [comment]
I have no accessibility setting enabled, but I have the text size set to minimum my display settings. In the other apps, the font size is roughly the same as the time in the upper left corner in the screenshot.

**Comment by rafaelks** [comment]
@guillaumerybak I assume the font size of Rocket.Chat now is very similar to the font-size in Mail application and Settings, right? That's because of your text size is set to minimum.

**Comment by guillaumerybak** [comment]
No, the font size in the Rocket.Chat app is smaller to the one in Mail.

**Comment by guillaumerybak** [comment]
![img_ef6c3dc96938-1](https://user-images.githubusercontent.com/5887099/50286311-4b1b5f00-045f-11e9-99bf-0de722c96622.jpeg)

**Comment by guillaumerybak** [comment]
You can see the 'a' size in the notification mail from GitHub and in the rocket chat screenshot

**Comment by rafaelks** [comment]
@guillaumerybak Got it! Will investigate the differences, thank you!

**Comment by guillaumerybak** [comment]
If you need to test some settings on my device, don't hesitate :)

**Comment by rafaelks** [comment]
@guillaumerybak Issue is fixed, will be present in our next TestFlight build, if you want to join you can find the link on the readme of the repo, thanks!

**Comment by guillaumerybak** [comment]
Nice ! Thanks for the hard work 👍. I'll join the testflight then :)
