### ISSUE TITLE
[IMPROVEMENT] Send button must be clicked on the actual icon to work

### ISSUE THREAD

**Issue by Justintime50** [RocketChat/Rocket.Chat.iOS#2444]
- Your Rocket.Chat app version: 3.2.0
- Your Rocket.Chat server version: 0.72.3
- Device (or Simulator) you're running with: iPhone Xs

On iOS, you have to select the actual paper airplane icon to send a message (only started happening in the newest version). Essentially the send button became much smaller (functionally) so the user needs to continually smash that button until their finger catches the small portion of the airplane image that's actually shown. Before, even the transparent parts in-between the airplane and surrounding it would allow the user to send the message. This leads to more frustration with sending messages to make sure the actual blue icon is hit and you weren't just hitting that bottom right corner.

**Comment by rafaelks** [comment]
@Justintime50 Thanks for the feedback, we'll be increasing the tap area in future releases. 👍

**Comment by Justintime50** [comment]
It appears this wasn't truly fixed as I still often have to click multiple times on the send button to get the message to send.

**Comment by amoebav** [comment]
@Justintime50 
I'm testing as well and I get the same results. Except this time I've discovered it's because not enough surface contact. The opposite of what you had (too little surface contact).

**Comment by Justintime50** [comment]
Was this ever fixed then? I honestly am not sure at this point if I just go so used to needing to tap all around to get it that I forgot it was even broken or if this was actually fixed and we can close haha.

**Comment by diegolmello** [comment]
Hi, @Justintime50!
This repo is [deprecated](https://github.com/RocketChat/Rocket.Chat.iOS#important---please-read-this-first).
If you're using using the latest version on the store, you're using the [the new app](https://github.com/RocketChat/Rocket.Chat.ReactNative/) built in React Native.
Let me know if this is still an issue though.
Thanks.
