### ISSUE TITLE
[INVESTIGATE] iOS app didn't show picture/file/Katex

### ISSUE THREAD

**Issue by Simon2046** [RocketChat/Rocket.Chat.iOS#2451]
- Your Rocket.Chat app version: 3.2.0（223）
- Your Rocket.Chat server version: 0.72.3
- Device (or Simulator) you're running with: iPhoneX and iPhone 7 plus

Server is OK. I can connect with web browser on windows an Mac.,Desktop APP on  Mac.
Also can connect with iOS app.
But on iOS app:
1. Can't show any picture. Even pictures upload by app itself. Pictures can show on web browser and desktop app.
2. Can't open any file uploaded. Which  can be opened by  web browser and desktop app too.
3. Katex can't explain at app side.

I find that images can show on app Rocket.ChatExperimental. But it was so unstable and functions uncompleted.
Image below for reference 

![img_8316](https://user-images.githubusercontent.com/43597646/50414417-741d6480-0850-11e9-914d-62a57b2c1e69.PNG)

**Comment by rafaelks** [comment]
@Simon2046 Katex is not currently supported on the iOS application. But files and uploads are, let me ask you few info:

- Are you using subpaths on your URL?
- Are you using secure assets (`https://` instead of `http://`)?
- What's the upload type that your server is using?

**Comment by rafaelks** [comment]
@Simon2046 Can you please try this solution and see if upload will work again for you? https://github.com/RocketChat/Rocket.Chat.iOS/issues/2184#issuecomment-423517754

**Comment by Simon2046** [comment]
> @Simon2046 Can you please try this solution and see if upload will work again for you? [#2184 (comment)](https://github.com/RocketChat/Rocket.Chat.iOS/issues/2184#issuecomment-423517754)

Thanks! It works.

**Comment by rafaelks** [comment]
Awesome!
