### ISSUE TITLE
Getting crash in ChannelActionsViewController

### ISSUE THREAD

**Issue by arpitjain03** [RocketChat/Rocket.Chat.iOS#2453]
I am getting crash in following tabs of Actions Screen when there is some data

- Mentions
- Members
- Starred
- Pinned

**Crash reason(same for all):** 

Terminating app due to uncaught exception 'RLMException', reason: 'Attempting to modify object outside of a write transaction - call beginWriteTransaction on an RLMRealm instance first.

**Comment by rafaelks** [comment]
@arpitjain03 What's the version of your app?

**Comment by arpitjain03** [comment]
Hello @rafaelks

**Comment by rafaelks** [comment]
@arpitjain03 From the App Store?

**Comment by rafaelks** [comment]
@arpitjain03 Make sure you update it to latest 3.2.0 (223), this crash is already fixed.

**Comment by arpitjain03** [comment]
Hey, actually I have integrated it in my project, can you tell me what to change?
