### ISSUE TITLE
add function

### ISSUE THREAD

**Issue by 10veMars** [RocketChat/Rocket.Chat.iOS#2456]
- Your Rocket.Chat app version: new version
- Your Rocket.Chat server version: 
- Device (or Simulator) you're running with: simulator

###
Are there no voice calls and video chat functions in the project?

**Comment by Simon2046** [comment]
I think it has Video conference function. You can find at MANAGEMENT item.
 I'm not use it yet. I hope someone can tell me the experience of this function.  :-P

**Comment by rafaelks** [comment]
@10veMars Currently in development: https://github.com/RocketChat/Rocket.Chat.iOS/pull/2450.
