### ISSUE TITLE
[BUG] Different fonts on default profile images

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat.iOS#2463]
On regular desktop session they show up the same.
![GitHawk Upload by soundstorm](https://i.imgur.com/yQzFACe.jpg)

**Comment by coruble** [comment]
@soundstorm Same serif font here both on iOS and Android, they appeared tight after I upgraded my server to 0.73.1. Probably not an iOS issue, let's file one on https://github.com/RocketChat/Rocket.Chat/ ?

**Comment by soundstorm** [comment]
Ah, okay, maybe on desktop cached.
