### ISSUE TITLE
[BUG] Read receipts aren't shown since 3.2.0

### ISSUE THREAD

**Issue by coruble** [RocketChat/Rocket.Chat.iOS#2464]
Title should be pretty self-explanatory, since version 3.2.0 (installed from App Store or compiled on Xcode doesn't matter), read receipts aren't shown in chats anymore. Self-hosted Rocket.Chat. Tried to upgrade the server to the latest version and verified settings, but no success. Any idea @rafaelks ? Thanks !

- Rocket.Chat app version : 3.2.0
- Rocket.Chat server version : 0.73.1
- Device : iPhone X, iOS 12.1.2

**Comment by coruble** [comment]
Hey Rocket.Chat team, just to bump this issue : is there supposed to be support for read receipts in this version ? I don't understand why they vanished. Anything I can do to help ? Thanks !

**Comment by rafaelks** [comment]
@coruble Yes, it was suppose to be working, but I'm going to investigate your report and if there's actually a bug we'll be sending a fix for that on next release. 👍
