### ISSUE TITLE
[QUESTION] Push notifications not working when click on Send Test Push

### ISSUE THREAD

**Issue by arpitjain03** [RocketChat/Rocket.Chat.iOS#2465]
- Rocket.Chat app version: 3.2.0 (223)
- Rocket.Chat server version: 0.72.3  
- Device h: iPhone 7/iOS 12.1

I have done all the setup mentioned in below link.
[https://rocket.chat/docs/administrator-guides/notifications/push-notifications]

But everytime I click on Send a test Push I got error saying
**There are no tokens for this user**

Also I have checked View Logs while logging in to app all the 

`Push: updated { _id: 'DE108A429D2240AFB934752EFD59C967',   token:     { apn: '9aa052714fd2a0e413f754b9b193ff9dd5837368b53e0c9c362ba4958aca0f95' },   appName: 'com.resellcalendar',   userId: 'eiBnnCawfhfpBxKFD',   enabled: true,   createdAt: 2018-12-31T09:18:17.950Z,   updatedAt: 2018-12-31T09:48:18.825Z } `

All the data seems to be send properly.

**Note:** I am checking with my server

**Comment by rafaelks** [comment]
@arpitjain03 

1. Are you using our gateway?
2. Are you using the app from the App Store?

**Comment by arpitjain03** [comment]
No I am not using your gateway I am using my server

**Comment by rafaelks** [comment]
@arpitjain03 If you're not using our gateway to send pushes, you need to have your own application for iOS (fork) because of the keys to send pushes. Make sure you've your setup correct and try again, please. In the meantime, I'm closing the issue.

**Comment by arpitjain03** [comment]
I have my application as well I have tried with both. Also, I have added proper Certificate and Private Key. Finding no push notification coming out while mentioning users or by sending a test push

**Comment by rafaelks** [comment]
@arpitjain03 Something in your setup is missing... are tokens being registered on the server? Is the app making the requests? What's the branch you're using in your fork?

**Comment by arpitjain03** [comment]
Yes, tokens are being registered on the server. The same I have shared log I have shared above. Yes the app is making proper requests as I have achieved everything in the chat, the only point is with Push notification.

**Comment by rafaelks** [comment]
@arpitjain03 Is your server sending the notification to Apple using your keys? Are you using production release or debug?

**Comment by arpitjain03** [comment]
I am using debug release.

**Comment by rafaelks** [comment]
Looks like something is wrong in your back-end setup.

**Comment by arpitjain03** [comment]
Is there anything specific related with Push notification needed to be done while server setup, as i am able to send and receive messages from server properly

**Comment by GoetheG** [comment]
Why is this push thing that complicated at all? How is a normal user supposed to set this up?

**Comment by atorscho** [comment]
Me too I've had problems with Rocket Chat's notifications since 6 months now. I could not get my iPhone's push notifications to work and now desktop's notifications do not work either.

**Comment by oemb1905** [comment]
same issue ... no notifications on desktop or on app
