### ISSUE TITLE
Server returned error when I try to upload image.

### ISSUE THREAD

**Issue by gradler** [RocketChat/Rocket.Chat.iOS#248]
Your Rocket.Chat version: 0.50.1 (My Own Server)

When I trying to upload image, the server returns the following logs:
2017-02-07 11:00:04.925787 Rocket.Chat[549:201116] [Generic] Creating an image format with an unknown type is an error
Socket will send message: {
  "method" : "slingshot\/uploadRequest",
  "id" : "KDoXgRn3IMYVVzVDPFvjy0LwFbEKdTeIybXVxrlO2YfwkXTNuL",
  "params" : [
    "rocketchat-uploads",
    {
      "type" : "image\/jpeg",
      "name" : "IMG_0002.JPG",
      "size" : 347571
    },
    {
      "rid" : "bpz8hgJq5SS3p9yPacmgXMpDWsB8YAHGk9"
    }
  ],
  "msg" : "method"
}
[WebSocket] did receive JSON message: {
  "methods" : [
    "KDoXgRn3IMYVVzVDPFvjy0LwFbEKdTeIybXVxrlO2YfwkXTNuL"
  ],
  "msg" : "updated"
}
[WebSocket] did receive JSON message: {
  "id" : "KDoXgRn3IMYVVzVDPFvjy0LwFbEKdTeIybXVxrlO2YfwkXTNuL",
  "error" : {
    "message" : "The directive rocketchat-uploads does not seem to exist [Invalid directive]",
    "reason" : "The directive rocketchat-uploads does not seem to exist",
    "error" : "Invalid directive",
    "errorType" : "Meteor.Error"
  },
  "msg" : "result"
}

However, on Android, images are uploaded normally.
When I look at the Android source, they try to upload it separately according to whether storage_type is Amazon S3, GridFS or FileSystem. I think we seems to need that.

**Comment by rafaelks** [comment]
@gradler Hey, thanks for your report. Do you know what type does your server support? On iOS we're currently only supporting Amazon S3.

**Comment by gradler** [comment]
@rafaelks The type supported by our server is GridFS.

**Comment by rafaelks** [comment]
@gradler OK, cool... I already created the issues to support GridFS (#256) and FileSystem (#257). Thank you! 👍
