### ISSUE TITLE
Push notifications not working with Rocket Chat in my application

### ISSUE THREAD

**Issue by arpitjain03** [RocketChat/Rocket.Chat.iOS#2480]
Rocket.Chat app version: 3.2.0 (223)
Rocket.Chat server version: 0.72.3  
Device h: iPhone 7/iOS 12.1

I have successfully implemented Rocket Chat in my application by using the Rocket Chat iOS repository classes.

I have done all the setup mentioned in below link.
[https://rocket.chat/docs/administrator-guides/notifications/push-notifications]

But every time I click on Send a test Push I got an error saying
There are no tokens for this user
Also, I have tried with mentioning users in the application, but no push notification arrives.

I have tested my push notifications certificate and private key they are appropriate

Also, I have checked View Logs while logging in to rocket chat using my app all the

Push: updated { _id: 'DE108A429D2240AFB934752EFD59C967', token: { apn: '9aa052714fd2a0e413f754b9b193ff9dd5837368b53e0c9c362ba4958aca0f95' }, appName: 'com.resellcalendar', userId: 'eiBnnCawfhfpBxKFD', enabled: true, createdAt: 2018-12-31T09:18:17.950Z, updatedAt: 2018-12-31T09:48:18.825Z }

All the data seems to be sent properly.

Note: I am checking with my server

**Comment by rafaelks** [comment]
@arpitjain03 Please don't duplicate your own issue #2465, let's continue the discussion over there so we can help you.
