### ISSUE TITLE
Build and simulator works no errors.Click archive and errors out

### ISSUE THREAD

**Issue by S0U1SB4N3** [RocketChat/Rocket.Chat.iOS#2486]
- Your Rocket.Chat app version: 3.3.0
- Your Rocket.Chat server version: ####
- Device (or Simulator) you're running with: iOS

I can build the project and load to the native simulator on MacBook Pro in Xcode 10 
I can test the build on directly connected devices successfully, however when I need to click archive to upload to App Store it errors out as shown below 

<img width="456" alt="screen shot 2019-01-10 at 1 01 20 pm" src="https://user-images.githubusercontent.com/22788570/50990938-125c2c00-14d9-11e9-85c5-446e0ee4cf96.png">

**Comment by coruble** [comment]
Hi @S0U1SB4N3, the error output points to DifferenceKit, did you properly `pod install` and / or `pod update` ? Also, you say you're trying to compile 3.3.0, which is in development and unreleased. If you want to compile and run something stable, maybe you should work on the 3.2.0 source code

**Comment by rafaelks** [comment]
@S0U1SB4N3 This is a bug in CocoaPods (they still didn't ship the fix), because we've a reference for DifferenceKit in two places... in order to fix that, you'll need to change your **Workspace Settings** to use the Legacy Build System, like the screenshot. That needs to be done only for Archiving.

![screen shot 2019-01-11 at 09 41 48](https://user-images.githubusercontent.com/551004/51031882-2a898500-1585-11e9-85dd-26c3e5da0c16.png)

**Comment by S0U1SB4N3** [comment]
yes with error stating there are two Differencekit.Framework trying to be written. Differencekit and difference kit-core 

Im in legacy as well and still errors 

I will try again in a few hours

**Comment by y0unghe** [comment]
> @S0U1SB4N3 This is a bug in CocoaPods (they still didn't ship the fix), because we've a reference for DifferenceKit in two places... in order to fix that, you'll need to change your **Workspace Settings** to use the Legacy Build System, like the screenshot. That needs to be done only for Archiving.
> 
> ![screen shot 2019-01-11 at 09 41 48](https://user-images.githubusercontent.com/551004/51031882-2a898500-1585-11e9-85dd-26c3e5da0c16.png)

Select Legacy Build did work, but the messages list view is completed messed up. Run app directly from Xcode is working fine.
![image](https://user-images.githubusercontent.com/1100727/60752495-1f298a80-9ff9-11e9-8001-c6e162791d96.png)

**Comment by BeatriceFeltre** [comment]
> > @S0U1SB4N3 This is a bug in CocoaPods (they still didn't ship the fix), because we've a reference for DifferenceKit in two places... in order to fix that, you'll need to change your **Workspace Settings** to use the Legacy Build System, like the screenshot. That needs to be done only for Archiving.
> > ![screen shot 2019-01-11 at 09 41 48](https://user-images.githubusercontent.com/551004/51031882-2a898500-1585-11e9-85dd-26c3e5da0c16.png)
> 
> Select Legacy Build did work, but the messages list view is completed messed up. Run app directly from Xcode is working fine.
> ![image](https://user-images.githubusercontent.com/1100727/60752495-1f298a80-9ff9-11e9-8001-c6e162791d96.png)


I have the same problem. How can I solve it?
