### ISSUE TITLE
Graphic error in the login screen

### ISSUE THREAD

**Issue by drego85** [RocketChat/Rocket.Chat.iOS#2499]
- Your Rocket.Chat app version: 3.2.0
- Your Rocket.Chat server version: I'm using your demo server
- Device (or Simulator) you're running with: iPhone SE - iPad Air 2 - iPad Mini 4

Hello,
I wanted to tell you a graphic bug in the login screen on iOS.

I am attaching an explanatory screenshot.

Andrea

**Comment by drego85** [comment]
Screenshot: https://cloud.draghetti.it/owncloud/index.php/s/3WxUWcsfkZ3vKFO

**Comment by rafaelks** [comment]
@drego85 Sounds good, just fixed it in https://github.com/RocketChat/Rocket.Chat.iOS/commit/229c5446c8e7de5ac2773ab0e51558801c790782. 👍
