### ISSUE TITLE
[BUG] Forgot Password button is invisible but active.

### ISSUE THREAD

**Issue by yugantarjain** [RocketChat/Rocket.Chat.iOS#2505]
- Your Rocket.Chat app version: 3.2.0
- Your Rocket.Chat server version: 0.74.0
- Device (or Simulator) you're running with: iPhone 7(Device & Simulator both)

In 'Login Table View Controller', the 'Forgot Your Password' button is invisible to the user while actually being active i.e. by clicking on the empty space below the 'LOGIN' button the forgot your password UI shows up.

Steps to reproduce-
1. Open application, log out if logged in.
2. Click on 'Join the Community' button on the initial screen.
3. Click on Login with Email.
4. The space below LOGIN button is empty, but clicking on this empty space brings up the forgot your password UI.

**Comment by promehul** [comment]
@rafaelks we want to keep this feature right? If yes then why is it hidden in the first place?
