### ISSUE TITLE
[BUG] Server can be lost from DatabaseManager.servers

### ISSUE THREAD

**Issue by luismachado** [RocketChat/Rocket.Chat.iOS#2515]
During the authentication process, there are some instances where the server can be lost from the server list before the login finishes.

Flow: 'Join the community' on auth flow. 

If the server replies fast enough (before `viewDidAppear` is called on `ConnectServerViewController.swift`) this will happen:

1) `createNewDatabaseInstance` is called
2) viewDidAppear on ConnectServerViewController is called which will fire `DatabaseManager.cleanInvalidDatabases()` which will remove the server as it still doesn't has any auth information
3) By the time the user logs in (the login works) the server isn't anymore on the server list. This affects changing between servers and also any external sharing functionality.

One solution would be to move these two lines

`SocketManager.sharedInstance.socket?.disconnect()
DatabaseManager.cleanInvalidDatabases()`

to `viewDidLoad`, before the `connect` if.

**Comment by rafaelks** [comment]
@luismachado Thank you for the investigation; I'll take a look at this soon. 👍
