### ISSUE TITLE
Create new Dm doesn't work on IOS APP

### ISSUE THREAD

**Issue by tavakoli-ali** [RocketChat/Rocket.Chat.iOS#2518]
- Your Rocket.Chat app version: 3.3.0
- Your Rocket.Chat server version: 0.73.2
- Device (or Simulator) you're running with:iPhone 7plus (iOS 12.1), iPhone SE (iOS 12.1, Simulator

when search user for new and first message , chat page shows up by last conversation opened .
and every message send in new chat immediately delete. 

this problem exists on Android and I fix it by function : update Realm .
but in iOS still have problem .

**Comment by rafaelks** [comment]
@tavakoli-ali To start a new DM right now you need to search for the user and just start the conversation. In future releases we'll be working on Directory support: https://github.com/RocketChat/Rocket.Chat.iOS/issues/2290.

**Comment by tavakoli-ali** [comment]
But right now it doesn't work. 
When user search someone for new DM conversation didn't create a new private message in Apps. In Android, we find the problem because of function updating Realm in the app. 
But in IOS it has some complexity.

**Comment by pego** [comment]
@rafaelks I have the same issue, on iOS it's impossibile to create direct messages to users I never created direct messages before.

**Comment by rafaelks** [comment]
This is fixed in 3.3.1, please check our TestFlight for the new version (coming soon) and will be available in the store later this week or early next week.

**Comment by tavakoli-ali** [comment]
is it fixed in new release code ?

**Comment by rafaelks** [comment]
@tavakoli-ali This fix is already in the App Store, version 3.3.1. 👍

**Comment by tavakoli-ali** [comment]
release code ???

**Comment by rafaelks** [comment]
@tavakoli-ali Not sure I understood your question...

**Comment by tavakoli-ali** [comment]
thanks 👍
when it's dow let me know

**Comment by rafaelks** [comment]
@tavakoli-ali The code is already merged, if that was your question. Check branch `master`.

**Comment by tavakoli-ali** [comment]
thanks
