### ISSUE TITLE
Use the Rocket.chat with another server, instead of open.rocket.chat

### ISSUE THREAD

**Issue by rtizi** [RocketChat/Rocket.Chat.iOS#2519]
- Your Rocket.Chat app version: ####
- Your Rocket.Chat server version: ####
- Device (or Simulator) you're running with: ####

We want to use the Rocket.chat with our own server instead of open.rocket.chat. What action plan should we make. Thanks:)

**Comment by rafaelks** [comment]
@rtizi What do you mean? You just need to connect into another URL when the application opens. 🤔
