### ISSUE TITLE
Good day! Is it possible to forward messages between conversations? Thank you

### ISSUE THREAD

**Issue by rtizi** [RocketChat/Rocket.Chat.iOS#2528]
- Your Rocket.Chat app version: ####
- Your Rocket.Chat server version: ####
- Device (or Simulator) you're running with: ####

**The app isn't connecting to your server?**
Make sure your server supports WebSocket. These are the minimum requirements for Apache 2.4 and Nginx 1.3 or greater.

**Comment by rafaelks** [comment]
@rtizi Right now, you can long press the message and tap "Copy Hyperlink" to copy a message to another channel.
