### ISSUE TITLE
Can't upload photos

### ISSUE THREAD

**Issue by dfreddie** [RocketChat/Rocket.Chat.iOS#2529]
- My Rocket.Chat app version: 3.2.0
- My Rocket.Chat server version: 0.74.1

Hi, it seems with version 0.74.0 I cannot upload images (I've tried only with .jpeg files). Pdf's and docs works fine. Same result with iPhone X, iPhone 7 and iPhone 5S.

**Comment by dfreddie** [comment]
Yes is a premise install. I've set -1 as file size. And more from web or desktop it works with no problem!

**Comment by rafaelks** [comment]
@dfreddie Have you checked this thread? https://github.com/RocketChat/Rocket.Chat.iOS/issues/2184#issuecomment-423517754

**Comment by dfreddie** [comment]
> @dfreddie Have you checked this thread? [#2184 (comment)](https://github.com/RocketChat/Rocket.Chat.iOS/issues/2184#issuecomment-423517754)

Thank you very much!!!
