### ISSUE TITLE
[IMPROVEMENT] Auto suggesting slash commands even when not first character

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat.iOS#2530]
- Your Rocket.Chat app version: latest from test flight (234)
- Your Rocket.Chat server version: open
- Device (or Simulator) you're running with: xs

Seems to pop autocomplete even when typing / other places in the messages.  Kind of misleading since won’t work there

**Comment by blewjy** [comment]
Will take on this issue over the weekend 👍

**Comment by blewjy** [comment]
I might need a little help here... I can't seem to find the code that is responsible for listening to the `textView` text changes and showing/hiding the suggestions. Anyone has any idea?

**Comment by snuff4** [comment]
Hey @blewjy I think in the `MessagesViewControllerComposerDelegate.swift`, there is a function `hintsView`. That should help.

**Comment by snuff4** [comment]
Hi @blewjy, were you able to solve it?

**Comment by blewjy** [comment]
Hey @snuff4, unfortunately no. Setting breakpoints at the hintsView function didn’t help either...

If you want to take on this issue, you can go ahead

**Comment by rafaelks** [comment]
@blewjy I believe you will need to check the code inside our SDK: https://github.com/RocketChat/RocketChatViewController/.

Do you want to continue working on that?

**Comment by blewjy** [comment]
@rafaelks I think I managed to find a solution! PR soon!
