### ISSUE TITLE
size of send button in mobile ios client

### ISSUE THREAD

**Issue by Shaverdoff** [RocketChat/Rocket.Chat.iOS#2531]
- Your Rocket.Chat app version: 320 (223)
- Your Rocket.Chat server version: 074
- Device (or Simulator) you're running with: iPhoneX 12.1.3

i think this is no issues as well, this is maybe were features request

Button "send" in chat windows bacame very small after update client to 3.2.0 version.
maybe make a cicrle around the airplane icon of send button like in over messangers - whatsup,viber,skype?
Problem is - Hard to correct tap on that small button. sometimes have to tap several times until you hit the send button

**Comment by rafaelks** [comment]
Duplicates #2444
