### ISSUE TITLE
Deleted messages are displayed in the mobile application, there is no synchronization.

### ISSUE THREAD

**Issue by sharkmax88** [RocketChat/Rocket.Chat.iOS#2537]
- Your Rocket.Chat app version: ####
- Your Rocket.Chat server version: ####
- Device (or Simulator) you're running with: ####

**The app isn't connecting to your server?**
Make sure your server supports WebSocket. These are the minimum requirements for Apache 2.4 and Nginx 1.3 or greater.

**Comment by rafaelks** [comment]
Duplicates #2208
