### ISSUE TITLE
[NEW] Avatars aren't loaded if unauthenticated access to avatars is disabled.

### ISSUE THREAD

**Issue by davidlougheed** [RocketChat/Rocket.Chat.iOS#2540]
- Your Rocket.Chat app version: 3.3.0
- Your Rocket.Chat server version: 0.74.0
- Device (or Simulator) you're running with: iPhone 8

The server provides a setting to disable unauthenticated access to avatars. If this is enabled, avatars are not loaded by the iOS app (see https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/603 and https://github.com/RocketChat/Rocket.Chat.Android/issues/1749 )

I'm working on a fix for the React Native client (see https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/604 ) but it would be nice to see the same fixes in the other apps.

To fix this, pass `rc_token` and `rc_uid` as URL params when fetching the avatar via URL.

**Comment by davidlougheed** [comment]
@rafaelks this works for users but not channel icons (same problem, same endpoint as far as I know) in the latest dev build, so it's not fully fixed

**Comment by rafaelks** [comment]
@davidlougheed True, it needs to be fixed for channels as well 👍

**Comment by rafaelks** [comment]
@davidlougheed Fixed here: https://github.com/RocketChat/Rocket.Chat.iOS/pull/2620
