### ISSUE TITLE
[INVESTIGATE] Images not loading anymore

### ISSUE THREAD

**Issue by guillaumerybak** [RocketChat/Rocket.Chat.iOS#2541]
- Your Rocket.Chat app version: 3.3.0
- Your Rocket.Chat server version: 0.74.0
- Device (or Simulator) you're running with: iPhone XS Max

Since the last iOS app update, all of the images (images uploads in channels, user uploaded avatars, ...) are not downloaded/rendered anymore. In channels, we got blank placeholders and the user avatars seem to fall back to the default generated ones using the username. It works fine on the webapp and worked fine in 3.2.0 so it's most likely a regression introduced in the latest version. I compiled the app and launched it in XCode but didn't see any error in the console. The only exotic thing about my rocket chat setup is that the ROOT_URL configures is on a subpath of the server (ex: awsom.tld/rocketchat). Sorry, I could get more informations than that. I'm at your disposal if you need extra logs, screenshots or others.

**Comment by tmbiOS** [comment]
Also I can’t send message to founded user ( message and subscription don’t save). (Version 3.3.0)

**Comment by rafaelks** [comment]
@guillaumerybak Did you also updated your server version?

**Comment by guillaumerybak** [comment]
No, i left it in 0.74.0, not the latest 0.74.2. Is it a requirement ?

**Comment by rafaelks** [comment]
@guillaumerybak It's not... it doesn't load any asset or just some of the assets? Does it load avatars?

**Comment by guillaumerybak** [comment]
It doesn't seem to work for any asset: avatars, room icons, user uploads (I tried images & a zip file)

**Comment by rafaelks** [comment]
@guillaumerybak Can you check your `Site_Url` setting and `CDN_URL`? If that's correct, can you talk to me in `open.rocket.chat (rafael.kellermann)` so we can investigate the problem?

**Comment by tmbiOS** [comment]
> Also I can’t send message to founded user ( message and subscription don’t save). (Version 3.3.0)

@rafaelks Pls, check this too.

**Comment by guillaumerybak** [comment]
These haven't changed since the last update and seem correct: no CDN_URL specified and the site_url set to the usual value.
I compiled the app yesterday and tried on my server the 3.3.0 and the 3.2.0 using the iOS simulator. The 3.2.0 works but the 3.3.0 doesn't, on the same server with the same settings, which led me to thing this was a regression. Sorry I wasn't more clear in the description. I'll come find you on open.rocket.chat :)

**Comment by guillaumerybak** [comment]
Ok, turns out it's a configuration issue on the server. By default the settings in:
- General > Rest API > Default Count is set to 50, it needs to be set to unlimited (0)
- General > Rest API > Allow Getting Everything is set to False, it needs to be set to True

Thanks @rafaelks for the help :)
