### ISSUE TITLE
[BUG] Can't start new direct message

### ISSUE THREAD

**Issue by tmbiOS** [RocketChat/Rocket.Chat.iOS#2544]
- Your Rocket.Chat app version: 3.3.0
- Your Rocket.Chat server version: open.chat
- Device (or Simulator) you're running with: device 

I installed the app from appstore and I can't start a new direct message.
(subscription rid doesn't send to Messages view controller because it's nil).
Pls check. it should be a hotfix. I
n version 3.2.0 everything works fine.
![img_7114](https://user-images.githubusercontent.com/37933181/52618739-b1958a00-2eb0-11e9-8238-f5cb1574aa21.PNG)

**Comment by rafaelks** [comment]
This is being fixed as a hot fix for 3.3.1. 👍

**Comment by rafaelks** [comment]
I'll be sending a fix to TestFlight soon, please join here to see if that works for you guys: https://testflight.apple.com/join/3gcYeoMr.
