### ISSUE TITLE
[QUESTION] Push Notifications

### ISSUE THREAD

**Issue by rtizi** [RocketChat/Rocket.Chat.iOS#2545]
How to enable push notifications for another server, download a project from a beta branch and it looks like just creating certificates and connecting insufficiently, nothing works, what changes do you need to make a project besides that? Thank

- Your Rocket.Chat app version: ####
- Your Rocket.Chat server version: ####
- Device (or Simulator) you're running with: ####

**The app isn't connecting to your server?**
Make sure your server supports WebSocket. These are the minimum requirements for Apache 2.4 and Nginx 1.3 or greater.

**Comment by rtizi** [comment]
And how did you solve the problem with the global shutdown of push notifications? I wanted to create a switch in the settings, for example, to enable and disable. Big thanks to everyone

**Comment by rafaelks** [comment]
@rtizi You question is very confusing... you want to have your own server of push notification?

**Comment by RishatYakushev** [comment]
@rafaelks Yes, exactly, thanks for the clarification, do you need to follow this instruction https://github.com/raix/push/blob/v3.x/docs/IOS.md? And do I need to make any settings on the server?

**Comment by rtizi** [comment]
@rafaelks Which fields are required in /admin/Push and what to insert in the field with the APN certificate?

**Comment by rtizi** [comment]
@rafaelks Yes, exactly, thanks for the clarification, do you need to follow this instruction https://github.com/raix/push/blob/v3.x/docs/IOS.md? And do I need to make any settings on the server?

**Comment by RishatYakushev** [comment]
@rafaelks Look here please:)

**Comment by rtizi** [comment]
@rafaelks Look here please:)

**Comment by rafaelks** [comment]
@rtizi Please use our forums for this type of question: https://forums.rocket.chat/c/community-support.

Thank you!

**Comment by rtizi** [comment]
@rafaelks check please;) https://forums.rocket.chat/t/push-notification-implementation/3138
