### ISSUE TITLE
Push Notifications

### ISSUE THREAD

**Issue by rtizi** [RocketChat/Rocket.Chat.iOS#2556]
- Your Rocket.Chat app version: ####
- Your Rocket.Chat server version: ####
- Device (or Simulator) you're running with: ####

**The app isn't connecting to your server?**
Make sure your server supports WebSocket. These are the minimum requirements for Apache 2.4 and Nginx 1.3 or greater.

@rafaelks check please;) https://forums.rocket.chat/t/push-notification-implementation/3138
We buy your services, be more responsive
Thank you!

**Comment by rafaelks** [comment]
@rtizi Paying customers can use our official support channel (paid): https://support.rocket.chat. Have you tried that?

Let's keep the conversation on the forums please. Thank you!
