### ISSUE TITLE
[BUG] Images not shown since 3.3.0 release

### ISSUE THREAD

**Issue by si90** [RocketChat/Rocket.Chat.iOS#2557]
The app doesn't show images anymore since the 3.3.0 release.
This includes uploaded Images and Avatars. 

- Your Rocket.Chat app version: 3.3.1
- Your Rocket.Chat server version: 0.74.2
- Device (or Simulator) you're running with: Iphone 6

![19-02-15 18-00-43 2943](https://user-images.githubusercontent.com/19840670/52872278-5ed7fe80-314c-11e9-85e5-0324fc2300a5.png)

**Comment by rafaelks** [comment]
@si90 Have you checked the solution on this issue already? https://github.com/RocketChat/Rocket.Chat.iOS/issues/2541#issuecomment-462798292

**Comment by BobWs** [comment]
Having the same problem. Already tried this solution General > Rest API > Allow Getting Everything is set to False, it needs to be set to True
Still not showing pictures. 
iOS app version 3.5.2 (262)
Server version 2.2.0 on docker Synology 

Any suggestions on how to fix this?

**Comment by reetp** [comment]
Note this is actually closed.

You should try the React Native 'Experimental' version.

https://rocket.chat/2019/10/11/moving-mobile-apps-to-react/
