### ISSUE TITLE
Is it possible to extract SDK to be able integrate list of channels and chats into other app?

### ISSUE THREAD

**Issue by sergiorykov** [RocketChat/Rocket.Chat.iOS#2562]
As far as I understand there is separate repository RocketChat/RocketChatViewController to integrate view with concrete chat inside other application. Am I rigth that this view is supposed to show any kind of discussions (1-1, private group, channel)? And take care of all the staff with WebSocket connections?

**Comment by rafaelks** [comment]
@sergiorykov That's correct, we have an SDK to display the messages and the composer, but we currently don't have a modular way to only use the API requests or WebSocket connection, unfortunately.
