### ISSUE TITLE
Build error in xcode 10.1 - zh-Hant.lproj

### ISSUE THREAD

**Issue by myulz** [RocketChat/Rocket.Chat.iOS#2594]
- Your Rocket.Chat app version: 3.3.1
- Device (or Simulator) you're running with: iPhone 8 Simulator in Xcode 10.1

I cloned the repo, ran pod install, and tried to run from xcode but am running into this error:
`Error Group /../Rocket.Chat.iOS/Rocket.Chat/Resources/zh-Hant.lproj/Localizable.strings:514: [Missing] "directory.users.1_user" missing form ZH-HANT file /../Rocket.Chat.iOS/Rocket.Chat/Resources/zh-Hant.lproj/Localizable.strings:508: 
[Missing] "directory.title" missing form ZH-HANT file /../Rocket.Chat.iOS/Rocket.Chat/Resources/zh-Hant.lproj/Localizable.strings:510: 
[Missing] "directory.filters.users" missing form ZH-HANT file /../Rocket.Chat.iOS/Rocket.Chat/Resources/zh-Hant.lproj/Localizable.strings:512: 
[Missing] "directory.filters.global.title" missing form ZH-HANT file /../Rocket.Chat.iOS/Rocket.Chat/Resources/zh-Hant.lproj/Localizable.strings:509: 
[Missing] "directory.filters.channels" missing form ZH-HANT file /../Rocket.Chat.iOS/Rocket.Chat/Resources/zh-Hant.lproj/Localizable.strings:511: 
[Missing] "directory.filters.by" missing form ZH-HANT file /../Rocket.Chat.iOS/Rocket.Chat/Resources/zh-Hant.lproj/Localizable.strings:515: 
[Missing] "directory.users.x_users" missing form ZH-HANT file /../Rocket.Chat.iOS/Rocket.Chat/Resources/zh-Hant.lproj/Localizable.strings:513: 
[Missing] "directory.filters.global.subtitle" missing form ZH-HANT file`

Am I doing something wrong?

**Comment by rafaelks** [comment]
@myulz Are you updated with `develop` branch?

**Comment by myulz** [comment]
> @myulz Are you updated with `develop` branch?
:o I had just cloned the repo last night, but i just git pulled again and this problem is fixed! Thank you!!
