### ISSUE TITLE
Persistent Storage

### ISSUE THREAD

**Issue by gsaslis** [RocketChat/Rocket.Chat.iOS#26]
Add persistance storage to application. Either CoreData or SQLite

- [ ] Check CoreData vs SQLite
- [ ] Choose CoreData or SQLite
- [ ] Create prototype to store login credentials
- [ ] Expand Usage - Create appropriate data model and helpers

**Comment by filipealva** [comment]
@gsaslis What do you think about [Realm](https://realm.io/)? I'm starting with Realm on a project and I'm enjoying it. Maybe would be nice to check CoreData vs SQLite vs Realm.

**Comment by gsaslis** [comment]
@filipealva thanks for the suggestions, as well as the blog post! I haven't really looked into Core Data (@greenman18523 has) and I am not really sure what data we will have to persist locally (should we setup a call to discuss about that some time?) but....
I'm sold! :+1:  ; )

**Comment by filipealva** [comment]
@gsaslis I feel happy that you liked it. About the call: I'm just starting to explore the project, don't know if I can contribute too much, but I think we can call the other guys to contribute with this topic (@rafaelks would you like to give your 2cents here?), and after discussing a little here, if necessary, we can schedule a call to decide some details. 

What other kind of data (besides the messages) do you think that we will need to persist?

**Comment by rafaelks** [comment]
@filipealva Thanks your suggestion!

But, I think we really don't need to persist anything right now. I'm fine in just showing data downloaded from web services, just like desktop and web application does. There's no need to create complexity using some database in the app right now.

We really need to focus on getting/sending data via DDP before start thinking in persisting data. That's my opinion.

**Comment by gsaslis** [comment]
FYI - i've already began working on the interconnection with the server through ddp.

**Comment by filipealva** [comment]
@gsaslis @rafaelks totally agree!

When I commented here I was just browsing the issues, trying to get "synchronized" with the project.

**Comment by rafaelks** [comment]
@gsaslis @filipealva For sure! In the future we certainly can persist data to offline access and a better user experience. :+1:
