### ISSUE TITLE
Can't uninstall Rocket Chat app properly.

### ISSUE THREAD

**Issue by devpool007** [RocketChat/Rocket.Chat.iOS#2606]
- Your Rocket.Chat app version:3.3.1
- Your Rocket.Chat server version: ####
- Device (or Simulator) you're running with: iPhone 7

As you can see it is coming like this after I tried it unistalling it and Even after uninstallig it again it disappears from the home screen but can be seen in the Settings

![](http://www.simpleimageresizer.com/_uploads/photos/3e857ab4/IMG_4896_50.png)

See here it is still in settings after uninstalling , and when I go to app store it shows option to open Rocket chat but it doesn't open,  can someone see to this?

![](http://www.simpleimageresizer.com/_uploads/photos/3e857ab4/IMG_4895_50.png)

**Comment by rafaelks** [comment]
@devpool007 Are you sure you're not running two difference instances of Rocket.Chat? Do you have Jailbreak?

**Comment by devpool007** [comment]
> @devpool007 Are you sure you're not running two difference instances of Rocket.Chat? Do you have Jailbreak?

No I don't have jailbreak and I don't think so I am running two instances of Rocket.Chat
