### ISSUE TITLE
[INVESTIGATE] Uploading doesn't work after taking a photo

### ISSUE THREAD

**Issue by SV8** [RocketChat/Rocket.Chat.iOS#2607]
- Your Rocket.Chat app version: 3.3.1 
- Your Rocket.Chat server version: 1.0.0-develop
- Device (or Simulator) you're running with: iPhone XS Max, iOS 12.1.4

**uploading doesn't work after taking a photo**
On my iPhone XS Max, uploading a photo doesn't work. Every step seems fine but the image couldn't be uploaded in the end.

**Comment by SV8** [comment]
![1](https://user-images.githubusercontent.com/5517286/54889682-d2ee8a80-4ee0-11e9-9cd6-9b75a8a2b0d7.jpg)
![2](https://user-images.githubusercontent.com/5517286/54889686-d71aa800-4ee0-11e9-9198-2af812a68118.jpg)
![3](https://user-images.githubusercontent.com/5517286/54889691-dbdf5c00-4ee0-11e9-86a9-b5f5dc2a3312.jpg)

No photo uploaded in the end with steps done above.

**Comment by rafaelks** [comment]
@SV8 Does it work when selecting it from Library?

**Comment by SV8** [comment]
> @SV8 Does it work when selecting it from Library?
Selecting from Library also doesn't work, if I pick the photo taken by camera before. The photo is about 4 MB size. 
Then I tried to upload a much smaller picture (200 KB) from Library and it works really well. So this issue seems related to image size.

**Comment by SV8** [comment]
@rafaelks Thank u for reply.
Selecting from Library also doesn't work, if I pick the photo taken by camera before. The photo is about 4 MB size.
Then I tried to upload a much smaller picture (200 KB) from Library and it works really well. So this issue seems related to image size.

**Comment by SV8** [comment]
@rafaelks Thank u for reply.
Selecting from Library also doesn't work if I picked a photo taken by camera before. The photo size is about 4 MB.
Then I tried to upload a much smaller picture (200 KB) from Library and it works really well. So this issue seems some how related to image size.

**Comment by SV8** [comment]
Selecting from Library also doesn't work if I picked a photo taken by camera before. The photo size is about 4 MB. Then I tried to upload a much smaller picture (200 KB) from Library and it works really well.

**Comment by SV8** [comment]
Selecting from Library also doesn't work. The photo size is about 4 MB. Then I tried to upload a much smaller picture (200 KB) from Library and it works really well.

**Comment by rafaelks** [comment]
Have you tried this solution already? https://github.com/RocketChat/Rocket.Chat.iOS/issues/2184#issuecomment-423517754

**Comment by SV8** [comment]
That's it ! Solved by setting client_max_body_size directive in Nginx configuration.

**Comment by rafaelks** [comment]
Great, thanks! :)
