### ISSUE TITLE
[CHORE] Update Podfile to support new Swift Versions

### ISSUE THREAD

**Issue by TannerJuby1** [RocketChat/Rocket.Chat.iOS#2615]
Your Podfile currently attempts to compile `MobilePlayer` and `RCMarkdownParser` with Swift 3.1, however this swift version is unsupported:

```
SWIFT_VERSION '3.1' is unsupported, supported versions are: 4.0, 4.2, 5.0 (in target 'Mobile Player')
SWIFT_VERSION '3.1' is unsupported, supported versions are: 4.0, 4.2, 5.0 (in target 'RCMarkdownParser')
```

Please update to conform to supported versions

- Your Rocket.Chat app version: unrelated
- Your Rocket.Chat server version: unrelated
- Device (or Simulator) you're running with: unrelated

**Comment by snuff4** [comment]
There is a draft PR for this already, #2574 
You can checkout that branch, and work on it.
