### ISSUE TITLE
[I18N] Greek translations update

### ISSUE THREAD

**Issue by kmav** [RocketChat/Rocket.Chat.iOS#2622]
Missing translations to greek language.

**Comment by kmav** [comment]
Questions: What is "myaccount.settings.notifications.inapp" = "In-app and Desktop" ? What do you mean by desktop?

**Comment by kmav** [comment]
Can you advise how I can open notification preferences?

**Comment by kmav** [comment]
"myaccount.settings.notifications.inapp.footer" = "Displays a banner at the top of the screen when the app is open, and displays a notification on desktop.";
Is it footer that is at the top of the screen ? :)

**Comment by rafaelks** [comment]
@kmav Desktop is the Desktop app, yes. Gonna close the issue because the PR was merged, thank you @kmav! :-)

**Comment by kmav** [comment]
Kind regards :)

**Comment by kmav** [comment]
You are welcome!

Στις Δευ, 1 Απρ 2019 στις 3:52 μ.μ., ο/η Rafael Kellermann Streit <
notifications@github.com> έγραψε:
