### ISSUE TITLE
Xcode 

### ISSUE THREAD

**Issue by Jessting** [RocketChat/Rocket.Chat.iOS#2630]
- Your Rocket.Chat app version: ####
- Your Rocket.Chat server version: ####
- Device (or Simulator) you're running with: ####

**The app isn't connecting to your server?**
Make sure your server supports WebSocket. These are the minimum requirements for Apache 2.4 and Nginx 1.3 or greater.

**Comment by Jessting** [comment]
The targets “RCMarkdownParser” and “MobilePlayer” contains source code developed with Swift 3.x. This version of Xcode does not support building or migrating Swift 3.x targets.

Use Xcode 10.1 to migrate the code to Swift 4.

**Comment by rafaelks** [comment]
@Jessting We currently don't support Xcode 10.2, so you need to use Xcode 10.1. There's a PR open (in progress) to support it: #2574.

**Comment by Jessting** [comment]
hello, I use Xcode 10.1, but build failed. "The target “Rocket.Chat” contains source code developed with Swift 2.x. This version of Xcode does not support building or migrating Swift 2.x targets.Use Xcode 8.x to migrate the code to Swift 3."发自我的华为手机-------- 原始邮件 --------主题：Re: [RocketChat/Rocket.Chat.iOS] Xcode  (#2630)发件人：Rafael Kellermann Streit 收件人："RocketChat/Rocket.Chat.iOS" 抄送：Jessting <1094372441@qq.com>,Mention @Jessting We currently don't support Xcode 10.2, so you need to use Xcode 10.1. There's a PR open (in progress) to support it: #2574.
