### ISSUE TITLE
[BUG] Navigation bar disappears after subscription search

### ISSUE THREAD

**Issue by SV8** [RocketChat/Rocket.Chat.iOS#2631]
- Your Rocket.Chat app version: 3.4.0
- Your Rocket.Chat server version: 1.0.0 develop
- Device (or Simulator) you're running with: iPhone Xs Max, iOS 12.1.4

Search subscriptions and tap a row of the results. Navigation bar unexpectedly disappears in chat screen.

![IMG_1174](https://user-images.githubusercontent.com/5517286/55408216-207a8f80-5592-11e9-977e-05ffe9c74084.PNG)
![IMG_1175](https://user-images.githubusercontent.com/5517286/55408221-22dce980-5592-11e9-8858-3a7708c705ec.PNG)
![IMG_1176-2](https://user-images.githubusercontent.com/5517286/55408343-6899b200-5592-11e9-9384-99bf7beb8d0f.png)

**Comment by snuff4** [comment]
@SV8 I was able to solve the navigation bar bug, but found another bug. 

- If you click the Search button on the keyboard, then select a channel, the "Type a message" composer View is missing.

- If you directly click on a channel, without clicking the Search button on the keyboard, it is working fine.

**Comment by SV8** [comment]
@snuff4 
I found the same bug on my device.  It seems that both navigation bar and message composer disappeared. 

![IMG_1176-3](https://user-images.githubusercontent.com/5517286/55543913-8f73f780-56fc-11e9-816c-9c01e41012c1.jpg)
