### ISSUE TITLE
[NEW] Video player screen UI overlapping and hard to use.

### ISSUE THREAD

**Issue by SV8** [RocketChat/Rocket.Chat.iOS#2633]
Your Rocket.Chat app version: 3.4.0
Your Rocket.Chat server version: 1.0.0 develop
Device (or Simulator) you're running with: iPhone Xs Max, iOS 12.1.4

![IMG_1186_2](https://user-images.githubusercontent.com/5517286/55458112-a2b09580-561e-11e9-88aa-1628c4d8e42a.jpg)

**Comment by SV8** [comment]
@rafaelks Hi, Rafael. It seems this fix reverted. What went wrong with this fix?

https://github.com/RocketChat/Rocket.Chat.iOS/commit/fa6127f4f84370082ee4708313019376eb759d98

**Comment by snuff4** [comment]
@SV8 hi, the fix has been reverted because it will be added in the PR #2574

**Comment by SV8** [comment]
Thank you :) @snuff4 @rafaelks
