### ISSUE TITLE
Xcode 10.1  

### ISSUE THREAD

**Issue by Jessting** [RocketChat/Rocket.Chat.iOS#2634]
- Your Rocket.Chat app version: ####
- Your Rocket.Chat server version: ####
- Device (or Simulator) you're running with: ####

**The app isn't connecting to your server?**
Make sure your server supports WebSocket. These are the minimum requirements for Apache 2.4 and Nginx 1.3 or greater.

**Comment by Jessting** [comment]
The target “Rocket.Chat” contains source code developed with Swift 2.x. This version of Xcode does not support building or migrating Swift 2.x targets.

Use Xcode 8.x to migrate the code to Swift 3.

**Comment by snuff4** [comment]
@Jessting are you on the latest `develop` branch?

**Comment by Jessting** [comment]
> @Jessting are you on the latest `develop` branch?

YES, but I clone again, then it is ok.

**Comment by rafaelks** [comment]
Okay, closing the issue.
