### ISSUE TITLE
[IMPROVEMENT] Enhanced Notification Settings

### ISSUE THREAD

**Issue by jhmk** [RocketChat/Rocket.Chat.iOS#2635]
It would be very useful to be able to select which kind of Notification I'll get pushed via the iOS App.
For example:
- all notification
- only for direct messages
- for all mentions
....

On my Phone I just care about direct messages and not about notifications for all channels.

**Comment by yeoldegrove** [comment]
Just login to rocket.chat via your webbrowser.
There you can configure these kind of settings.
In the iOS app this is not possible currently.

**Comment by martinhoess** [comment]
Would be great if the iOS app would support quiet hours. I use RC at work, but I don't want to get any push notifications on mobile after work (e.g. display pushnotifications only from 07:00 to 18:00) mainly because there are some generated messages (build server ans such stuff, which is not important at night)

**Comment by diegolmello** [comment]
This issue can be closed as we already have notification preferences.

**Comment by martinhoess** [comment]
But they are global ... not specific for iOS?

**Comment by diegolmello** [comment]
I didn't get what you mean by `global`.
This repo is deprecated: https://github.com/RocketChat/Rocket.Chat.iOS#important---please-read-this-first

If you have an issue, please open an one on the new repo: https://github.com/RocketChat/Rocket.Chat.ReactNative/

**Comment by martinhoess** [comment]
> I didn't get what you mean by `global`.
> 
> If you have an issue, please open an one on the new repo: https://github.com/RocketChat/Rocket.Chat.ReactNative/

with global I mean, it is a setting which I make in my RC profile and this setting is used for all clients. So if I disable the notification on the desktop client, I also don't get the notification on the mobile client. But what I "need" is to do this device by device ...   and preferable with "quiet hours" so if I am at my work PC at 8 PM it is OK/wanted if the desktop client displays a notification but I dont't want to have any notification on my mobile device. Over kill solution would by "quiet hours" by device and channel ...

something like the MS Teams iOS client has: 
![image](https://user-images.githubusercontent.com/47973549/79594642-b28e0100-80dd-11ea-9c09-2a222547d0a8.png)

> This repo is deprecated: https://github.com/RocketChat/Rocket.Chat.iOS#important---please-read-this-first

Sorry didn't know that / did not read the main page ... I'm only using RC for about a week now ... so I'm still learning

**Comment by diegolmello** [comment]
Got it.
It should be done after https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/2045
Can you open a new issue?

> Sorry didn't know that / did not read the main page ... I'm only using RC for about a week now ... so I'm still learning

Np :)

**Comment by martinhoess** [comment]
> Got it.
> It should be done after [RocketChat/Rocket.Chat.ReactNative#2045](https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/2045)
> Can you open a new issue?

👍 
I'll make one tonight or tomorrow
