### ISSUE TITLE
How to combine this with Cordova?

### ISSUE THREAD

**Issue by Jessting** [RocketChat/Rocket.Chat.iOS#2650]
- Your Rocket.Chat app version: ####
- Your Rocket.Chat server version: ####
- Device (or Simulator) you're running with: ####

**The app isn't connecting to your server?**
Make sure your server supports WebSocket. These are the minimum requirements for Apache 2.4 and Nginx 1.3 or greater.

**Comment by rafaelks** [comment]
Really hard to understand your issue, but this is a separated app from Cordova.

**Comment by Jessting** [comment]
> Really hard to understand your issue, but this is a separated app from Cordova.

why?
