### ISSUE TITLE
How to run this app under cordova ?

### ISSUE THREAD

**Issue by Jessting** [RocketChat/Rocket.Chat.iOS#2655]
- Your Rocket.Chat app version: ####
- Your Rocket.Chat server version: ####
- Device (or Simulator) you're running with: ####

**The app isn't connecting to your server?**
Make sure your server supports WebSocket. These are the minimum requirements for Apache 2.4 and Nginx 1.3 or greater.

**Comment by Jessting** [comment]
I want to use this app in a Cordova environment , How to do it? Or integrate this app into my app ? I have no idea for this?

**Comment by rafaelks** [comment]
@Jessting Cordova application is deprecated and is in another repository: https://github.com/RocketChat/Rocket.Chat.Cordova
