### ISSUE TITLE
How to integrate this app into other app ? 

### ISSUE THREAD

**Issue by Jessting** [RocketChat/Rocket.Chat.iOS#2658]
- Your Rocket.Chat app version: ####
- Your Rocket.Chat server version: ####
- Device (or Simulator) you're running with: ####

**The app isn't connecting to your server?**
Make sure your server supports WebSocket. These are the minimum requirements for Apache 2.4 and Nginx 1.3 or greater.

**Comment by rafaelks** [comment]
@Jessting Please start describing your issues.

**Comment by Jessting** [comment]
I want to use this app as a module in other app.But I have no idea.-------- 原始邮件 --------主题：Re: [RocketChat/Rocket.Chat.iOS] How to integrate this app into other app ?  (#2658)发件人：Rafael Kellermann Streit 收件人："RocketChat/Rocket.Chat.iOS" 抄送：Jessting <1094372441@qq.com>,Mention @Jessting Please start describing your issues.

**Comment by rafaelks** [comment]
@Jessting Please, explain... how do you want to use it as a module? What do you want to do?

**Comment by Jessting** [comment]
How to import this project into a new iOS project? Now I have built a new iOS project. Do I need to do anything to make use of this project as a sub-project/sub-module?

**Comment by rafaelks** [comment]
@Jessting You want to import what parts of the project into your iOS project?

**Comment by Jessting** [comment]
All of this project. Is it ok？

**Comment by rafaelks** [comment]
@Jessting Why don't you simply clone it and use it them?

**Comment by Jessting** [comment]
Because I have other features in my new project that I want to do with hybrid development, this project is just as one of the modules.

**Comment by rafaelks** [comment]
@Jessting I'm afraid there's no easy way to do it... you can try opening Rocket.Chat using our deeplinks: https://rocket.chat/docs/developer-guides/deeplink/#deeplink

**Comment by Jessting** [comment]
I will try. Thank you.
