### ISSUE TITLE
[BUG] New messages icon not shown on channels

### ISSUE THREAD

**Issue by stefanandres** [RocketChat/Rocket.Chat.iOS#2659]
- Your Rocket.Chat app version: ####
3.4.0 and 3.4.1
- Your Rocket.Chat server version: ####
0.74.3

- Device (or Simulator) you're running with: ####
iPhone 8

Since version 3.4 the app does not show the indicator on the channel list whether a channel has new messages.

Only messages with `@myusername` will trigger the indicator. 

For users that are in many channels this makes this client hard to use since the user would need to manually enter any channel to check for new messages (that are not directly send via @username to me)

**Comment by MattiasMentzer** [comment]
Same app version: 3.4.0 and 3.4.1

Same server and therefore also the same server version: 0.74.3

Devices iPhone XS Max, iPad Air 2

**Comment by rafaelks** [comment]
@stefanandres @MattiasMentzer The badge was removed to stay the same as used on the web client. Do you think the coolers on the time and bold font is not making a difference?

**Comment by MattiasMentzer** [comment]
I can only hardly recognize the bold font. I only saw it now after you told us that there is the channel name in bold format.

For me the difference between bold and normal is not prominent enough.

On the web version it is much better in my opinion.

**Comment by engelgabriel** [comment]
@MattiasMentzer I just noticed by your screenshot that you are not using the new feature that shows the last message of each channel and the date of the last message. That's a use case that we forgot to look at, as almost every server has that feature now enabled. 

Do you have a reason to have turned that off? Or is a matter of not knowing about that feature? 

Please work with us to sort out this UX issue, thanks for your feedback.

**Comment by stefanandres** [comment]
Where do you enable this feature? Both my private and company server does not have this enabled

**Comment by engelgabriel** [comment]
Admin -> General 

![image](https://user-images.githubusercontent.com/1000217/55898460-801b0100-5b77-11e9-98f3-43229647cadd.png)

**Comment by stefanandres** [comment]
Ah, after enabling "store last message" in general it looks good. Is there a reason this was not enabled on an upgraded server?
I guess a lot of server wont have this enabled.

**Comment by engelgabriel** [comment]
please give it a try and give us your feedback

**Comment by engelgabriel** [comment]
when we created the feature we made it optional while we were testing, it won't be optional in future versions

**Comment by MattiasMentzer** [comment]
This way with that option enabled everyhting is fine for me.

**Comment by stefanandres** [comment]
Thanks for the support!
