### ISSUE TITLE
[QUESTION] Jitsi Meet SDK compatible source, to rebuild framework

### ISSUE THREAD

**Issue by nasircsms** [RocketChat/Rocket.Chat.iOS#2670]
- Your Rocket.Chat app version: 3.3.0
- Your Rocket.Chat server version: 0.74.3
- Device (or Simulator) you're running with: iPhone X

I am trying to hide/remove certain controls from Jitsi Video Call UI e.g. chat, invite, add participants etc. As Jitsi iOS SDK doesn't provide such configuration out of the box, I have to update their source and rebuild the framework.

I have built JitsiMeet framework with multiple source releases from here 
[https://github.com/RocketChat/jitsi-meet/releases](url)

but it is not working properly. I am unable to have call with the mac version 2.15.2. It shows that the call has started but the call actually never connects.

Kindly point me to the right direction i.e. which version of Jitsi Meet source will work with the above version of iOS app, so I can rebuild that Jitsi framework with required UI changes.

**Comment by rafaelks** [comment]
@nasircsms Hey, do you see something on the logs? What release are you trying to use?

**Comment by nasircsms** [comment]
In logs I can find following error
[error][tid:com.facebook.react.JavaScript] undefined is not an object (evaluating 't.callUUID')
[fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: undefined is not an object (evaluating 't.callUUID')

I have tried using 
[https://github.com/RocketChat/jitsi-meet/releases/tag/jitsi-meet_3671](https://github.com/RocketChat/jitsi-meet/releases/tag/jitsi-meet_3671)
[https://github.com/RocketChat/jitsi-meet/releases/tag/jitsi-meet_3670](https://github.com/RocketChat/jitsi-meet/releases/tag/jitsi-meet_3670)

and many other following in the series..

**Comment by nasircsms** [comment]
I found the issue.. Previously JitsiMeetView was initialized 
`jitsiMeetView?.loadURLObject([
            "config": [
                "startWithAudioMuted": false,
                "startWithVideoMuted": false,
                "iAmRecorder": true
            ],
            "context": [
                "user": [
                    "name": viewModel.userDisplayName,
                    "avatar": viewModel.userAvatar
                ],
                "iss": "rocketchat-ios"
            ],
            "url": viewModel.videoCallURL
        ])`

But in new SDK it was changed to following

`let joinOptions:JitsiMeetConferenceOptions = JitsiMeetConferenceOptions.fromBuilder {[weak self] (optionsBuilder) in
            if let weakSelf = self {
                optionsBuilder.serverURL = URL(string: weakSelf.viewModel.videoCallURL)
                optionsBuilder.audioOnly = false
                optionsBuilder.audioMuted = false
                optionsBuilder.videoMuted = false
                optionsBuilder.welcomePageEnabled = false
                optionsBuilder.room = optionsBuilder.serverURL?.lastPathComponent //weakSelf.viewModel.subscription?.rid
            }
        }
        
        jitsiMeetView?.join(joinOptions)`

I was sending RocketChat roomId in ‘room’ param of JitsiMeetView which was wrong. I changed it to JitsiMeet room from url and it started working.

**Comment by rafaelks** [comment]
Great! Can we close the issue then?

**Comment by nasircsms** [comment]
Yes, Thanks for responding.. keep up the awesome work 👍
