### ISSUE TITLE
SWIFT_VERSION '3.1' is unsupported

### ISSUE THREAD

**Issue by kenjiUT** [RocketChat/Rocket.Chat.iOS#2674]
- Your Rocket.Chat app version: ####
- Your Rocket.Chat server version: ####
- Device (or Simulator) you're running with: ####

**The app isn't connecting to your server?**
Make sure your server supports WebSocket. These are the minimum requirements for Apache 2.4 and Nginx 1.3 or greater.

**Comment by rafaelks** [comment]
@kenjiUT Please describe better your issue, gonna close the issue now.
