### ISSUE TITLE
Is there an SDK for this project?

### ISSUE THREAD

**Issue by Jessting** [RocketChat/Rocket.Chat.iOS#2675]
- Your Rocket.Chat app version: ####
- Your Rocket.Chat server version: ####
- Device (or Simulator) you're running with: ####

**The app isn't connecting to your server?**
Make sure your server supports WebSocket. These are the minimum requirements for Apache 2.4 and Nginx 1.3 or greater.

**Comment by rafaelks** [comment]
@Jessting No, there's no SDK at the moment.

**Comment by Jessting** [comment]
OK，I understand. Thank you. @rafaelks .

**Comment by Jessting** [comment]
Is there an API for this project?
