### ISSUE TITLE
Is there an API for this project?

### ISSUE THREAD

**Issue by Jessting** [RocketChat/Rocket.Chat.iOS#2676]
- Your Rocket.Chat app version: ####
- Your Rocket.Chat server version: ####
- Device (or Simulator) you're running with: ####

**The app isn't connecting to your server?**
Make sure your server supports WebSocket. These are the minimum requirements for Apache 2.4 and Nginx 1.3 or greater.

**Comment by soundstorm** [comment]
?

**Comment by rafaelks** [comment]
@Jessting This kind of question is very hard to understand and give you a proper reply, I'm sorry.

**Comment by Jessting** [comment]
emmmmm, @rafaelks @soundstorm , I would like to ask if there is an interface for this project so that it can be invoked.

**Comment by Jessting** [comment]
Now I have a new project. Can I add this chat project into my project? If so, how to operate it?
