### ISSUE TITLE
[NEW] Support biometric authentication

### ISSUE THREAD

**Issue by Nemental** [RocketChat/Rocket.Chat.iOS#2686]
Is it possible to implement iOS biometric authentication to protect the app of unwanted access? I mean FaceID/TouchID or at least password.

**Comment by rafaelks** [comment]
@Nemental I think this is a nice idea, will add the labels and if someone wants to work in a PR... :-)

**Comment by Nemental** [comment]
@rafaelks Can you please duplicate it for Android?

**Comment by Nemental** [comment]
https://github.com/rushisangani/BiometricAuthentication

**Comment by Nemental** [comment]
Biometric authentication simply to get access to the app, not necessarily for login, would be enough 👍

**Comment by kushthedude** [comment]
@rafaelks I am new to the repo , would like to work on the issue

**Comment by Nemental** [comment]
Are you still interested to work on this issue? @kushthedude

**Comment by kushthedude** [comment]
@Nemental Sorry for the delay, But i didn't receive any confirmation from mentors thats why i delayed it

**Comment by Nemental** [comment]
@kushthedude If I can help you with a little donation let me know
@rafaelks Can you help him?

**Comment by kushthedude** [comment]
@Nemental That'd be great if you help me !

**Comment by Nemental** [comment]
@kushthedude Unfortunately I can not help you with the repo, that's why I opened the issue. But a little donation would be possible for your work. ;)

**Comment by kushthedude** [comment]
@Nemental I will take care for the repo  , I meant to say it would be great if you could help me with some donation 😅

**Comment by Nemental** [comment]
@kushthedude i will send you an email tomorrow :)

**Comment by kushthedude** [comment]
> @kushthedude i will send you an email tomorrow :)

Sounds Great :D

**Comment by Nemental** [comment]
Is someone else interested to work on this issue? @kushthedude does not answer anymore

**Comment by shahianshu** [comment]
@Nemental yes , I would like to work on the issue. Could you please guide me how can i do it

**Comment by Nemental** [comment]
@shahianshu What type of guide do you need?

**Comment by shahianshu** [comment]
@Nemental what should be the steps i should follow inorder to implement biometric authentication ?

**Comment by Nemental** [comment]
@shahianshu Unfortunately I cant guide how to code or implement biometric authentication, sorry. The expected behaviour is to enable/disable TouchID/FaceID/PIN in settings. Then the biometric auth protection should appear on app start/launch. Maybe you know this feature from WhatsApp, Telegram or Signal.

**Comment by shahianshu** [comment]
@Nemental if i start working on the feature and run into some kind of trouble or issue can i ask your help or is there anybody who would be willing to help ?

**Comment by Nemental** [comment]
@shahianshu I'm absolutely ready to help you with problems, but notice that I'm a Swift beginner ;)

**Comment by reetp** [comment]
May I suggest that you wait a short while before committing too much work on the Swift iOS native version, and possibly take a look at the React Native version instead?

https://github.com/RocketChat/Rocket.Chat.ReactNative

There will be some news published about the future of the mobile apps soon.....

**Comment by Nemental** [comment]
I'm looking forward to the news
