### ISSUE TITLE
Add "arrow" to scroll down if user isn't in the bottom

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.iOS#270]

**Comment by biomassives** [comment]
I'd like to help with this

**Comment by rafaelks** [comment]
@biomassives Please, go ahead! There's no one working on it right now. Here's what we thought about this feature, something very similar from what Telegram does.

![image-1](https://cloud.githubusercontent.com/assets/551004/22879560/c147d50e-f1c5-11e6-8e72-320660368be1.jpg)

**Comment by legendecas** [comment]
Hi, since there is no further updates, I have implemented this feature. Take a look

<img src="https://cloud.githubusercontent.com/assets/8500303/23820563/28151ce8-0656-11e7-8233-387b032be26d.gif" width="350px"/>
