### ISSUE TITLE
[BUG] Major UI issue in list of messages when compiled on release

### ISSUE THREAD

**Issue by ryandailey100** [RocketChat/Rocket.Chat.iOS#2710]
- Your Rocket.Chat app version: 3.5.0
- Your Rocket.Chat server version: 1.1.0
- Device (or Simulator) you're running with: iPhone XR iOS 12.2
- Using Xcode 10.2.1

I am running the app with the latest changes from the prototype branch. I noticed that there is a bug (only when compiled on release) where the list of messages UI would be all messed up.  Note: This bug does not appear when compiling on debug, only when compiled for release. Here are some pictures demonstrating this bug in action:

![Simulator Screen Shot - iPhone Xʀ - 2019-05-29 at 13 23 44](https://user-images.githubusercontent.com/15038444/58577780-3c5a8480-8215-11e9-8352-9ce0f8f5b9cb.png)

**Comment by ryandailey100** [comment]
This issue seems to have started once https://github.com/RocketChat/Rocket.Chat.iOS/pull/2691 was merged into prototype. @cardoso I noticed you commented about this in the pull request above. Any information/progress you have of this issue to share?

**Comment by georgechr** [comment]
Experiencing the same issue +1

**Comment by gabonchaing** [comment]
I have the same problem

**Comment by georgechr** [comment]
Same problem +1.

Is there a workaround?

**Comment by ryandailey100** [comment]
@cardoso @filipealva @rafaelks Are you guys aware of this issue? I believe this issue should get more attention since it is a blocker for the next release.

**Comment by cardoso** [comment]
@ryandailey100 at this moment, this project is being run 100% by the community. Unfortunately, none of the old core maintainers are available to look at this issue.

**Comment by ryandailey100** [comment]
@cardoso In that case, #2691 should be reverted since it causes this major issue.

**Comment by cardoso** [comment]
@ryandailey100 it's causing the issue in develop branch only. No version is going to be published to the App Store with this issue occurring. You can (and should) still use the master branch.

Keeping it in the develop branch makes it more visible for contributors to hopefully investigate and fix it.

**Comment by cardoso** [comment]
Okay. I was able to take some time tonight to investigate this. Let me know if the PR works for you @ryandailey100 .

**Comment by ryandailey100** [comment]
@cardoso Works great! Thank you for the fix, appreciate it 👍
