### ISSUE TITLE
Xcode build failed

### ISSUE THREAD

**Issue by Taskyy** [RocketChat/Rocket.Chat.iOS#2718]
- Your Rocket.Chat app version: 3.5.0
- Your Rocket.Chat server version: 0.64
- Device (or Simulator) you're running with: simulator

error 1: Segmentation fault: 11
error2: Header 'RealmSwift-Swift.h' not found
error3: Could not build Objective-C module 'RealmSwift'

**Comment by reetp** [comment]
Please upgrade to the latest version of Rocket.Chat and test thank you.

Current version v1.1.1
