### ISSUE TITLE
Sync unread numbers via silent push

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.iOS#272]

**Comment by soundstorm** [comment]
Isn't it almost the same as #411 ? :)

**Comment by rafaelks** [comment]
@soundstorm No... this is for something like: the app is closed and you're using the chat from the web. We need to tell the app to change the number without alerting the user every time, you know?

**Comment by soundstorm** [comment]
But has heavy intersections ;-)
