### ISSUE TITLE
Archive Failed using New Build System

### ISSUE THREAD

**Issue by BeatriceFeltre** [RocketChat/Rocket.Chat.iOS#2745]
- Your Rocket.Chat app version: 3.5.0
- Your Rocket.Chat server version: ####
- Device (or Simulator) you're running with: ####

Goodmorning,

I'm using New Build System, when I try to archive, I received the follow error and build failed:
![image](https://user-images.githubusercontent.com/5756816/62464127-152bb080-b78c-11e9-9202-7e380f4dea22.png)

I also tried set "Legacy Build System", Archive done, but the chats content , is completed unusable; there are also avatar and content is empty like in the screenshot below:

![image](https://user-images.githubusercontent.com/5756816/62464662-7dc75d00-b78d-11e9-9ca2-2090208a76c9.png)

Someone had my same problem?
How can I solve it?

Thank you so much for the help,
B.

**Comment by Vacak7** [comment]
Hi ya, 
The problem is Xcode 10.2-3 update + Cocoapods. 
I had the same problem. There is a link to help the problem: [https://www.ralfebert.de/ios/blog/cocoapods-clean-input-output-files/(url). 
Use the Legacy Build System and you have to clean before you archive (command + shift + K) and also close any simulator. 
I hope that help.

**Comment by BeatriceFeltre** [comment]
> Hi ya,
> The problem is Xcode 10.2-3 update + Cocoapods.
> I had the same problem. There is a link to help the problem: [https://www.ralfebert.de/ios/blog/cocoapods-clean-input-output-files/(url).
> Use the Legacy Build System and you have to clean before you archive (command + shift + K) and also close any simulator.
> I hope that help.

Thank you for your reply.
I added the instruction into podfile mentions into link that you shared. Run pod install again and I followed the steps you described.
Archive is ok, but I still have the same problem with the chats content. :(
If I run app from xcode, I havn't the problem.
If I use New Build System, archive failed for the same reason described in the issue


B.

**Comment by Vacak7** [comment]
Hi there, try to use Rocket.Chat 3.4.1 version. That worked fine for me. It might be a bug with the latest release. 
I hope that help.

**Comment by ryandailey100** [comment]
For this issue regarding the weird UI, take a look at this fix: 
https://github.com/RocketChat/Rocket.Chat.iOS/pull/2722

**Comment by BeatriceFeltre** [comment]
> For this issue regarding the weird UI, take a look at this fix:
> #2722

Thank you so much. The fix resolve my problem.. :)

B.
