### ISSUE TITLE
Opening links inline -> stuck, no scrolling, no closer

### ISSUE THREAD

**Issue by stkjj** [RocketChat/Rocket.Chat.iOS#275]
Your Rocket.Chat version: 2.5.0, latest updates

Opening a link (to a website) from entry opens site in external browser

opening the site inline (tapping on the preview) means to get stuck in displaying the actual screen. No chance to scroll within the page, no chance to get back to rocket.chat. App has to be quit and restarted to enter the channel again.
![img_1262](https://cloud.githubusercontent.com/assets/832642/22930890/ba690c14-f2c2-11e6-9bdf-d29ced4c747a.PNG)

**Comment by rafaelks** [comment]
@stkjj This issue is related to the Cordova application, not the native one. Please, open your issue on this repository: https://github.com/RocketChat/Rocket.Chat.Cordova.

If you want to be a beta testar of our native app, comment your email and I'll send you the invitation.

**Comment by stkjj** [comment]
yes pls: stk@owncloud.com

**Comment by rafaelks** [comment]
@stkjj Just sent you the invitation. Thank you!

**Comment by Jellyfrog** [comment]
@rafaelks could you also add rocketchat@devshm.net? thanks

**Comment by rafaelks** [comment]
@Jellyfrog Added. 👍
