### ISSUE TITLE
Iphone App cannot connect to server

### ISSUE THREAD

**Issue by holzfelix** [RocketChat/Rocket.Chat.iOS#2769]
- Your Rocket.Chat app version: 3.5.1
- Your Rocket.Chat server version: 2.1.0
- Device (or Simulator) you're running with: iphone 7

**The app isn't connecting to your server?**

Hi Together, Rocket chat works fine in browser and on desktop app as well on android app. Only the iphone app can't connect to the server. What could be the issue in this case?

![image](https://user-images.githubusercontent.com/6866699/65961040-0b55bf00-e456-11e9-8cd6-0c85f68760b2.png)

It runs on default port 3000. my config looks like this:

`<Directory /var/www/chat.domain.de>
                AllowOverride None
                                Require all denied
                </Directory>

<VirtualHost *:80>

                                                                        DocumentRoot /var/www/chat.domain.de/web

                ServerName chat.domain.de
                ServerAlias www.chat.domain.de
                ServerAdmin webmaster@chat.domain.de

                ErrorLog /var/log/ispconfig/httpd/chat.domain.de/error.log

                Alias /error/ "/var/www/chat.domain.de/web/error/"
                ErrorDocument 400 /error/400.html
                ErrorDocument 401 /error/401.html
                ErrorDocument 403 /error/403.html
                ErrorDocument 404 /error/404.html
                ErrorDocument 405 /error/405.html
                ErrorDocument 500 /error/500.html
                ErrorDocument 502 /error/502.html
                ErrorDocument 503 /error/503.html

                <IfModule mod_ssl.c>
                </IfModule>

                <Directory /var/www/chat.domain.de/web>
                                # Clear PHP settings of this website
                                <FilesMatch ".+\.ph(p[345]?|t|tml)$">
                                                SetHandler None
                                </FilesMatch>
                                Options +FollowSymLinks
                                AllowOverride All
                                                                Require all granted
                                                </Directory>
                <Directory /var/www/clients/client0/web32/web>
                                # Clear PHP settings of this website
                                <FilesMatch ".+\.ph(p[345]?|t|tml)$">
                                                SetHandler None
                                </FilesMatch>
                                Options +FollowSymLinks
                                AllowOverride All
                                                                Require all granted
                                                </Directory>

                # suexec enabled
                <IfModule mod_suexec.c>
                        SuexecUserGroup web32 client0
                </IfModule>
                # php as fast-cgi enabled
        # For config options see: http://httpd.apache.org/mod_fcgid/mod/mod_fcgid.html
                <IfModule mod_fcgid.c>
                                IdleTimeout 300
                                ProcessLifeTime 3600
                                # MaxProcessCount 1000
                                DefaultMinClassProcessCount 0
                                DefaultMaxClassProcessCount 10
                                IPCConnectTimeout 3
                                IPCCommTimeout 600
                                BusyTimeout 3600
                </IfModule>
                <Directory /var/www/chat.domain.de/web>
                                <FilesMatch "\.php[345]?$">
                                        SetHandler fcgid-script
                                </FilesMatch>
                                FCGIWrapper /var/www/php-fcgi-scripts/web32/.php-fcgi-starter .php
                                FCGIWrapper /var/www/php-fcgi-scripts/web32/.php-fcgi-starter .php3
                                FCGIWrapper /var/www/php-fcgi-scripts/web32/.php-fcgi-starter .php4
                                FCGIWrapper /var/www/php-fcgi-scripts/web32/.php-fcgi-starter .php5
                                Options +ExecCGI
                                AllowOverride All
                                                                Require all granted
                                                </Directory>

                <Directory /var/www/clients/client0/web32/web>
                                <FilesMatch "\.php[345]?$">
                                        SetHandler fcgid-script
                                </FilesMatch>
                                FCGIWrapper /var/www/php-fcgi-scripts/web32/.php-fcgi-starter .php
                                FCGIWrapper /var/www/php-fcgi-scripts/web32/.php-fcgi-starter .php3
                                FCGIWrapper /var/www/php-fcgi-scripts/web32/.php-fcgi-starter .php4
                                FCGIWrapper /var/www/php-fcgi-scripts/web32/.php-fcgi-starter .php5
                                Options +ExecCGI
                                AllowOverride All
                                                                Require all granted
                                                </Directory>

                RewriteEngine on
                RewriteCond %{REQUEST_URI} ^/\.well-known/acme-challenge/
                RewriteRule ^ - [END]
        RewriteCond %{HTTPS} off
                RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L,NE]

                # add support for apache mpm_itk
                <IfModule mpm_itk_module>
                        AssignUserId web32 client0
                </IfModule>

                <IfModule mod_dav_fs.c>
                # Do not execute PHP files in webdav directory
                        <Directory /var/www/clients/client0/web32/webdav>
                                <ifModule mod_security2.c>
                                        SecRuleRemoveById 960015
                                        SecRuleRemoveById 960032
                                </ifModule>
                                <FilesMatch "\.ph(p3?|tml)$">
                                        SetHandler None
                                </FilesMatch>
                        </Directory>
                        DavLockDB /var/www/clients/client0/web32/tmp/DavLock
                        # DO NOT REMOVE THE COMMENTS!
                        # IF YOU REMOVE THEM, WEBDAV WILL NOT WORK ANYMORE!
      # WEBDAV BEGIN
                        # WEBDAV END
                </IfModule>

ProxyPreserveHost On
ProxyRequests On
ProxyVia On
ProxyPass / http://IP.IP.IP.IP:3000/
ProxyPassReverse / http://IP.IP.IP.IP:3000/

</VirtualHost>

<VirtualHost *:443>

                                                                        DocumentRoot /var/www/chat.domain.de/web

                ServerName chat.domain.de
                ServerAlias www.chat.domain.de
                ServerAdmin webmaster@chat.domain.de

                ErrorLog /var/log/ispconfig/httpd/chat.domain.de/error.log

                Alias /error/ "/var/www/chat.domain.de/web/error/"
                ErrorDocument 400 /error/400.html
                ErrorDocument 401 /error/401.html
                ErrorDocument 403 /error/403.html
                ErrorDocument 404 /error/404.html
                ErrorDocument 405 /error/405.html
                ErrorDocument 500 /error/500.html
                ErrorDocument 502 /error/502.html
                ErrorDocument 503 /error/503.html

                <IfModule mod_ssl.c>
                SSLEngine on
                SSLProtocol All -SSLv2 -SSLv3
                SSLHonorCipherOrder     on
              # <IfModule mod_headers.c>
                # Header always add Strict-Transport-Security "max-age=15768000"
                # </IfModule>
                SSLCertificateFile /var/www/clients/client0/web32/ssl/chat.domain.de-le.crt
                SSLCertificateKeyFile /var/www/clients/client0/web32/ssl/chat.domain.de-le.key
                                SSLCertificateChainFile /var/www/clients/client0/web32/ssl/chat.domain.de-le.bundle
                                                SSLUseStapling on
                SSLStaplingResponderTimeout 5
                SSLStaplingReturnResponderErrors off
                                </IfModule>

                <Directory /var/www/chat.domain.de/web>
                                # Clear PHP settings of this website
                                <FilesMatch ".+\.ph(p[345]?|t|tml)$">
                                                SetHandler None
                                </FilesMatch>
                                Options +FollowSymLinks
                                AllowOverride All
                                                                Require all granted
                                                </Directory>
                <Directory /var/www/clients/client0/web32/web>
                                # Clear PHP settings of this website
                                <FilesMatch ".+\.ph(p[345]?|t|tml)$">
                                                SetHandler None
                                </FilesMatch>
                                Options +FollowSymLinks
                                AllowOverride All
                                                                Require all granted
                                                </Directory>

                # suexec enabled
                <IfModule mod_suexec.c>
                        SuexecUserGroup web32 client0
                </IfModule>
                # php as fast-cgi enabled
        # For config options see: http://httpd.apache.org/mod_fcgid/mod/mod_fcgid.html
                <IfModule mod_fcgid.c>
                                IdleTimeout 300
                                ProcessLifeTime 3600
                                # MaxProcessCount 1000
                                DefaultMinClassProcessCount 0
                                DefaultMaxClassProcessCount 10
                                IPCConnectTimeout 3
                                IPCCommTimeout 600
                                BusyTimeout 3600
                </IfModule>
                <Directory /var/www/chat.domain.de/web>
                                <FilesMatch "\.php[345]?$">
                                        SetHandler fcgid-script
                                </FilesMatch>
                                FCGIWrapper /var/www/php-fcgi-scripts/web32/.php-fcgi-starter .php
                                FCGIWrapper /var/www/php-fcgi-scripts/web32/.php-fcgi-starter .php3
                                FCGIWrapper /var/www/php-fcgi-scripts/web32/.php-fcgi-starter .php4
                                FCGIWrapper /var/www/php-fcgi-scripts/web32/.php-fcgi-starter .php5
                                Options +ExecCGI
                                AllowOverride All
                                                                Require all granted
                                                </Directory>
                <Directory /var/www/clients/client0/web32/web>
                                <FilesMatch "\.php[345]?$">
                                        SetHandler fcgid-script
                                </FilesMatch>
                                FCGIWrapper /var/www/php-fcgi-scripts/web32/.php-fcgi-starter .php
                                FCGIWrapper /var/www/php-fcgi-scripts/web32/.php-fcgi-starter .php3
                                FCGIWrapper /var/www/php-fcgi-scripts/web32/.php-fcgi-starter .php4
                                FCGIWrapper /var/www/php-fcgi-scripts/web32/.php-fcgi-starter .php5
                                Options +ExecCGI
                                AllowOverride All
                                                                Require all granted
                                                </Directory>

                RewriteEngine on
                RewriteCond %{REQUEST_URI} ^/\.well-known/acme-challenge/
                RewriteRule ^ - [END]
               # add support for apache mpm_itk
                <IfModule mpm_itk_module>
                        AssignUserId web32 client0
                </IfModule>

                <IfModule mod_dav_fs.c>
                # Do not execute PHP files in webdav directory
                        <Directory /var/www/clients/client0/web32/webdav>
                                <ifModule mod_security2.c>
                                        SecRuleRemoveById 960015
                                        SecRuleRemoveById 960032
                                </ifModule>
                                <FilesMatch "\.ph(p3?|tml)$">
                                        SetHandler None
                                </FilesMatch>
                        </Directory>
                        DavLockDB /var/www/clients/client0/web32/tmp/DavLock
                        # DO NOT REMOVE THE COMMENTS!
                        # IF YOU REMOVE THEM, WEBDAV WILL NOT WORK ANYMORE!
      # WEBDAV BEGIN
                        # WEBDAV END
                </IfModule>

ProxyPreserveHost On
ProxyRequests On
ProxyVia On
ProxyPass / http://IP.IP.IP.IP:3000/
ProxyPassReverse / http://IP.IP.IP.IP:3000/

</VirtualHost>

<IfModule mod_ssl.c>
        SSLStaplingCache shmcb:/var/run/ocsp(128000)
</IfModule>
`

**Comment by reetp** [comment]
Did you read this and test first?

> **The app isn't connecting to your server?**
> Make sure your server supports WebSocket. These are the minimum requirements for Apache 2.4 and Nginx 1.3 or greater.

And then this?
https://rocket.chat/docs/getting-support/

99.9 % certain this is not a bug, and if you check you will find that your websockets/SSL are not working correctly - browser and Android fall back to XHR but iOS will not.

Chromium. Inspect, Network, F5 to reload, look for the filter WS for 'websocket' and then look for these

```
 General
  Request URL: wss://open.rocket.chat/sockjs/123/sjhc92iy/websocket
  Request Method: GET
  Status Code: 101 Switching Protocols
```
```

 Response Headers
  Connection: Upgrade
  Sec-WebSocket-Accept: OFbckwmGIDv82L4kV9V3H0zJLDQ=
  Upgrade: websocket
```

I think you need to go back and start with your Apache setup.

Use this as a guide - you can setup an individual virtual host.

https://rocket.chat/docs/installation/manual-installation/configuring-ssl-reverse-proxy/#running-behind-an-apache-ssl-reverse-proxy

**Comment by holzfelix** [comment]
a2enmod proxy_wstunnel was missing
