### ISSUE TITLE
Remember Scrollback position with in-app browser

### ISSUE THREAD

**Issue by Jellyfrog** [RocketChat/Rocket.Chat.iOS#279]
When closing the _in app browser_ it scrolls the channel to the bottom.  
To reproduce:

- Scroll up in chat
- find link and press it
- close the in app browser
- you will now be at bottom of channel

.

- Your Rocket.Chat app version: 1.0.0 (30)
- Your Rocket.Chat server version: 0.51.1
- Device (or Simulator) you're running with: iPhone 7

**Comment by rafaelks** [comment]
Good catch, thanks!

**Comment by rafaelks** [comment]
This is fixed already.
