### ISSUE TITLE
Change keyboard type to `UIKeyboardType.twitter`

### ISSUE THREAD

**Issue by williamhatcher** [RocketChat/Rocket.Chat.iOS#2793]
I propose that the keyboard type should be set to `UIKeyboardType.twitter` in room messages to more easily ping people.

**Note:** I'm willing to make a pull request myself, but I'm not sure where the chat text box code is.

**Comment by reetp** [comment]
The mobile apps are moving to React Native.

Please read the following links.

https://github.com/RocketChat/Rocket.Chat.Android#legacy-rocketchat-android-native-application

https://rocket.chat/2019/10/11/moving-mobile-apps-to-react/

Any issues here are now unlikely to get fixed.

You should test the Experimental RN app on iOS and look in the React Native repo

https://github.com/RocketChat/Rocket.Chat.ReactNative
