### ISSUE TITLE
iOS App don't connect in rocket.chat server

### ISSUE THREAD

**Issue by diegorafaelc** [RocketChat/Rocket.Chat.iOS#2809]
- Your Rocket.Chat app version: 4.1.0
- Your Rocket.Chat server version: 2.2.0
- Device (or Simulator) you're running with: iOS

iOS App don't connect, but the android app connect normally.

![WhatsApp Image 2020-01-07 at 08 46 42](https://user-images.githubusercontent.com/58229821/71895365-a7ffbb00-312f-11ea-9347-4191b0d62ec7.jpeg)

**Android connection log**

_I20200107-09:16:02.704(-3) server.js:204 API ➔ debug GET: /api/info 
I20200107-09:16:02.710(-3) server.js:204 API ➔ debug Success { statusCode: 200, body: { version: '2.2.0', success: true } } 
I20200107-09:16:02.915(-3) server.js:204 Meteor ➔ publish null -> userId: null, arguments: [] 
I20200107-09:16:02.985(-3) server.js:204 API ➔ debug GET: /api/v1/settings.oauth 
I20200107-09:16:02.987(-3) server.js:204 API ➔ debug Success { statusCode: 200, body: { services: [], success: true } } 
I20200107-09:16:03.289(-3) server.js:204 API ➔ debug GET: /api/v1/settings.public?query={%22_id%22:{%22$in%22:[%22Accounts_CustomFields%22,%22Accounts_EmailOrUsernamePlaceholder%22,%22Accounts_NamePlaceholder%22,%22Accounts_PasswordPlaceholder%22,%22Accounts_PasswordReset%22,%22CROWD_Enable%22,%22FEDERATION_Enabled%22,%22LDAP_Enable%22,%22Jitsi_Enabled%22,%22Jitsi_SSL%22,%22Jitsi_Domain%22,%22Jitsi_URL_Room_Prefix%22,%22Message_AllowDeleting%22,%22Message_AllowDeleting_BlockDeleteInMinutes%22,%22Message_AllowEditing%22,%22Message_AllowEditing_BlockEditInMinutes%22,%22Message_AllowPinning%22,%22Message_AllowStarring%22,%22Message_GroupingPeriod%22,%22Message_TimeFormat%22,%22Site_Name%22,%22Site_Url%22,%22Store_Last_Message%22,%22uniqueID%22,%22UI_Use_Real_Name%22,%22Assets_favicon_512%22,%22Message_Read_Receipt_Enabled%22,%22Message_Read_Receipt_Store_Users%22,%22Threads_enabled%22,%22FileUpload_MediaTypeWhiteList%22,%22FileUpload_MaxFileSize%22,%22API_Gitlab_URL%22,%22AutoTranslate_Enabled%22,%22CAS_enabled%22,%22CAS_login_url%22]}} 
I20200107-09:16:03.296(-3) server.js:204 API ➔ debug Success { statusCode: 200,   body:     { settings:        [ [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object] ],      count: 34,      offset: 0,      total: 34,      success: true } } 
I20200107-09:16:03.493(-3) server.js:204 Meteor ➔ publish null -> userId: null, arguments: []_  

**iOS connection log (only this)**

_I20200107-09:17:28.615(-3) server.js:204 Meteor ➔ publish null -> userId: null, arguments: []_

**Comment by TheZLabs** [comment]
I also have this issue with the iOS app. However, if I connect to my VPN first...it works. Using a valid SSL cert from Digicert.

**Comment by TheZLabs** [comment]
Is your SSL cert configured properly? This ended up being my issue. https://www.ssllabs.com/ssltest/

**Comment by diegorafaelc** [comment]
We don't use HTTPS. Our rocketchat server use only HTTP connection.

**Comment by diegolmello** [comment]
It's an Apple recommendation to support only HTTPS: https://developer.apple.com/documentation/security/preventing_insecure_network_connections
You should enable it on your server as well.
