### ISSUE TITLE
Search in iOS client does not provide the Jump to Message option

### ISSUE THREAD

**Issue by alleait** [RocketChat/Rocket.Chat.iOS#2814]
- Your Rocket.Chat app version: latest
- Your Rocket.Chat server version: 1.3.1

Describe the bug
While in Desktop app you can search and jump to message to see more in Android there is no such option , so you cannot see messages send previously or after that message.

To Reproduce
Expected behavior
Have a jump to message button just like the desktop client.

**Comment by diegolmello** [comment]
This repo is deprecated: https://github.com/RocketChat/Rocket.Chat.iOS#important---please-read-this-first

There's an issue on the new repo already: https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/1315
