### ISSUE TITLE
Server not connected

### ISSUE THREAD

**Issue by ntfchris** [RocketChat/Rocket.Chat.iOS#2816]
- Your Rocket.Chat app version: 3.5.2
- Your Rocket.Chat server version: 
- Device (or Simulator) you're running with: simulator iphone 11 pro max

**The app isn't connecting to your server?**

Can I disable SSL in app? so can I use http instead of https?

**Comment by diegolmello** [comment]
Please update your app to >4.0.0.
This repo is deprecated: https://github.com/RocketChat/Rocket.Chat.iOS#important---please-read-this-first
