### ISSUE TITLE
App completely crashes when clicking on top-right icon

### ISSUE THREAD

**Issue by Krinkle** [RocketChat/Rocket.Chat.iOS#2820]
- Your Rocket.Chat app version: 4.6.0.289
- Your Rocket.Chat server version: 3.1.0-develop
- Device (or Simulator) you're running with: iOS 13.4

<img alt="Screenshot" src="https://user-images.githubusercontent.com/156867/78588543-bfd20280-7836-11ea-9483-c20dd6333110.png" width="200"/>

I don't yet know what this will do, but no matter which channel I'm in (public or private, empty or non-empty), and no matter how often I try, the app just crashes completely whenever I tap it – bringing me back to the OS home screen.

**Comment by diegolmello** [comment]
This repo is deprecated: https://github.com/RocketChat/Rocket.Chat.iOS#important---please-read-this-first

Here's the new repo: https://github.com/RocketChat/Rocket.Chat.ReactNative
Here's the fix for this issue: https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/1997

**Comment by Krinkle** [comment]
@diegolmello Thanks. I did see that notice, but I assumed it meant that the app is currently being rewritten – meaning this repo is still behind the app currently promoted in the App Store (e.g. the new repo is a fresh start, and only where you'd file long-term ideas).

The repo is also still pinned from <https://github.com/RocketChat/>. Might want to change that.

Thanks for the quick fix!

**Comment by diegolmello** [comment]
@Krinkle nice tip!
We updated our pins.
Thanks.
