### ISSUE TITLE
User profile picture not shown

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat.iOS#283]
- Your Rocket.Chat app version: 1.0.0 (30)
- Your Rocket.Chat server version: 0.52.0
- Device (or Simulator) you're running with: iPhone 6 Plus

Hey @rafaelks 

i tested the rocket.chat native app with my server, unfortunately where are no user profile pictures shown?

Screenshot:
![img_3791](https://cloud.githubusercontent.com/assets/5877910/22977893/cb47d0e6-f390-11e6-848a-bcb07368b2b3.PNG)

from electron app:
![image](https://cloud.githubusercontent.com/assets/5877910/22977971/1265d7fc-f391-11e6-9069-d42b265bcac7.png)

**Comment by rafaelks** [comment]
@TheReal1604 That's because I'm handling it incorrectly in the app. Just created a new issue to fix it: #284. Thanks for your report! 👍

**Comment by housemaster1987** [comment]
Hello,
We are currently running server version 0.69.2. One of our users is missing her profile picture. We've noticed that profile pictures will disappear from time to time but come back after a short time. This user's profile picture has been missing for weeks. I know this is an old thread, but has anyone else experienced this?

**Comment by rafaelks** [comment]
@housemaster1987 It only happens in the mobile client? Is this avatar an URL or an image uploaded?

**Comment by housemaster1987** [comment]
@rafaelks We are not running a mobile client. Our users are connecting to a server we are hosting internally. The user profiles are synced up with Active Directory and the profile pictures are connected to each user's exchange photo.

**Comment by rafaelks** [comment]
@housemaster1987 This app looks very old... is this a fork of our app or the version from the App Store? Could you try using the version from the App Store?
