### ISSUE TITLE
[NEW] User list in channel

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat.iOS#285]
![image](https://cloud.githubusercontent.com/assets/5877910/22989571/ac7b2ac0-f3b6-11e6-99fd-0cb4bca0977f.png)

There is a need for a list of online / offline users who joined the channel

**Comment by rafaelks** [comment]
@TheReal1604 The back-end guys are changing the API, so this will take a bit longer.

**Comment by TheReal1604** [comment]
@rafaelks some news from the backend guys?

**Comment by rafaelks** [comment]
Yes, we already have the REST API for that.

**Comment by Jamirkhan50** [comment]
Hi @rafaelks  Can u share the API details to get user list

**Comment by Jamirkhan50** [comment]
I am not able to get the list of users under channel.
It gives following warning to me when i run the info API.
"developerWarning=[WARNING]: The "usernames" field has been removed for performance reasons. Please use the "*.members" endpoint to get a list of members/users in a room"

**Comment by rafaelks** [comment]
@Jamirkhan50 These are the APIs that we're using:

```swift
fileprivate extension SubscriptionType {
    var path: String {
        switch self {
        case .channel:
            return "/api/v1/channels.members"
        case .group:
            return "/api/v1/groups.members"
        case .directMessage:
            return "/api/v1/dm.members"
        }
    }
}
```
