### ISSUE TITLE
[Feature Request] Add fav-star to the top near channel

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat.iOS#286]
We need this to get more favorite channels via the app, at the moment you can only favorite a channel on the webinterface

![image](https://cloud.githubusercontent.com/assets/5877910/22989608/db830bb2-f3b6-11e6-880a-3ce87a45459d.png)

**Comment by rafaelks** [comment]
@TheReal1604 This duplicates #172.
