### ISSUE TITLE
[NEW] Show unread message bubble on channel selector

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat.iOS#287]
At the moment there is no indicator that i have unread messages in another channel and i cant see it, because the indicator at the channel selector button is missing. 

![image](https://cloud.githubusercontent.com/assets/5877910/22989764/5d00314c-f3b7-11e6-9f03-10fbda4ae009.png)

**Comment by rafaelks** [comment]
That's a good one! 👍

**Comment by agu3010** [comment]
I'll check this out - under progress

**Comment by rafaelks** [comment]
This is going to be addressed on #731
