### ISSUE TITLE
[NEW] Menu for changing push notification settings

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat.iOS#288]
Menu for changing the push notification on a per channel basis is missing. I think the app gets the settings from the configured settings on the web?
![image](https://cloud.githubusercontent.com/assets/5877910/22989821/8c64d83e-f3b7-11e6-83cc-2748ea9e8d33.png)

**Comment by rafaelks** [comment]
@TheReal1604 Yes, it does. But would be cool have it in the app. 👍

**Comment by djschilling** [comment]
I also want to support this issue. Most users of our chat installation only use the mobile app to work with rocket.chat.

To change any of these settings they always have to go to the Desktop App or website. So most of them don't change it at all, and are frustrated to not get all messages as push.

**Comment by artrmz** [comment]
I have started working on this feature but I do not have any ETA yet when I will finish that.

**Comment by rafaelks** [comment]
@djschilling @artrmz Thank you for your interest guys!

@MarcosSpessatto Can you please confirm if we have a REST API that returns and updates the notification settings from a specific channel?

**Comment by MarcosSpessatto** [comment]
@rafaelks, i opened [this](https://github.com/RocketChat/Rocket.Chat/pull/10128) PR with the two endpoints. Please, take a look.

**Comment by artrmz** [comment]
@MarcosSpessatto Awesome! What about global (user) notification's settings, do we have to use `/api/v1/settings` with a specific id? Is there maybe a list of all possible settings?

**Comment by rafaelks** [comment]
@artrmz You mean, an API to fetch all the public settings? We already have that in the app... it's on `AuthSettingsManager.swift`.

**Comment by artrmz** [comment]
@rafaelks Thanks, will check that out.
