### ISSUE TITLE
[NEW] Support for geolocation messages

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat.iOS#290]
(Where you can send you´re location)

**Comment by rafaelks** [comment]
Nice!

**Comment by rafaelks** [comment]
@TheReal1604 Do you have any example how to send this kind of message?

**Comment by TheReal1604** [comment]
I think like whatsapp it does would be nice. (new option from the + menu) with a little preview of a map.

@rafaelks what you think?

**Comment by rafaelks** [comment]
@TheReal1604 I see... so you don't have `geolocation` messages in your server yet?
