### ISSUE TITLE
Favicon from image preview not shown

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat.iOS#291]
- Your Rocket.Chat app version: 1.0.0 (30)
- Your Rocket.Chat server version: 0.52.0
- Device (or Simulator) you're running with: iPhone 6 Plus

![cb47d0e6-f390-11e6-848a-bcb07368b2b3](https://cloud.githubusercontent.com/assets/5877910/22990041/37928cce-f3b8-11e6-917c-9e53afffb724.PNG)

The favicons from the link previews are not displayed.

**Comment by rafaelks** [comment]
Good catch!

**Comment by rafaelks** [comment]
@TheReal1604 Is this still happening? I guess that the image URL is using HTTP. I'll close the issue for now.
