### ISSUE TITLE
Special formatting in messages break view

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat.iOS#294]
- Your Rocket.Chat app version: 1.0.0 (31)
- Your Rocket.Chat server version: 0.52.0
- Device (or Simulator) you're running with: iPhone 6 Plus

My bot is using special formatting in the messages:

![image](https://cloud.githubusercontent.com/assets/5877910/23010991/aa637bee-f41e-11e6-9fa8-5da1227506d3.png)

And in the app it looks like:

![image2](https://cloud.githubusercontent.com/assets/5877910/23010999/b1763318-f41e-11e6-9ff9-18c4b7043a8d.PNG)

**Comment by Jellyfrog** [comment]
Due to #265

**Comment by rafaelks** [comment]
Closing it since #265 is fixed.
