### ISSUE TITLE
[NEW] Deleted messages not synced properly 

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat.iOS#296]
Mobile version: 1.0.0 (31) 
Server Version: 0.52.0 

If I post something in a channel and delete that message on the web UI it is not correctly synced with the mobile app. 

![](http://i.imgur.com/4orLwMZ.jpg)

(I deleted the "This is a very long text." messages.)

**Comment by rafaelks** [comment]
Added as a improvement. We don't sync deleted messages yet. Thanks for reporting it.

**Comment by rafaelks** [comment]
@TheReal1604 Is this issue still happening?

**Comment by TheReal1604** [comment]
Yes!

Tested with: 0.58.3 and 1.5.0 (102)

**Comment by cardoso** [comment]
Are you sure @TheReal1604 ? When I delete from the web interface, the message is updated with "message removed" in real time on iOS.

Could it be happening occasionally?

**Comment by rafaelks** [comment]
Closing it, looks like it's already fixed in 1.6.0.
