### ISSUE TITLE
Link preview sometimes not working

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat.iOS#297]
- Your Rocket.Chat app version: 1.0.0 (32)
- Your Rocket.Chat server version: 0.52.0
- Device (or Simulator) you're running with: iPhone 6 Plus

![image](https://cloud.githubusercontent.com/assets/5877910/23055437/1865b018-f4e6-11e6-92d8-37e86c2d1d0e.png)

The Link preview is not generated.

**Comment by rafaelks** [comment]
@TheReal1604 I'll have to investigate if the preview is coming from back-end. We only use the preview that comes from the API.

**Comment by rafaelks** [comment]
This isn't working anymore, since we support updates on-the-fly into the messages object.
