### ISSUE TITLE
[BUG] Online Status sometimes not synced properly

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat.iOS#298]
- Your Rocket.Chat app version: 1.0.0 (32)
- Your Rocket.Chat server version: 0.52.0
- Device (or Simulator) you're running with: iPhone 6 Plus

Sometimes the online status is not synced properly between all indicators, you can see this in the screenshot:

![image](https://cloud.githubusercontent.com/assets/5877910/23062136/e9280b10-f504-11e6-9522-fbd815b47dac.png)

You can reproduce the error with the following steps:

- Open the chat, go into a channel
- chat into the private room (user is offline)
- user comes online regarding to your private msg push notification
- Online status on the private chat room is out of sync
- Online Status in channel list is fine

**Comment by rafaelks** [comment]
We're currently not handling the status updates in the Chat screen. Good catch! 👍

**Comment by TheReal1604** [comment]
@rafaelks this is also happening in newer releases (like 1.3.0 (84))

**Comment by TheReal1604** [comment]
The online status indicator seems to be also not synced properly on server switch (all of them).

**Comment by TheReal1604** [comment]
@rafaelks and on 1.3.0 (88)
