### ISSUE TITLE
Authentication failure(eg token expiration) on reconnection attempts is missed.

### ISSUE THREAD

**Issue by gradler** [RocketChat/Rocket.Chat.iOS#301]
- Your Rocket.Chat app version: 0.0.1(30)
- Your Rocket.Chat server version: 0.52.0
- Device (or Simulator) you're running with: Both

When the application switches to the foreground in the background, it tries to reconnect. 
In this case, even if authentication fails, there is no processing and malfunction occurs.

**Comment by rafaelks** [comment]
Thanks for reporting, adding it as a bug.
