### ISSUE TITLE
Send local push notification when user isn't in the app but Socket is connected

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.iOS#305]

**Comment by dgraziotin** [comment]
is this concerning the issue that if the desktop app is open (and in background and/or computer is locked), I do not get notifications on my iPhone?

**Comment by stardothosting** [comment]
Came here to +1 ... would love to get notifications when my screen is locked. I would imagine most people have their iOS device set to auto lock after X minutes.

**Comment by rafaelks** [comment]
Since we disconnect the user when user goes to background, we don't need this anymore.
