### ISSUE TITLE
Always show cached messages instead of loading "dots" animation when switching chats

### ISSUE THREAD

**Issue by carlos-arce-movile** [RocketChat/Rocket.Chat.iOS#306]
Previously opened and cached messages should be preloaded on screen while the app syncs new messages from server (online), avoiding the "loading dots animation" that delay the user reading.
This increases a lot user experience mainly when using slow data connections, like 2G or high-latency 3G (taking more than 5 secs), though using high-speed dedicated links to our server last ~ 1.5-2 sec also bad user experience.
For comparison, when offline (e.g. airplane mode) the user experience is smoother better because the loading animation completes in a fraction of a second.

Suggestion is to show all messages preloaded, allow normal chat history browsing and "append" all new messages when online synced.

#
- Your Rocket.Chat app version: 1.0.1 (33)
- Your Rocket.Chat server version: 0.48.2
- Device (or Simulator) you're running with: iPhone 5S iOS 10.2

**Comment by TheReal1604** [comment]
@carlos-arce-movile Nice suggestions, should be really good for the user experience. I think its important to have a loading animation (maybe on the top of the channel) if there are not all messages synced.

**Comment by rafaelks** [comment]
@carlos-arce-movile Thanks for opening the issue! That's for sure an improvement we'll do! 👍
