### ISSUE TITLE
Attachment field support

### ISSUE THREAD

**Issue by Jellyfrog** [RocketChat/Rocket.Chat.iOS#314]
When using attachment fields an empty message is printed:
![img_1689](https://cloud.githubusercontent.com/assets/759887/23258382/50134426-f9c8-11e6-920a-55374f3fa55b.PNG)

(I know there is only initial support for attachments so this is more like a todo reminder.)

To reproduce:
```bash
curl -X POST -H 'Content-Type: application/json' --data '{
  "attachments": [
    {
      "fields": [
        {
          "title": "Title Title",
          "value": "Text Text"
        }
      ]
    }
  ]
}' https://rocket-chat-hook-url/
``` 

- Your Rocket.Chat app version: 1.0.1 (33)
- Your Rocket.Chat server version: 0.52.0
- Device (or Simulator) you're running with: iPhone 7

**Comment by rafaelks** [comment]
@Jellyfrog Good finding! Is this in our demo server? I would like to join this chat to support it correctly.

**Comment by Jellyfrog** [comment]
@rafaelks sorry it's a private one, don't think its possible to get "incoming webhook"-access to the demo server?

**Comment by rafaelks** [comment]
@Jellyfrog Is this server something I can join into?

**Comment by Jellyfrog** [comment]
@rafaelks see email (the one in your profile)

**Comment by rafaelks** [comment]
@Jellyfrog Thanks! I'll use it to implement.
