### ISSUE TITLE
[NEW] Allow user to see just the mentions of some channel

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.iOS#344]
## General information

The user needs to have another option in our Channel Info screen that will let him see all the messages with mentions to him in a list.

To implement this list, there's already a list of messages being used to display the pinned and starred messages.

### How to request only the mentions

(to be documented).

**Comment by filipealva** [comment]
@rafaelks can you provide a little bit more information on this one?

**Comment by rafaelks** [comment]
@filipealva Yes! Just improved the issue a little bit, but I guess we'll still require one API to be developed. Can you confirm if we have an API that list all the mentions of a channel @MarcosSpessatto?
