### ISSUE TITLE
Google oauth fails

### ISSUE THREAD

**Issue by adam-kulagowski** [RocketChat/Rocket.Chat.iOS#350]
We at codilime.rocket.chat are using Google Oauth as primary way to authenticate our users (it works with web clients, and native android app). However with IOS native application such attempt to log in ends with the error: 400 (see attached screenshot).

- Our Rocket.Chat app version: 1.0.3
- Our Rocket.Chat server version: 0.51
- Device (or Simulator) we're running with: whatever is running on *.rocket.chat cloud :)

![image](https://cloud.githubusercontent.com/assets/15870825/23786642/85d5e418-056e-11e7-845e-5a7a7e11cbce.jpg)

Please let us know if anything more is needed.

**Comment by rafaelks** [comment]
@adam-kulagowski Hey! Thanks for reporting it. We're not showing the correctly alert yet, but can you update your server to the latest version and check if it works? We had to develop a new authentication method for iOS, and it's not in the 0.51. Thank you!

**Comment by adam-kulagowski** [comment]
@rafaelks We are hosting codilime.rocket.chat at Your cloud platform and AFAIK there is no shell access. Is there any way I can do it my self?

**Comment by rafaelks** [comment]
@adam-kulagowski I asked @geekgonecrazy to update it for you. He already done it. Can you try again, please?

**Comment by adam-kulagowski** [comment]
Still the same (error 400). The iPhone in question is: 7+ with IOS 10.2.1 on board.  The user in question was: krzysztof.klimonda and he tried to log around 12-III 7:30PM CET.

**Comment by rafaelks** [comment]
@adam-kulagowski Just to mention that I'm investigating the issue. Will try to reply to you ASAP.

**Comment by rodrigok** [comment]
Hi @adam-kulagowski, the google login with iOS only works with our current develop version. We will release a new version today, as soon we release the new version I will update your server and let you know.

Thanks.

**Comment by rafaelks** [comment]
@rodrigok Thank you!

**Comment by adam-kulagowski** [comment]
That's a great news. 
Is there any ETA regarding new version as on the web page (and on the cloud) there is still 0.53 listed as the latest.

**Comment by geekgonecrazy** [comment]
@adam-kulagowski i've updated yours to the latest version 0.54.1

**Comment by adam-kulagowski** [comment]
Hi,

I can confirm - iPhone+Google Auth works correctly with 0.54.1

**Comment by rafaelks** [comment]
@adam-kulagowski That's awesome! Thank you @geekgonecrazy and @rodrigok!
