### ISSUE TITLE
Rocket.Chat+ not loading (spinning wheel on URL)

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat.iOS#371]
Rocket.Chat Version: 0.54.0
iOS Version: 10.2.1 (iPhone), 9.3.5 (iPad)
Rocket.Chat+ Version: 1.0.4

Just installed RC+ on my Devices (not tested with any RC instance before 0.54). But when entering the correct URL, I just see a spinning wheel. Neither local network nor LTE works. Wrong URLs will show error message, so connection from App to server somehow works. Regular Rocket.Chat App works, just the "plus" App not.
![img_9879](https://cloud.githubusercontent.com/assets/193273/24228211/2814ca6a-0f73-11e7-92af-f44a9a46fcca.PNG)

**Comment by rafaelks** [comment]
@soundstorm It worked? I was testing it.

**Comment by soundstorm** [comment]
Yep, see https://github.com/RocketChat/Rocket.Chat/issues/6435

**Comment by rafaelks** [comment]
Great, thanks @soundstorm!
