### ISSUE TITLE
application crash

### ISSUE THREAD

**Issue by nORKy54** [RocketChat/Rocket.Chat.iOS#404]
- Your Rocket.Chat app version: 2.5.0
- Your Rocket.Chat server version: 0.54.2
- Device (or Simulator) you're running with: IOS, iPhone 6S, latest IOS public version

The IOS application crash when playing a mp3 file.

**Comment by rafaelks** [comment]
@nORKy54 Hey, thank you for opening the issue. Can you describe more about the crash? For example: where are you playing the mp3 file? Is it in the app or other apps? Can you record a video and send us? Do you have some crash log?

Thank you!

**Comment by rafaelks** [comment]
Closing, because I don't have more info.
