### ISSUE TITLE
[NEW] Support OTR in private Conversations

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat.iOS#405]
(or something other end-to-end encryption)

**Comment by Aktariel** [comment]
Looks like Signal is in process: https://rocket.chat/blog/mrinal-dhar-developing-end-to-end-encryption-with-signal-protocol

**Comment by CineXMike** [comment]
That is only in webversion.

**Comment by rafaelks** [comment]
With E2E being implemented for 3.3.0, we can close this one.
