### ISSUE TITLE
[sandstorm] notifications not working 

### ISSUE THREAD

**Issue by rawwerks** [RocketChat/Rocket.Chat.iOS#409]
we finally got rocket chat working on mobile with sandstorm, but the only problem is that the notifications are not working for anyone on our team. 

- Your Rocket.Chat app version: 2.5.0
- Your Rocket.Chat server version: 0.52.0
- Device (or Simulator) you're running with: iOS 10.2.1

server logs have a whole lot of this:  app.js:401 [31mSystem ➔ error Error sending push to gateway (3 try) -> { [Error: tunneling socket could not be established, cause=Parse Error] code: 'ECONNRESET' } 

push gateway was: https://gateway.rocket.chat, the default. test pushes show 'successfully pushed to 1 device' on the admin panel, but the pushes never come through and the logs show the error above. (i also tried https://rocket.chat as the gateway to no avail, referencing https://github.com/RocketChat/Rocket.Chat/issues/4527)

**Comment by mguide** [comment]
I am also experiencing this issue with RocketChat on my iphone. Same app version, server version, and operating system as original poster. I have notifications turned on for the app and in each channel I made sure that Mobile notifications was set to "all messages". 

Any help on this issue would be much appreciated. My team wants to use this as our primary messaging app, but not being "ping'ed" by notifications in realtime is preventing us from using the app effectively.

Thanks!

**Comment by rafaelks** [comment]
@rawwerks @mguide You're all using the Cordova version of the app, not the native, right? If yes, this isn't the correct repository. This is: https://github.com/RocketChat/Rocket.Chat.Cordova.

**Comment by rawwerks** [comment]
@rafaelks - on mobile i'm just using the version in the app store...which i thought is this one. am i wrong? on the server side we're using sandstorm.

**Comment by rafaelks** [comment]
@rawwerks We have two version of the app in the App Store: `Rocket.Chat` and `Rocket.Chat+`. Which one are you using?

**Comment by rawwerks** [comment]
@rafaelks Rocket.Chat , will try the other to see if this is fixed there...

**Comment by rafaelks** [comment]
@rawwerks What's the server URL?

**Comment by rawwerks** [comment]
it is a custom generated url generated by sandstorm that is unique to that grain. @kentonv - any thoughts here? we really need notifications to work with rocket chat, it completely changes the usability without it.

**Comment by rafaelks** [comment]
@rawwerks Are you using our servers to send the push? Because to use the native app, you'll have to use our servers to send the push (as a middleware, because we have the certificates, etc).

**Comment by rawwerks** [comment]
@rafaelks - the push gateway in the settings is  https://gateway.rocket.chat - is that what you mean?

**Comment by kentonv** [comment]
See https://github.com/RocketChat/Rocket.Chat.Cordova/issues/183#issuecomment-294185142

**Comment by rafaelks** [comment]
@rawwerks @kentonv Thank you! Closing the issue here, it seems to be related to the Cordova app.
