### ISSUE TITLE
Update badge with the number of alert messages

### ISSUE THREAD

**Issue by netpages** [RocketChat/Rocket.Chat.iOS#411]
notification badge is not updated, it shows all the time "1"

- Your Rocket.Chat app version: 1.0.6
- Your Rocket.Chat server version: 0.54.2
- Device (or Simulator) you're running with: iPhone 7 Plus

**Comment by soundstorm** [comment]
Also the messages from the notification center are not ack'ed so they'll stay until you delete them manually (would be nice to mark them as acknowledged when switching to the channel). New issue or same as this? 😛

**Comment by rafaelks** [comment]
@soundstorm Yes, that's included. But thanks for letting me know! 👍
