### ISSUE TITLE
Persist credentials and add "retry" authentication function

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat.iOS#414]
- Your Rocket.Chat app version: 1.0.6
- Your Rocket.Chat server version: 0.54.1
- Device (or Simulator) you're running with: iPhone 6 Plus

hey @rafaelks ,

I think a persistence of the user credentials between updates could be nice (or is this bug related to testflight updates?) and sometimes if i take the app from the background in the foreground, I get these error page with "User not authenticated" "try connecting to another server". There also should be a button for retrying the authentication, at the moment I only close the app and restart it.

**Comment by rafaelks** [comment]
@TheReal1604 Yes, that's a nice feature we must have. Thanks for opening the issue!

**Comment by TheReal1604** [comment]
@rafaelks The persistence now works fine 👍 . So we only need the "retry login" button.

**Comment by rafaelks** [comment]
@TheReal1604 Yes, but we still need a "Retry" button for cases when user can't connect into the server when the app starts.

**Comment by rafaelks** [comment]
This can be closed now since we support offline reading.
