### ISSUE TITLE
Dismiss the keyboard (by scrolling or tapping elsewhere)

### ISSUE THREAD

**Issue by UsmanArbisoft** [RocketChat/Rocket.Chat.iOS#418]
Tap anywhere to dismiss the keyboard. Or have a 'scroll to dismiss' kind of experience like other messaging apps (e.g. the native messaging app or WhatsApp)

- Your Rocket.Chat app version: 1.0.6 (46)
- Your Rocket.Chat server version: 0.54.2
- Device (or Simulator) you're running with: iPhone 7, iOS 10.1.1

**Comment by rafaelks** [comment]
That's a good one, thanks!
