### ISSUE TITLE
Badge app icon is not clearing

### ISSUE THREAD

**Issue by arahlin** [RocketChat/Rocket.Chat.iOS#435]
I received a couple one-on-one messages that sent notifications (as expected), and set the badge app icon.  Upon reading and responding to the messages, the badge app icon did not clear, and still hasn't cleared after nearly 24 hours, even though I have no more unread messages.  This happened while I was running version 1.0.7, and persists after updating to 1.0.8 today.

- Your Rocket.Chat app version: 1.0.7/1.0.8
- Your Rocket.Chat server version: 0.55.1
- Device (or Simulator) you're running with: iPhone 7

**Comment by rafaelks** [comment]
Thanks for reporting it! We definitely need to keep the badges synced with the unread messages.

**Comment by floridabrits** [comment]
I have this problem too and it's quite irritating ;-)  Any idea when you might have a resolution available for this one...  Happy to show you the issue if you need more info... Thanks!

**Comment by rafaelks** [comment]
Closing this issue, was fixed already and is going to be included on next release.

**Comment by navigosgroupjsc** [comment]
Hello I have this issue today, any idea on how to solve it? Mobile app works properly but app doesn't.

**Comment by soobax** [comment]
Same issue on Mac OS. And the 'unread messages' line doesnt go away even after I've opened them.

**Comment by reaact** [comment]
I have this issue as well. Rocket.Chat+ Version 2.12.0

**Comment by kaiiiiiiiii** [comment]
Please stop spamming this closed issue! Your problem is related to the Electron App, not to the iOS App ...

The issue Mac Electron issue was already reported and will be fixed in the next release.
