### ISSUE TITLE
Newest messages not visible if app comes from background

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat.iOS#436]
- Your Rocket.Chat app version: 1.0.8 (52)
- Your Rocket.Chat server version: 0.55.0
- Device (or Simulator) you're running with: iPhone 6 Plus

If i access the app from the background and i open a channel - the newest messages are not displayed. If I write a message or access the channel again, the newest messages are displayed.

**Comment by rafaelks** [comment]
Thanks for reporting @TheReal1604!

**Comment by TheReal1604** [comment]
Additionally on the new TestFlight release this is happening if I access a channel for the first time. 
(It is displayed empty) Then I access the channel again via the sidebar it is updated and all messages are visible. @rafaelks should I open a separate issue for this one? 

![](http://i.imgur.com/As7P17k.jpg)

**Comment by rafaelks** [comment]
@TheReal1604 Fixed both in the same PR, will send a new beta build soon so we can play with it again.
