### ISSUE TITLE
[NEW] Support deep links

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.iOS#440]
Idea coming from https://github.com/RocketChat/Rocket.Chat/issues/6820

### Authentication
> rocketchat://auth/?token=foobar&host=foo.bar&userId=foobar123

### Server + Chat
> rocketchat://room/?host=foo.bar&rid=foobar123

**Comment by cardoso** [comment]
I think this needs some discussion with @RocketChat/core so we agree on a standard that is possible to be implemented across all platforms.

**Comment by geekgonecrazy** [comment]
For sure!  Because on electron it's actually I think: rocketchat://host?ssl=true or something to that nature.  But host always first

**Comment by cardoso** [comment]
Blocked by https://github.com/RocketChat/Rocket.Chat.Operations/issues/149

**Comment by soundstorm** [comment]
@cardoso can we then deeplink mentions and channels in messages not only highlight them? 😏

**Comment by cardoso** [comment]
I think it's definitely possible @soundstorm :)

**Comment by szab100** [comment]
@rafaelks Is this still only in 'develop' branch? When will this be released? I tried on the latest available app from App Store and it's not working yet (rocketchat://room?host=...&rid=...)

**Comment by rafaelks** [comment]
@szab100 Yes, it's on the App Store build. Have you tried with a valid `rid` and a valid `host`?

**Comment by szab100** [comment]
@rafaelks Thanks for the quick answer! Sorry, was my fault, I messed up the link. Tried again, works now! Is there any documentation how the auth deeplink works? Which token we need to pass? Can it be combined with rid=.. ? Do these work on Android as well? Thank you!

**Comment by rafaelks** [comment]
@szab100 Yes, here's the documentation: https://rocket.chat/docs/developer-guides/deeplink/.

**Comment by seybsen** [comment]
Is deeplinking to DM a specific user possible? I'm not sure because it's mentioned in the headline of the docs section but no example is given.

**Comment by diegolmello** [comment]
@seybsen this [repo is deprecated](https://github.com/RocketChat/Rocket.Chat.iOS#important---please-read-this-first) and this issue is closed.
You can relate to https://github.com/RocketChat/Rocket.Chat.ReactNative/ for issues on mobile.

**Comment by karthikindia** [comment]
i have installed a fork of rocket chat, where can i change my deep url to my own server
