### ISSUE TITLE
Save Mobile Bandwidth Option

### ISSUE THREAD

**Issue by kormic** [RocketChat/Rocket.Chat.iOS#45]
Can someone please explain to me what is exactly the option Save Mobile Bandwidth? Is this the case which if this is true you can only use wifi and not your mobile data?

**Comment by geekgonecrazy** [comment]
In the context of the main Rocket.Chat web app.  It is preventing the loading of images automatically etc.  Doing little things to prevent eating un-needed data.

**Comment by kormic** [comment]
So I guess this is only for the web app and not the mobile one???

**Comment by kormic** [comment]
Is this taking action on the server or locally?

**Comment by gsaslis** [comment]
@kormic i'm not sure this should be closed?

on mobile especially, when you're out and about - with poor signal - it is even more important to have this option!!  ; )

**Comment by kormic** [comment]
@gsaslis  I just closed this because I marked it as a question. I thought I had to create another issue with a different label but I will just reopen this and change the label (duh!)
