### ISSUE TITLE
Markdown on URLs

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat.iOS#458]
Current behaviour is to format URLs like .../download_this_fine_file.pdf like .../download _this_ fine_file.pdf (without the whitespaces). So the parser seems to be a bit too aggressive. Happening in 1.1.0 as far as I can test.

**Comment by rafaelks** [comment]
@soundstorm Thanks for opening the issue!

**Comment by haakoo** [comment]
I encountered a similar problem today, that a `'` in a google URL escaped the rest of the url, e.g.:

https://www.google.no/maps/place/59°54'30.7"N+10°45'05.9"E/@59.908534,10.7500924,17z/data=!3m1!4b1!4m5!3m4!1s0x0:0x0!8m2!3d59.908534!4d10.75164

https://www.google.no/maps/place/59%C2%B054'30.7%22N+10%C2%B045'05.9%22E/@59.908534,10.7500924,17z/data=!3m1!4b1!4m5!3m4!1s0x0:0x0!8m2!3d59.908534!4d10.75164


Same URL, one from the address field in the browser, the second from "share link" field.

The first escapes after the `°` and the second after the `'` symbol.

**Comment by haakoo** [comment]
Maybe the solution is to wait for a space before parsing anything when detecting an URL?

**Comment by rafaelks** [comment]
@haakoo Thanks for your comment! That makes sense!

**Comment by haakoo** [comment]
I've later realised that space is a valid character in an URL... how about looking at how CommonMark handle URLs?

**Comment by soundstorm** [comment]
Spaces occurr only as `%20` in urls. No no Problem at all. It get's more tricky with brackets, eg `(see http://example.org/)`
