### ISSUE TITLE
App is crashing if multiple high-res pictures in channel

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat.iOS#459]
- Your Rocket.Chat app version: 1.1.1 (60)
- Your Rocket.Chat server version: 0.55.1
- Device (or Simulator) you're running with: iPhone 6 Plus

We have a photography club which uses rocket.chat for exchanging photos and making votes on this photos. We have an upload limit of 5MB per picture. In 1 Channel we have many pictures around 2-5MB. If the mobile app is loading the previews it crashs if I try  to interact with the channel (like trying to write a message).

**Comment by rafaelks** [comment]
I'll investigate it, thank you @TheReal1604.

**Comment by nhy656** [comment]
Its highly possible that is connected with use of cocoapod "SDWebImage".

I had very bad experience with that.
That lib consumed 1 000 MB of ram, while it was only caching about 100 images x 2MB.
I don't know how they did this and probably don't want to know ;)

I migrated to YYWebImage, and it fixed all problems. Both are opensource so you can see code ;) I like code of YYWebImage much more.  
(however YYWebImage has less options)

Also writing your own disk cache for images is simple and might be good enough.

**Comment by rafaelks** [comment]
@nhy656 Thanks for the suggestion! I'll take a look at this lib and give it a try.

**Comment by rafaelks** [comment]
@rodrigok Are we planning to have thumbs/resized images soon? Downloading 5MB images is a killer for any application that wants to run smoothly. If we're not planning that, I'll have to work on something to shrink the size of the image client-side.

**Comment by rodrigok** [comment]
@rafaelks we plan to save the image thumb, extra small, in message as base64 then you can show the blurred image and the button to download the original one like whatsapp does.

We can prioritize this, but it will take some time to develop and will not support old instances.

What about the `click to load image` as we have in our cordova version? Almost like the whatsapp solution without the blurred image behind, and you can put the blurred image when available in the near future.

**Comment by TheReal1604** [comment]
@rodrigok really good idea. A "click to load image" would be a great solution for this.

**Comment by rafaelks** [comment]
@rodrigok @TheReal1604 Yes, but I think not showing a preview right now for most of the cases isn't cool... I would say: let's wait until we support the extra-small thumb and implement this feature.

But anyway, I think would still be good have a "large" (500x500) size of the image, to be automatically downloaded when user is on Wi-Fi, for example, and only download the original asset when user actually taps into the image.

What do you think?

**Comment by TheReal1604** [comment]
@rafaelks Tested this with the app version 1.3.0 (88) and it is not crashing anymore. Fixed for me!
