### ISSUE TITLE
Specify hostname when signing in

### ISSUE THREAD

**Issue by jimmccusker** [RocketChat/Rocket.Chat.iOS#46]
The currently deployed rocket.chat app doesn't let you specify the host to connect to, but one of the major advantages of rocket.chat is being able to set up your own server. Ideally, users should be able to have accounts logged in on multiple servers as well.

**Comment by rodrigok** [comment]
@jimmccusker are you talking about the Rocket.Chat Desktop app or Mobile app?

**Comment by jimmccusker** [comment]
I'm talking about the iOS mobile app.

**Comment by rodrigok** [comment]
@jimmccusker sorry, I didn't look at the repository name, yes the current app for iOS is basically a webview pointing to demo.rocket.chat, we are working in a new version of hybrid app to enable multiple servers like we have in the Desktop app.

This project (native iOS app) will have this feature too.

**Comment by gsaslis** [comment]
a cool way to implement this (later on, after we have a stable v1.0.0) would be for the server to have a QR code that you can scan from the native iOS app   ; )

**Comment by Sing-Li** [comment]
:+1:  Awesome.  For android + cordova (and even Electron) as well. And optionally enter a code for devices with crappy camera or QR scanner app that crashes all the time :smiley:

**Comment by jimmccusker** [comment]
Or, just the hostname. We set up a fairly simple one that I can just tell people verbally. :-)

**Comment by Sing-Li** [comment]
support can be a BIG problem, especially with large installs, if end-users (of all non-computer background) enter raw hostnames.  Bascially when it doesn't work (and the thing SAVED it for all future access) ... the phones will be ringing.   Just IMHO.

**Comment by jimmccusker** [comment]
That's why you need to set up up-front validation of the hostname. When initial sign-in doesn't work, you let them know. The sign in/registration process should have the triple (with a default of https://rocket.chat) of URL, username, and password.

**Comment by felixwidjaja** [comment]
+1 on this one.

**Comment by carlyleec** [comment]
+1

**Comment by adairs** [comment]
+1 (from several of us). Definitely would like to see the IOS app allow a server to be specified so we can connect to our own instance.

**Comment by iMHLv2** [comment]
+1....really looking forward to this feature

**Comment by Megatronic79** [comment]
+1

**Comment by jclabaugh** [comment]
+1

**Comment by flsf** [comment]
+1

**Comment by flashguy22** [comment]
+1

**Comment by Sing-Li** [comment]
Implemented in currently beta-ing mobile clients. On Cordova project. Closing issue.

**Comment by jimmccusker** [comment]
How do we participate in the beta?

**Comment by tholu** [comment]
+1 (for native iOS - works in Cordova project)

**Comment by felixwidjaja** [comment]
I really can't wait to have this feature.

**Comment by tholu** [comment]
@felixwidjaja Try to sign up for the beta programm (support@rocket.chat) with the subject "iOS Beta testing" - worked for me :)
