### ISSUE TITLE
[NEW] Support SAML

### ISSUE THREAD

**Issue by isometry** [RocketChat/Rocket.Chat.iOS#461]
Our Rocket.Chat Cloud instance is configured for SAML-only authentication, with Accounts / "Show form-based Login" set to False and Accounts / Registration / "Registration Form" set to Disabled. Through the web and the Cordova client, all works as expected. However, when connecting with the Rocket.Chat+ iOS client, the SAML login button is not shown and only an unbranded form-based login option is presented, along with a link to "Create new account".

- Your Rocket.Chat app version: 1.1.0
- Your Rocket.Chat server version: 0.55.1
- Device (or Simulator) you're running with: iPhone 7 Plus

**Comment by rafaelks** [comment]
Thanks for opening the issue, the app really doesn't support all that yet.

**Comment by patrickhanft** [comment]
According to https://github.com/RocketChat/Rocket.Chat.Android/issues/230#issuecomment-334482385 the corresponding issue should be addressed soon in the Android app. Does that mean, it will be handled here in the iOS version accordingly?

**Comment by rafaelks** [comment]
@patrickhanft  Yes, it will be support in iOS as well. 👍

**Comment by rafaelks** [comment]
Part of this issue is being fixed in #850

**Comment by thef1sh** [comment]
The 'Cordova' apps had a troubling update to the README file saying that their apps will be deprecated at the end of March. For those of us using these auth methods, if deprecated means delisted, we're without a mobile app for our instance unless this is resolved.

**Comment by rafaelks** [comment]
@thef1sh We'll support all the authentication methods by March. 👍

**Comment by rafaelks** [comment]
@thef1sh (and all following this topic) What authentication methods are you guys using? If you're using ANY that's not implemented yet, please say it here and if you have a server that we could use to test (specially SAML and CAS), it would help **a lot**.

**Comment by patrickhanft** [comment]
@rafaelks we use SAML authentication on "chatbegruenung.de", where we as enthusiasts provide the Rocket.Chat server, while the SAML authentication service is not managed by us (and we don't have to think about user accounts). 

Please feel free to test against this. If you need any more information, please contact me!

**Comment by mrsimpson** [comment]
+1 for SAML

**Comment by cardoso** [comment]
@mrsimpson @thef1sh @patrickhanft @isometry 

Can you guys help us test it? #1255

**Comment by cardoso** [comment]
@mateusmedeiros @jandubois tagging you guys who +1 the issue :)

**Comment by isometry** [comment]
@cardoso Any chance of a TestFlight build for testing?

**Comment by cardoso** [comment]
We're sending one soon today @isometry 

If you dont have access to our TestFlight yet, please send me your Apple ID at https://open.rocket.chat/direct/matheus.cardoso
