### ISSUE TITLE
Datetime mark above messages is not displayed correct

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat.iOS#466]
- Your Rocket.Chat app version: 1.1.0 (57)
- Your Rocket.Chat server version: 0.55.1
- Device (or Simulator) you're running with: iPhone 5c

If I access a group chat the mark above the chatmessages on which day the message is written is missing.

**Comment by rafaelks** [comment]
@TheReal1604 Is this issue still happening? Can you provide more info?

**Comment by TheReal1604** [comment]
@rafaelks It's working fine now! Thanks.

**Comment by rafaelks** [comment]
Closing it, thanks @TheReal1604!
