### ISSUE TITLE
Badge App Icon of Push Notifications does not disappear

### ISSUE THREAD

**Issue by cpoetter** [RocketChat/Rocket.Chat.iOS#471]
First of all thanks for this awesome app! I love it! But I have a problem with the push notifications. Once I receive them the Badge App Icon (the "1" on the top right of the App Icon) does not go away. Even after I open the App, read the new message, delete the message in the notification center. Only a restart of the iPhone helps. I can reproduce it to 100% with every message I receive.

I use the official Rocket.Chat+ version from the App Store.

- My Rocket.Chat app version: 1.1.0
- My Rocket.Chat server version: 0.55.1
- Device (or Simulator) I'm running with: iPhone 6s

**Comment by cpoetter** [comment]
Oh I see just now this is already reported: [Badge app icon is not clearing](https://github.com/RocketChat/Rocket.Chat.iOS/issues/435)

And maybe even fixed with the commit? [Update badge with all unread](https://github.com/RocketChat/Rocket.Chat.iOS/commit/81b2130313131ed536b9e3090d9ccbb036ff1864)

**Comment by rafaelks** [comment]
Hey @cpoetter, thanks for your feedback! :-)

Yes, you're right, this is fixed on the build we're submitting today (1.1.1).

I'm closing the issue.
