### ISSUE TITLE
Import File From does not work

### ISSUE THREAD

**Issue by cpoetter** [RocketChat/Rocket.Chat.iOS#472]
As the title says already, the `Import File From...` button does not work for me. Nothing happens if I click it, besides the dismiss of the `Take Photo, Choose From Library, Import From File..., Cancel` overlay.

- My Rocket.Chat app version: 1.1.0
- My Rocket.Chat server version: 0.55.1
- Device (or Simulator) I'm running with: iPhone 6s

**Comment by rafaelks** [comment]
This issue was closed in #568
