### ISSUE TITLE
[BUG] In very rare cases a message written in the app is never sent to the server

### ISSUE THREAD

**Issue by martinvonwittich** [RocketChat/Rocket.Chat.iOS#473]
- Your Rocket.Chat app version: 1.1.0 (57)
- Your Rocket.Chat server version: 0.55.0-rc.6
- Device you're running with: iPhone 6s (model MKQP2ZD/A), iOS 10.3.1 (14E304)

Hi, I sent a message to one of our channels this morning at 09:26 UTC+2, but it apparently never left my phone - it is now 11:35 UTC+2, but the iOS app still displays the message with grey text, and nobody else can see the message. It also won't show up in other clients, e.g. on my desktop client. The app seemed to have a connection to the server though, because a message from another person in the channel 25 minutes later was received just fine. I then tried to restart the app, but that didn't have any effect - the message remains unsent.

I've attached a redacted screenshot of our channel; I took care to redact it in a way where you can still see the original text color. Note that my message at 09:26 is grey, while all others are black: https://cloud.githubusercontent.com/assets/6863569/26147838/09f9005c-3af5-11e7-9e3c-7f2552a6f90c.PNG

As this was the first time this has happened after using Rocket.Chat for about a month, I assume that this is a bug that occurs only very rarely.

**Comment by rafaelks** [comment]
@martinvonwittich Thanks for reporting it, will take a look and try to reproduce.

**Comment by dgraziotin** [comment]
Same issue here, actually while trying the mobile app for the first time. Messages written on the mobile app do not appear on the desktop app (as chat history) as well.

Your Rocket.Chat app version: 1.1.1
Your Rocket.Chat server version: 0.56.0
Device you're running with: iPhone 7 Plus (model MN4M2M2ZD/A), iOS 10.3.2 (14F89)

**Comment by kmindi** [comment]
There should be no case where messages are lost or percieved as sent while they are actually not!
This needs to be fixed **asap**. Otherwise users loose trust in this app or even in RocketChat.

Does it have to do with the `fileprivate func sendMessage()` adding the message to the realm db before knowing it has been sent? in https://github.com/RocketChat/Rocket.Chat.iOS/blob/master/Rocket.Chat/Managers/Socket/SocketManager.swift

**Comment by rafaelks** [comment]
@dgraziotin Thanks for your feedback!

@kmindi You're right, it needs to be fixed ASAP. Working on it today. 👍

**Comment by kmindi** [comment]
I experienced the same issue but I don't remember weather it was in the Android App or the Browser Page. So maybe this is not a client app problem. But I can't debug it afterwards now of course. I have not yet tried reproducing this behavior, and I don't see any issue on the main repo.

**Comment by rafaelks** [comment]
This one should be fixed with #830.
