### ISSUE TITLE
Login need two confirmations

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat.iOS#482]
- Your Rocket.Chat app version: 1.1.1 (62)
- Your Rocket.Chat server version: 0.56.0
- Device (or Simulator) you're running with: iPhone 6 Plus

If I try to login i need to confirm the login prompt twice (the account information is filled correctly).

So to reproduce it just try:

- fill in the server URL -> Login form appears
- fill in the account information, press on "Open" -> keyboard disappears
- click in the account name field 
- click again on "open" 
- now it does login

**Comment by rafaelks** [comment]
@TheReal1604 I'm not sure I understood your issue... can you explain with more details? Maybe a video?

**Comment by marbetschar** [comment]
Same issue here, video below. Please not I have to submit the user form twice in order to successfully login.


[RocketChatDoubleLogin.zip](https://github.com/RocketChat/Rocket.Chat.iOS/files/1028313/RocketChatDoubleLogin.zip)

**Comment by marbetschar** [comment]
@rafaelks all the times. Don't know if it matters that I never enter the protocol (https://) though.

**Comment by rafaelks** [comment]
@marbetschar It should not be that, but if you add the `https://` to the URL, it works just fine?

**Comment by marbetschar** [comment]
@rafaelks what's the issue? I think it doesn't  behave the way it is expected anyways, as you can see in the video...?

**Comment by rafaelks** [comment]
@marbetschar Yes, there's a bug. I just want to know that, if you try with `https://` does it work just fine?

**Comment by TheReal1604** [comment]
Thanks Guys for following on this issue! @rafaelks I tested it with https:// and its **NOT** working.
