### ISSUE TITLE
New version of RocketChat+ app truncates some messages.

### ISSUE THREAD

**Issue by gregs007** [RocketChat/Rocket.Chat.iOS#497]
I can't work out why a message gets truncated, but the new version (1.1.1) now truncates avery 4th or 5th message. Logging in via mobile web browser shows entire message. Sometimes this coincides with quotation marks, sometimes it doesn't. It doesn't appear to be message length related, as even some short messages are affected.

- Your Rocket.Chat app version: 1.1.1
- Your Rocket.Chat server version: 0.56.0
- Device (or Simulator) you're running with: iOS 10.3.2 (also happened on 10.3.1) iPhone 6

**Comment by rafaelks** [comment]
Good catch! I guess this is related to the font-size that I've changed. Thank you!
