### ISSUE TITLE
[NEW] Custom Oauth not working in latest app

### ISSUE THREAD

**Issue by bstillman** [RocketChat/Rocket.Chat.iOS#499]
It appears Custom Oauth is not working in this version of the app. It does on the old app (Rocket.Chat without the +). The button doesn't appear on the login screen at all. 

![img_6790](https://cloud.githubusercontent.com/assets/5289825/26472377/c72f4396-4173-11e7-9d9b-29668b870753.PNG)

- Your Rocket.Chat app version: 1.1.1
- Your Rocket.Chat server version: 0.56.0
- Device (or Simulator) you're running with: iPhone 6+

**Comment by rafaelks** [comment]
@bstillman We don't support it yet, I'll let this issue opened until we implement it. Thank you!

**Comment by kmindi** [comment]
Is there a plan for the implementation of this feature? 😄
Our RocketChat has OAuth as the only login method (with one specific application) and our iOS users can't login (except if setting a custom/explicit password for the account created with OAuth, but this workaround defeats the purpose of having OAuth and users remembering only one login)

**Comment by rafaelks** [comment]
@kmindi Yes, we want to support more oAuth, including the custom one. This is high priority for us, I would that this is the next feature after fixing #442.

**Comment by kmindi** [comment]
as #442 was closed recently, when can we use OAuth, is there any help you need?

**Comment by rafaelks** [comment]
@kmindi Yes, we do need help to support all the OAuth methods! 😄
