### ISSUE TITLE
[NEW] Web conference support

### ISSUE THREAD

**Issue by ToniIltanen** [RocketChat/Rocket.Chat.iOS#507]
Is there any news on ability to join Web conference (Jitsi Meet)
A embedded jitsi meet would do the job like it does on the actual Rocket.Chat (+ electron), now it requires the separate Jitsi Meet -app on the phone. Also, the "Click to join!" -links from a started web conference are not visible, so users must share the link separately to the channel for mobile users to join.
If the web conference cannot be done embedded inside the app, it would be good that the "click to join!" -button would redirect straight on the the jitsi meet link.

**Comment by rafaelks** [comment]
Closing this one from #672.

**Comment by asshewale** [comment]
Hi @ToniIltanen  How did you aceived the video conference(Jitsi) with in Rocket Chat...? I am stuck on same issue, 

Please see my question 
https://github.com/RocketChat/Rocket.Chat.iOS/issues/1057

Your help will be highly appreciated.
