### ISSUE TITLE
Rocket.Chat+ doesn't display backslashes

### ISSUE THREAD

**Issue by pshute** [RocketChat/Rocket.Chat.iOS#510]
- Your Rocket.Chat app version: 1.1.2 (67)
- Your Rocket.Chat server version: 0.55.1
- Device (or Simulator) you're running with: iPad 4, iOS 10.3.2

Backslashes in messages, e.g. in a Windows path C:\windows\system32, are not displayed in Rocket.Chat+. They display ok in the other Rocket.Chat app, and in Firefox on a PC.

**Comment by cardoso** [comment]
@pshute thanks for submitting the issue!

This was fixed by PR #637!
