### ISSUE TITLE
App hangs when loading channels with long history

### ISSUE THREAD

**Issue by arahlin** [RocketChat/Rocket.Chat.iOS#512]
- Your Rocket.Chat app version: 1.1.2
- Your Rocket.Chat server version: 0.56.0
- Device (or Simulator) you're running with: iPhone 7, iOS 10.3.2

I'm finding that the app hangs reliably when I navigate to or from a channel with a long history buffer.  I cannot scroll, write messages or even move to other channels until the channel history is fully loaded (or at least, I assume that's what's taking so long).  The time recover is so slow -- at least a full minute every single time I go into the app -- that this app is basically unusable for me.  I don't know what the history threshold is, but I have noticed that the channels that are rarely used by my team don't seem to have this same problem.

**Comment by arahlin** [comment]
I should add that the desktop app doesn't seem to have this problem.

**Comment by rafaelks** [comment]
@arahlin Thanks for opening the issue! This is definitely an improvement that we want to do.

**Comment by TheReal1604** [comment]
@rafaelks Thats something we discussed earlier. Maybe related to the internal database that fills to a level it decreases the performance.

**Comment by thiesschneider** [comment]
This behaviour is really bad and it makes the app more and more unusable.
Is there anybody working on this? 
To illustrate I can write down the normal behaviour:
I am opening the app. And then I have to wait for 14 seconds to see something. But this is anywhere on the timeline of the conversation and I am not able to press any buttons or scroll. Then I have to wait another 21 seconds until I see the last messages. Now it depends on my Internet connection how long I have to wait until I can write. On my home wifi I can write after ~5 seconds, when I am using LTE it can be up to 15 seconds. 
When I press send I have to wait another 5-10 seconds until the message is sent.
In this channel I am frequently using there are 12405 messages at the moment. But also another one with 562 messages does not change the time I have to wait.

Is the solution to use the Rocket.Chat app instead of the Rocket.Chat+ app?

**Comment by thiesschneider** [comment]
not the best solution. but works for some time...
Is there somebody working on a solution for "normal users"?

**Comment by rafaelks** [comment]
@thiesschneider I'm sorry about that... not for the next release, but certainly we'll be working on this very soon.

**Comment by reekob** [comment]
@rafaelks any chance of this being prioritised? The iOS app is unusable like this :(

**Comment by rafaelks** [comment]
@reekob What's actually happening for you? When you change between rooms it freezes the app? Would be very helpful if you could send us a video.

**Comment by ampyx** [comment]
I experience similar behavior on an iphone 7. The application is terrible slow on start, comeback from background or switch to a channel with a longer history. Each reply also takes about 5 seconds which makes the app unusable. We are are now using the browser version instead, which is somewhat faster. 

Perhaps it would be an idea to only load the channel messages up to a certain point, instead right now the channel buffer is filled with all the history.

**Comment by reekob** [comment]
@rafaelks when i open the app it hangs. When i press keyboard to type it hangs. When i switch channel it hangs. We use whatsapp on mobile now and rocket for desktop only.

**Comment by ampyx** [comment]
I would suggest adding something like infinite-scroll (https://github.com/pronebird/UIScrollView-InfiniteScroll) for each channel. This way the channel does not need to load all history of the channel, but only tiny fractions and can get more data at request. Infinite scroll on that github page works on the bottom of a page, but can easily be switched when scrolling upwards.

This would definately make the application a hell of a lot faster.

**Comment by rafaelks** [comment]
Just to let you guys know that I'm working on this issue right now. 👍

**Comment by ampyx** [comment]
Cool! Did you implement a sort of infinite scroll? Or is it a way how messages are loaded?

**Comment by rafaelks** [comment]
@ampyx Yes, I'm working in a "pagination" of the Realm results manually, since Realm doesn't support limits or pagination by default. The PR (#577) is almost done, I'm finishing the test. If you want to help us to test the app over TestFlight, leave your email here.

**Comment by rafaelks** [comment]
The implementation is finalized. I'm gonna merge the PR and submit a build to the App Store with the fix. It's looking good guys, thanks for the patience and all your feedback, the app is looking MUCH better now! 👍

**Comment by amonemian** [comment]
@rafaelks Thanks for your greate work.
How can we change the paging size of loading histories of a room? It seems that RC loads a huge size of history when loading the room. (for example, 5 previous messages would be great)

**Comment by rafaelks** [comment]
@amonemian It's a team work here (@cardoso & me), but thanks anyway! 👊 

So, if you're forking our app, you'll have to change this file:

https://github.com/RocketChat/Rocket.Chat.iOS/blob/baf42d163d34cac12d979944fb0eabcd3ca5b378/Rocket.Chat/Managers/Model/MessageManager.swift#L12-L14

Just pay attention that 5 messages won't be enough to fill most of the devices screens if the messages are very short. We have a high number so we can fill the screen for all devices and have scrolling enabled.
