### ISSUE TITLE
Truncated messages, with plain text and fixed width fonts

### ISSUE THREAD

**Issue by arahlin** [RocketChat/Rocket.Chat.iOS#514]
- Your Rocket.Chat app version: 1.1.2
- Your Rocket.Chat server version: 0.56.0
- Device (or Simulator) you're running with: iPhone 7, iOS 10.3.2

It looks to me like issue #497 is not quite resolved?  I still get truncated text in messages containing only plain text, often when a single word rolls over to a new line.  I also always get truncated messages when there is `fixed width text` in the message, either as a code block or in line.

**Comment by rafaelks** [comment]
@arahlin Thanks for opening the issue! I'm going to investigate it.

**Comment by TheReal1604** [comment]
@rafaelks can confirm this, its much better than before - but not completely gone..
