### ISSUE TITLE
How do you make Push Notification works

### ISSUE THREAD

**Issue by teamsoo** [RocketChat/Rocket.Chat.iOS#515]
I see that people keep asking a lot about this but I can't seem to find a good place to start configuring the Push Notification in Rocket.Chat.iOS.

Is there anything that I have to do on the server side?
eg. setting Certificates and Keys in Push admin menu

I was following this [https://github.com/raix/push/blob/v3.x/docs/IOS.md](https://github.com/raix/push/blob/v3.x/docs/IOS.md) but can't seem to make it works.

I also tried Pusher from [https://github.com/noodlewerk/NWPusher](https://github.com/noodlewerk/NWPusher) ... didn't work. Can't seem to send any message to my phone.

Can someone guide me or point me to a good instructions on how to make the push notification works?

Thanks.

**Comment by teamsoo** [comment]
PS. just downloaded Officeial Android from Play Store. Send a test push show 2 devices but only Android receive the push.

**Comment by rafaelks** [comment]
@teamsoo Did you take a look at this documentation? https://rocket.chat/docs/administrator-guides/notifications/push-notifications/

**Comment by teamsoo** [comment]
@rafaelks Thank you for answering me. The answer is yes. As I mention above that I've tried https://github.com/raix/push/blob/v3.x/docs/IOS.md which is from the link that you gave me (on the iOS section). 

I went through the final step and got ```Verify return code: 0 (ok)``` using my pems.

The problem is I'm not so sure what to do next after I got the pems. Can you suggest?

Thanks in advance.

**Comment by rafaelks** [comment]
@teamsoo Can you open this issue on the back-end project? It seems to be related to back-end, not the mobile app: http://github.com/RocketChat/Rocket.Chat.

**Comment by rafaelks** [comment]
Closing this issue, not related to the iOS app.
