### ISSUE TITLE
How to reset rocket.chat to default setting?

### ISSUE THREAD

**Issue by ssjbrady** [RocketChat/Rocket.Chat.iOS#517]
- Your Rocket.Chat app version: 2.6.1
- Your Rocket.Chat server version: 0.56
- Device (or Simulator) you're running with: Mac OS X 10.10.5

Hey, I was wondering if there was a way to reset rocket.chat to the default settings in Mac OS? 

Thanks

**Comment by rafaelks** [comment]
@ssjbrady Closing the issue, this is the wrong project. Can you open in on https://github.com/RocketChat/Rocket.Chat.Electron?
