### ISSUE TITLE
Wrong Message Order in ChatViewController

### ISSUE THREAD

**Issue by xlbs-rm** [RocketChat/Rocket.Chat.iOS#524]
If writing Messages from 2 (or more) Different Chat Views in the native iOS App, the own Messages stay at the bottom. Newer Messages from others (or from the same user but other Devices or the WebView) appear over the first own Message (written in the App).
Leaving the Chat and come back will order all Messages like they should be ordered.
This does not happen with the Web Version of the Chat.

-Rocket.Chat app version: 1.1.1 and also last Commit from 2017-07-03 #d1f205bc9d9597c5fc244cc57017a7b8d3dce158 
-Rocket.Chat server version: 0.56
-Simulator iPhone 7 iOS 10.3 and various Devices

**Comment by hubermat** [comment]
Happens for me as well. 
We have a chat bot running, if I send a message with a keyword, the reply from the chatbot is displayed before/earlier in the view than my message! If I switch to a different channel and then back, the messages are displayed in the right order again.
For a colleague of mine (same App version, same iPhone 5s, same iOS version) this does _not_ happen...

-Rocket.Chat+ App 1.1.4 from AppStore
-Rocket.Chat server version: 0.57.1
-iPhone 5s, iOS 10.3.2

**Comment by xlbs-rm** [comment]
Guess its the same reason like: https://github.com/RocketChat/Rocket.Chat.iOS/issues/533
Your Device Time is different to the RC-Server, your Colleagues is nearly in sync with Server Time @hubermat Cann you confirm this?

**Comment by hubermat** [comment]
@xlbs-rm : Yes, my phone was (for unknown reasons) _not_ set to automatic time sync. It ran 2 minutes ahead... Now it works perfectly! Thank you!

**Comment by rafaelks** [comment]
Thanks for the finding @xlbs-rm, I'll close this issue in this case.

**Comment by xlbs-rm** [comment]
Its not a Solution due You cannot Controll the Time of the App Users Device. The Message Time in Database is right the Solution should be updating the UI (Collection View) with the Data from Database not the currently used in UI.

**Comment by rafaelks** [comment]
@xlbs-rm Yes, but if we get the correct timezone from server and use on the app, all this bugs (including your issue opened) will be fixed AFAIK, so I'll just let one issue opened.
