### ISSUE TITLE
With iOS SDK, I can't receive message

### ISSUE THREAD

**Issue by migueltg** [RocketChat/Rocket.Chat.iOS#526]
I'm working with the SDK branch for developing a native app using Rocket.Chat as the core for message exchange.
I can open the socket with "RocketChat.configure" and I can send messages, but when I try to receive a message, the "websocketDidReceiveMessage" callback is not called and therefore I can not read the message.

**Comment by rafaelks** [comment]
@migueltg Thanks for your feedback. Currently the SDK only supports our LiveChat feature, are you trying to develop a chat application or a LiveChat one?

**Comment by migueltg** [comment]
@rafaelks Thanks for your quick response 👍  Currently I am trying to develop a chat application.

**Comment by rafaelks** [comment]
@migueltg I'll close the issue in this case, since we don't support a chat application on the SDK yet.
