### ISSUE TITLE
Xcode Beta ?

### ISSUE THREAD

**Issue by danielgomezrico** [RocketChat/Rocket.Chat.iOS#53]
In contributing says `XCode-Beta (at the time of writing). You'll need Swift 2 support.`

For contributions should use beta or stable XCode 7?

**Comment by gsaslis** [comment]
Yes, at the moment you can use the stable one!  ; )



-- 
Yorgos Saslis
Software Engineer

**Comment by danielgomezrico** [comment]
@gsaslis :+1:

**Comment by gsaslis** [comment]
let us know if you need any help getting up to speed.. 
I think @kormic is currently working on the interconnection with the meteor server at the moment...

**Comment by kormic** [comment]
Hey @danielgomezrico as @gsaslis  said I m working on the interconnection with the server. Let me know if you need anything! :)

**Comment by danielgomezrico** [comment]
@kormic is there a todo list or something to know what's missing, who is working on what or something?

**Comment by gsaslis** [comment]
we used github issues for the tasks and the waffle.io [board](https://waffle.io/RocketChat/Rocket.Chat.iOS) for a better overall visualization...
