### ISSUE TITLE
SDK Examples

### ISSUE THREAD

**Issue by Schade974** [RocketChat/Rocket.Chat.iOS#530]
Hello, 

I would like to know if you have more examples about the iOS SDK. 
"See more with SDKExample app, also API Reference." the following guideline refers to a death link. 

Do you have a roadmap and a list of features implemented ?

I would like to know if the Rocket.Chat.iOS could be a solution to integrate in our existing iOS application. We are looking for a way to integrate a chatroom and to be able to perform teleconference between our application and a web plateform. Our application is dedicate to promote the telemedecin.

You have done a really good work with RocketChat ! 

See you,
Schade

**Comment by rafaelks** [comment]
@Schade974 We're currently developing our iOS/Android SDK, the documentation for iOS is available here: http://github.io/Rocket.Chat.iOS/index.html.

It currently supports only LiveChat.
