### ISSUE TITLE
[BUG] No Failure Message if Send of an Image failed

### ISSUE THREAD

**Issue by xlbs-rm** [RocketChat/Rocket.Chat.iOS#537]
Users reported the following Issue with the Chat, during bad Network e.g. in Subway.

Steps to Reproduce from everywhere (not only in Subway):
1. Action: Start a Chat
2. Action: Turn Off Internet
3. Action: Add a Image to the Chat (Camera or Camera Roll)
3.1 Result/Failure: Image did not appear in Chat
3.2 Result/Failure: No Failure Message
3.3 Result Image not send
3.4 Details: In SubscriptionManager the Completion Block is queued but callback is never called

4. Action: Next, Turn On Internet (Do not touch Reconnect)
5. Action Add a Image to the Chat (Camera or Camera Roll)
5.1 Result/Failure: Image did not appear in Chat
5.2 Result/Failure: No Failure Message
5.3 Result: Image not send

6. Action: Touch Reconnect
7. Action: Writing now something, sending Image
7.1 Result/Success: Message/Image Appears in Chat
7.2 Image send

Using the Developer Option in iOS Setting (https://stackoverflow.com/a/40132545), enable Network Link Conditioner to 100% Loss also Text Messages are not send and the Send Button is enabled. This Text Messages seam to be never send. Don't matter the perfect Internet Connection Later or leaving, re enter the same Chat the still appear in unsend gray.

- Your Rocket.Chat app version: 1.4.1 #69 from AppStore
- Your Rocket.Chat server version: 0.57
- Device (or Simulator) you're running with: iPhone 6 iOS 10.3.2

**Comment by rafaelks** [comment]
@xlbs-rm Thanks for opening the issue and writing down all the steps. The networking sync is something we need to still work on to fix this bad paths. I'll let this issue opened.

**Comment by rafaelks** [comment]
This one should be fixed with #830.

**Comment by cardoso** [comment]
Should we close this @rafaelks ?

**Comment by rafaelks** [comment]
@cardoso Yes!
