### ISSUE TITLE
Honor first name / last name setting

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat.iOS#543]
Reference to issue created on main repo: https://github.com/RocketChat/Rocket.Chat/issues/7573

There is a setting to display first name and last name instead of username.  The Rocket.Chat+ doesn't yet have that feature

**Comment by rafaelks** [comment]
@geekgonecrazy Thank you! I'm gonna add it to the next milestone of both platforms. Do we have a documentation on how to implement this already? Is this a setting?

**Comment by geekgonecrazy** [comment]
@rafaelks no documentation yet.... but:
* Setting: `UI_Use_Real Name`
* When enabled... `message.u.name` contains the name
* The subscription should be updated when their name changes

PR that contains the implementation: https://github.com/RocketChat/Rocket.Chat/pull/6597/files

**Comment by rafaelks** [comment]
@geekgonecrazy Oh, that's enough to implement the feature. Thanks!!!

**Comment by rafaelks** [comment]
@geekgonecrazy @rodrigok OK, this is kind of weird... some parts of the responses are using `name` and others are using `fname`. Why don't we use the same everywhere?

**Comment by rodrigok** [comment]
@rafaelks the subscriptions and room will use `fname` cuz we already use `name` for the current slugged name

**Comment by rafaelks** [comment]
@rodrigok OK... so both properties are valid user's fullname?
