### ISSUE TITLE
Second domain URL not valid in any client software

### ISSUE THREAD

**Issue by mhou1981** [RocketChat/Rocket.Chat.iOS#544]
- Your Rocket.Chat app version: 1.1.4
- Your Rocket.Chat server version: 0.57.2
- Device (or Simulator) you're running with: iPhone 6s and Windows client

In my rocket chat's caddy file, I have the following setting
```
domain.example.com {
    proxy / localhost:3000 {
        websocket
        transparent
    }
    tls cert.crt cert.key
}

domain2.example.com {
    proxy / localhost:3000 {
        websocket
        transparent
    }
    tls cert.crt cert.key
}
```
Both using the wild card certificate. 

However, when entering the second URL, iOS and Windows client will report the second domain (domain2.example.com) as an invalid URL and refuse to connect.  When tested on web browser, every thing works well.  Client will always saying second domain is an invalid domain.

**Comment by rafaelks** [comment]
@mhou1981 Both servers have valid SSL certificates and both support socket connections? One way to try is to make this request...

```shell
$ curl -i -N -H "Connection: Upgrade" \
          -H "Upgrade: websocket" \
          -H "Host: chat.yourhost.com" \
          -H "Origin: chat.yourhost.com" \
          -H "Sec-WebSocket-Key: fVXESE8fjBMx8HheW0YlZQ==" \
          -H "Sec-WebSocket-Version: 13" \
          https://chat.yourhost.com/websocket
```

**Comment by mhou1981** [comment]
Both are using the same wildcard certificate purchased from DigiCert Inc for all sub domain.  Firefox/Chrome/IE/Edge trust the certificate and display both domain without any issue.  Interestingly that the command you gave me showing both domains for:

```curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

The -k option worked.

**Comment by rafaelks** [comment]
@mhou1981 It seems that your SSL is invalid or self-signed? Can you send me the URLs you're trying to connect?

**Comment by mhou1981** [comment]
Sorry, it is an internal URL and you won't be able to access it.  The Web browser can verify the SSL and display the page without any issue.   Just client on iOS cannot access the second URL.

**Comment by rafaelks** [comment]
@mhou1981 Do you have any logs that can help us?

**Comment by rafaelks** [comment]
@mhou1981 Closing the issue due to inactivity.
