### ISSUE TITLE
Upload .xls, .doc, .pdf files through the app

### ISSUE THREAD

**Issue by gueeme** [RocketChat/Rocket.Chat.iOS#552]
- Your Rocket.Chat app version: 1.0.15
- Your Rocket.Chat server version: 0.57.2
- Device (or Simulator) you're running with: iPhone 7

When will it be possible to upload .xls, .doc, .pdf files through the app?

**Comment by rafaelks** [comment]
That's something we'll work soon... support to any kind of documents for both iOS and Android. Thank you! I'll let this issue opened.

**Comment by gueeme** [comment]
@rafaelks but do you have a date when it will be released?
A company I manage is extremely urgent in this role and have asked for a solution.

**Comment by rafaelks** [comment]
@gueeme Next release: `1.1.6`. Hopefully still in August.

**Comment by rafaelks** [comment]
@gueeme Just to let you know, started working on this.

**Comment by gueeme** [comment]
@rafaelks Thank´s for you atention.
