### ISSUE TITLE
iOS app doesn't go beyond the launch screen

### ISSUE THREAD

**Issue by UniK** [RocketChat/Rocket.Chat.iOS#570]
After updating the Rocket.Chat server to version 0.57.3 the iOS app doesn't go beyond the launch screen.
No further messages are provided.

- Your Rocket.Chat app version: 2.5.0
- Your Rocket.Chat server version: 0.57.3
- Device you're running with: iPhone 6 @ iOS 10.3.3

**Comment by rafaelks** [comment]
@UniK Are you authenticated? Have you tried uninstalling the app and installing it again?

**Comment by UniK** [comment]
@rafaelks 
>Are you authenticated?

Yes. The auth-credentials were saved on the device/app before the bug came along.

>Have you tried uninstalling the app and installing it again?

It might solve the problem, but it will definitely not fix the bug.

**Comment by ZelleAP** [comment]
I have the same Issue uninstall/intall will not fix the problem!

**Comment by rafaelks** [comment]
@UniK I know, wanted to know what's causing it... do you have access to the logs? Is it even trying to authenticate?

@ZelleAP Your issue seems to be different... can you explain it a little more?

**Comment by ZelleAP** [comment]
my server Address is https://camchat.nachbar.chat I have the same Server-Version 0.57.3 since the update I can't login to this server (rocket chat demo server working) with i OS App (Iphone 7plus).

**Comment by UniK** [comment]
@rafaelks 
> do you have access to the logs?

Server or device logs? I do not have access to the server logs. Could retrieve app's log on the device if the app saves any.

**Comment by nathanmarcos** [comment]
Same problem here, the error is:
```
[Error] Failed to load resource: The requested URL was not found on this server. (cache_manifest.js, line 0)
[Log] Error in Success callbackId: File1880830253 : SyntaxError: JSON Parse error: Unable to parse JSON string (console-via-logger.js, line 173)
[Error] SyntaxError: JSON Parse error: Unable to parse JSON string
callbackFromNative (cordova.js:314)
nc2 (cordova.js:1046)
bugsnag (bugsnag.js:1:166)
(anonymous function) (bugsnag.js:1:5089)
```
Reinstall the app always solves the problem, but eventually it happens again.

**Comment by rafaelks** [comment]
@UniK What screen it gets stuck? Is it the loading or it enters in the app? A screenshot would be helpful.

**Comment by rafaelks** [comment]
@nathanmarcos When do you see this logs? This looks like server logs.

**Comment by nathanmarcos** [comment]
@rafaelks I got this logs from safari inspector, but it's from the hybrid app.

**Comment by rafaelks** [comment]
@nathanmarcos If the issue is related to the hybrid app, please use this repository: http://github.com/RocketChat/Rocket.Chat.Cordova/.

**Comment by nathanmarcos** [comment]
@rafaelks Sorry, I dropped here from a link and didn't realize that I was in a wrong repository. I'll delete my comments.

**Comment by rafaelks** [comment]
@UniK It looks like you're also using the Cordova app. Can you open the issue in the correct repository? Thanks!

**Comment by nathanmarcos** [comment]
@rafaelks Can you delete the comments that I was mentioned too, please? Sorry for my mistake.

**Comment by nathanmarcos** [comment]
@rafaelks I deleted all my comments, can you delete the comments that I was mentioned too, please? Sorry for my mistake.

**Comment by ZelleAP** [comment]
My issue isn't fixed?!

**Comment by rafaelks** [comment]
@ZelleAP Your issue is related to the native app or the Cordova one?

**Comment by ZelleAP** [comment]
I use the native I OS app.

**Comment by rafaelks** [comment]
@ZelleAP And what's your issue?

**Comment by ZelleAP** [comment]
If I enter the server address I can't log in the spin weel runs again without a errror messages. This behavior is now since the update to 0.57.3

**Comment by rafaelks** [comment]
@ZelleAP What's your server URL?

**Comment by ZelleAP** [comment]
https://camchat.nachbar.chat/

**Comment by rafaelks** [comment]
@ZelleAP I think you're using a version of Nginx that doesn't support WebSocket, do you know what version are you using? Take a look...

```shell
curl -i -N -H "Connection: Upgrade" -H "Upgrade: websocket" -H "Host: camchat.nachbar.chat" -H "Origin: camchat.nachbar.chat" -H "Sec-WebSocket-Key: fVXESE8fjBMx8HheW0YlZQ==" -H "Sec-WebSocket-Version: 13" https://camchat.nachbar.chat/websocket
HTTP/1.1 400 Bad Request
Server: nginx
Date: Wed, 16 Aug 2017 23:14:44 GMT
Transfer-Encoding: chunked
Connection: keep-alive

Not a valid websocket request
```

You can look for more references about Nginx and WebSockets here: http://nginx.org/en/docs/http/websocket.html.

**Comment by ZelleAP** [comment]
Ok, I will Check this tomorrow 1:18 am here. Thx for the hint! Good Night

Rafael Kellermann Streit <notifications@github.com> schrieb am Do. 17. Aug.
2017 um 01:16:

**Comment by ZelleAP** [comment]
This is my Version (the latest with Plesk):
root@vmd18304:/etc/nginx# nginx -V
nginx version: nginx/1.11.10
built with OpenSSL 1.0.2g  1 Mar 2016
TLS SNI support enabled
configure arguments: --prefix=/usr/share --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --modules-path=/usr/share/nginx/modules --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --lock-path=/var/lock/nginx.lock --pid-path=/var/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --user=nginx --group=nginx --with-ipv6 --with-file-aio --with-http_v2_module --with-http_ssl_module --with-http_realip_module --with-http_sub_module --with-http_dav_module --with-http_gzip_static_module --with-http_stub_status_module --add-dynamic-module=/usr/share/passenger/ngx_http_passenger_module

**Comment by ZelleAP** [comment]
This is my Version (the latest with Plesk):
root@vmd18304:/etc/nginx# nginx -V
nginx version: nginx/1.11.10
built with OpenSSL 1.0.2g 1 Mar 2016
TLS SNI support enabled
configure arguments: --prefix=/usr/share --sbin-path=/usr/sbin/nginx
--conf-path=/etc/nginx/nginx.conf --modules-path=/usr/share/nginx/modules
--error-log-path=/var/log/nginx/error.log
--http-log-path=/var/log/nginx/access.log --lock-path=/var/lock/nginx.lock
--pid-path=/var/run/nginx.pid
--http-client-body-temp-path=/var/lib/nginx/body
--http-fastcgi-temp-path=/var/lib/nginx/fastcgi
--http-proxy-temp-path=/var/lib/nginx/proxy
--http-scgi-temp-path=/var/lib/nginx/scgi
--http-uwsgi-temp-path=/var/lib/nginx/uwsgi --user=nginx --group=nginx
--with-ipv6 --with-file-aio --with-http_v2_module --with-http_ssl_module
--with-http_realip_module --with-http_sub_module --with-http_dav_module
--with-http_gzip_static_module --with-http_stub_status_module
--add-dynamic-module=/usr/share/passenger/ngx_http_passenger_module

2017-08-17 1:19 GMT+02:00 Alexander Passauer <alexanderpassauer@gmail.com>:

**Comment by UniK** [comment]
@rafaelks 
>What screen it gets stuck? Is it the loading or it enters in the app?

As mentioned in the title it is a [launch screen](https://developer.apple.com/ios/human-interface-guidelines/graphics/launch-screen/). So there's no interaction with the app that can be made.

>It looks like you're also using the Cordova app.

Rocket.Chat iOS app at version: 2.5.0

>Can you open the issue in the correct repository? Thanks!

Wich repository is it now? Rocket.Chat or Rocket.Chat+? (btw. it is indistinguishable on the App Store, besides the plus sign).

**Comment by ZelleAP** [comment]
I using Rocket.Chat+

**Comment by rafaelks** [comment]
@ZelleAP You need to upgrade your Nginx to `1.3.13` or greater to support WebSockets. Can you do that?

@UniK `Rocket.Chat+` is the native one (this repository). `Rocket.Chat` is the Cordova one.
