### ISSUE TITLE
Textinput bar customization

### ISSUE THREAD

**Issue by AnilKukadeja** [RocketChat/Rocket.Chat.iOS#571]
Hello 

I just want to suggest that what if if I want to customise text input bar in iOS.

Developer should have facility to customise everything.

Just let me know your response. I am not sure if I am asking a right question here or not?

Thanks

**Comment by rafaelks** [comment]
@AnilKukadeja Thanks for your feedback! What exactly do you want to customize?

**Comment by AnilKukadeja** [comment]
@rafaelks  : First of all thanks to this wonderful community by seeing your code I have improved a lot.
Now coming on point let's say if I want to design my bottom text input bar similar as whats'app or I want to customise both buttons on left or right so I should have a direct access as property with their constraints or something like that...

**Comment by rafaelks** [comment]
@AnilKukadeja Gotcha! So, basically you want to change the icons of the buttons? Currently we don't support this kind of customization via server-side. You can always customize the app by creating a fork and changing the assets.
