### ISSUE TITLE
[NEW] Support for emoji in avatar would be welcomed for Rocket Chat +!

### ISSUE THREAD

**Issue by cftang** [RocketChat/Rocket.Chat.iOS#581]
Will someone like to add support of emoji in avatar in "rocket chat +"?
As "rocket chat" ios app has been able to do it for a long time.

Screenshot of rocket chat ios app is attached for your reference.

![2017-08-20 164939](https://user-images.githubusercontent.com/4529937/29542915-d602e918-870f-11e7-9d84-b2906682ee57.png)

**Comment by rafaelks** [comment]
@cftang Thanks for opening the issue, I'll let the issue opened for future releases.

**Comment by cardoso** [comment]
I'll wait for #1108 to be merged so we can also support custom emojis here :)
