### ISSUE TITLE
Mark conversation as read when receiving new messages and conversation is opened

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.iOS#586]
The app isn't marking the conversation as read when using is in it and receive new messages. Need to mark the conversation as read in this case.

**Comment by ggglopes** [comment]
Unsubscribe 

    Em Quarta-feira, 23 de Agosto de 2017 8:17, Rafael Kellermann Streit <notifications@github.com> escreveu:
 

 The app isn't marking the conversation as read when using is in it and receive new messages. Need to mark the conversation as read in this case.—
