### ISSUE TITLE
[NEW] Add Server parameter to build process & Add parameter to enable/disable server url entry screen

### ISSUE THREAD

**Issue by nicdaddy** [RocketChat/Rocket.Chat.iOS#610]
- Create a parameter that can be set & changed at build time to be the default server url.

- Create a parameter that disables the server entry page when a default server url is available.

**Comment by rafaelks** [comment]
@nicdaddy Thank you!!!

**Comment by HarveyDoom** [comment]
This is the most important thing for me.

**Comment by rafaelks** [comment]
@HarveyDoom This feature is going to be addressed soon!
