### ISSUE TITLE
[NEW] Honor Create Channel Permissions

### ISSUE THREAD

**Issue by danieljhochman** [RocketChat/Rocket.Chat.iOS#614]
Currently, users can create public or private rooms even if they are not permissioned to do so
Honor these permissions:
Create Public Channels [create-c]
Create Private Channels [create-p]

**Comment by rafaelks** [comment]
@danieljhochman Thank you! 👍

**Comment by dennispost** [comment]
I think this should be done by the server. If a user is not allowed to, the server has to answer with a corresponding error message. 
All applications just have to handle these errors correctly.

**Comment by danieljhochman** [comment]
The user should never see a button or option which they are not permissioned to use. Therefore, just like we do on the web version of RC, the client should not show the option to add a room.

**Comment by rafaelks** [comment]
I agree that server should stop and return user in case user uses the API, of course, but we can hide it from the interface, because we have a setting for that.
