### ISSUE TITLE
[NEW] Allow room names with special characters

### ISSUE THREAD

**Issue by danieljhochman** [RocketChat/Rocket.Chat.iOS#615]
In admin settings there is an option to "Allow special chars on room names" . The app should support this setting. We specifically need it for spaces and capital letters.

**Comment by rafaelks** [comment]
@danieljhochman Where the app isn't supporting this setting? Can you point me? Thanks!

**Comment by danieljhochman** [comment]
Sure- just create a room with the name "Test Room" and in the app it will show as "test-room". On web, it shows as "Test Room"
