### ISSUE TITLE
[NEW] Honor "Hide Message" options

### ISSUE THREAD

**Issue by danieljhochman** [RocketChat/Rocket.Chat.iOS#616]
Please honor the following admin settings (from web admin) in the app:

Message_HideType_uj -> User Joined messages
Message_HideType_ul -> User Leave messages
Message_HideType_au -> User Added messages
Message_HideType_mute_unmute -> User Muted/Unmuted messages
Message_HideType_ru -> User Removed messages

The "User Added" one is the most important for our use-case. Currently, these auto-messages are showing in the app and there is no way to hide them. For example, we created a room and added 100s of users, so now it shows 100s of messages.

**Comment by rafaelks** [comment]
Closing, it duplicates #607.

**Comment by danieljhochman** [comment]
Ooops sorry.
