### ISSUE TITLE
[NEW] Implement sequential (grouped) messages

### ISSUE THREAD

**Issue by cardoso** [RocketChat/Rocket.Chat.iOS#617]
Some messages should be grouped together when the same user posts in sequence.

The web app makes some exceptions like images which do not merge.
I haven't investigated which other ones don't merge yet.

**Comment by cardoso** [comment]
I'm implementing this in my fork, but i didn't get the layout just right yet.
https://github.com/cardoso/Rocket.Chat.iOS/tree/feat/sequence_cells

| my attempt (normal) | my attempt (debug) |
|-|-|
|![](http://i.imgur.com/JfJ5ArB.png)|![](http://i.imgur.com/Sy3Q797.png)|

There's some extra spacing (in cyan) which i can't get rid of yet. I'm not sure where it's coming from. I even tried looking in the SlackTextViewController lib. Maybe i'm a bit rusty with UICollectionViews?

**Comment by rafaelks** [comment]
Sweet!!! Yes, the spacing is related to the UICollectionView. To complete remove it, simply add this code to `UICollectionViewDelegateFlowLayout` delegate:

```swift
func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, minimumLineSpacingForSectionAt section: Int) -> CGFloat {
    return 0
}
```

**Comment by cardoso** [comment]
I think that's it then! Everything looks fine here after i add that method. I'll just do some testing and make a PR.
