### ISSUE TITLE
[NEW] Let user choose different variations of Rocket.Chat icons

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.iOS#619]
Using new iOS APIs, user can choose what icon the application will use based on a set of icons in the bundle of the app. My suggestion is that we have a few options (dark, clean, default, blue, red, etc...) and let user choose the one that fits well. 

If you have suggestions, please comment here! 👍

**Comment by soundstorm** [comment]
![rc_icon_red](https://user-images.githubusercontent.com/193273/34878509-ab3e079c-f7aa-11e7-9023-a5b16e83a812.png)
![rc_icon_white](https://user-images.githubusercontent.com/193273/34878511-ad038fd4-f7aa-11e7-8e59-577092f60440.png)
![rc_icon_blue](https://user-images.githubusercontent.com/193273/34878515-af903bc6-f7aa-11e7-96be-65cf007389a5.png)
![rc_icon_gray](https://user-images.githubusercontent.com/193273/34878520-b2355032-f7aa-11e7-97fb-bcedc165111f.png)

**Comment by soundstorm** [comment]
For easier adaption of the color schemes I altered the #cccccc shadow to #000 at 20% transparency.
Illustrator files available ;-)

**Comment by rafaelks** [comment]
@soundstorm That's pretty cool dude! Thank you a lot! Do you mind also doing one with complete BLACK background for the iPhone X users? 😎

**Comment by rafaelks** [comment]
BLACK and the SYMBOL in white would be super cool I think.

**Comment by soundstorm** [comment]
![rc_icon_blred](https://user-images.githubusercontent.com/193273/34879452-90a6e572-f7ad-11e7-81d8-e33099ba47d0.png)
![rc_icon_mono](https://user-images.githubusercontent.com/193273/34879468-a11350a8-f7ad-11e7-92eb-7ce6464ebeb9.png)

**Comment by rafaelks** [comment]
Amazing! Thank you very much! 👊

**Comment by artrmz** [comment]
Seems like alternate icons must be included outside assets catalog, that kinda sucks :( Although could use https://github.com/alexaubry/alternate-icons if we can to keep them nicely grouped in assets.

- https://developer.apple.com/documentation/uikit/uiapplication/2806818-setalternateiconname
- https://www.hackingwithswift.com/example-code/uikit/how-to-change-your-app-icon-dynamically-with-setalternateiconname

Once I have time I might give it a shot and try to configure it. @soundstorm any change you can export all needed resolutions from Illustrator? I can do that in Photoshop but do not know if down scaling .png will not lose quality?

**Comment by rafaelks** [comment]
@artrmz I can generate all sizes required here if you need, using an application that exports everything together (Asset Catalog Creator).

**Comment by soundstorm** [comment]
@rafaelks @artrmz I got the raw path data in Illustrator. So I can output any size without any side effects (aliasing).
