### ISSUE TITLE
iOS app doesn't seem to be working, white bar on blue screen

### ISSUE THREAD

**Issue by adam-antonik** [RocketChat/Rocket.Chat.iOS#62]
Just installed the iOS app from the app store, and pointed it towards my newly set up rocket chat server (which I can access fine in a web-browser).  The app seemed happy and said it was downloading files, but now just displays a horizontal white rectangle on a blue background.  Restarting the app just results in it saying that it is connecting to the address it should, then white rectangle again.

**Comment by kormic** [comment]
@adam-antonik This is not the hybrid app that is on the app store. This is the native app which is not released yet.You want to go [here] (https://github.com/RocketChat/Rocket.Chat.Cordova)

**Comment by adam-antonik** [comment]
Oops.  Sorry about that.
