### ISSUE TITLE
Support for multiple servers?

### ISSUE THREAD

**Issue by marbetschar** [RocketChat/Rocket.Chat.iOS#624]
Is it possible to add support for multiple servers to the mobile application? We have several instances running and also some of our partners use Rocket.Chat which works absolutely great.

The only downside is, we always have to logout and login to another server - which on mobile is quite annoying. Because of this we rarely ever use the mobile app.

Support for multiple servers would boost our productivity a lot so would really love to see this on mobile.

**Comment by rafaelks** [comment]
This is already in progress, will be released in our next release: https://github.com/RocketChat/Rocket.Chat.iOS/pull/609.
