### ISSUE TITLE
[BUG] Search function broken

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat.iOS#626]
- Your Rocket.Chat app version: 1.3.0 (84)
- Your Rocket.Chat server version: 0.58.2
- Device (or Simulator) you're running with: iPhone 6 Plus

If you search for a user, it displays the result weird.

![image](https://user-images.githubusercontent.com/5877910/30203172-8ae781b2-9481-11e7-981e-1cce14d4f456.png)

**Comment by rafaelks** [comment]
@TheReal1604 I believe you're using the setting that display user real name instead of username, right? That's the reason of the bug I think.

**Comment by TheReal1604** [comment]
@rafaelks correct.

**Comment by rafaelks** [comment]
@TheReal1604 Can you confirm this is fixed in 1.3.0 (88)?

**Comment by TheReal1604** [comment]
It's fixed! Thanks.
