### ISSUE TITLE
app needs to be reinstalled when server-sided proxy settings changed, because of blue screens or white screens ("connection..."

### ISSUE THREAD

**Issue by finius** [RocketChat/Rocket.Chat.iOS#63]
After setting up the RocketChat server, we tried to use an iOS 9 device to connect to the server. Although the web UI was reachable using the browser, the app wasn't able to establish a connection:
![img_0347](https://cloud.githubusercontent.com/assets/5287181/13075960/3a31a10a-d4af-11e5-9693-7d66cf4f5b91.PNG)
I deleted the app from the iPhone, made a change to proxy configuration on the server side and then, after reinstalling and reconfiguring the Ap, the white connection screen had disappeared. But i didn't get an app-like user login window - however I got an ugly html form:
![img_0345](https://cloud.githubusercontent.com/assets/5287181/13075965/3e657d00-d4af-11e5-8530-98c0091605bb.PNG)
When I log in by entering username in the second field and my password in the fourth one I can do login, but then it get's even more ugly because the displayed UI is text-only:
![img_0348](https://cloud.githubusercontent.com/assets/5287181/13076229/3a0c6b86-d4b1-11e5-8285-372b3e027353.PNG)

With the current server release 0.18.1 it's unusable, so this app needs an overhaul. Even in the past we had a lot of issues with empty and one-colored screens (in most cases blue) when using the app, so we were not able to continue using the app except to hardly exit and reopen it.
I would really appreciate if the app get's back it original Rocket.Chat look - like the web UI does. Furthermore the App has to be more hardened against connection problems or other crashes. There is nothing more frustrating than always hanging in an app that is used several times per hour.

In my opinion, what is really really needed, is some kind of a fixed settings button from where I can always reach a possibility to cleanup any cached server settings, reset the local saved login credentials or change the server URL or port. All the really important stuff that needs an App to work which can be found there. That might cause problems to the app, when some of these server sided settings have changed.

**Comment by kormic** [comment]
Hello there! This is the native app for ios. You are referring to the hybrid app (cordova).

**Comment by finius** [comment]
I didn't get this. Are there two iOS apps? I only realized that there had been one RocketChat app in the App Store.

**Comment by kormic** [comment]
Yes, there are two apps. There is this one, the native one which is not released yet in the app store and then there is the hybid app which is the one you found in the store. You need to go [here](https://github.com/RocketChat/Rocket.Chat.Cordova)

**Comment by finius** [comment]
Ok, thank you for the hint! Is there already any release date in sight?
