### ISSUE TITLE
[IMPROVEMENT] Improve @mentions styling

### ISSUE THREAD

**Issue by cardoso** [RocketChat/Rocket.Chat.iOS#633]
We are currently using NSAttributedString to achieve the current visuals which doesn't easily allow for padding and round corners by default.

| Currently (iOS) | Desired (Web) |
| - | - |
| ![](https://i.imgur.com/RLieEYU.png) | ![](https://i.imgur.com/XKk3KOH.png) |

Where to look:
[NSAttributedStringExtensions.swift: 69](https://github.com/RocketChat/Rocket.Chat.iOS/blob/master/Rocket.Chat/Extensions/NSAttributedStringExtensions.swift#L69-L80)

**Comment by sabrown84** [comment]
Hi! I'd like to try this one...

**Comment by rafaelks** [comment]
@sabrown84 That would be great! Can you send us a PR with your solution? Thanks! ✌️

**Comment by sabrown84** [comment]
Hi @rafaelks I've been trying a few things to get the desired result, but I haven't had any luck. Do you have a suggestion on how I should approach this that would work?

**Comment by sabrown84** [comment]
@rafaelks I have read about it a little. I'm unfamiliar with how it will work here, but I will do some more research and try it. Thank you this really helps and gives me more direction.

**Comment by artrmz** [comment]
I have started working on this improvement, so far I have implemented subclass of UITextView where I try to draw background under mentions using CoreText (implementation here: https://github.com/artrmz/Rocket.Chat.iOS/blob/028f5a06d67ad9848a2d0162a1ab71a479800e4b/Rocket.Chat/Views/Chat/HighlightTextView.swift). 

Although right now I am stuck with a problem... as you can see on the screen it draws background in wrong place for some reason and I cannot find a reason. If anyone got any idea feel free to give me a hand.

![issue633](https://user-images.githubusercontent.com/3925166/31861124-94ebe572-b727-11e7-93c9-35d067e95d53.jpg)

Taking last message from the screen as example:

` let lines = CTFrameGetLines(totalframe) as NSArray`

returns me 4 lines and as you can see on the screen it should be 5. I have no idea why, I guess I am taking wrong textView's frame or something?

**Comment by artrmz** [comment]
Started working on this improvement: https://github.com/RocketChat/Rocket.Chat.iOS/pull/834

**Comment by macabeus** [comment]
@artrmz Thank you for the alert. I'll check in more detail.
