### ISSUE TITLE
app can't connect to a local url

### ISSUE THREAD

**Issue by finius** [RocketChat/Rocket.Chat.iOS#64]
when trying to connect the iOS App using WiFi to an internal URL http://10.0.0.64 it ends up with this error:
![img_0349](https://cloud.githubusercontent.com/assets/5287181/13076553/4835afa4-d4b3-11e5-97c0-68059b45e4ea.PNG)
Every time I tap on "connect", it dublicated the same error below the button, which seems to be a bug.
I guess every user would appreciate if the App would try itself to establish a connection on the RocketChat default port 3000. I typed manually the new URL http://10.0.0.64:3000. The URL screen disappeard now, but a new white screen showed this unsatisfying message:
![img_0350](https://cloud.githubusercontent.com/assets/5287181/13076598/89bd9cca-d4b3-11e5-8a56-9d6a20af103f.PNG)
However, using the web UI with Safari on the phone works like a charm - but after all, it's no app with notification :-(

**Comment by Sugaroverdose** [comment]
This repo contains native not yet released iOS app, your issue is for https://github.com/RocketChat/Rocket.Chat.Cordova
