### ISSUE TITLE
Assume HTTPS by default

### ISSUE THREAD

**Issue by marbetschar** [RocketChat/Rocket.Chat.iOS#644]
On the login window I can enter the URL to the chat server. But If I don't enter a protocol explicitly, the form throws an error.

Is it possible to handle this more gracefully? E.g. using HTTPS if no protocol was entered by default?

**Comment by rafaelks** [comment]
@marbetschar The app actually uses HTTPS by default, if you don't enter the protocol. Can you provide me the steps you're using to test it? Here's the code that constructs the URL.

https://github.com/RocketChat/Rocket.Chat.iOS/blob/8cdd9c5a4504096b9d076b36754d3f5b4a8785f8/Rocket.Chat/Extensions/URLExtension.swift#L25-L51

**Comment by marbetschar** [comment]
mhm, you're right - seems to work now...? Maybe it was just a connection issue.

**Comment by rafaelks** [comment]
It's possible. Anyway, thanks for opening the issue, closing it now.
