### ISSUE TITLE
Search by "#channel" returns no results

### ISSUE THREAD

**Issue by anthonylavado** [RocketChat/Rocket.Chat.iOS#676]
- Your Rocket.Chat app version: 1.3.0
- Your Rocket.Chat server version: 0.58.2
- Device (or Simulator) you're running with: iPhone 6, iOS 11.0 GM (15A372)

Hi there!
Just had this confirmed by one of our users and myself.

If we search for a channel by name alone, we get a result. If we search for a channel with a "#" infront of the name, there are no results returned.

In the Cordova version of the app (which is the same as the Web UI), the search works with either format for channel name.

Example:
<img src="https://user-images.githubusercontent.com/596194/30557080-1de70acc-9c7b-11e7-9012-e38dda4266b8.jpg" width="250" height="250">
<img src="https://user-images.githubusercontent.com/596194/30557079-1de490b2-9c7b-11e7-87de-527d5f009126.jpg" width="250" height="250">

**Comment by cardoso** [comment]
Thanks for opening this issue! We'll take a look soon.

**Comment by macabeus** [comment]
Another detail is that the browser searcher ignore space, but the iOS version not.

![image](https://user-images.githubusercontent.com/9501115/30577837-31d8a0ce-9ce7-11e7-82fd-12634f161fe2.png)

And, as long I observed, if you use # as prefix in search field, you only to search for channels. And, if you use @, you search only for users. It is?

![image](https://user-images.githubusercontent.com/9501115/30578042-38c98abe-9ce8-11e7-83fb-e4d6108d59c4.png)

**Comment by rafaelks** [comment]
@macabeus I believe this is all handled by web-client, but should be in our back-end, the method that we use to search. Let me talk to the back-end team and see what we can do.

**Comment by rafaelks** [comment]
This is going to be handled by back-end: https://github.com/RocketChat/Rocket.Chat/issues/8205.
