### ISSUE TITLE
[BUG] "Contact us" button doesn't work.

### ISSUE THREAD

**Issue by falcaoaugustos** [RocketChat/Rocket.Chat.iOS#681]
- Your Rocket.Chat app version: 1.4.0
- Your Rocket.Chat server version: 0.59.0
- Device (or Simulator) you're running with: iPhone SE, iPhone 8s (Simulator), iPhone X (Simulator)

In settings screen, the "Contact us" button doesn't work when it pressed.

![contactissue](https://user-images.githubusercontent.com/21058835/30644248-2ca85296-9de8-11e7-8a9e-e0f4d0d44521.png)

**Comment by rafaelks** [comment]
@falcaoaugustos On Simulator, it really doesn't work, because you can't send emails from Simulator. Does your device has any email configured in iOS?

**Comment by falcaoaugustos** [comment]
I found this bug using the app in my iPhone SE (iOS 10.3.3), logged in with my personal google account.

**Comment by rafaelks** [comment]
@falcaoaugustos Is the email enabled in your iOS settings?

**Comment by falcaoaugustos** [comment]
The Mail wasn't enabled. I use the gmail app.
I tried to press the "Contact us" button after configure the Mail app and it worked.
I was not notified about this requirement.
I am sorry. Thank you.

**Comment by rafaelks** [comment]
@falcaoaugustos Yes, we need to show an alert to the user in this case. Do you want to go for it? :-)

**Comment by falcaoaugustos** [comment]
I do.
: )
