### ISSUE TITLE
[BUG] After rotating device 180º the status bar stays in the wrong place

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.iOS#687]
- Your Rocket.Chat app version: 1.5.0
- Device (or Simulator) you're running with: iPad Air 2, iOS 11

# Screenshot

![img_0015](https://user-images.githubusercontent.com/551004/30693245-0c5587f8-9ea5-11e7-96f3-05be1cdb5d5c.jpg)

**Comment by cardoso** [comment]
This also happens on iPhone.

When in a chat:
1. Move to landscape orientation
2. Open side menu
3. Move to portrait orientation

![example](https://i.imgur.com/M9zMoCF.png)

**Comment by rafaelks** [comment]
@cardoso Good finding! Thanks!

**Comment by falcaoaugustos** [comment]
This bug occurs because of a pod (SideMenuController) problem.
I've sent a Pull Request to your repository fork.

**Comment by rafaelks** [comment]
@falcaoaugustos Looking good, thank you!
