### ISSUE TITLE
[NEW] Add support to Reactions

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.iOS#689]
# Description

Let user see and react to a message (including with custom emojis).

## Custom emojis

There's a web socket call that returns all custom emojis from the server, you can read more about it here: https://rocket.chat/docs/developer-guides/realtime-api/method-calls/list-custom-emoji/#list-custom-emoji.

Blocked issue: #699.

## Fetching the reactions of some message

On the message object, there's a property called `reactions` that contains all the reactions for that message. This field is returned by default in all web socket calls. Example:

```json
{
    "reactions" : {
        ":heart_eyes:" : {
            "usernames" : [
                "matheus.cardoso",
                "rafael.kellermann"
            ]
        },
        ":rocket:" : {
            "usernames" : [
                "matheus.cardoso",
                "rafael.kellermann"
            ]
        }
    }
}
```

## Adding a reaction to a message

Documentation: https://rocket.chat/docs/developer-guides/realtime-api/method-calls/set-reaction/#set-reaction

**Comment by arthurgiustina** [comment]
![reactions ipad](https://user-images.githubusercontent.com/30700871/34530566-ad807d5c-f096-11e7-965a-7bbd0a9ce820.png)


@rafaelks Updated https://share.goabstract.com/a1b6019b-cf72-49f5-9003-a23f154ce365
