### ISSUE TITLE
[BUG] Allow channel unsubscribing

### ISSUE THREAD

**Issue by macabeus** [RocketChat/Rocket.Chat.iOS#690]
- Your Rocket.Chat app version: 1.4.0 (93)
- Your Rocket.Chat server version: 0.58.2
- Device (or Simulator) you're running with: Simulator iPhone 5SE

In some situations, like this, #683 , we needs unsubscribe for one channel.

Another situation is when the user change the chat channel, but still receive the messages from previous channel. For example, if you change the channel from X to Y, you still receive the messages from channel X.

**Comment by rafaelks** [comment]
Thank you @macabeus
