### ISSUE TITLE
[NEW] Allow the creation of channels and groups

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat.iOS#707]
private and public channels - and invite other users to.

**Comment by macabeus** [comment]
I want resolve this issue, but, I have some questions.

![image](https://user-images.githubusercontent.com/9501115/30809069-da666570-a1d6-11e7-8cea-a29ad399dae6.png)

The Add Button needs show in what place? In left of Search field (like Rocket Chat web) or in left of Channel label (like Slack)?

And, when the user taped in Add Button, the form to create a new channel may fill the entire screen (like Slack) or only the side bar (like Rocket Chat web)?

**Comment by rafaelks** [comment]
@macabeus Thanks for your interest in working on this issue. Thanks for the help also @TheReal1604.

Here are the mocks we've been working on.

## Add button

We don't want to add the button to each section, the idea is to have a **+** button on the top-right of our left sidebar, like the mock below. What do you think? Tapping this button would call the "Create channel screen" (description below).

![screen shot 2017-09-25 at 11 29 01 am](https://user-images.githubusercontent.com/551004/30813862-f5cada18-a1e4-11e7-9f45-c2ecabbb20de.png)

## Create channel screen

You can follow exactly this screen, but you don't need to add the *cover* yet.

![screen shot 2017-09-25 at 11 28 49 am](https://user-images.githubusercontent.com/551004/30813793-c2547e50-a1e4-11e7-8539-653cde063171.png)

Does it answers your question? :-)

**Comment by macabeus** [comment]
I really liked this mockup. Well interesting and beautiful.

But, some questions:
What element will do the function that currently the `imageViewArrowDown` is doing, that is, show screen to change status and sing out?
What the function for Discovery?

In this moment, I only will create one simple add button and New Channel screen, ok?

**Comment by rafaelks** [comment]
@macabeus Yes, good questions.

1) You'll tap in the "User" area and it will navigate to another screen, where user will be able to make more changes on the status;
2) We're working on Discovery yet, these are just mocks;

Yes, sounds great. The + button calling the New Screen works! 👍
