### ISSUE TITLE
[NEW] Pre-select last selected room (or first room in list)

### ISSUE THREAD

**Issue by danieljhochman** [RocketChat/Rocket.Chat.iOS#714]
When a user opens the app, pre-select the last selected room. Also, for the first time a user opens the app- select the first room in the list.

**Comment by rafaelks** [comment]
@danieljhochman The last selected room, implies in the last selected room on other clients as well? For example, if I was on the web client talking to `@foo`, when I open the app (if it's closed) it should open the conversation with `@foo`, right?

**Comment by danieljhochman** [comment]
Great question. I think it makes sense to make this cross client. However, we just tested this now in iOS and it seems to already load the last selected room. So perhaps this is only an issue on Android?

**Comment by rafaelks** [comment]
@danieljhochman I believe it is, because this is already implemented in some way in iOS. Can you confirm and close the issue if it's done?

**Comment by danieljhochman** [comment]
This already exists. Sorry.
