### ISSUE TITLE
[BUG] Crash when attaching file with import from iPad

### ISSUE THREAD

**Issue by emign** [RocketChat/Rocket.Chat.iOS#715]
- Your Rocket.Chat app version: 1.4.1
- Your Rocket.Chat server version: 0.58.2
- Device (or Simulator) you're running with: iPad Pro 12,9 inch, 2017 

When clicking on import file dialogue from the attachment menu (left side, plus icon) the app instantly crashes to the home screen. Literally every time.

**Comment by rafaelks** [comment]
@emign Thank you for reporting this issue! We're going to address for the next release, coming this week.
