### ISSUE TITLE
[BUG] It's crashing on iPad when you long-press on the servers list

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat.iOS#722]
Needs a way to remove a server

**Comment by rafaelks** [comment]
@geekgonecrazy You can long press the server or logouts from it. What version of the app are you using?

**Comment by geekgonecrazy** [comment]
Latest from app store ( not beta ).  I long press and nothing happens.

**Comment by rafaelks** [comment]
@geekgonecrazy Just figured it out. It's actually crashing on iPad this feature. Thanks for the heads up, I'm addressing it right now.
