### ISSUE TITLE
[NEW] Support authentication with Twitter

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.iOS#724]
Integrate authentication using Twitter OAuth with WebView.

**Comment by rafaelks** [comment]
We'll be able to integrate Twitter SDK with the new REST API (going to be available on next server release): https://github.com/RocketChat/Rocket.Chat/pull/9816

**Comment by cardoso** [comment]
Should we update this to not say "using Twitter SDK"? @rafaelks

**Comment by rafaelks** [comment]
@cardoso Updated!

**Comment by filipedelimabrito** [comment]
@rafaelks Are the iOS app planning to ship this feature even twitter not fully supporting the OAuth 2?

_Twitter offers applications the ability to issue authenticated requests on behalf of the application itself (as opposed to on behalf of a specific user). Twitter’s implementation is based on the Client Credentials Grant flow of the OAuth 2 specification. Note that OAuth 1.0a is still required to issue requests on behalf of users._ (https://developer.twitter.com/en/docs/basics/authentication/overview/application-only)

**Comment by cardoso** [comment]
@filipedelimabrito I've tried many times and I'm not sure if it's possible. Or maybe it needs custom code for this OAuth 1 + 2 mix :/

**Comment by filipedelimabrito** [comment]
Thanks for replying @cardoso!

I only want to say what other guys said [here](https://twittercommunity.com/t/getting-started-with-oauth-2-0/2338/10) and [here](https://twittercommunity.com/t/getting-started-with-oauth-2-0/2338/13). (:sad_parrot:)  😢

**Comment by rafaelks** [comment]
Let's close this issue for now.
