### ISSUE TITLE
[NEW] Allow user to record an audio message and send it

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.iOS#735]
We need a way to record and send audio messages without leaving the app.

Like so:
![media](https://cdn.igeeksblog.com/wp-content/uploads/How-to-Send-Audio-iMessage-on-iOS-8.jpg)

Instead of a swipe to cancel like in WhatsApp, for now we can have a UIAlertView with Send and Cancel options after the user raises his finger from the mic button.

Where to look:
[ChatControllerUploader.swift](https://github.com/RocketChat/Rocket.Chat.iOS/blob/master/Rocket.Chat/Controllers/Chat/ChatControllerUploader.swift)
[ChatViewController.swift](https://github.com/RocketChat/Rocket.Chat.iOS/blob/master/Rocket.Chat/Controllers/Chat/ChatViewController.swift)

**Comment by artrmz** [comment]
Should close it duo to #1061 I think.

**Comment by cardoso** [comment]
Thanks @artrmz !
