### ISSUE TITLE
[BUG] Channel is not refreshed on new messages if server was switched

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat.iOS#739]
Version: 1.5.0 (100)

The channel gets not automatically refreshed if you switch the server before. An indicator for this bug is that the „Is typing..“ function is also not working correctly. You can see the new messages in the channel just in the menu. This behaviour can only fixed by restarting the app on both devices.

**Comment by cardoso** [comment]
@TheReal1604 can you confirm if this is still a problem, and if it is, could you specify steps to reproduce it? 

I didn't have any synchronization problems while switching between servers and sending messages from multiple accounts.
