### ISSUE TITLE
Swift compiler errors. 

### ISSUE THREAD

**Issue by anonopanda** [RocketChat/Rocket.Chat.iOS#748]
- Your Rocket.Chat app version: development branch
- Device (or Simulator) you're running with: 5S & 7
- Xcode Version, 8.1 & 8.3.3

Getting a few swift compiler errors. 
<img width="1272" alt="screen shot 2017-10-01 at 11 10 54 am" src="https://user-images.githubusercontent.com/32401481/31057543-5a52a89a-a699-11e7-9fa3-daf318069c3f.png">

What is the version of Xcode you use to build the project? Not sure whats wrong with my environment.

**Comment by rafaelks** [comment]
@anonopanda Make sure you're running Xcode 9+.
