### ISSUE TITLE
Loses state after reloading

### ISSUE THREAD

**Issue by pshute** [RocketChat/Rocket.Chat.iOS#778]
- Your Rocket.Chat app version: 2.5.0
- Your Rocket.Chat server version: 0.57.2
- Device (or Simulator) you're running with: iPad 4, iOS 11.0.2

If I use other apps for a while then return to Rocket.Chat, it will often start up from scratch, and go to the home screen. It usually stays logged in, but I have seen it log me out, perhaps after an app update, can't remember.

I assume this is to do with the app being unloaded from RAM by iOS. This iPad only has 1GB RAM, so more recent devices may not encounter the problem as much.

It would be great if it could restore the state of the app and restart in the channel I was in, with the messages scrolled to the same position. 

Is it too much to ask for it to also restore a message I was part way through typing? A typical scenario is I switch to Safari to research something for a message I'm typing, then when I return later it's all gone.

It would probably be a good idea to retain the current behaviour when restarting after the app has been forced closed by the user, in case they're trying to recover from a problem.

**Comment by rafaelks** [comment]
Looks like your issue is related to our Cordova app, not the native one. If that information proceeds, please open the issue in the right repository: https://github.com/RocketChat/Rocket.Chat.Cordova/.

And I encourage you to try our native app by downloading it with the name of `Rocket.Chat+` in App Store and Google Play.

**Comment by pshute** [comment]
Yes, you're correct. I'm aware there are two, but assumed this repository was for the other app because of the repository name.

When I opened the issue, it put this text in the text box:
`"Before writing an issue, please make sure you're talking about the native application and not the Cordova one. If you are looking to open an issue to the Cordova application, go to this URL: https://github.com/RocketChat/Rocket.Chat.Cordova."`
Nothing there to warn newbs they're posting in the wrong area - I have no clue which app is native, and I have no clue what Cordova is. All I know is that one's called Rocket.Chat, and one's called Rocket.Chat+. Perhaps you could modify that text to reduce this problem:
`"Before writing an issue, please make sure you're talking about the native application (called Rocket.Chat+ in the app store) and not the Cordova one (called Rocket.Chat in the app store). If you are looking to open an issue to the Cordova application, go to this URL: https://github.com/RocketChat/Rocket.Chat.Cordova."`

**Comment by rafaelks** [comment]
Done #795! Thank you very much for your feedback! 👍
