### ISSUE TITLE
[BUG] The app crash when gives up to add a new team

### ISSUE THREAD

**Issue by macabeus** [RocketChat/Rocket.Chat.iOS#780]
- Your Rocket.Chat app version: 1.6.0 (104) (develop branch)
- Your Rocket.Chat server version: 0.58.2
- Device (or Simulator) you're running with: Simulator iPhone SE and physical device iPhone SE

![](https://media.giphy.com/media/3ov9jSuDoKn6GFwZMs/giphy.gif)

**Comment by rafaelks** [comment]
I can't reproduce it right now... is it still reproducible? What are the steps?

**Comment by macabeus** [comment]
I reproduced this bug now again, with Rocket.Chat+ from AppStore, as well in the last version at develop branch.

Step by step to reproduce this bug:
1. Tap "Add new Team"
2. Enter a URL with server that hasn't yet
3. Tap enter
4. In the next screen, don't type the user and password. Tap button to return from the previous screen
5. Tap "X"
6. Crash!
