### ISSUE TITLE
[IMPROVEMENT] Show loader when app is connecting after resuming from background

### ISSUE THREAD

**Issue by danieljhochman** [RocketChat/Rocket.Chat.iOS#791]
Version: 1.50 (102)

If I close the app (not kill) and then re-open it, the "You're offline, try connecting again" message shows until you click the refresh button. The app should re-connect automatically when you open it.

**Comment by rafaelks** [comment]
@danieljhochman The app actually reconnects again once you come back from background, but we're not showing the loader I think. I'll let this issue open to address it.
