### ISSUE TITLE
[BUG] Online indicator not synced properly on server switch

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat.iOS#801]
- Your Rocket.Chat app version: 1.6.0(108)
- Your Rocket.Chat server version: 0.58.4
- Device (or Simulator) you're running with: iPhone 6 Plus

If I switch between servers the online indicators are not synced with the actual state of the server.

**Comment by rafaelks** [comment]
@TheReal1604 Is this still happening? I think it's fixed in currently TestFlight build.

**Comment by rafaelks** [comment]
Closing it for now.

**Comment by TheReal1604** [comment]
@rafaelks This is now also working fine.
