### ISSUE TITLE
[BUG] Wrong behavior on long press gesture at chat message

### ISSUE THREAD

**Issue by macabeus** [RocketChat/Rocket.Chat.iOS#811]
- Your Rocket.Chat app version: 1.6.0 (108), also the lasted version in develop branch
- Device (or Simulator) you're running with: iPhone SE, in physic device and simulator

<img src="https://user-images.githubusercontent.com/9501115/31717545-c677d81e-b3e2-11e7-8f1e-9d48974a063e.png" width="300" />

When we uses the long press gesture in chat messages, the correct result is to open the menu with options to pin message, to reply... But, sometimes, is opened the menu to select text message.

**Comment by filipealva** [comment]
Hey guys, I did some research on it and unfortunately I could not find any elegant solution for this issue that keeps the link functionality.

The most elegant solution that I found and tested was [this one](https://medium.com/@sdrzn/swifty-approach-to-handling-uitextviews-with-links-in-cells-d89e0e4b83d1)

Just adding it to the discussion

**Comment by rafaelks** [comment]
This is fixed already! 👍
