### ISSUE TITLE
[NEW] Allow sharing of images, weblinks etc. from other apps

### ISSUE THREAD

**Issue by M4urice** [RocketChat/Rocket.Chat.iOS#820]
Rocket.Chat app version: 1.6.0
Rocket.Chat server version: newest I think (hope)
Device: iPhone 6s

Same feature request as https://github.com/RocketChat/Rocket.Chat.Android/issues/98 for Android. Allow users to share images, weblinks and so on via the share extentions (?) https://developer.apple.com/library/content/documentation/General/Conceptual/ExtensibilityPG/Share.html.

Basically Rocketchat should appear here: 

![img_4642](https://user-images.githubusercontent.com/1615089/31819759-58fa4052-b59e-11e7-97ab-3af5042a2a09.PNG)

**Comment by rafaelks** [comment]
That's a great feature request! 👍

**Comment by rafaelks** [comment]
Now is possible to send files via REST: https://github.com/RocketChat/Rocket.Chat/pull/8947

**Comment by soundstorm** [comment]
@rafaelks the branches referencing this issue seem outdated.
I still like the regular share interface like used on Twitter/Slack/... and not the fullscreen window (as in [share_extension.820](https://github.com/RocketChat/Rocket.Chat.iOS/tree/feature/share_extension.820) or WhatsApp).

Slack simply shows two fields to select Workspace/Team/Server and Channel.
Server is using an simple list with icons and names; Channel uses a searchable list (window title: [teamname]).
![slack sharing](https://user-images.githubusercontent.com/193273/35169935-acddc114-fd5e-11e7-8812-bd28993567b8.PNG)

**Comment by rafaelks** [comment]
@soundstorm The problem with this style, is that is very limited. You don't have much control over previewing images/links and other stuff.

**Comment by boblmartens** [comment]
Since this missed the 2.0.0 milestone, do we have an idea when it is planned to be released?

**Comment by rafaelks** [comment]
@boblmartens Yes, we focused our 2.0.0 milestone on the features that were missing from the Cordova application. This is now probably going to be released in our next major release. 👍
