### ISSUE TITLE
[NEW] Add debugging to debug/ad-hoc builds

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.iOS#821]
Need to find a few suggestions.

**Comment by cardoso** [comment]
@rafaelks few suggestions:

https://github.com/Flipboard/FLEX
https://github.com/krzysztofzablocki/LifetimeTracker
https://github.com/remirobert/Dotzu
https://github.com/dbukowski/DBDebugToolkit
https://github.com/Buglife/Buglife-iOS
