### ISSUE TITLE
[NEW] Add Home Screen Quick Actions

### ISSUE THREAD

**Issue by artrmz** [RocketChat/Rocket.Chat.iOS#833]
Home screen quick actions. Customizable via settings if possible. Could add ie. most used chats (or favourites) as quick actions.

https://developer.apple.com/ios/human-interface-guidelines/extensions/home-screen-actions/

**Comment by rafaelks** [comment]
@artrmz Yes, that's a great feature request! Another idea is to use the multi-server to allow the user to choose which server wants to connect.

**Comment by RahulDhiman93** [comment]
Can I work on that?

**Comment by cardoso** [comment]
@RahulDhiman93 thanks for taking interest in this issue. 

We still need to discuss which options we should have here. I'll mark this "needs more info" for now. You can start working on it if you have any ideas.

cc @rafaelks

**Comment by rafaelks** [comment]
@RahulDhiman93 @cardoso Sounds good to me! I think a great start is listing the 5 chats with latest activity. What do you guys think? You could do something like this, what do you think?

````
+--------------------------+
| @rafaelks                |
| Last message...          |
+--------------------------+
| #general                 |
| Last message...          |
+--------------------------+
|            ...           |
+--------------------------+

**Comment by artrmz** [comment]
Not sure about showing the last message there. Maybe should server's name on the second line? There are common channel's names like `#general` so showing what server it belongs to might be helpful information. Could also show the number of unread messages if possible. What do you think?

**Comment by rafaelks** [comment]
@artrmz Result would look like this, right? Sounds good to me.

````
+--------------------------+
| @rafaelks                |
| unstable.rocket.chat     |
+--------------------------+
| #general                 |
| open.rocket.chat         |
+--------------------------+
|            ...           |
+--------------------------+

**Comment by artrmz** [comment]
@rafaelks I think so, could show server's actual name but those could be (in a rare situation) repeated unless we should not worry about that and just show ie. `Rocket.Chat`.

**Comment by rafaelks** [comment]
@artrmz Exactly! If user has only one server, I would show "Tap to open"... what do you think?

**Comment by rafaelks** [comment]
@artrmz Forget... we can show the serve URL for one server algo. :-)

**Comment by artrmz** [comment]
@rafaelks Yeah, that sounds good :)
