### ISSUE TITLE
[BUG] Filenames with umlauts cause broken upload

### ISSUE THREAD

**Issue by gdelavald** [RocketChat/Rocket.Chat.iOS#851]
@emign commented on [Tue Oct 24 2017](https://github.com/RocketChat/Rocket.Chat.Electron/issues/579)

On rocketchat+ on iOS when you upload a file (eg pdf) with an umlaut the file seems to upload correctly and is shown in the message stream. But clicking it does not open it but only shifts the text up and down a bit 

---

@gdelavald commented on [Tue Oct 24 2017](https://github.com/RocketChat/Rocket.Chat.Electron/issues/579#issuecomment-338983212)

@emign Sorry, is this mobile or on a Mac computer?

---

@emign commented on [Tue Oct 24 2017](https://github.com/RocketChat/Rocket.Chat.Electron/issues/579#issuecomment-338984487)

It is on iOS mobile (iPad and iPhone) with version 1.6.0. the same (umlaut-titled file) can be downloaded via a browser on the device just fine btw.

**Comment by rafaelks** [comment]
@emign Could you please, send us a PDF file that doesn't open, so we can test it?

**Comment by emign** [comment]
You can use the any PDF file with an umlaut in the title.
Try this one eg. 
[ÄSemesterarbeit.pdf](https://github.com/RocketChat/Rocket.Chat.iOS/files/1414117/ASemesterarbeit.pdf)
