### ISSUE TITLE
[CRASH] App crashes in one channel

### ISSUE THREAD

**Issue by djschilling** [RocketChat/Rocket.Chat.iOS#854]
- Your Rocket.Chat app 1.6.0
- Your Rocket.Chat server version: 0.59.1
- Device (or Simulator) you're running with: iPhone 6

Since the last update to version 1.6 the app crashes every time i visit one of our channels.
I saw some crashlog issues reported here but i'm not sure if they are related to my issue.
Its the channel with most messages in our rocket chat installation.

Example of the messages in the channel:
```
rocket.cat BOT 22:29
✅ RECOVERY domain (General Instance Test): *OK* | HTTP OK: HTTP/1.1 200 OK - 422 bytes in 0.013 second response time | [ ** ]

rocket.cat BOT 22:30
✅ RECOVERY domain (Instance Test Instance102): *OK* | HTTP OK: HTTP/1.1 200 OK - 444 bytes in 0.015 second response time | [ ** ]

rocket.cat BOT 22:30
❗ PROBLEM domain (galera_cluster): *CRITICAL* | CRITICAL: node is not synced OK: number of NODES = 3 | [ ** ]

rocket.cat BOT 22:30
✅ RECOVERY domain (Instance Test Router 103): *OK* | HTTP OK: HTTP/1.1 200 OK - 422 bytes in 0.019 second response time | [ ** ]

rocket.cat BOT 22:31
✅ RECOVERY domain (Instance Test Router 102): *OK* | HTTP OK: HTTP/1.1 200 OK - 422 bytes in 0.009 second response time | [ ** ]

rocket.cat BOT 22:31
✅ RECOVERY domain (galera_cluster): *OK* | OK: number of NODES = 3 | [ ** ]

rocket.cat BOT 22:33
⚠ PROBLEM domain (galera_cluster): *WARNING* | WARNING: number of NODES = 2 | [ ** ]

rocket.cat BOT 22:34
⚠ PROBLEM domain (galera_cluster): *WARNING* | WARNING: number of NODES = 2 | [ ** ]

rocket.cat BOT 22:34
⚠ PROBLEM domain (load): *WARNING* | WARNING - load average: 4.67, 4.00, 3.32 | [ ** ]

rocket.cat BOT 22:34
⚠ PROBLEM domain (load): *WARNING* | WARNING - load average: 6.83, 5.19, 2.78 | [ ** ]

rocket.cat BOT 22:35
✅ RECOVERY domain (galera_cluster): *OK* | OK: number of NODES = 3 | [ ** ]

rocket.cat BOT 22:36
✅ RECOVERY domain (galera_cluster): *OK* | OK: number of NODES = 3 | [ ** ]

rocket.cat BOT 22:36
✅ RECOVERY domain (galera_cluster): *OK* | OK: number of NODES = 3 | [ ** ]

rocket.cat BOT 22:36
✅ RECOVERY domain (load): *OK* | OK - load average: 1.18, 3.65, 2.51 | [ ** ]

rocket.cat BOT 22:43
❗ PROBLEM domain (load): *CRITICAL* | CRITICAL - load average: 10.65, 4.72, 3.69 | [ ** ]

rocket.cat BOT 22:53
⚠ PROBLEM domain (load): *WARNING* | WARNING - load average: 0.45, 2.78, 3.78 | [ ** ]

rocket.cat BOT 22:58
✅ RECOVERY domain (load): *OK* | OK - load average: 0.75, 1.50, 2.94 | [ ** ]
```

**Comment by cardoso** [comment]
Thanks for this detailed report!!

We are currently looking into a crash that has to do with our markdown parser.

**Comment by rafaelks** [comment]
@djschilling Thank you! Is there any chance you could add us to your channel? Or create a new one with the last ~25 messages?

**Comment by TheReal1604** [comment]
@rafaelks have also an affected channel.. maybe i can create a same on my system there you can get access.

**Comment by cardoso** [comment]
@TheReal1604 please! We're very anxious to fix this crash :)

**Comment by TheReal1604** [comment]
@cardoso i tested a bit with a new channel, just copy pasting this messages is not working... In our messages we have some text which is linked to an internal URL. Maybe this could be an issue if the device could not resolve the url? (preview)

**Comment by cardoso** [comment]
@TheReal1604 we have a crash in our markdown parser that has to do with links in very specific cases that we could not reproduce yet.

If we could join the channel and reproduce this in debug mode, it would be quite easy to fix. (Provided it's actually this crash)

**Comment by TheReal1604** [comment]
@cardoso can i send a crash report via the app to you? I think an access directly to the channel is not possible at the moment because of sensitive data in this monitoring messages. :(

**Comment by TheReal1604** [comment]
@cardoso @rafaelks maybe this could you help:

We are using this script to notify in Rocket.chat and you can see there how the url is formatted:

https://github.com/BackIsBachus/icinga2-rocketchat-notification/blob/master/rocketchat-host-notification.sh

**Comment by djschilling** [comment]
We are using the same plugin. Access to our system is not possible. I have not the right to grant that to you.

**Comment by cardoso** [comment]
@TheReal1604 I think we are in the right track here.

<https://host.com/path?query|display name>

This style of link formatting is related to the crash. But just copying and pasting the template you sent me isn't causing it.

Could you send an actual example from your chat log? With the sensitive information carefully redacted?

**Comment by MauriceBrg** [comment]
@cardoso @TheReal1604 

The template from the script looks like this (just the text value, I belive the rest is not relevant):
`${ICON} ${NOTIFICATIONTYPE} <https://${ICINGA_HOSTNAME}/icinga-web2/monitoring/host/services?host=${HOSTNAME}|${HOSTDISPLAYNAME}> (<https://${ICINGA_HOSTNAME}/icinga-web2/monitoring/service/show?host=${HOSTNAME}&service=${SERVICEDESC}|${SERVICEDISPLAYNAME}>): *${SERVICESTATE}* | ${SERVICEOUTPUT} | [ *${NOTIFICATIONAUTHORNAME}* ] ${NOTIFICATIONCOMMENT} `

And this is what it might look like after the script puts in the values:
`:warning: PROBLEM <https://companyname.intern/icinga-web2/monitoring/host/services?host=servername022|Servername022> (<https://companyname.intern/icinga-web2/monitoring/service/show?host=servername022&service=customer_application_service_prod|Customer Application Service Prod>): *Critical* | Some plain text output from the check | [ ** ] `

- `${ICINGA_HOSTNAME}` is a normal URI
- `${HOSTNAME}` is the name of a server and containts lower case characters and numbers
- `${HOSTDISPLAYNAME}` is the same as HOSTNAME
- `${SERVICEDESC}` contains lower case charactes, underscores and numbers (just our convention, could be different)
- `${SERVICEDISPLAYNAME}` can contain a variety of characters, usually from the ASCII Space + the German Umlauts äöü
- `${SERVICESTATE}` can be CRITICAL/OK/UNKNOWN/WARNING
- `${SERVICEOUTPUT}` is plain text
- ``${NOTIFICATIONAUTHORNAME}` and `${NOTIFICATIONCOMMENT}` are usually empty

Hope, this helps :)

**Comment by TheReal1604** [comment]
@mauricebrg thanks for the example data!

**Comment by cardoso** [comment]
Thank you very much for the help guys :)
