### ISSUE TITLE
[CRASH] App crashes when GIF is posted in channel

### ISSUE THREAD

**Issue by the86freak** [RocketChat/Rocket.Chat.iOS#856]
- Your Rocket.Chat app version: 1.6.0
- Your Rocket.Chat server version: 0.57.2 (also tested on 0.59.1)
- Device (or Simulator) you're running with: iPhone 5S and iPhone 8 on iOS 11.0.3

Steps:
1. Post the attached gif in a channel from a desktop system 
2. open iOS App
3. enter channel where you posted the gif
3.i. wait a few seconds while the gif is loading
app crashes with black screen and then the main screen appears again

you can re-open the app by double-clicking the home-button, because it seems to still be idle in the background. But the same thing appears again: channel tries to be loaded, but then app crashes.
You can't switch the channel.

Workaround:
- delete gif from channel
- reinstall app

GIF:
![test](https://user-images.githubusercontent.com/3979170/31987685-dabd1ff2-b96c-11e7-9d47-0650b176e9fe.gif)

edit: also tested on 0.59.1

**Comment by the86freak** [comment]
I tried to reproduce it on open.rocket.chat and wasn't able. So We'll update the server on our side first and come back to this later.

**Comment by cardoso** [comment]
@the86freak same here.

Thanks for the report! We should look into this even if it only happens in older versions of the server.

**Comment by the86freak** [comment]
well, we were able to reproduce it again with the following gif:
If you can't reproduce it, I can demo it in any channel on open.rocket.chat if you want.


![broken-gif](https://user-images.githubusercontent.com/3979170/32002628-388825fc-b99d-11e7-85a4-0e10434bf3cc.gif)

**Comment by cardoso** [comment]
Posted it in my test channel #cardoso_test

No crash :thinking: weird

**Comment by rafaelks** [comment]
@cardoso Are you testing on device? I could reproduce it here, looks like a memory issue.

**Comment by cardoso** [comment]
@rafaelks yes, iPhone SE.

I don't have any other to try and reproduce this. Maybe this only happens after heavy use?

**Comment by the86freak** [comment]
@cardoso 
you might need to open and close the according channel a view times, but as the last channel you visited is opened by default, it happend for me without "heavy" use.
