### ISSUE TITLE
Can't reach the chats page

### ISSUE THREAD

**Issue by demonotter** [RocketChat/Rocket.Chat.iOS#86]
After I login to the server, I see just this page
https://cloud.githubusercontent.com/assets/5362165/16943939/24be2fca-4dc0-11e6-8042-09d96bffae08.png

How can I reach the chats page after that?

**Comment by rafaelks** [comment]
@demonotter Yes, this is the main page today because we're still working on the chats page. The project is still in development. Keep looking into the project, because soon we'll have the basic support to use the app, like the chat rooms and the messages.
