### ISSUE TITLE
[NEW] Autocomplete needs to list all available channels/users

### ISSUE THREAD

**Issue by macabeus** [RocketChat/Rocket.Chat.iOS#860]
- Your Rocket.Chat app version: 1.7.0 (109) - last version at develop branch

![image](https://user-images.githubusercontent.com/9501115/32015924-e6a0b5e6-b998-11e7-8dbf-aae66c52b54e.png)

![image](https://user-images.githubusercontent.com/9501115/32015954-f8e8a40c-b998-11e7-8c3d-6c734a450e43.png)

Currently, in autocomplete of iOS list only channels that the user has join, and people that the user saw. It's different in web version, which list all channels and people.

**Comment by rafaelks** [comment]
@macabeus I don't think we need to show all the channels/users from the server. In large communities, this can be a pain in the ass, user may have a hard time to find what he/she's looking for. I think we can only display information that user knows about: users and servers that are related to them.

But, I think we can improve the autocomplete, with some of this things:

1. Sort the users list by last recent activity in the current channel;
2. Sort the channels list by name;
3. When user external keyboard, using autocomplete and pressing `Return` could select the first item;
4. Add an icon to the channels (I think we have, but it's white);

**Comment by rafaelks** [comment]
Closing this one for now.
