### ISSUE TITLE
[BUG] Muted state not being handled correctly

### ISSUE THREAD

**Issue by cardoso** [RocketChat/Rocket.Chat.iOS#862]
Currently, the sent message just becomes blank and the message from the BOT is not displayed

This is what happens in the web version:

![](https://i.imgur.com/hJ1Vccj.png)

Maybe we should try to handle this differently. 
The same way we'll handle read-only channels: #861

What do you think @rafaelks?

**Comment by rafaelks** [comment]
@cardoso Do we know if the user was muted? I don't think we do to... (there's probably a way, but we don't have this information now). If we can have this information, yes, I think we can block the textField. Otherwise, let's try to show this `rocket.chat` message in the same format.
