### ISSUE TITLE
[NEW] Allow changing app language inside application settings

### ISSUE THREAD

**Issue by artrmz** [RocketChat/Rocket.Chat.iOS#872]
If I am correct right now app uses device's language settings. It would be better user experience if user could choose which language to use regardless of device's settings.

**Comment by artrmz** [comment]
@rafaelks, personal preferences I guess. Maybe it is just me but I like to use system in my native language but any other app in English.

**Comment by rafaelks** [comment]
@artrmz LOL, yes, I think it's a good feature request! I'll keep it here with `feature` label. 👍

**Comment by cardoso** [comment]
I do this a lot too.

The ideal would be for Apple to support this in their "Settings" app. Set locale per App.

But I don't think they would ever care about this 😞

**Comment by dennispost** [comment]
Do you know a way to set these settings? Localization, Message Settings, Mentions etc. ? 
I'm working on a Preferences View, where you can change all these settings like in Desktop App.

I found none: RocketChat/Rocket.Chat#8694

**Comment by rafaelks** [comment]
@dennispost Are you talking about the user settings, like we have on the web also? To change name, photo, etc? If yes, here is how to change some of the User's properties: https://docs.rocket.chat/developer-guides/rest-api/users/update#user-update.

**Comment by dennispost** [comment]
@rafaelks Yep but thats only one part of the story. What's about the rest as mentioned in RocketChat/Rocket.Chat#8694 like sound, notification, mentions settings?

**Comment by rafaelks** [comment]
@dennispost Yes, we need all this settings into the app, but I believe the "language" is something "local", right guys? Or are you talking about a language to be selected thought all Rocket.Chat clients?

**Comment by artrmz** [comment]
@rafaelks Yeah, I think language should be local. There is already such setting in desktop's (electron) Rocket.Chat, I don't know if it's local setting though?
