### ISSUE TITLE
[BUG] Side menu's background is too short on iPhone X

### ISSUE THREAD

**Issue by artrmz** [RocketChat/Rocket.Chat.iOS#880]
Ad title says and image shows. There is ugly black rect at the bottom of side menu.

![simulator screen shot - iphone x - 2017-10-29 at 14 41 42](https://user-images.githubusercontent.com/3925166/32144327-7fe33230-bcb7-11e7-9467-b5e779c71081.png)

**Comment by rafaelks** [comment]
Good finding! Also, the status bar isn't hiding.

**Comment by artrmz** [comment]
@rafaelks Do we want to hide status bar on iPhone X though? According to Human interface guidelines it should be hidden only in rare situations:

> If your app currently hides the status bar, reconsider that decision for iPhone X. The display height on iPhone provides more vertical space for content than the displays of 4.7" iPhones, and the status bar occupies an area of the screen your app probably won't fully utilize. The status bar also displays information people find useful. It should only be hidden in exchange for added value.

**Comment by rafaelks** [comment]
@artrmz You're right, let's not hide it for iPhone X. Maybe we can change the color of status bar to light?

**Comment by artrmz** [comment]
@rafaelks Not changing color for now, seems like it's been fixed (or I don't know why it didn't hide before) in Xcode 9.1/iOS 11.1

**Comment by rafaelks** [comment]
@artrmz Sounds good!
