### ISSUE TITLE
[i18n] "Required ssl label" missing string for ptBR language 

### ISSUE THREAD

**Issue by filipealva** [RocketChat/Rocket.Chat.iOS#889]
- Your Rocket.Chat app version: 1.7.0 (109)
- Your Rocket.Chat server version: 13
- Device (or Simulator) you're running with: iPhone 6s

When connecting to a new server in a device with ptBR language the localized strings key is showed.

![ss01](https://user-images.githubusercontent.com/6117280/32199728-04db0d66-bdb5-11e7-9460-2758ddbff094.jpg)

**Comment by rafaelks** [comment]
Good finding! Also missing for German. Thank you @filipealva! :v:
