### ISSUE TITLE
[IMPROVEMENT] Loading forever with no user feedback when adding a new server

### ISSUE THREAD

**Issue by filipealva** [RocketChat/Rocket.Chat.iOS#890]
- Your Rocket.Chat app version: 1.7.0 (109)
- Your Rocket.Chat server version: ?
- Device (or Simulator) you're running with: iPhone SE Simulator

I'm getting stuck in this loading when trying to connect to some servers.

<img width="252" alt="screen shot 2017-10-30 at 20 14 23" src="https://user-images.githubusercontent.com/6117280/32199855-a9f7c938-bdb5-11e7-9ce9-f761a2d27dd3.png">

The problem is not that there is a connection error but it seems that the error is not being handled properly. I could see that always when the following web socket error appears on the console the loading stuck and there is no feedback for the user:

![screen shot 2017-10-30 at 20 14 26](https://user-images.githubusercontent.com/6117280/32199928-181d86dc-bdb6-11e7-86e9-b294b81eff5b.png)

**Comment by rafaelks** [comment]
@filipealva That's definitely something we need to improve. This error happens if your server doesn't support SSL or WebSocket protocol. Do you know if that's the case?

**Comment by filipealva** [comment]
@rafaelks I'm not sure because I just grabbed some random public RC instances on the web to test, but I think that's the case.
