### ISSUE TITLE
Push Notifications

### ISSUE THREAD

**Issue by JohnBueno** [RocketChat/Rocket.Chat.iOS#90]
I am exploring the possibility of embedding RocketChat inside an existing app as webview.  I am also running RocketChat on a private server.  I want to register a device through my app using my apps entitlements.  Is there an endpoint I can hit on my private rocketchat instance to register a device for push notifications?  If so what is the post body I should be sending?

**Comment by rafaelks** [comment]
@JohnBueno That's interesting. I believe we currently don't support it, but you definitely should open a issue on the main project, since this is related to back-end side and not the native iOS application: https://github.com/RocketChat/Rocket.Chat.

**Comment by JohnBueno** [comment]
@rafaelks I am not super familiar with Cordova so I might be missing something while going over that code base but there must be call in which when a user logs in you are pairing that username with that device so that they will receive push notifications on that device.  Would you be able to point me to the section where that is happening and maybe we can work something out from that?

**Comment by graywolf336** [comment]
@JohnBueno Take a look at the server code under `packages/rocketchat-ui/lib/cordova/push.coffee` and see if what you're looking for exists in there. If you have any further questions about that, I'd recommend hitting up the demo/community server at `demo.rocket.chat` and go into the `#learn` or `#support` channels and asking there, you'll hit a better audience then on this repository.
