### ISSUE TITLE
[BUG][INVESTIGATE] The server URL will have a Bug with a path, like this: "https: 192.168.1.100/chat"

### ISSUE THREAD

**Issue by xingchen966** [RocketChat/Rocket.Chat.iOS#900]
- Your Rocket.Chat app version: 1.7.0 (109)
- Your Rocket.Chat server version: 0.59.1
- Device (or Simulator) you're running with: iPhone 6s and iPhone 7 on iOS 11.0.3

Hey, If I enter the server URL in the App with a path, such as: "https://192.168.1.100/chat", it will produce an error. Because there are fixed paths in many packages under "API / Requests", for example:
`/api/v1/info`
If my server URL has a path “/chat”, Those files with the fixed path under "API / Requests" package will add the path "/chat". like this:
`/chat/api/v1/info`

**Comment by jpowie01** [comment]
Any update on this issue? I’ve just set up a self-hosted server on subdirectory and found this issue. I can confirm that it still exists :( I cannot even go through the server connection screen.

**Comment by rafaelks** [comment]
@jpowie01 This is a little tricky to solve... for now, the easiest thing is to create a subdomain. Can you do that?

**Comment by jpowie01** [comment]
Sadly, I'm unable to do this as it is not under my control.

I've spent some time reading the code and trying to debug it on my own but as you've said - it's tricky. Is there a plan to solve it in the near future? I could try to do something with the implementation but I'm not a Swift/iOS developer on my daily basis and it will take me 10x longer to solve...

**Comment by jpowie01** [comment]
I've done what I could and prepared a PR. I've tested it manually on my computer by logging into my Rocket.Chat instance and my own account. It would be nice if anyone would continue my work as I probably won't have more available time to work on this.

Here is my PR: https://github.com/RocketChat/Rocket.Chat.iOS/pull/1277

Don't hesitate to close/delete this PR If you find it terrible :)

**Comment by rafaelks** [comment]
@jpowie01 Nice!!! We're reviewing it soon. Thank you!
