### ISSUE TITLE
[NEW] Add user to a channel you creating

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat.iOS#902]
- Your Rocket.Chat app version: 1.7.0 (110)
- Your Rocket.Chat server version: 0.59.3
- Device (or Simulator) you're running with: iPhone 6 Plus

At the moment we can create new channels from the iPhone App, but couldnt invite new users to the channel.

**Comment by cardoso** [comment]
We need to to this in the add channel screen, but you can also just mention the user to invite him (as far as I know)

**Comment by TheReal1604** [comment]
@cardoso this is not working with private channels at my systems. Maybe there is a setting?

**Comment by artrmz** [comment]
I am (slowly at my spare  time) working on this feature ;)

**Comment by artrmz** [comment]
Just wondering, should we fetch all users on the server or fetch first few people matching typed name?

**Comment by rafaelks** [comment]
@artrmz I don't think so... let's use all `User` objects we have in Realm for now. Having all the users list from large servers can be a very heavy operation. We already do something similar in our `autocomplete` feature.

**Comment by artrmz** [comment]
@rafaelks In Realm there are only users from most recent subscription? Could use that although in some cases it'll be really annoying ;)

**Comment by rafaelks** [comment]
@artrmz Actually, you've all users that was ever used in the app. All your subscriptions list and all users that you already read a message from. I *think* you'll have all users you want. But I liked your suggestions of "searching" users while typing too (just not all the users). We have a method for that already also: 

https://github.com/RocketChat/Rocket.Chat.iOS/blob/c9b74a8957049e45efc11f505668dc47d40fd436/Rocket.Chat/Managers/Model/SubscriptionManager.swift#L230-L236

But I'm thinking that maybe we could try to use a REST API for that 🤔, there's one called `users.list`: https://docs.rocket.chat/developer-guides/rest-api/users/list.

**Comment by artrmz** [comment]
@rafaelks Yup, that's what I already started implementing (REST API), although it gives me quite strange results though for request with regex query (doesn't seem to return any users in some cases). Anyway will take a look at what you suggested (that method in `SubscriptionManager`), should be a good start :)

**Comment by rafaelks** [comment]
@artrmz It's possible that this API is buggy. Let me know about your tests and we can investigate if the API is handling correctly or not. 👍
