### ISSUE TITLE
[BUG] App is not connecting sometimes when started from background

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat.iOS#917]
- Your Rocket.Chat app version: 1.7.1 (111)
- Your Rocket.Chat server version: 0.59.3
- Device (or Simulator) you're running with: iPhone 6 Plus

If you start the App from background the "Connecting to server.." message is displayed and the indicator is working.. but the app is not connecting. If you kill the app and restart the app is connecting fine.

**Comment by rafaelks** [comment]
I also experienced this bug on my device today a couple of times.

**Comment by TheReal1604** [comment]
got this also with the new testflight version 1.7.2

**Comment by mrsimpson** [comment]
Same problem here as well - actually almost never returns when returning from background. I have to kill the app via the switcher in order to make it reconnect.
Backend 0.59.2
Version 1.7.1

This is really a critical one...
