### ISSUE TITLE
[BUG] Wrong chat frame size while hotspot is active after rotation

### ISSUE THREAD

**Issue by artrmz** [RocketChat/Rocket.Chat.iOS#923]
- Your Rocket.Chat app version: 1.7.1
- Device (or Simulator) you're running with: iPhone 6s

After toggling in-call status bar or turning on hotspot and rotating device there is black gap at the bottom in portrait orientation and height is too big on landscape orientation as you can see on screens.

![simulator screen shot - iphone 6s - 2017-11-05 at 13 36 18](https://user-images.githubusercontent.com/3925166/32414788-c20e2ada-c22e-11e7-9552-9bf0ec2bd5d8.png)
![simulator screen shot - iphone 6s - 2017-11-05 at 13 36 09](https://user-images.githubusercontent.com/3925166/32414789-c230c856-c22e-11e7-9ee6-45c228dd286c.png)

**Comment by Sameesunkaria** [comment]
I believe it has something to do with the `SideMenuController` pod. It has a property called `centerPanelFrame` which is returning an incorrect value.

**Comment by filipealva** [comment]
I also noticed that in the same scenario but rotating the device to landscape position half of the input text view is being off the bounds of the window. I'm moving it to the 3.0.0 milestone as we are planning to define a common approach to fix these chat layout issues.

**Comment by Sameesunkaria** [comment]
@filipealva I believe `SideViewController` will no longer be required for 3.0.0, since it’s forgoing the side bar type of layout and going for a more conventional iMessage/WhatsApp style view hierarchy.
