### ISSUE TITLE
[BUG] Chat's scroll is jumping after rotation

### ISSUE THREAD

**Issue by artrmz** [RocketChat/Rocket.Chat.iOS#924]
- Your Rocket.Chat app version: 1.7.1
- Device (or Simulator) you're running with: iPhone 6s

After rotating device to either orientation the chat's content is jumping a little bit. It should stay where it was (ie. to be able to see the last message if we were at the very bottom of conversation)

**Comment by rafaelks** [comment]
@filipealva Verify if it's still happening please.

**Comment by artrmz** [comment]
Still happens on TF 2.1.0 (148). When chat is scrolled to the very bottom and we rotate device it scrolls a little bit.

**Comment by filipealva** [comment]
As @artrmz pointed out, it's still happening. I will move it to the 3.0.0 milestone so we can think how to better approach this issue.
