### ISSUE TITLE
[NEW] Handle HTTP redirects (301, 308) and update the server list accordingly

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat.iOS#937]
# Description

When server changes it's URL the app needs to ask the user if user wants to change it or not, showing the new URL.

So, the app needs to do the following things:

1. Before connecting to the web-socket, check `/api/info` always and see server is valid;
2. If response is `301` or `308` status code, app needs to check if there's a `Location` header in the 
3. If `Location` is a valid URL, needs to check if it's a valid Rocket.Chat server, by requesting `/api/info`. This process is already being done on the `ConnectViewController.swift` file;
4. If new server is valid, user needs to be prompted with an alert asking if user want's to change the old URL to the new one;
5. If user taps "Yes", the app needs to clear all the database, change server information to the new URL and keep the auth information;

**Comment by rafaelks** [comment]
Updated the description accordantly.
