### ISSUE TITLE
[BUG] Typing on the app is causing "flickering" of "user is typing" on the web

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.iOS#940]

**Comment by rafaelks** [comment]
@RocketChat/core How should we actually handle this? Today we're sending the `typing` status for each character user types. What should be the correct way to implement it?

**Comment by cardoso** [comment]
What I noticed when investigating this is the back-end resets "isTyping" after a few seconds.

Maybe we should only send set "isTyping" after these few seconds (also reduces data usage)

PS: I couldn't replicate this myself, but I saw it happening in DM with you a lot :)

**Comment by rafaelks** [comment]
I'll close it for now, since we don't have enough information to implement this feature in the app.

**Comment by rafaelks** [comment]
Just added this one to the roadmap, will implement it to avoid the flickering on the web client.
