### ISSUE TITLE
[QUESTION] No login possible with iPhone/iPad

### ISSUE THREAD

**Issue by marzie82** [RocketChat/Rocket.Chat.iOS#947]
Hi,
I need some help please. We are testing our new Rocket.Chat installation that works really great. Now we would like to connect some mobile Devices like iPhone and Android... Android works fine after importing ca.cert with CAdroid. iPhone still cannot not connect- I can only see on the Firewall some States- not on the Server itself. Using telnet with some Port (443) works!

Our Server was installed with snap, we are also using caddy with self generated Certs.

my.domain:443
tls ../certs/cert.pem ../certs/key_un.pem
proxy /  localhost:3000 {
  websocket
  transparent
}

- Your Rocket.Chat app version: 1.7.1
- Your Rocket.Chat server version: 0.59.3
- Device (or Simulator) you're running with: iPhone 7 / iPad Air 2 with iOS 11.1

Do you have any hint for me?
Thanks,
Martin

**Comment by rafaelks** [comment]
@marzie82 Hey! Is your server available externally? If yes, I would live to give it a try and see what the logs are saying.

**Comment by marzie82** [comment]
Hello,
thanks for your answer. Yes, the server can be reached externally- our Androids working this way. My problem is that I have NO Logs- even no state "netstat -anp" on the server itself. For all other OS I have a state! I have a port forward on Port 443- do I need anything else for ios?
Thanks in advance!

**Comment by rafaelks** [comment]
@marzie82 Can you send me your email? I'll send you our TestFlight version of the app and you can confirm if it works in our beta version.

**Comment by marzie82** [comment]
Hello, 

you can use this account for direct communication. Do you need to know my AppleID? 



Von: "Rafael Kellermann Streit" <notifications@github.com> 
An: "RocketChat/Rocket.Chat.iOS" <Rocket.Chat.iOS@noreply.github.com> 
CC: "marzie82" <mziebura@midoco.de>, "Mention" <mention@noreply.github.com> 
Gesendet: Donnerstag, 9. November 2017 13:11:10 
Betreff: Re: [RocketChat/Rocket.Chat.iOS] [QUESTION] No login possible with iPhone/iPad (#947) 



[ https://github.com/marzie82 | @marzie82 ] Can you send me your email? I'll send you our TestFlight version of the app and you can confirm if it works in our beta version.

**Comment by marzie82** [comment]
Hello,
app installed and started- same situation. Did you get any logs?

**Comment by rafaelks** [comment]
@marzie82 What's your server URL?

**Comment by marzie82** [comment]
https://chat.midoco.de

**Comment by marzie82** [comment]
Hi, we've tested the last version from Testflight- still not work... Do you think it's an Cert issue?

**Comment by rafaelks** [comment]
@marzie82 Your server is having timeout for me. Is it working to you? 🤔 

```shell
➜  ~  curl -i -N -H "Connection: Upgrade" \
>           -H "Upgrade: websocket" \
>           -H "Host: chat.midoco.de" \
>           -H "Origin: chat.midoco.de" \
>           -H "Sec-WebSocket-Key: fVXESE8fjBMx8HheW0YlZQ==" \
>           -H "Sec-WebSocket-Version: 13" \
>           https://chat.midoco.de

curl: (7) Failed to connect to chat.midoco.de port 443: Operation timed out
```

**Comment by marzie82** [comment]
For us it works well, Android devices can connect from external. I still have no session on my server. Can you try again and let me know your IP?

**Comment by rafaelks** [comment]
Still could not access, but looks like your SSL is invalid -> https://www.ssllabs.com/ssltest/analyze.html?d=chat.midoco.de.

**Comment by marzie82** [comment]
I confirm it's a cert problem. We just purchased a SSL cert- now it works. 
Thanks for your help!

**Comment by rafaelks** [comment]
Great to hear that! 👍
