### ISSUE TITLE
[NEW] socket error on connecting

### ISSUE THREAD

**Issue by alex-LE** [RocketChat/Rocket.Chat.iOS#952]
When trying to connect to our server i just get a alert "alert.connection.socket_error.title" - "alert.connection.socket_error.message"

- Your Rocket.Chat app version: 1.7.1
- Your Rocket.Chat server version: 0.59.3
- Device (or Simulator) you're running with: iPhone 6S (latest iOS)

We have a haProxy running on this server forwarding port 3000.
Our server is working well with the Android App, Webapp and Desktop apps.
Even the Rocket Chat Cordova App is working.

**Comment by rafaelks** [comment]
@alex-LE Today we're releasing 1.7.2. that fixes this connection issue. Thank you! 👍
