### ISSUE TITLE
[NEW] Let user open admin panel (if user has access to it)

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.iOS#961]

**Comment by rafaelks** [comment]
@RocketChat/core How can we detect if user has permission to open admin?

**Comment by sampaiodiego** [comment]
we [currently check](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-ui-sidenav/client/accountBox.js#L41) if user has at least one of the following permissions: `'view-statistics', 'view-room-administration', 'view-user-administration', 'view-privileged-setting'`

**Comment by rafaelks** [comment]
@sampaiodiego Excellent, thank you!
