### ISSUE TITLE
[BUG] Could not complete server setup if wrong credentials entered once

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat.iOS#974]
- Your Rocket.Chat app version: 1.7.2 (115)
- Your Rocket.Chat server version: 0.59.3
- Device (or Simulator) you're running with: iPhone 6 Plus

The app could not connect successfully if in the setup screen an username is entered wrong. On the second try the connection indicator is turning all the time but not finishes the setup process.

Workaround: Go one screen back to the "enter your server url", connect to your server again and enter the correct credentials on the first try -> setup is working.

**Comment by cardoso** [comment]
I think this might actually be #975 in disguise. I'm looking into it.

**Comment by TheReal1604** [comment]
@cardoso @rafaelks could not reproduce it anymore. I close this one.
