### ISSUE TITLE
Several new issues with 1.7.3(117)

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat.iOS#983]
- The unread messages indicator at the channels is not refreshing correctly (so it displays an indicator for unread messages but I read them already)
- Got at all teams a logout with „your session is expired“
- in the setup screen I can’t switch to my other teams that are configured
- the online indicator of a user is not refreshing correctly (the indicator above the current channel)
- Translation in the setup screen is not correctly displayed (the server must support ss..) 

Do you need screenshots? ;-)

**Comment by TheReal1604** [comment]
And another one:

- can’t configure the open.rocket.chat again if it is already configured (default behaviour is that the apps switches to the already configured team, this is not working for open)

**Comment by cardoso** [comment]
We sent a bad commit to TestFlight. I think some of these might have been fixed by #984.

**Comment by rafaelks** [comment]
Let me close this one for now, should be gone in next TestFlight, otherwise we open again. @TheReal1604

**Comment by TheReal1604** [comment]
@rafaelks thanks! Waiting for new TestFlight build. 😜
